# הטיפול האנטיביוטי בשדה

## הקדמה

זיהום פציעות הוא גורם משמעותי לתחלואה ולתמותה בקרב נפגעים בשדה הקרב, ונחשב לאחת הסיבות החשובות למוות בר-מניעה[@Kotwal2011]. כשליש מפצועי צבא ארה"ב בעיראק ובאפגניסטן סבלו מסיבוך זיהומי[@Murray2009] כאשר ספסיס גרם ל- 2%-9% ממקרי המוות בר-המניעה והיווה את הסיבה הרביעית בשכיחותה למוות מסוג זה[@Holcomb2007; @Blyth2015]. בצבא בריטניה שיעור פצועים דומה סבל מזיהומים, מהם 84% סבלו מזיהום פצע ו- 38% אף פיתחו ספסיס[@parker2008].

פציעות בשדה הקרב הן כר פורה לזיהום, וזאת בעיקר מהסיבות הבאות: (א) פגיעה של שלמות העור וחשיפת הרקמות שתחתיו לסביבה החיצונית; (ב) חדירת גופים זרים מזוהמים; (ג) פגיעה בזילוח ונמק של איברים; (ד) פגיעה באיברים חלולים הגורמת לכניסה של מיקרואורגניזמים לאזורים סטריליים; (ה) עיכוב בטיפול דפניטיבי.

עדויות ליתרון בטיפול אנטיביוטי מוקדם בפצועים בשדה הקרב, בעיקר כאשר הטיפול הניתוחי מתעכב, אפשר למצוא כבר בתקופת מלחמת-העולם השנייה7. עבודות פרה-קליניות הצביעו על כך שמתן אנטיביוטיקה מוקדמת, בעיקר בשעות הראשונות לאחר הפציעה, הפחיתה שיעור סיבוכים זיהומיים8-11. נתונים שנאספו בצה"ל במלחמת יום הכיפורים בשנת 1973 הדגימו שיעור זיהומים נמוך יחסית, שיוחס לטיפול אנטיביוטי בטווח של 30 עד 60 דקות מרגע הפציעה12. בטראומה במתאר האזרחי מספר עבודות רטרוספקטיביות הדגימו גם כן יתרון במתן מוקדם של אנטיביוטיקה 9, 14, 15.

## פרוטוקול

```{mermaid}
%%{init: {'theme':'default'}}%%
graph TD
    A([A penetrating injury]) --> B[Rinse and dress]
    B --> C{<b>Time to hospital > 1h</b>}
    C --> |No|D([No need for antibiotics])
    C --> |Yes|E{<b>Penetrating abdominal<br/>or head injury?</b>}
    E --> |No|F([IV Ceftriaxone 2g])
    E --> |Yes|G([IV Ceftriaxone 2g<br/>IV Metronidazole 500mg])
```

## ביאור הפרוטוקול

### פרק א': מיקרוביולוגיה

באופן גס, ניתן לחלק את הקונטמינציה של הפצע למוקדמת ומאוחרת: בקונטמינציה המוקדמת חשוב להבדיל בין החיידקים הקטלניים בעלי הפוטנציאל ליצור זיהום חודר ומסכן חיים לבין כאלה שלא. החיידקים הקטלניים כוללים חיידקים גרם-חיוביים פיוגניים, חיידקים ממשפחת ה- Clostridia וסטרפטוקוקים אנאירוביים. חיידקי ה- Clostridiaהם המשמעותיים ביותר, שכן חיידקים ממשפחה זו עשויים להוביל ל- Gas Gangrene ולטטנוס. מהחיידקים הגרם-חיוביים Streptococcus pyogenes ו- Staph. aureus הם המשמעותיים ביותר21. Staph. aureus הוא גורם שכיח לזיהום פצע ועצם לאחר טראומה22, ומבין החיידקים הווירולנטיים הוא היה הנפוץ ביותר בתרביות פצע שנלקחו מפצועים מצבא ארה"ב בעיראק מייד עם הגעתם לבית החולים (23); קונטמינציה מאוחרת מוגדרת ככזו הנרכשת במתקנים הרפואיים בהם מטופל הפצוע, בדומה לזיהומים נוזוקומיאליים בבתי החולים. מספר חיידקים שנמצאו כמזהמים משניים שכאלה: Pseudomonas aeruginosa, Acinetobacter baumannii, Enterobacteriaceae ו- Staph. aureus 2, 25. ראוי לציון כי במערכות האחרונות בעיראק ואפגניסטן תוארו גם זיהומים חודרניים של פטריות 26 .

פקטורים רבים הקשורים בפציעות בשדה הקרב תורמים למעבר משלב הקונטמינציה המוקדמת לשלב הזיהום, ביניהם ראוי לציין את מידת האיסכמיה והנמק הרקמתי, את מידת ההלם ואת הירידה בתנגודת החיסונית21. הרציונל העומד בבסיס הטיפול האנטיביוטי בנקודת הפציעה הוא מיגורם של הקונטמיננטים המוקדמים, ובעצם כך מניעת סיבוכים זיהומיים שתביא להפחתת שיעור המוות בר-המניעה והתחלואה הזיהומית הקשה (אוסטאומייליטיס, מורסות ועוד).

### פרק ב': בחירת התכשיר האנטיביוטי

בעת בחירת האנטיביוטיקה האידאלית לטיפול בפצועים בשדה, יש להתחשב בשורה של פרמטרים:

1.  יעילות מוכחת כנגד החיידקים הרלוונטיים למניעת זיהום בפצע.

2.  טווח פעילות צר ככל האפשר -- האנטיביוטיקה נדרשת לכסות את החיידקים הקונטמיננטים המוקדמים, במיוחד את אלו בעלי הפוטנציאל הקטלני.

3.  ריכוז אנטיביוטיקה גבוה בפצע -- דרושה יכולת דיפוזית נאותה של האנטיביוטיקה בכדי שתתרכז באזור הפציעה כאשר מדובר ברקמה פגועה. כדי שניתן יהיה להשיג מטרה זו, המינון הניתן הוא לרוב המינון הבטוח הגבוה ביותר.

4.  זמן מחצית חיים ארוך -- חיוני בכדי להוריד את מספר המנות הדרושות לטיפול, בעיקר אם הזמן עד להגעת הנפגע לטיפול דפיניטיבי ארוך.

5.  אפשרויות מתן מגוונות -- לפצועים שנבצר מהם ליטול טיפול פומי (מחוסרי הכרה, שוק, פציעת בטן) קיימת עדיפות לתכשיר המאפשר טיפול בהזרקה תוך- ורידית/שרירית/גרמית.

6.  שיקולים לוגיסטיים -- זמן מדף ארוך ככל האפשר, עמידות בתנאי אקלים מגוונים וקשים והתחשבות בהתניידות הכוחות (עדיף שמשקל התכשיר ונפחו לא יכבידו על הכוחות המצוידים בו).

7.  תופעות לוואי -- האנטיביוטיקה צריכה להיות בעלת פרופיל טוקסיות נמוך עם מיעוט תופעות לוואי.

### פרק ג': תהליך קביעת מדיניות מתן האנטיביוטיקה

תהליך בחירת התכשירים האנטיביוטיים לפצוע בשדה, עוברים שינויים תמידיים. לאחרונה בוצע תהליך שינוי מדיניות הטיפול מסוג זה במס' שלבים:

1.  סקירת ספרות נרחבת בענף רפואה מבצעית.

2.  כינוס ועידת מומחים בינואר 2017 (שמות המשתתפים מפורטים בנספח א'). הוועדה גיבשה את המסקנות הבאות:

-   יש מקום לטיפול אנטיביוטי בנקודת הפציעה, בעיקר במתארים בהם הפינוי הרפואי צפוי להתעכב. זאת על אף היעדר מחקרים מקיפים בנושא. מטרת הטיפול האנטיביוטי בשדה היא להוריד את העומס החיידקי באיזור הפציעה, ובכך להפחית את הפוטנציאל לתמותה מוקדמת מספסיס ולמנוע זיהומים בפצע.

-   צפלוספורינים בעלי כיסוי טוב של חיידקים גרם-חיוביים וכיסוי משתנה של גרם- שליליים ואנאירובים ע"פ התכשיר הנבחר. הספרות המדעית מעידה על יעילותם במניעת זיהומים במתאר קדם-ניתוח ובטראומה. Ceftriaxone הוא בעל פעילות טובה נגד המחוללים הרלוונטיים עם זמן מחצית ארוך במיוחד. יתר על כן, התכשיר מסופק בפלקונים קטנים, זמן המדף שלו ארוך יחסית וניתן לתת אותו בהזרקה מהירה תוך- ורידית ותוך-שרירית.

-   הוספת Metronidazole לצורך כיסוי חיידקים אנאירובים גרם-שליליים במקרים של פציעת בטן ומוח חודרות.

-   לאחר שהובאו בחשבון כלל השיקולים ועל בסיס המוצג בפרוטוקול שהוצג לעיל, גובשו ההנחיות המעודכנות לטיפול אנטיביוטי בשדה:

-   שטיפה וניקוי של הפצע הם שלב חיוני במניעת זיהומים.

-   טיפול אנטיביוטי צריך להינתן בפציעות חודרות במקרים בהם הפינוי צפוי להתעכב מעבר לשעה. שטיפה, ניקוי וחבישה של הפצע צריכים להתבצע כמקובל ללא קשר לזמן הפינוי.

-   בכל סוגי הפציעות יש לטפל תוך ורידית ב- Ceftriaxone 2gr: 2 ויאלים (פלקונים עם אבקה) המהולים כל אחד ב-10 מ"ל מים להזרקה ב- IV push של 2-4 דקות לפחות פעם ב 24 שעות. ניתן לתת את התרופה IM (תוך-שרירית) בשתי זריקות נפרדות, של 1 גרם מהול ב-3.5 מ"ל מים להזרקה . מומלץ שלא לטפל IM בפצוע הסובל מהלם, שכן אז הספיגה נחותה משמעותית. בילדים, יינתן Ceftriaxone במינון 100 מ"ג/ק"ג עד מקסימום של 2 גר', פעם ביום.

-   בכל מקרה חל איסור למהול את התרופה עם תמיסת Hartmann (Ringer Lactate).

-   לפציעות בטן וראש חודרות נדרשת תוספת של Metronidazole 500mg תוך-ורידית. במקרה של עיכוב בפינוי מעבר ל-8 שעות, יש להמשיך טיפול ב-Metronidazole 500mg בכל 8 שעות. בילדים, יינתןMetronidazole במינון 10 מ"ג/ק"ג שלוש פעמים ביום.

## סיכום

מניעת זיהומים, וכחלק מזה הטיפול האנטיביוטי, בפצועי טראומה הסובלים מפציעה חודרת הוא מרכיב חשוב בטיפול במהלך הסקר השניוני, זאת בפרט כאשר צפוי זמן פינוי ממושך. התאמת התכשירים האנטיביוטיים כוללת מגוון שיקולים. הפרוטוקול הצבאי מאפשר מתן מענה אנטיבקטריאלי הולם למניעת זיהומי פצע וההשלכות החמורות שעלולות להתלוות אליהם.
