# הטיפול בכלבים

## עיקרי העדכונים
- 11/07/2021
    -  כתיבת הפרק

## הקדמה ורקע 
כלבי ולוחמי עוקץ נוטלים חלק פעיל ומשמעותי כמעט בכל מבצע או תרגיל. כפועל יוצא מפיזור זה, לא בלתי סביר, כי הצוות הרפואי האורגני של היחידה הנחברת יידרש להגיש טיפול רפואי לכלב, במידה ויפצע. חשוב להדגיש כי הטיפול בחיילים אנושיים יבוא תמיד לפני טיפול בכלבים, אולם מתוקף תפקידם, במקרים רבים הנפגע היחיד בכח עשוי להיות הכלב.  מטרת הפרק לתת כלים בסיסיים למטפל שאינו וטרינר להערכה, זיהוי וטיפול במצבים מסכני חיים בכלבים.

****************** תמונה


#### 1. סימנים חיוניים תקינים במנוחה
1. דופק: 50-120, נמדד בעורק הפמורלי (ראה תמונה 1)
2. נשימות: 10-40 נשימות/ לדקה
3. חום (PR) 38-39.5
4. ל"ד 120/80 (ממוצע)
5. האזנה ללב: בשני הצדדים, באזור הצלעות. ( ניתן למצוא את המיקום ע"י קיפול הרגל הקדמית של הכלב בᵒ90- הנק' בה קצה המרפק של הכלב מצביע היא נק' ההאזנה- * בתמונה מס' 1).

****************** תמונה


#### 2. דימומים
1. סימני ההלם דומים לבני אדם: דופק מהיר, ריריות חיוורות, שינויים במצב הכרה, ירידה בטמפ' רקטאלית. 
2. הטיפול: **עצירת הדימום**, החזר נוזלים קריסטלואידים **ומתן חמצן.**
3. עצירת דימום מתבצעת ע"י חבישת לחץ/ לחץ מקומי באמצעות פדי גזה ומרבית הדימומים יעצרו ע"י לחץ. ניתן להשתמש בתחבושת המוסטטית. ח"ע (מסוג גומי) לרוב לא שימושי בדימום מהגפים בשל ההבדלים אנטומים - הצורה החרוטית של רגלי הכלב- מונעת מהח"ע להישאר במקומו. במידה והדימום איננו נעצר, ניתן לנסות ולהשתמש בח"ע מסוג CAT.
 
****************** תמונה

4. **השגת גישה ורידית והחזר נוזלים:** 
    1. פתיחת וריד תתבצע באמצעות החדרת קטטר G18 לוריד הצפאלי ברגל הקדמית, אפשר גם לוריד הספנוס ברגל האחורית. יש להשתמש בח"ו או לחלופין לבצע חסימה ידנית ולאחר מכן לחטא באמצעות ספונג'טות (במידה וניתן רצוי גם לגלח את האזור). יש לציין כי ונפלונים לפתיחת וריד וכן סכין לגילוח האזור מצויים **אצל  הלוחם** בערכה ייעודית. לאחר החדרתו, חשוב לקבע היטב את קטטר הוריד על מנת למנוע תלישה ע"י הכלב.
****************** תמונה
****************** תמונה
****************** תמונה
    2. מתן נוזלים: תמיסת "הרטמן" בבולוסים תוך הערכת תגובה. לכלב ממוצע במשקל 30 ק"ג ניתן לתת בולוס של 1 ל'.**יודגש כי אין לתת פלסמה או מוצרי דם אנושיים אחרים לכלב.**
    
#### 3. נתיב אוויר
1. חסימה בדרכי אויר עליונות תתכן עקב שברים בלסתות/ בצקות בפנים/ צוואר, הכשת נחש בפנים, שאיפת עשן, שאיפת גוף זר גדול.
2. הטיפול: חמצן ע"י מסכה או צינור חמצן המוצמד לפה/ אף או מוצמד באמצעות אזיקונים לזמם של הכלב.
3. פתיחת הפה ונסיון גריפה ( בחשד לגו"ז): 

****************** תמונה

4. אינטובציה לכלב: ( ראה תמונה 5 ) מתבצע כשאנחנו ניצבים מול הכלב כשהוא שכוב על הבטן ( ולא מאחוריו). פתיחת פה ושימוש בלרינגוסקופ *הפוך, עם להב מסוג MAC 4*, על מנת ללחוץ את הלשון קדימה ולמטה (בדומה לשימוש בבני אדם, אין לגרוף את האפיגלוטיס), שימוש בטובוס הגדול ביותר (עדיף 9, אך גם 7-8 יספיק). החדרת הטובוס  לכל אורכו כך שהבלונית נמצאת באזור הכניסה לחזה – "Thoracic inlet". ניפוח הבלונית ואבטוח הטובוס באמצעות תחבושת גזה מסביב למקסילה מאחורי הניבים.
****************** תמונה
    1. טרכיאוסטומיה: גילוח הפרווה (במידה וניתן) מהלרינקס ועד לאמצע הצוואר, הרדמה מקומית ע"י לידוקאין, חתך **אורכי** לאורך הטרכיאה שמתחיל בלרינקס ונמשך כ-3 ס"מ*, חיתוך בין טבעות הסחוס עד ל 50% מההיקף (רצוי באחד המרווחים בין טבעות 3-5). בניגוד למבוצע באדם, **אין לחתוך בליגמנט הקריקותאירויד** מאחר וכיפוף הצוואר במנח הטבעי יגרום לחסימה של הטרכיאוסטום. 

****************** תמונה

#### 4.נשימה
1. מצוקה נשימתית, לרוב ע"ר טראומה. הכלב יראה במצוקה, יסרב לשבת או לרבוץ, רגלים קדמיות מפוסקות, ראש וצוואר מורמים למעלה. 
2. פנאומוטורקס/ המוטורקס: סימנים- נשימה שטוחה ומהירה. בהאזנה קולות נשימה עמומים או חסרים. טיפול כולל אנלגזיה/הרגעה וניקוז בחשד לחזה אויר בלחץ/דם.
    1. **אנלגזיה-** מורפיום 10-20 מ"ג+מידזולם 10-15 מ"ג I**M.**
    2. **ניקוז-** ראשית באמצעות מחט- ונפלון G18 המחובר למזרק, בין צלעות 6-9. הניקוז יהיה דורזלי בחשד לאויר וונטרלי בחשד לנוזל. בניגוד למבוצע באדם יש לבצע *ב-2 צידי בית החזה ( זאת בשל נטיית המדיאסטינום להיקרע בכלבים.*  
    3. **Open pneumothorax** לבצע חסימה של הפתח באמצעות ניילון/ שסתום חד כיווני ולחבוש מסביב לבית החזה.

****************** תמונה


#### 5. פגיעות אקלים
1. פגיעת חום: מנגנון הקירור המרכזי של הכלב- הלחתה. בדומה לאדם, פגיעת חום עלולה להתרחש ע"ר מאמץ גופני אשר אינו תואם את יכולות הכלב, בסביבה חמה ולחה. 
    1. תשישות חום- הכלב מלחית בכבדות, ריריות בצבע בורדו כהה , טמפ' רקטאלית >41.5, טשטוש והליכת "זיג/זג", הקאות/ שלשולים.
    2. Heat stroke- הופעת סימנים נוירולוגים: אגרסיה, רעידות, עוויתות ואף הופעת פטכיות ע"פ העור (כסימן ל DIC).
    3. **טיפול:** העברה למקום מוצל, פתיחת וריד ומתן נוזלים בקצב מהיר. הרטבת הכלב עד ספיגת כלל הפרווה במים מאזור הצוואר אחורנית. רצוי להשתמש במים קרים אך לא בקרח. הפסקת קירור חיצוני בהגעה לטמפ' 39.0.
    4. **יש לפנות את הכלב בהקדם מיד לאחר קירור.**
2. היפותרמיה: עקב חשיפה ממושכת לסביבה קרה ורטובה. טמפ' רקטאלית תהיה בין 32-37 בהיפותרמיה קלה- בינונית ( ומתחת ל 32 בהיפותרמיה קשה).
    1. טיפול: חימום מהיר אך הדרגתי ( 2 מעלות בשעה) , עד ל 38 מעלות צלזיוס. יש לייבש את הכלב, להכניסו לחדר מחומם, ניתן לשים שקיות חימום על החזה והבטן. 
#### 6. לסיכום: 
המענה הרפואי לכלבים אשר נוטלים חלק בפעילות המבצעית השוטפת בשיגרה ובחירום נשען על הצוותים הרפואיים האורגנים. מפעיל הכלב מיומן במתן מענה בסיסי בלבד לכלב ( הגשת ע"ר) וכן נושא עימו ציוד אשר יסייע למטפלים האורגנים להגיש סיוע. כמו כן, מפעיל הכלב יסייע בעיקר בריסון והחזקת הכלב בעת מתן הטיפול. 

## נספח א' - מינונים מקובלים בטיפול בכלבים
1. מורפין: 0.2-0.5 מ"ג/ ק"ג **IM** או SC כל 4-6 שעות. ( לא לתת IV).
2. אין לתת לכלבים אקמול או איבופן ( עלול להביא לפגיעה כבדית). אפשר לתת אופטלגין לפי 25 מ"ג/ ק"ג ו/או טרמדקס לפי 3-5 מ"ג/ ק"ג.
3. רוצפין 22 מ"ג/ק"ג **IV** כל 8-12 שעות.  (אנטיביוטיקה בכלבים בטראומה תינתן באותן ההתוויות כמו בבני אדם בהתאם לפרק "הטיפול האנטיביוטי בשדה")
4. פלג'יל 10-15 מ"ג/ ק"ג **PO** כל 12 שעות.
5. טשטוש עמוק: מידזולם 0.4 מ"ג/ ק"ג  + קטמין 3מ"ג/ ק"ג IM/IV.

****************** תמונה


****************** תמונה
