# הגישה לפציעות חזה

## עיקרי העדכונים:

-   19.5.22
    -   עדכון הגדרת שוק עמוק- כך שתואמת להגדרת שוק עמוק בפרק החייאת בקרת נזקים בשדה.
    -   העשרה בחמצן לכל פצוע עם פגיעת חזה משמעותית או טכיפניאה (ללא קשר לסטורציה)
-   24.1.2021:
    -   עדכון הפרוטוקול -- אינדיקציות לניקור וניקוז חזה.
    -   קבלת החלטות על בסיס מדדים נמדדים
    -   הגבלת מספר ניסיונות ניקור חזה (needle application)
-   1.2022
    -   עדכון מיקום חליפי נוסף לביצוע ניקור חזה- אפשרות לביצוע במרווח בין צלעי 5 (במיקום הזהה לנקז)
    -   עדכון מבנה הפרק
    -   דגשים להתקנת נקז חזה כולל מס' ניסיונות

## מבוא

פציעות חזה כרוכות בתחלואה ובתמותה משמעותיות. עם זאת, ניתן למנוע חלק משמעותי מהתמותה הזו ע"י זיהוי מהיר וטיפול יעיל בפציעה בשטח.

בית החזה בנוי מכלוב גרמי, המשתרע מהטבור ועד לבסיס הצוואר (מלפנים ומאחור), ומגן על מספר רב של איברים חיוניים לרבות הלב, הריאות וכלי הדם הגדולים, שפגיעה בהם טומנת בחובה סיכון גבוה לתמותה מיידית או מאוחרת. במתאר טרום בית החולים- ברוב רובן של פציעות החזה מסכנות החיים ניתן לטפל בניקוז של בית החזה במחט (להלן "ניקור חזה") או באמצעות החדרת נקז, זאת לצד העשרה בחמצן והחזר נפח באמצעות מוצרי דם על פי הצורך. רק מיעוט מפציעות החזה מחייבות טיפול כירורגי דפיניטיבי בחדר ניתוח (פחות מ 10% מהחבלות הכהות ו 15-30% מהחבלות החודרות).

חזה אוויר בלחץ היא פגיעת החזה מסכנת החיים הראשונה אותה עלינו לשלול. המדובר במנגנון פציעה אשר מייצר שסתום חד כיווני המוביל להצטברות אוויר בבית החזה, בין קרומי הפלאורה, מבלי יכולת לצאת, מה שמוביל לתמט של הריאה ולבסוף לדחיקת המדיאסטינום אל הכיוון הנגדי ולירידה בהחזר הורידי אל הלב. דבר זה מוביל למצב הלם (המכונה שוק חסימתי --obstructive). חזה אוויר בלחץ הינו אבחנה קלינית, שילוב של סימני פגיעת חזה לצד קיפוח נשימתי והמודינמי. הטיפול המרכזי בפציעה זו הוא ניקוז הלחץ- תחילה ע"י ניקור חזה במחט ובהמשך (לרוב בבית החולים) ע"י התקנת נקז חזה. פציעות חזה **מסכנות חיים** נוספות: - חזה דם מסיבי- מוגדר מסורתית ע"י איבוד של כליטר וחצי או שליש מנפח הדם אל חלל בית החזה. מאפיין בעיקר פגיעות חודרות בכלים גדולים בחזה. הטיפול המרכזי: ניקוז חזה לצד עירוי של מוצרי דם (בהמשך ידרש לעיתים טיפול ניתוחי). - חזה אוויר פתוח "שואב"- נגרם מחבלה משמעותית לדופן בית החזה אשר גורמת ליצירת פצע יונק דרכו נכנס אוויר מבחוץ (במקום שיכנס דרך קנה הנשימה). הדבר מוביל לפגיעה באוורור ולהיפוקסיה משמעותית. הטיפול- כיסוי לא אוטם של הפצע (3 צדדים) ובהמשך התקנת נקז חזה. - טמפונדה לבבית- נגרמת כתוצאה מהצטברות נוזל בחלל הפריקרדיאלי דבר אשר מוביל לירידה בתפוקה הלבבית משנית לירידה במילוי הלבבי. הטיפול יתבסס על העלאת Preload ויתכן שניקוז בבית החולים.

::: callout-important
## אבחנת חזה אוויר בלחץ

חשוב לזכור שאת הטריאדה 'הקלאסית' המתארת את הפגיעה (קולות לב מרוחקים, גודש ורידי צוואר ושוק) נדיר מאוד לזהות בשטח ועיקר הטיפול בטרום בית חולים מתרכז בטיפול בשוק- קרי, רסוסיטציה על פי פרוטוקול החייאת בקרת נזקים בשדה.
:::

חשוב להדגיש כי אין צורך בזיהוי ודאי של סוג הפגיעה בשטח ועל פי העיקרון של 'מטפלים במה שהורג קודם'- הטיפול בפגיעות חזה מסכנות חיים הינו **גנרי** ועיקרו: *העשרה בחמצן, ניקוז חזה והחייאת מוצרי דם (ראה פרוטקול מפורט).*

פציעות חזה נוספות אשר ראוי להזכיר: - קונטוזיה ריאתית- משנית לרוב לחבלה קהה משמעותית לבית החזה. דם ונוזלים אחרים אשר מצטברים ברקמת הריאה ומפריעים לאוורור וגורמים להיפוקסיה. חבלה זו יכולה להתפתח בהדרגתיות לאורך זמן עד ל 48-72 שעות ועיקר הטיפול בטרום בית החולים מתרכז בהעשרה בחמצן ואנלגזיה על פי רמת הכאב. ניקוז חזה אינו חלק מהטיפול. - חזה אוויר/דם 'פשוט'- כזה אשר אינו מלווה במנגנון חזה אוויר בלחץ או באיבוד דם מסיבי לחלל בית החזה ועל כן לרוב מזוהה רק בבית החולים (בצילום החזה או ב CT) ומטופל דפיניטיבית בבית החולים ע"י התקנת נקז חזה במקרים בהם היקפו רחב או הפצוע סימפטומטי. - Flail Chest -- מצב הנוצר מריבוי שברים בצלעות סמוכות (למעלה משני שברים, בכל אחת משתי צלעות סמוכות או יותר) ומאופיין בקושי בנשימה הנגרם מכאב וכן מקטע ריאתי בו מתקיימת "נשימה פרדוקסית". פגיעה זו תלווה לעיתים קרובות בקונטוזיה ריאתית. הטיפול העיקרי בשטח מתבסס על העשרה בחמצן וטיפול בכאב. - קונטוזיה לבבית -- משנית לחבלה קהה לבית החזה, ואחת הסיבות המובילות למוות מיידי או מוקדם מחבלות מסוג זה. קונטוזיה לבבית עלולה לגרום להפרעות קצב קטלניות ובשל כך מחייבת ניטור בבית החולים, **ללא אפשרות ממשית לאבחן או לטפל במתאר טרום בית חולים.**

שכיחות ואופי פציעות החזה משתנים בהתאם לעצימות העימות, לכלי הנשק המשמשים את הצדדים ולמיגון האישי של הלוחמים. בצה"ל, במלחמת לבנון השנייה פציעות חזה היוו 11% מכלל הפציעות, ואחוז פציעות חזה בקרב חללים עמד על 70%. במבצע "עופרת יצוקה" נצפתה ירידה משמעותית בשכיחות פציעות חזה (פציעות חזה היוו 7% מכלל הפציעות), ואת הירידה הזאת ניתן לשייך לשימוש במיגון קראמי. עם זאת, למרות הירידה בשכיחות, פציעה זו עדיין גרמה לתמותה משמעותית: 30% מהחללים סבלו מפגיעות חזה.

**מטרת פרק זה היא לשפר את ההכרות של המטפלים עם פגיעות החזה, ואת יכולות האבחנה והטיפול בהן.**

## פרוטוקול הגישה לפציעות חזה בשדה

\*\*\*\*\*\*\*\*\*\*\*\*\*\*תרשים

## ביאור הפרוטוקול

### 1. דגשים מרכזיים לפרוטוקול

1.  בהגדרת פציעות חזה נכללות פציעות מקו הטבור ועד לבסיס הצוואר (הן מלפנים והן מאחור).
2.  בטיפול בפציעות בית חזה יש להתמקד בזיהוי בעיות מסכנות חיים באופן מידי, אשר גורמות למוות בר מניעה (כגון חזה-אויר בלחץ), ולטפל בהן במהירות.
3.  בפציעות חזה משולבות במתאר בית החולים **שוק עמוק** (על פי ההגדרה המופיעה בפרק החייאת בקרת נזקים בשדה - RDCR) יכול לנבוע מאיבוד דם ועל כן במקרה של פציעת חזה המלווה בשוק- במקביל לטיפול בפציעת החזה נטפל במוצרי דם על פי אגרת בקרת נזקים בשדה.
4.  יש לתת העשרה בחמצן בריכוז הגבוה ביותר לכל פצוע עם פגיעת חזה משמעותית.
5.  ניקור חזה במכשיר ייעודי (Vygon / Tpak) הידוע גם בכינוי NA-Needle Application יתבצע במקרים של חשד להפרעה המודינמית על רקע חזה אוויר בלחץ.
6.  ניתן לחזור על פעולת ניקור החזה פעם נוספת רק אם לאחר הפעם הראשונה נצפה שיפור במצב הפצוע (המתבטא המודינמית בירידת הדופק/ עליה בלחץ הדם או שיפור במצב ההכרה)
7.  במידה ולאחר ניקור החזה ומתן הנפח לא נצפה שיפור במצב הפצוע יש לבצע הערכה מחדש- האם מצב הפצוע נובע מתהליך בין הפלאורות? במידה וכן יש להכניס נקז חזה.

### 2. זיהוי הפגיעה בשטח

יש להתייחס לפצוע כפצוע חזה בכל מקרה של חבלה חודרת מקו הצוואר ועד קו הטבור, מלפנים ומאחור, כולל בתי שחי וכתפיים. כמו-כן, חשד לפגיעת חזה צריך לעלות במקרים של חבלה קהה משמעותית לאזור החזה, וכן במקרים של פגיעות הדף, פגיעות מעיכה של החזה ופגיעות צלילה. חזה אוויר, עלול לקרות כסיבוך של טיפול רפואי, למשל בארוטראומה כתוצאה מהנשמה בלחץ חיובי, או במהלך פעולה פולשנית בצוואר, כדוגמת קוניוטומיה, החדרת עירוי לוריד הג'וגולארי החיצוני או נסיון החדרת וריד מרכזי לוריד התת-בריחי או הוריד הג'וגולארי הפנימי.

פרט לאנמנזה וזיהוי החבלה, תלונות של קוצר נשימה הינן שכיחות בפגיעת חזה, ותמונה של מצוקה נשימתית עד כדי כחלון ו"רעב לחמצן" עשויות להיות בולטות לעין. בנוסף בהתאם לאופי הפגיעה ניתן למצוא סימני הלם (עליה בדופק, ירידה בל"ד וסימני הלם אחרים) עד לסימני הלם עמוק בהתאם לכמות הדם אותה הפצוע יאבד. במהלך הבדיקה הגופנית חיוני לבצע הפשטה של הפצוע, ולבצע את הבדיקה תוך שימוש במקור אור. יש לחפש פציעות חודרות ( במתאר טרום בית חולים קשה לקבוע מה "כניסה" ומה פצע "יציאה")., חבלות נראות לעין ושינוי בצורה של בית החזה. האזנה לבית החזה יכולה לתרום אך מאתגרת במתאר טרום בית החולים ודורשת מיומנות. האזנה תתבצע דו-צדדית בבתי שחי ובגב, מבלי לעכב את ביצוע הסקר הראשוני או סקר ההחייאה. חשוב לזכור כי פגיעת חזה, במיוחד באזור התחתון (מתחת לקו הפטמות), עלולה להיות מלווה גם בפגיעה באיברי הבטן, עם כל המשמעויות לכך וגם להיפך - כל פציעה מעל לגובה הטבור תיחשב כפציעת חזה עד שהוכח אחרת.

**חשוב למדוד ולתעד רוויון חמצן (סטורציה) בכל נפגע חזה.** ערכי רוויון החמצן ישמשו אותנו בקבלת החלטות טיפוליות וקביעת קדימות הפינוי.

### 3. הטיפול בשטח

יש חשיבות גבוהה לזיהוי פגיעות מסכנות חיים, טיפול מהיר (שמורכב מניקור ו/או ניקוז חזה בהתאם לצורך, החייאת בקרת נזקים לפי התוויה וטיפול תומך הולם) ופינוי מתאים.

#### 1. **ניקור וניקור חזה**

פצוע חזה שסובל מעלייה בלחץ בתוך חלל בית החזה (בין אם כתוצאה מחזה אויר בלחץ או מחזה דם מאסיבי), זקוק לניקוז חזה באמצעות החדרת נקז חזה בין צלעות 4-5 בין הקו האקסילרי הקדמי והאמצעי, המחובר לשסתום חד כיווני. עם זאת, ניקוז חזה היא פעולה פולשנית, בעלת סיבוכים וסיכונים, מעכבת פינוי ומצריכה מיומנות. ניקור חזה במחט היא פעולה פשוטה ומהירה יותר שמטרתה לשחרר באופן זמני לחץ חיובי בבית החזה.

בעשור האחרון, לאור עדויות שהצטברו על כישלון בביצוע ניקור חזה בשימוש במחטים קצרות (50% הצלחה בביצוע ניקור חזה עם מחט של 5 ס"מ לעומת \>90% הצלחה תוך שימוש במחט של 8 ס"מ), עודכנו ההמלצות ב ATLS לשימוש במחטים ארוכות יותר של לפחות 8 ס"מ (כפי שצה"ל נוהג מזה זמן רב בשימוש ב Vygon). כמו כן, במהדורת הALTS האחרונה (10th), עודכנה גם ההמלצה לביצוע הניקור במיקום חליפי נוסף- בין צלעות 4-5 (במיקום הזהה למיקום נקז החזה). על כן, ניתן לבצע את פעול הניקור בשני אתרים: - בין צלעות 2-3, מיד קלוויקולרי (ולטרלית לקוו פטמות), מעל לצלע 3 - בין צלעות 4-5, בין קוו מיד אקסילרי לאנטריור אקסילרי, מעל לצלע 5

לאחר חיטוי מקומי, החדרת המחט תתבצע מעל לצלע ובזווית של 90 מעלות לבית החזה. בשימוש ב-Vygon יש לבצע חתך על העור עם סקלפל טרם החדרת המחט. המחט תוחדר עד המגרעת (ב-Tpak יש להחזיק אותה במקום במשך 5-10 שניות) ולאחר מכן יש לשלוף את המחט ולהשאיר את הקתטר במקום.

ניקור חזה במחט מתבצע במקרה של חזה אוויר בלחץ כדי להקל בעיקר על התסמינים ההמודינמיים, אולם הוא מביא לרוב תועלת זמנית בלבד ונושאת בחובה סיכונים גם כן. לכן, חשוב להבין היטב מתי עלינו לבצע ניקור/ניקוז חזה ללא היסוס, ומתי עלינו לעקוב, לתת טיפולים אחרים ולפנות את הפצוע במטרה שהטיפול הדפיניטיבי יינתן בדרג רפואי מתקדם יותר.

\*\*\*\*\*\*\*\*\*\*תמונה

תמונה מס' 1: מחט Vygon

\*\*\*\*\*\*\*\*\*\*8תמונה

תמונה מס' 2: מחט Tpak

#### התוויות לביצוע ניקור/ניקוז חזה

1.  **פציעת חזה מלווה בהלם עמוק**

הלם עמוק בפצוע חזה יכול להיגרם כתוצאה מאיבוד דם (הלם היפוולמי), כתוצאה מעלייה בלחץ בבית החזה וירידה בהחזר הורידי (הלם חסימתי), או משילוב של השניים. בפצוע חזה עם סימני הלם עמוק (על פי ההגדרה בפרק RDCR) עלינו לשלול מקור אחר לדמם, ולעצרו במידת האפשר. בהיעדר דמם אחר שיכול להסביר את ההלם העמוק, יש מקום לחשוד בחזה אוויר בלחץ או ב-Massive hemothorax. חזה אוויר בלחץ המתבטא בהלם עמוק הינו מצב מסכן חיים באופן מידי וישנה חשיבות למתן טיפול מהיר להפחתת הלחץ. לכן, בפצוע חזה עם סימני הלם עמוק, יש לבצע ניקור חזה (ב Vygon או Tpak ) -- קודם בצד הפגוע, ודו-צדדית במידת הצורך (לדוגמא כאשר לא ברור באיזה צד הפגיעה). אחוזי הכשלון בביצוע ניקור חזה אינם מבוטלים ומשתנים כתלות במחט שעושים בה שימוש ובמיומנות של המטפל. כישלונות נובעים לרוב **מהחדרה לא מספיק עמוקה** של המחט או החדרתה בזווית ( יש להקפיד על החדרה בצורה אנכית, 90 מעלות לבית החזה). על כן, יש להקפיד על שימוש במחטים המאושרות בצה"ל להתוויה זו (Vygon או T-pak). חשוב לזכור כי עקב נטיית הקתטר להיחסם ע"י קרישי דם או לעבור כיפוף שימנע את המשך פעולתו, הפעולה נותנת פתרון להצטברות לחץ בחלל בית החזה לזמן קצוב בלבד. לאחר ניקור חזה מקובל להתקין נקז חזה, **אולם לרוב אין צורך לעשות זאת בטרום בית-החולים,** אלא ניתן לבצע זאת בתנאים טובים יותר בבית החולים. לכן, לאחר ביצוע ניקור חזה במחט והתחלת טיפול במוצרי דם בהתאם לפרק "החייאת בקרת נזקים בשדה", יש להעריך את המצב ההמודינמי של הפצוע כעבור כ- 5 דקות.

שיפור לאחר ניקור חזה מוגדר כשיפור המודינמי- עליית לחץ דם, ירידה בדופק, שיפור במצב ההכרה.

במידה ולא הופיע שיפור לאחר ניקור והחייאת נפח והפצוע עדיין בהלם עמוק, אין ככה"נ טעם בניקור נוסף ויש לבצע ניקוז חזה.

בפצוע שהשתפר לאחר ניקור של בית החזה והתדרדר שוב, ניתן לבצע ניקור חוזר. במידה ומרחק הנסיעה לבית החולים בשלב זה הוא מעל ל-15 דקות, יש לבצע גם ניקוז של בית החזה. 2. **פציעת חזה עם רוויון חמצן נמוך מ- 85%למרות טיפול מיטבי תומך**

במתאר טרום בית החולים יש להתמקד בטיפול במצבים הגורמים למוות בר מניעה. בפציעות חזה עיקר המוות בר המניעה הוא כתוצאה מחזה אוויר בלחץ. יחד עם זאת ישנם מצבים של הצטברות אוויר/דם רב בחלל הפלאורלי אשר לא מייצרים לחץ שגורר הלם אך פוגעים משמעותית בחמצון. בערכי רוויון חמצן נמוכים, עקומת הדיסוציאציה בין המוגלובין-לחמצן היא תלולה והדרדרות הפצוע יכולה להיות מהירה. על כן, נדרש להגדיר סף תחתון שמחייב ניקוז בטרום בית החולים. ניקוז חזה במצבים כאלו עשוי לשפר את מצבו של הפצוע במידה והסיבה לבעיית האוורור היא הצטברות האוויר/הדם בחלל הפלאורלי, אך **לא תסייע** לפצוע עם פגיעה אחרת כגון קונטוזיה ריאתית. יש לזכור כי לפצועים אלו ביצוע ניקור חזה לא יסייע. לאחר כינוס ועדת מומחים, הוחלט כי הסף לניקוז חזה בנוכחות פציעת חזה יעמוד על **רוויון חמצן של 85%.**

אם כן, בפצוע חזה, אשר אינו סובל מבעיה בנתיב אוויר ,עם רוויון חמצן מתחת 85% למרות טיפול מיטבי תומך (חמצן באם קיים, ניהול נתיב אוויר בהתאם לפרק "נתיב האוויר -- הערכה וטיפול" וכן טיפול בכאב על פי התוויה) יש להתקין נקז חזה. אין מקום לביצוע ניקור חזה. לאחר הניקוז יש להקפיד על חבישה של פציעות חודרות בבית החזה, על מנת לאפשר ניקוז חד כיווני.

3.  **אובדן סימני חיים תוך כדי טיפול**

אובדן סימני חיים בשטח יכול להיות ביטוי לחזה-אויר בלחץ או חזה דם מאסיבי. לכן, בכל פצוע חזה שמאבד סימני חיים תוך כדי טיפול יש מקום לבצע ניקור חזה דו-צדדי, מתוך הבנה כי תתכן פגיעה דו-צדדית גם אם יש סימני חבלה בצד אחד בלבד, ומתוך הבנה כי מצבו של הפצוע הנו קשה מאוד והסיכוי להחמיר את מצבו נמוך מאד. הטיפול בפצוע המאבד סימני חיים תוך כדי הטיפול הינו בהתאם לכתוב בפרק *"סיום מאמצי החייאה וקביעת מוות בנפגע טראומה".*

#### 2. **טיפול בהלם עמוק**

הלם עמוק בפגיעת חזה עלול להיגרם כאמור כתוצאה מאובדן דם בכמות רבה, כתוצאה מחזה אוויר בלחץ, או שניהם. במצב של דימום, עם נפח דם ירוד ההשפעה של עליית הלחץ בבית החזה על ההחזר הורידי מועצמת. לכן בכל מקרה של הלם עמוק חשוב לטפל בפצוע בהתאם לפרוטוקול בפרק *"החייאת בקרת נזקים בשדה (RDCR)"*, לרבות החייאה במוצרי דם ומתן הקסקפרון וכמובן שלילת דימומים פעילים ממקורות אחרים ועצירתם.

#### 3. **טיפול תומך**

חשוב לזכור כי למתן חמצן ושיכוך כאבים יש משקל משמעותי בטיפול בהיפוקסיה שנגרמת מפגיעות חזה. כל פצוע חזה הסובל מכאב צריך לקבל טיפול אנלגטי מתאים, בהתאם לפרק "הטיפול בכאב בדרג השדה". בנוסף, לכל פצוע חזה עם פציעה משמעותית או טכיפניאה ניתן העשרה בחמצן בריכוז הגבוה האפשרי. כמו-כן, במידה וניתן, נשתדל לאפשר לפצוע לשבת, כדי לאפשר מכניקת נשימה טובה יותר, ונימנע ככל הניתן מהנשמה בלחץ חיובי שעלולה להחמיר את פציעת החזה.

#### 4. **חבישה**

חבישה של פצע חודר בבית החזה, במידה ולא בוצע ניקוז, תתבצע מ-3 צדדים בלבד, על מנת להימנע מכליאת אויר בחלל בית החזה. לאחר החדרת נקז חזה יש לבצע חבישה אוטמת ככל הניתן, על מנת לאפשר ניקוז חד כיווני (דרך הנקז בלבד). בכל מקרה, אם יש החמרה של התסמינים הנשימתיים או ההמודינמיים לאחר ביצוע החבישה, יש להסירה באופן מיידי.

#### 5. **הנשמה בלחץ חיובי**

בהנשמה בלחץ חיובי הסיכון להתפתחות חזה-אויר בלחץ עולה משמעותית. למרות זאת, לאור מורכבות הפעולה והסיכונים הכרוכים בה אין מקום לבצע ניקוז חזה פרופילקטי בצד הפגיעה. בפצוע מונשם יש להגביר עירנות ולנטר את הפצוע באופן תדיר. במקרה של התדרדרות בפצוע המונשם (הופעת סימני הלם או ירידת סטורציה מתחת ל-85%) יש לבצע ניקור חזה, ומיד לאחר מכן ניקוז חזה. בנוסף יש לזכור כי גם בהיעדר חזה אוויר בלחץ, בפצוע בהלם המעבר להנשמה בלחץ חיובי עלול לגרום להתדרדרות המודינמית משמעותית, ויש לטפל בהחזר נפח בהתאם לפרק "החייאת בקרת נזקים בשדה (RDCR)".

#### 6. **ניקוז חזה במתארי קיצון מבצעיים**

פצוע חזה שלא עונה על הגדרות המקרים אותם חייבים לנקז באופן מיידי (ראה לעיל) **לרוב ניתן וצריך לפנות ללא ביצוע נקז חזה,** בהשגחת מטפל בכיר. **במצבים נדירים ביותר**, בהם בשל תנאי קיצון מבצעיים אשר לא מאפשרים ניטור וליווי על ידי מטפל בכיר וכשמשך הפינוי גדול מ 15 דקות- ישקול המטפל הבכיר ביצוע נקז חזה גם לפצועי חזה שטופלו **בניקור חזה בהצלחה.**

#### דגשים ו Pitfalls מרכזיים בהתקנת נקז חזה

-   *מיקום:* פעמים רבות נמצא עצמנו נמוכים מדי ממה שתכננו על כן חשוב להיעזר בlandmarks האנטומים הקלאסים: קוו פטמות, קוו שיעור תחתון או קוו 'החזיה'- inframammary fold/creaseבנשים. כמו כן, באם קיימת התלבטות לגבי המיקום, תמיד נעלה מרווח צלעי אחד למעלה (צפאלית\סופריורית).
-   *חתך*: זה לא הזמן לבצע ניתוח זעיר פולשני, החתך צריך לפחות 2-3 ס"מ במקביל לצלעות. חתך קטן יותר יגרום לכך שגם אם נצליח להגיע לחלל הפלאורלי נתקשה להחדיר את הנקז.
-   *ווידוא מיקום והימנעות מ-false rout*e: עם החדירה לחלל הפלאורלי באמצעות המכשיר יש לפתוח את 'פיית' המכשיר ולהוציאו כשהוא פתוח (זאת על מנת להרחיב את הפתח בפלאורה וברקמות הרכות). פעולת החדירה לחלל הפלאורלי דורשת הפעלת כח אך יש לוודא כי החדירה עם הפאן אינה עמוקה מדי. לאחר מכן יש להכניס אצבע ולוודא כי המיקום נכון ('מאחורי הצלעות'- מדיאלית) וכן לפנות קרישים/ הידבקויות. הכנסת האצבע משמשת גם כפעולה טיפולית **(finger thoracostomy)** וגם כדי לשמש מראה מקום לקראת סיום הפעולה בהחדרת הנקז עצמו.
-   *החדרת הנקז*: יש להחדיר את הנקז על גבי מכשיר ולהחדירו עד לסימון על גבי הצינור. סימנים שהנקז ממוקם היטב יכול להיות יציאה של דם, תנועה של פלס הדם/ אוויר בצינור תוך כדי נשימה וכן אדים על הצינור בעת נשיפה.
-   *במקרה של כישלון* בהחדרת הנקז עצמו לחלל הפלאורלי בשני ניסיונות, נסתפק בחבישה לא אוטמת של הפצע ('3 כיוונים') ונתקדם בפינוי.
-   קיבוע: כמו בכל פעולה פולשנית, יש להקפיד על קיבוע נאות של הנקז. באם הנקז נשלף תוך כדי פינוי ומצבו של הפצוע אינו מתדרדר תחת ניטור מטפל בכיר אין הכרח בעצירת הפינוי להחדרה מחודשת (אלא להניח חבישה לא אוטמת ולהתקדם בפינוי).

## סיכום

1.  עלינו לזהות פגיעות חזה שמחייבות ניקור/ניקוז, ולטפל בהן בהקדם.
2.  התוויות מרכזיות לניקור חזה: פציעת חזה + סימני שוק או אבדן סימני חיים תו"כ טיפול.
3.  התוויות מרכזיות לניקוז חזה: פציעת חזה + שוק + היעדר שיפור לאחר ניקור או בפציעות חזה בליווי דה-סטורציה \<85% למרות תמיכה מיטבית בחמצן.
4.  אין לשכוח כי דמם הוא עדיין הבעיה השכיחה ביותר בשדה הקרב ולרוב הוא המוביל לסימני ההלם. על כן, לטיפול במוצרי דם בפצוע המצוי בשוק לצד פינוי מהיר לבית החולים חשיבות מכרעת בטיפול בפצועי חזה.
5.  כל פצוע מונשם נמצא בסיכון מוגבר להתפתחות חזה אויר בלחץ, יש לנטר באדיקות ולהגביר עירנות.
6.  אין צורך לבצע נקז חזה בפצוע ללא סימני הלם עמוק, שאנו מצליחים לשמור על חמצון טוב שלו.
7.  לטיפול תומך יש חשיבות רבה בטיפול בפגיעות חזה, ויש להוסיף משככי כאבים לכל פצוע הסובל מכאבים, וחמצן לכל פצוע עם רוויון חמצן נמוך מ-94% או כזה המתוכנן לפעולה פולשנית.
