# מעיכה

## סיכום דיון ועדת מומחים -- פציעות אגן וירך

#### 1. כללי

1.  בתאריך 21.12.2020 נערך דיון בנושא פציעות אגן וירך
2.  המשתתפים בדיון --
    1.  סא"ל ד"ר אבי בנוב -- רע"ן ענף הרפואה המבצעית (מומחה בכירורגיה כללית)
    2.  סא"ל ד"ר רן אנקורי -- רע"ן ענף רפואת אב"כ (מומחה באורטופדיה)
    3.  רס"ן ד"ר גיא אביטל -- סרע"ן ענף הרפואה המבצעית (מתמחה בהרדמה)
    4.  רס"ן ד"ר דודי סגל -- רמ"ד רפואה פצ"ן (מתמחה באורטופדיה)
    5.  סרן ד"ר שאול ג'ליקס -- ע רמ"ד קליני, ענף הרפואה המבצעית
    6.  ד"ר יורם קליין -- מנהל היחידה לטראומה וכירורגיה קריטית, ביה"ח שיבא תל השומר (מומחה בכירורגיה כללית, התמחות על בטראומה).
    7.  ד"ר ירון בר לביא -- מנהל אגף טיפול נמרץ כללי בקריה הרפואית רמב"ם (מומחה בהרדמה, התמחות על בטיפול נמרץ כללי).
    8.  ד"ר נחשון שזר -- מנהל יחידת טראומה אורתופדית, ביה"ח שיבא (מומחה בכירורגיה אורטופדית, התמחות על בטראומה אורטופדית).
    9.  ד"ר אסף אקר- רופא בכיר יחידת טראומה אורתופדית, ביה"ח סורוקה (מומחה בכירורגיה אורטופדית, התמחות על בטראומה אורטופדית).
    10. פרופ' גדי שקד -- מנהל יחידת הטראומה, ביה"ח סורוקה (מומחה בכירורגיה כללית, התמחות על בטראומה וטיפול נמרץ).
    11. ד"ר אלון שוורץ -- מנהל יחידת הטראומה, ביה"ח שערי צדק (מומחה בכירורגיה כללית, התמחות על בטראומה).
    12. ד"ר באלה מיקלוש -- מנהל יחידת הטראומה, ביה"ח הדסה עין כרם (מומחה בכירורגיה כללית).
3.  בטרם הדיון בוצעה סקירת ספרות על הנושאים בכותרת, לרבות מעבר על הנחיות מקבילות (TCCC, ATLS) וכן על מסמך קונצנזוס אשר פורסם על ידי ענף הרפואה המבצעית בעקבות ועדה דומה שכונסה במאי 2003 ואשר מסקנותיה לא יושמו במלואן.1

#### 2. רקע

בשנת 2003 נערכה ועדת מומחים אשר עסקה בטיפול בפציעות אורטופדיות במתאר טרום בית החולים. ממצאי ועדה זו פורסמו לאחר מכן גם בכתב עת מדעי. בהתייחס לפציעות אגן וירך מסקנות אותה הועדה היו: 1. **פציעות אגן:** 1. לאור הקושי להעריך יציבות אגן בשטח -- יש לקבע בעזרת סדין את האגן של כל מטופל עם כאב באגן כתוצאה מחבלה באנרגיה גבוהה. 2. **פציעות ירך:** 1. סד מתיחה (סד תומס) הכרחי לטיפול בפציעות ירך בכלל התרחישים (פינוי קצר וארוך) 2. שימוש בסד ייעשה בשברים מבודדים של הירך או בפציעות ירך עקב ירי בפצועים ללא פציעות מסכנות חיים נוספות. 3. בנוכחות פציעת אגן או פציעות נוספות באותה הגפה (קרסול, שוק), יש להניח את הסד ללא מתיחה.

הלכה למעשה, חרף המסקנות לעיל, השימוש הן בסד התומס והן בקיבוע אגן על ידי צוותי צה"ל הוא אנקדוטלי. יתרה מכך, אין הנחיה ענפית כרגע בנושאים הנידונים. על כן הושלמה סקירת ספרות וכונסה בשנית הועדה. \#### 3. סקירת ספרות פציעות אגן שבר באגן הוא פציעת לוחמה שכיחה וקטלנית. בקרב המתים במהלך הלחימה של צבא ארה"ב בעיראק ואפגניסטאן, ב- 16% הייתה מעורבות של האגן. נצפתה תמותה גבוהה יותר של פצועים עם שברים באגן שנגרמו כתוצאה מהדף או ירי.2 התמותה יכולה להגיע עד 40% בפצועים עם שברים מדממים באגן ואי יציבות המודינמית.3 בקרב פצועים במתאר צבאי, 76% משברי האגן הקטלניים הם תוצאה של פגיעות הדף, 15% פציעות ירי ו-4.5% תאונות דרכים.4 הטיפול הרלוונטי היחיד בשבר באגן בדרג השטח הראשוני הוא קיבוע.

חרף המחסור במחקר והוכחות חד משמעיות לכך שקיבוע אגן מפחית תמותה, זוהי פעולה מומלצת על ידי איגודים מקצועיים רבים לרבות: האיגוד העולמי לכירורגיה דחופה (WSES)5, האיגוד הצרפתי להרדמה וט"נ (SFAR)6, איגודים מקצועיים איטלקיים רב-תחומיים (כחלק מכנס קונצנזוס)7, האיגוד המזרחי לכירורגיה של טראומה (EAST)8, קונצנזוס מומחים סיני9 וכן איגוד הטראומה האחוד (JTS) בהנחיותיו לטיפול בשדה הקרב (TCCC).10 על פי מחקרים בגופות, מקבע אגן בגובה הטרוכנטרים והסימפיזיס פוביס מייצב שברים באגן ומצמצם את תנועתם. כמו כן, ישנן עדויות קליניות (אמנם חלשות) שמקבע אגן מצמצם צורך במנות דם ומפחית שכיחות דימום קטלני.10

על פי ה-WSES ישנה עדיפות לשימוש במקבע אגן ייעודי על פני קיבוע בסדין בשליטה על דימום באגן והם ממליצים שהקיבוע יתבצע בשלב ההחייאה המוקדם.5 ה-SFAR ממליצים לקבע את האגן של כל פצוע בשוק או מעורפל הכרה ולבצע את הקיבוע 'מוקדם ככל הניתן'.6 לפי ה-JTS קיבוע האגן יתבצע בשלב ה-C לכל פצוע אשר נפגע בחבלה קהה חמורה או במנגנון הדף ואשר לו: כאב באגן, קטיעה מלאה או חלקית של גפה תחתונה, בדיקה פיזיקלית מחשידה לשבר באגן, שוק או חוסר הכרה. 10

#### 4. סקירת ספרות פציעות ירך

סד התומאס אשר הומצא במאה ה-19 נכנס לשימוש מאסיבי יותר בעיצומה של מלחמת העולם הראשונה. שם על פי התיאור של Colonel H. W. Orr השימוש בסד הוריד את התמותה משבר בירך ב-80 אחוזים. הספרות המודרנית הנוגעת לסד התומאס דלה. מחקר אחד על נפגעי טראומה באיזור עירוני בארה"ב מצא בשנה 16/4513 (0.35%) מקרים של פגיעות ב- shaft של הירך, מה שמעיד על שכיחות נמוכה יחסית של הפגיעה.11

מחקר רטרוספקטיבי שפורסם לאחרונה ואשר התבסס על נתונים ממרשמי טראומה גדולים בארה"ב (NTRACS, Trauma one) כלל 579 פצועים מתוכן 218 עם פציעת ירך מבודדת.12 במחקר זה 30% מהפצועים קובעו בסד תומאס בטרום בית החולים והם נזקקו לפחות דם ושוחררו מאשפוז מהר יותר, יחד עם זאת ה-ISS של פצועים אלו היה נמוך יותר וכשנלקחו המקרים של פגיעת ירך מבודדת ההבדל בצורך בדם ומשך האשפוז נעלם. מחקר מדרום אפריקה אשר כלל 106 פצועים עם שבר מבודד של ה-shaft מצא כי הנחה מוקדמת (בטרום בית החולים) של סד תומאס הייתה קשורה בפחות צורך במנות דם ובפחות סיבוכים ריאתיים.13

בנוגע לסיבוכים אפשריים ממתיחת הסד. מאמר על 40 פצועי מולטי-טראומה שקובעו בסד תומאס מצא כי ל 15 (38%) היה מצב שיכול להיחשב להתוויית נגד למתיחת הסד (שבר באגן, פגיעה ברצועות הברך או שברים בעצם השוק/שוקית). המאמר לא התייחס להשלכות של אותן הנחות שבוצעו על אף התוויות הנגד.14

#### 5. השאלות שעלו בפני הועדה

1.  פציעות אגן:
    1.  באילו מצבים נקבע את האגן?
    2.  באיזה שלב במהלך הטיפול נקבע את האגן?
    3.  האם יש עדיפות למקבע אגן ייעודי בהשוואה לסדין?
2.  פציעות ירך:
    1.  באילו מצבים נקבע את הגפה בעזרת סד תומס?
    2.  האם ישנם מצבים בהם יש להנחות שלא לבצע מתיחה של הסד?
    3.  באיזה שלב יש לבצע את הקיבוע?

#### 6. סיכום החלטות הועדה

ראשית כל, הדגישו המומחים כי בטיפול טרום בית החולים פציעות אגן ופציעות ירך מובילות בראש ובראשונה **לסכנה המודינמית** ולא אורטופדית. לכן, הקיבועים שיבוצעו בטרום בית החולים בהקשר לפציעות אלו מטרתם העיקרית להפחית את הדימום. מעבר לכך הקיבועים יכולים לסייע בהפחתת הכאב. 1. **פציעות אגן:**

i.  **באילו מצבים נקבע את האגן?**

על פי חברי הועדה בקיבוע אגן במיקום נכון (*בגובה הטרוכנטרים*) יש סיכונים מועטים. היות שכך והיות שהקיבוע עשוי להיות בעל תועלת המודינמית, יש מקום להיות מתירנים במצבים בהם נבצע את הקיבוע. המומחים ממליצים על קיבוע אגן לכל פצוע עם מנגנון חבלה קהה/הדף משמעותיים ואנמנזה מתאימה לחבלת אגן וכן לכל פצוע עם פציעת ירי באגן או בהלם.

ii. **באיזה שלב במהלך הטיפול נקבע את האגן?**

חברי הועדה מסכימים כי קיבוע האגן אינו מצדיק עיכוב של פינוי הפצוע. הקיבוע יכול להתבצע גם במהלך הפינוי. הוסכם כי הפתרון המתאים ביותר הוא להכין את הסדין/מקבע על האלונקה בטרם העברת הפצוע אליה, ולהשלים את הקיבוע עם ההעברה לאלונקה, מבלי לעכב פינוי.

iii. **האם יש עדיפות למקבע אגן ייעודי בהשוואה לסדין?**

ישנה תמימות דעים שיותר קל לקבע את האגן נכון בעזרת מקבע ייעודי. היתרון גדול יותר עבור המטפל הלא מיומן ולכן ההמלצה של חברי הועדה היא על שימוש במקבע ייעודי בצה"ל.

2.  **פציעות ירך:**

i.  **באילו מצבים נקבע את הגפה בעזרת סד תומס?**

בהתייחס לשאלה זו, לאור הסיכון הנמוך לנזקים בעקבות הקיבוע והמשמעות ההמודינמית, חברי הועדה סבורים **שכל חשד** לשבר בירך (כגון המטומה בירך או דפורמציה וקיצור של הגפה) מצדיק קיבוע בעזרת סד תומס. בזמני פינוי ארוכים, היה קונצנזוס בקרב חברי הועדה שיש מקום להנחת הסד על ידי צוותי צה"ל. באשר לזמני פינוי קצרים יותר, מרבית חברי הועדה תומכים בשימוש בסד על ידי צוותי צה"ל.

ii. **האם ישנם מצבים בהם יש להנחות שלא לבצע מתיחה של הסד?**

ישנה תמימות דעים בקרב חברי הועדה שהסיכון לנזק בעקבות מתיחה של הסד קטן משמעותית מהתועלת האפשרית, זאת גם כאשר יש מעורבות של הקרסול, רצועות הברך או האגן. יתרה מכך, מציינים המומחים כי אין משמעות לשימוש בסד ללא מתיחה.

iii. **באיזה שלב יש לבצע את הקיבוע?**

בדומה לאותה השאלה בנוגע לקיבוע האגן, מדגישים המומחים כי קיבוע הירך לא צריך לעכב פינוי של הפצוע. ניתן ורצוי לבצע קיבוע בעזרת סד תומס במהלך הפינוי. \#### 7. סיכום ענף הרפואה המבצעית **רע"ן הרפואה המבצעית מודה למשתתפי הועדה ולמדור הקליני על הצגת התשתית המדעית הידועה כיום. לאור ממצאי הוועדה להלן החלטות רע"ן קפמ"צ:**

##### פציעות אגן

1.  מקבע אגן יושם על כל פצוע עם חשד לפגיעה אגנית עפ"י המנגנון (פיצוץ, חבלה קהה באנרגיה גבוהה, פציעת ירי) בשלב ההכנה לפינוי, לאחר הסקר הראשוני.
2.  לאור הסיכון בהנחה לא נכונה (בדגש על לחץ על הבטן) יש להכניס את הפעולה כחלק מהכשרת המטפלים הבכירים ואימוניהם.
3.  ענף רפמ"צ יוביל לשינוי תקינה ולהצטידות במקבעי אגן יעודיים. עד אז יש לצייד את הצוותים המטפלים בסדינים ולהדריכם בהתאם. מצ"ב נספח א' -- אופן קשירת אגן באמצעות סדין.

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* תמונה

תמונה 1: קיבוע אגן בעזרת מקבע ייעודי \##### פציעות ירך 1. סד תומס יונח ויימתח בכל מקרה של חשד לשבר בירך, אם מפציעה חודרת או קהה. 2.לאור הסיכון בהנחה לא נכונה (בדגש על לחץ על הקרסול) יש להכניס את הפעולה כחלק מהכשרת המטפלים הבכירים ואימוניהם. 3. יש להשתמש בסד תומס כחלק מכוננות הבט"ש וכחלק מציוד החירום בתאג"ד (בתרמיל סקר שניוני).

בברכה, ד"ר שאול ג'ליקס, סרן ד"ר גיא אביטל, רס"ן ד"ר אבי בנוב, סא"ל ע' רמ"ד קליני, ענף רפמ"צ סרע"ן ענף רפמ"צ רע"ן רפמ"צ

# נספח א' -- קשירת אגן באמצעות סדין

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* תמונה

שלב ראשון: טרם העלאת הפצוע פורסים סדין

שלב שני: מעבירים את הפצוע לאלונקה וממקמים במרכז האלונקה לרוחב (רוחב הסדין 25 ס"מ). כך שמרכז הסדין בגובה הטרוכנטרים.

שלב שלישי: אוחזים בשני קצוותיו של הסדין ומותחים

שלב רביעי: תוך שמירה על המתיחה מצליבים את כלפי מעלה קצוות הסדין

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* תמונה

שלב חמישי: תוך שמירה על מתח כל העת מבצעים שלושה סיבובים

שלב שישי: על מנת לסיים את הקיבוע מצניעים את הקצוות בתוך הקיבוע.

## בביליוגרפיה

<div dir="ltr">

1.  Melamed E, Blumenfeld A, Kalmovich B, et al. Prehospital care of orthopedic injuries. Prehosp Disaster Med. Published online 2007. doi:10.1017/S1049023X00004295
2.  Davis JM, Stinner DJ, Bailey JR, Aden JK, Hsu JR, Skeletal Trauma Research Consortium. Factors associated with mortality in combat-related pelvic fractures. J Am Acad Orthop Surg. Published online 2012. doi:10.5435/JAAOS-20-08-S7
3.  White CE, Hsu JR, Holcomb JB. Haemodynamically unstable pelvic fractures. Injury. Published online 2009. doi:10.1016/j.injury.2008.11.023
4.  Bailey JR, Stinner DJ, Blackbourne LH, Hsu JR, Mazurek MT. Combat-related pelvis fractures in nonsurvivors. J Trauma - Inj Infect Crit Care. Published online 2011. doi:10.1097/TA.0b013e31822154d8
5.  Coccolini F, Stahel PF, Montori G, et al. Pelvic trauma: WSES classification and guidelines. World J Emerg Surg. Published online 2017. doi:10.1186/s13017-017-0117-6
6.  Incagnoli P, Puidupin A, Ausset S, et al. Early management of severe pelvic injury (first 24 hours). Anaesth Crit Care Pain Med. Published online 2019. doi:10.1016/j.accpm.2018.12.003
7.  Magnone S, Coccolini F, Manfredi R, et al. Management of hemodynamically unstable pelvic trauma: Results of the first Italian consensus conf (coop guidelines of the Italian Society of Surgery, the Italian Assoc of Hospital Surgeons, the Multi-specialist Italian Soc of Young Surg, the Italian Soc o. World J Emerg Surg. Published online 2014. doi:10.1186/1749-7922-9-18
8.  Cullinane DC, Schiller HJ, Zielinski MD, et al. Eastern association for the surgery of trauma practice management guidelines for hemorrhage in pelvic fracture-update and systematic review. In: Journal of Trauma - Injury, Infection and Critical Care. ; 2011. doi:10.1097/TA.0b013e31823dca9a
9.  Zong Z wen, Chen S xu, Qin H, et al. Chinese expert consensus on echelons treatment of pelvic fractures in modern war. Mil Med Res. Published online 2018. doi:10.1186/s40779-018-0168-3
10. Shackelford S, Hammesfahr R, Morissette D, et al. The Use of Pelvic Binders in Tactical Combat Casualty Care: TCCC Guidelines Change 1602 7 November 2016. J Spec Oper Med. Published online 2017.
11. Abarbanell NR. Prehospital midthigh trauma and traction splint use: Recommendations for treatment protocols. Am J Emerg Med. Published online 2001. doi:10.1053/ajem.2001.21302
12. Campagne D, Cagle K, Castaneda J, Weichenthal L, Young M, Anastopoulos P SS. Prehospital traction splint use in midthigh trauma patients. J Emerg Trauma Shock. 2020;13(4):296-300.
13. Hoppe S, Keel MJB, Rueff N, Rhoma I, Roche S, Maqungo S. Early versus delayed application of Thomas splints in patients with isolated femur shaft fractures: The benefits quantified. Injury. Published online 2015. doi:10.1016/j.injury.2015.09.039
14. Wood SP, Vrahas M, Wedel SK. Femur fracture immobilization with traction splints in multisystem trauma patients. Prehospital Emerg Care. Published online 2003. doi:10.1080/10903120390936860

</div>

*-בלמ"ס-* מפקדת קצין הרפואה הראשי ענף רפואה מבצעית סיכום ודעת מומחים אוגוסט 2019

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* תמונות וסמלים

14.08.2019

### רשימת תפוצה- נספח א'

### סיכום דיון בנושא השימוש בקרש גב בשדה הקרב

#### כללי

1.  בתאריך ה12.08.2019 נערך דיון בנושא השימוש בקרש גב בשדה הקרב. 2.המשתתפים בדיון:
    1.  אל"מ ד"ר יובל רן, מפקד המשר"פ.
    2.  סא"ל ד"ר יעקב חן, רע"ן רפמ"צ.
    3.  רס"ן ד"ר רועי נדלר, רמ"ד קליני ענף רפמ"צ.
    4.  רס"ן ד"ר אלכס סורקין, רמ"ד רפואה מתקדמת בשדה, ענף רפמ"צ.
    5.  רס"ן ד"ר ניר צור, מדור קליני, ענף רפמ"צ.
    6.  סרן ד"ר אבישי צור ע.רמ"ד קליני, ענף רפמ"צ.
    7.  ד"ר רפי סטרוגו, סמנכ"ל רפואה מגן דוד אדום.
    8.  פרופ' יגאל מירובסקי, מנהל יחידת עמוד שדרה ביה"ח אסה"ר.
    9.  ד"ר ניסים אוחנה, מנהל מחלקת אורתופדיה בית החולים מאיר.
    10. פרופ' יונה קוזשוילי, מנהל מחלקת אורתופדיה ביה"ח קפלן.
    11. ד"ר איתי פריזם מנהל המערך האורתופדי סורוקה.
    12. ד"ר נמרוד רחמימוב, מנהל מחלקת אורתופדיה ביה"ח נהריה.
    13. ד"ר ג'וש שרודר, אורתופד יחידת עמוד שדרה ביה"ח הע"כ.
2.  מטרת הדיון הייתה לסקור את הספרות הרפואית בנושא, לבחון את הצורך בשימוש בקרש גב בשדה הן בהיבט של הפצועים שיקובעו לקרש הגב והן הפלטפורמה לקיבוע כמו גם לבחון את פרוטוקול הקיבוע המקובל כיום בצה"ל. לבסוף, נבחנו מרכיבים נוספים שצריכים להיעשות בטיפול בפצוע עמוד שדרה כחלק מסקר שניוני. בטרם הדיון הופץ מסמך שנכתב ע"י ענף רפמ"צ הסוקר את הנושא (נספח ב').

#### מהלך הועדה

-   בפתח הדברים **הודינו** לכלל המשתתפים על שהגיעו לקחת חלק בנושא המדובר.
-   המשכנו **בהצגת הנתונים** אודות פציעות עמוד שדרה החודרות והקהות על פי המנפ"צ.
-   בוצעה **סקירת ספרות** קצרה לרבות ההנחיות העדכניות בעולם בנוגע לקיבוע עמוד שדרה, יתרונות וחסרונות שימוש בקרש הגב, והמלצות לדיון.
-   הוצגו **ההנחיות הצה"ליות כיום** לפיהן
    1.  פצוע עם **חבלה קהה** יקובע במידה וישנה הפרעה להכרה/חשד להרעלה, חסרים נוירולוגיים, פציעה ממסכת ובעיית תקשורת.
    2.  פצוע עם **חבלה חודרת** יקובע במידה וקיימים חסכים נוירולוגיים המעלים חשד לפגיעה בעמוד השדרה.
-   הופנו **השאלות המרכזיות** למומחים בכללו
    1.  **מי** מהפצועים צריך להיות מקובע?
    2.  האם די להסתפק **באלונקה סטנדרטית על פני קרש גב** לקיבוע?
    3.  האם ישנם **אמצעים נוספים** שיש לנקוט בפצוע עם חשד גבוה **ל-Acute spinal cord injury?**

#### סיכום החלטות הוועדה

-   **באשר לשאלה שנשאלה "מי יקובע?"**

    -   **כלל הפצועים צריכים להיות מאובטחים לפלטפורמת פינוי בדמות אלונקה סטנדרטית**. אין מקום להיעזר בפרוטוקולים המוכרים של PHTLS מתוך הבנה כי המטפלים בשטח אינם מיומנים או מנוסים מספיק בבחינת תלונות נוירולוגיות סובייקטיביות, חסרים נוירולוגיים אובייקטיביים וכיוב'.

-   **באשר לשאלה שנשאלה "מהי פלטפורמת הקיבוע האידיאלית?"**

    -   **במהלך החילוץ**- יש לשקול שימוש ב"חצי קרש" או אמצעי קיבוע אחר לצורך הפחתת התנועתיות וכוחות הגזירה במהלך החילוץ וכן קיצור משך החילוץ כפי שמתואר בספרות.
    -   **במהלך הניוד והפינוי**
        -   **פציעות חודרות**- די לקבע לאלונקה סטנדרטית ללא צורך בקיבוע נוסף
        -   **פציעות קהות**- די לקבע לאלונקה סטנדרטית ובתנאי שניתן דגש על קיבוע הולם.

-   **בשלב הזה חברי הוועדה הסכימו כי קרש הגב אינו נותן מענה לקיבוע הולם שכן החלק הגבי שצפוי שיסבול מפגיעה גרמית (המעבר ה-thoracolumbar)** למעשה ממוקם על קרש הגב בצורה שאיננה נותנת מענה. כמו כן, פרופ' יונה קוזשוילי הציג את מאמרו לפיו שטח המגע בקרש גב סטנדרטי הינו נמוך לעומת שטח מגע המושג באמצעות אלונקה סטנדרטית בשילוב שמיכת שדה (איור מוצג).

-   **סוכם בין חברי הוועדה כי יש להעמיק ולרדת לפרטים בנושא הקיבוע לאלונקה לרבות:**

    -   שימוש בצווארון קשיח לקיבוע עמוד השדרה הצווארי **ללא שינוי**.
    -   שימוש ברצועות לקיבוע בדומה לקיבוע בקרש הגב על גבי החזה, האגן והגפיים התחתונות- **ללא שינוי**.
    -   שימוש בשמיכת שדה על גבי האלונקה לצורך העלאת שטח המגע והפנים בין הפצוע לבין האלונקה; **כך יינתן מענה הן לשטח המגע והן למניעת ההיפותרמיה.**
    -   **יש מקום לבחון קיבוע הולם שיוכן מבעוד מועד לקראת קבלת פצוע.**

-   **באשר לשאלה "מהם התהליכים הנוספים שצריכים להתרחש במסגרת הסקר השניוני לפצוע עם חסרים נוירולוגיים ברורים או חשד גבוה לפציעת עמוד שדרה שלמעשה עונה להגדרה- Acute spinal cord injury?"**

    -   מתן **נוזלים**- על פי תכנית נוזלים סטנדרטית תוך **ניטור סימני שוק**.
    -   יש להכניס **קטטר שתן**- תכליתו ריקון השלפוחית וניטור תפוקת השתן.
    -   יש להכניס **זונדה**- תכליתה ריקון הקיבה ומניעת אספירציה.
    -   אין מקום לטיפול בסטרואידים
    -   באם ניתן, יש לשקול ייעוץ **טלה-רפואה** למומחה עמוד שדרה; כלל המומחים בוועדה הביאו נכונות לקחת חלק בפרויקט מסוג זה.
    -   **דגשים לפינוי**:
        -   הפצוע מוגדר **כדחוף לפינוי**
        -   יש **לפנות את הפצוע** מוקדם ככל הניתן למקום בו יוכל להיות מנוטר כפצוע ביחידה **לטיפול נמרץ**.
        -   במהלך העברה של פצוע פאראפלגי/קוואדריפלגי יש לבחון את משטח ההשכבה לוידוא אחידות המשטח והיעדר **גופים זרים** שעשויים ליצור פצעי לחץ גם לאחר השכבה קצרה.

-   **הערות נוספות של חברי הועדה**

    -   יש מקום לשקול פיתוח של **חליף קרש גב** אלונקה שייתן מענה כפלטפורמה יחידה לחילוץ מרכב/רק"מ, לקיבוע עמוד שדרה לרבות שטח מגע הולם ולפינוי רגלי; חברי הוועדה ציינו כי אלונקת השדה הסטנדרטית אומנם נותנת מענה אך אבד עליה הכלח.
    -   יש מקום **לחדד ולתרגל** את נושא פגיעות עמוד השדרה באימוני צוותי הרפואה הצהליים בסדיר ובמילואים.

-   **בסיכום** הודה רע"ן רפמ"צ לוועדת המומחים בפגיעות אורתופדיות בעמוד השדרה שתרמו מזמנם בהתנדבות והגיעו לדיון ולענף רפמ"צ על ההירתמות לנושא החשוב והבוער המדובר מתוך רצון אמיתי לשפר את איכות המענה הרפואי בשטח לחיילים וללוחמים.

**כתבו: רס"ן ד"ר ניר צור, ענף רפואה מבצעית, מפקדת קצין רפואה ראשי.**

#### **נספח א'- רשימת תפוצה**

מקרפ"ר/מחלקת רפואה מבצעית/ענף הרפואה המבצעית/רע"ן מקרפ"ר/לשכה/קרפ"ר מקרפ"ר/לשכה/סגן קרפ"ר משר"פ 8280/רמ"ח שירותי הבריאות ומפקד המשר"פ מרפ"א 8282/מכלול מומחים/ ראש תחום אורתופדיה

<div dir="rtl">

# נספח ב'- השימוש בקרש גב בשדה הקרב- סקירת ספרות לקראת הדיון

## היסטוריה של השימוש בקרש גב

בסוף שנות ה-60 של המאה ה-20 החלו להופיע תיאורים הנוגעים לחבלות סמויות בעמוד השדרה שהובילו לאיחור באבחנה והופעה של פאראפלגיה בפצועים אשר סבלו מטראומה קהה בעיקר במתארים אזרחיים (תאונות דרכים)1. בשנת 1971 פרסם ארגון המנתחים האורתופדיים האמריקאיים את ההנחיות הראשונות למתאר קדם-בית החולים הנוגעים לשימוש בצווארון ולוח גב. ואולם, כבר בשנת 1979 מתארת סדרה של 100 מטופלים עם שיתוק מאוחר מתוך סדרה של 300 מטופלים עם שבר בעמוד השדרה משנית להיפוקסיה רקמתית, דחיסה של חוט השדרה על רקע בצקת או קונטוזיה, או מפגיעה ישירה באספקת הדם לחוט השדרה. אף אחד מהפגיעות המאוחרות לא הייתה מיוחסת ל-post injury spinal manipulation על ידי צוות רפואי או מחלצים מזדמנים.

ואולם, בשל החשש לתת אבחנה של פגיעה נסתרת בעמוד השדרה על ידי מטפלים במתאר PHTLS, היתרונות האפשריים של קרש גב במטופל עם שבר לא יציב בעמוד השדרה ובלא פגיעה נוירולוגית, העלות הנמוכה והקלות בשימוש; הפך השימוש בצווארון ולוח גב אוניברסלי לכלל הפצועים עם מנגנון פציעה שעשוי להביא לפגיעת עמ"ש פוטנציאלית.

למעשה ייעודו של קרש הגב הינו למנוע פגיעה בחוט השדרה בפצועים המתייצגים עם שבר בלתי יציב של עמוד השדרה וכן למנוע החמרה של פציעת חוט שדרה בלתי צפויה. קרש הגב יכול לסייע בשמירה על חוט השדרה במהלך חילוץ מרכב וכן כאשר יש להניע את הפצוע מספר רב של פעמים מאתר הפגיעה לכלי הפינוי. כאשר הפצוע מגיע כבר לכלי הפינוי השימוש בקרש הגב איננו ברור. למעשה, ישנם מחקרים המעידים כי שימוש בקרש גב מחמיר את הפציעות של מטופלים;

במאמר שהתפרסם ב1998 השוו את התוצאות של מטופלים שטופלו בשני אתרים עם ובלי קרש גב; הוכח כי הסכנה לפגיעה נוירולוגית הייתה גבוהה יותר במטופלים שקובעו לקרש גב.

## יתרונות השימוש בקרש גב

בעוד שבניתוח הספרות על השימוש בקרב גב ישנה עדות ליתרונות במהלך חילוץ מרכב או רק"מ, אין עדות כי קרש גב מונע הידרדרות של פגיעת עמ"ש במהלך העברה. \## חסרונות השימוש בקרש גב **כאב**- הכאב שמקורו בהשכבה על לוח הגב נובע הן מכאבים באזורי המגע והן מכאבים בעמ"ש ועמש"צ משנית למיקום אנטומי לקוי על גבי לוח הגב הישר. למעשה, גם אנשים בריאים ששכבו על לוח גב משך זמן קצר מדווחים על כאבים.

**בדיקות רדיולוגיות מיותרות**- כאשר צוות המיון מבצע הערכה של פצוע טראומה קיים קושי אינהרנטי להבחין בין כאב שמקורו בטראומה הראשונית לבין כאב שמקורו בשכיבה על קרש הגב. על כן, עשויים לעבור המטופלים בדיקות רנטגניות מיותרות הטומנות בחובן את הסיכונים לרבות עלייה בשיעור ממאירות, משך שהייה ארוך בחדר המיון ועלות למערכת הבריאות

**קיפוח נשימתי-** בבחינה שנעשתה למטופלים בריאים שקובעו לקרש גב נמצאה תבנית נשימתית רסטריקטיבית עם הקטנה של FVC ו-FEV1 7. יותר מכך, בפצועים עם פגיעות משולבות של חזה וריאות תועד שיפור במדדי הנשמה לאחר הסרה של הקיבוע לקרש הגב.

**פצעי לחץ-** במחקרים שבוצעו על מטופלים בריאים הוכח כי פצעי לחץ באיזורי המגע על קרש גב (Sacrum, occiput) מתחילים להופיע כבר 30 דקות לאחר הקיבוע, כלומר עוד קודם ההגעה לבית החולים.

למעשה, בשנת 2001 בוצע Cochrane הנוגע לשימוש בקרש גב אשר סיכם כי אין עדות מסוג Level 1 או RCT שהדגים את האפקט של קיבוע עמוד שדרה על תמותה, חסר נוירולוגי, יציבות עמוד שדרה ותופעות לוואי.

## השוואה בין קרש גב לאלונקה סטנדרטית

בניסיון לאתר השוואה במדדים של משך זמן, איכות הקיבוע ותופעות הלוואי של הקיבוע בין אלונקה סטנדרטית לבין קרש גב לא נמצא מאמר המשווה את השניים. האופציות הקיימות על מנת להשוות את שתי פלטפורמות הפינוי הללו הן:

1.  **מודל ממוחשב-** בשיח עם ענף חדשנות בשלב זה אינם מכירים מודל ממוחשב כמות זה שכן המודל מחייבים משתנים רבים (מקדמי החיכוך של החומרים מהם עשויים אמצעי הפינוי, כוחות גזירה וכיוב'). ואולם ב09.2019 עתיד להתקיים הקאתון של מד"א ומכללת אפקה שם ניתן יהיה לאתגר את הסטודנטים בצורך להשוות בין שתי הפלטפורמות.
2.  **מודל אדם**- במאמר שהתפרסם בשנת 2017 השוו מדדים של misalignment בין קרש גב לבין אלונקה מסוג Scoop stretcher במגוון תנועות באמבולנס (מהירויות, פניות וכיוב') והדגימו יתרון ל-Scoop stretcher 11. בנוסף, במחקרם פרופ' יונה קוזשוילי ואחרים השוו את שטח הפנים בפלטפורמות פינוי שונות; במאמר סוכם כי שטח הפנים המושג על גבי אלונקה סטנדרטית גדול יותר מאשר בקרש גב אלומיניום וגדל אף יותר תוך שימוש בשמיכת שדה סטנדרטית 12. ניתן לבצע מודל דומה בהשוואה בין אלונקה סטנדרטית לקרש גב. ואולם, מדידות כמות אלו לא בהכרח יש להן משמעות קלינית.

## השימוש בקרש גב בטראומה חודרת

**השימוש בקרש גב בטראומה חודרת הינו שנוי במחלוקת**. בשנת 2010 למעשה נבדקה סדרה גדולה של פצועי טראומה; רק 0.01% מהמדגם סבלו מפציעות עמוד שדרה בלי יציבות שדרשו התערבות ניתוחית. עוד הוכח כי פצועים אשר סבלו מטראומה חודרת וקובעו לקרש גב הדגימו שיעור תמותה גבוה לעומת אלו שלא קובעו

למעשה המלצות ה-prehospital emergency care מדווחות כי פצוע עם טראומה חודרת צריך להיות מושם עם צווארון על **גבי אלונקה סטנדרטית.**

במחקר שבחן קיבוע לקרש גב במתארים צבאיים סוכם כי מומלץ לא לקבע פצועים בשדה הקר לקרש גב באם סובלים מטראומה חודרת מבודדת 14.

## השימוש בקרש גב במתאר הצבאי

בארה"ב- נכון לסוף שנת 2008 סבלו 432 לוחמים אמריקאיים מפציעות עמוד שדרה במהלך המבצעים הלחימה בעיראק14. במאמר שסוקר את הפצועים, אופן הקיבוע ואת המהלך הנוירולוגי ממליצים הכותבים לבצע סלקציה של הפצועים שיקובעו לקרש גב על פי הקריטריונים המתוארים בתרשים. עוד במאמר מסכמים כי קיבוע אוניברסלי של כלל הפצועים בלחימה איננו חיוני ועשוי להיות יותר חמור ממועיל. ההמלצה הינה לקבע פצועים שאכן יש להם חשד לפגיעה בעמוד השדרה או חוט השדרה והללו צריכים להיות מקובעים עד שנשללה הפגיעה.

## בביליוגרפיה

<div dir="ltr">

1.  Geisler WO, Wynne-Jones M, Jousse AT. Early management of the patient with trauma to the spinal cord. Med Serv J Can. 22(7):512-523. http://www.ncbi.nlm.nih.gov/pubmed/5970010. Accessed August 14, 2019.
2.  Bohlman HH. Acute fractures and dislocations of the cervical spine. An analysis of three hundred hospitalized patients and review of the literature. J Bone Joint Surg Am. 1979;61(8):1119-1142. http://www.ncbi.nlm.nih.gov/pubmed/511875.
3.  Hauswald M, Ong G, Tandberg D, Omar Z. Out-of-hospital spinal immobilization: its effect on neurologic injury. Acad Emerg Med. 1998;5(3):214-219. http://www.ncbi.nlm.nih.gov/pubmed/9523928. Accessed August 14, 2019.
4.  EMS spinal precautions and the use of the long backboard. Prehospital Emerg Care. 2013;17(3):392-393. doi:10.3109/10903127.2013.773115
5.  Lerner EB, Billittier AJ, Moscati RM. The effects of neutral positioning with and without padding on spinal immobilization of healthy subjects. Prehosp Emerg Care. 2(2):112-116. http://www.ncbi.nlm.nih.gov/pubmed/9709329. Accessed August 14, 2019.
6.  March JA, Ausband SC, Brown LH. Changes in physical examination caused by use of spinal immobilization. Prehosp Emerg Care. 6(4):421-424. http://www.ncbi.nlm.nih.gov/pubmed/12385610. Accessed August 14, 2019.
7.  Bauer D, Kowalski R. Effect of spinal immobilization devices on pulmonary function in the healthy, nonsmoking man. Ann Emerg Med. 1988;17(9):915-918. doi:10.1016/S0196-0644(88)80671-1
8.  Walsh M, Grant T, Mickey S. Lung function compromised by spinal immobilization. Ann Emerg Med. 1990;19(5):615-616. doi:10.1016/S0196-0644(05)82211-5
9.  Berg G, Nyberg S, Harrison P, Baumchen J, Gurss E, Hennes E. Near-infrared spectroscopy measurement of sacral tissue oxygen saturation in healthy volunteers immobilized on rigid spine boards. Prehospital Emerg Care. 2010;14(4):419-424. doi:10.3109/10903127.2010.493988
10. Kwan I, Bunn F, Roberts I. on behalf of the WHO Pre-Hospital Trauma Care Steering Committee: Spinal immobilisation for trauma patients (Review) on behalf of the WHO Pre-Hospital Trauma Care Steering Committee. Cochrane Database Syst Rev 2001. 2001;(22):Art. No.: CD002803. doi:10.1002/14651858.CD002803
11. Gordillo Martín R, Alcaraz Ramón PE, Manzano Capel F, et al. \[Kinematic analysis of the spine during placement on 2 transfer devices: a spinal backboard and a scoop stretcher\]. Emergencias Rev la Soc Esp Med Emergencias. 2017;29(1):43-45. http://www.ncbi.nlm.nih.gov/pubmed/28825268. Accessed August 14, 2019.
12. Kosashvili Y, Backstein D, Ziv YB, Safir O, Blumenfeld A, Mirovsky Y. A biomechanical comparison between the thoracolumbosacral surface contact area (SCA) of a standard backboard with other rigid immobilization surfaces. J Trauma. 2009;66(1):191-194. doi:10.1097/TA.0b013e318156835c
13. Haut ER, Kalish BT, Efron DT, et al. Spine immobilization in penetrating trauma: More harm than good? J Trauma - Inj Infect Crit Care. 2010;68(1):115-120. doi:10.1097/TA.0b013e3181c9ee58
14. Kang DG, Lehman RA. Spine immobilization: prehospitalization to final destination. J Surg Orthop Adv. 2011;20(1):2-7. http://www.ncbi.nlm.nih.gov/pubmed/21477526. Accessed August 14, 2019.
15. Quinn RH, Williams J, Bennett BL, Stiller G, Islas AA, McCord S. Wilderness medical society practice guidelines for spine immobilization in the austere environment: 2014 update. Wilderness Environ Med. 2014;25(4):S105-S117. doi:10.1016/j.wem.2014.05.004

</div>
