# השלמת הסקר הראשוני

## הקדמה ורקע

תכלית הסקר הראשוני הוא באיתור מצבים מסכני חיים הדורשים התייחסות מיידית, טיפול במצבים אלו וכן איתור מצבים שיצריכו התייחסות במהלך סקר ההחייאה. בפרקים הקודמים בספר ("הסכמה -- הטיפול בפצוע טראומה בשדה", "הטיפול תחת אש ובטיחות הטיפול", "נתיב אוויר -- הערכה וטיפול", "נשימה -- הגישה לפציעות חזה בשדה" ו"החייאת בקרת נזקים בשדה") תוארו הפעולות שמבוצעות בשלבים S-C להערכת מצבו של הפצוע וכן תוארו בהרחבה הפרוטוקולים שמתווים את דרך הטיפול בהתאם לממצאים שעולים. מרבית הפציעות מסכנות החיים יאותרו בשלבים אלו.

על אף האמור לעיל, השלמת הסקר הראשוני כוללת את השלבים D ו-E. בשלבים אלו מבצעים הערכה נוספת ומעמיקה יותר של הפצוע במטרה לאתר פציעות מסכנות חיים שפוספסו וכאלו שעשויות לגרום לתחלואה ונכות קשים ולטפל בהתאם, כמו גם נערכים לפינוי הפצוע ומצמצמים אובדן חום הקשור בתמותה מוגברת.

## שלב ה -- D

בשלב זה תתבצע קודם כל הערכה חוזרת של מצב ההכרה בסולם A.V.P.U. הערכת ההכרה בשלב זה מבוצעת תחת הבנה טובה יותר אודות מצבו של הפצוע ופציעותיו.

הערכה נוספות שיש לבצע בשלב זה הינה של תנועות הגפיים וזאת כסימן לפגיעה מוחית ו/או פגיעה בעמוד השדרה. להערכה זו השפעה על אופן הקיבוע של הפצוע לאלונקה כפי שמפורט בפרק "פציעות עמ"ש". לבסוף, בשלב זה מתבצעת הערכה של רמת הכאב של הפצוע, וזאת על מנת לטפל בהתאם במהלך סקר ההחייאה וכפי שמפורט בפרק "הטיפול בכאב בדרג השדה".

## שלב ה-E

פספוס פציעות בקרב נפגעי טראומה היא תופעה שכיחה ומסוכנת. הפציעות המפוספסות עשויות להיות חסרות משמעות קלינית בשלב של טרום בית-החולים, אך לעיתים הן בעלות משמעות קלינית ואף עלולות להיות מסכנות חיים. במתאר טרום בית החולים אמצעי אבחון שונים, דוגמת דימות, אינם זמינים. הפשטה מלאה מכף רגל ועד ראש, הפיכה וחיפוש אקטיבי של פציעות (לרבות נעליים ואזורים מוצנעים) הן הפעולות החשובות ביותר למניעת פספוס פציעות במתאר טרום בית החולים. חשוב לזכור כי מבין סיבות המוות בר הצלה בפצועי טראומה, דימום הוא הסיבה המובילה, לכן במהלך ההפשטה יש לשים דגש על איתור ועצירה של דימומים.

היפותרמיה מהווה חלק מ"משולש המוות" של הטראומה וקשורה בעלייה בתמותה. אובדן חום מהגוף בבני אדם מתרחש בארבעה מנגנונים עיקריים:

1.  הולכה -- אובדן חום ישיר ממגע עם עצם דומם (קרקע)

2.  הסעה -- אובדן חום לאוויר או מים זורמים

3.  הקרנה -- הקרנה של חום גוף לסביבה (ללא קשר למגע ישיר)

4.  הזעה (אידוי)

לכן, תוך כדי הפשטת המטופל לאיתור פציעות נוספות, יש להעלות את המטופל לאלונקה (גם לצורך מוכנות לפינוי וגם לצורך הפרדתו מהקרקע) ולכסותו בשמיכה ובשמיכת מילוט. במידה וזו בנמצא מומלץ להניח שמיכת חימום אקטיבית Ready Heat (לא ישירות על הגוף, אופטימלית: שמיכה -\> Ready Heat -\> שמיכת מילוט). במידה וקיימת אינדיקציה לכריכת אגן, זו תבוצע תוך כדי העמסה לאלונקה.

עד תום שלב זה יקבע המטפל את דחיפותו של הפצוע בהתאם לכלל הממצאים בסקר הראשוני. כאן המקום להעביר דיווח תואם ועדכני. הדיווח כולל פרטים אודות המתאר (ירי, פיצוץ, נפילה מגובה וכו'), אזורי הגוף העיקריים שנפגעו, הגדרת דחיפות, ביטוי פיזיולוגי (הלם עמוק, היפוקסיה, שינוי במצב הכרה וכיוצ"ב), מדדים חיוניים רלוונטיים, ודרישות סיוע (רפואי ופינוי). הדיווח בשלב הזה חשוב ביותר כיוון שהוא קורה לאחר כלל שלבי ההערכה של הפצוע. דיווח נכון מאפשר הקצאת משאבי פינוי תואמים. יתרה מכך, הדיווח מכין את הדרג הטיפולי הבא לקליטת הפצוע דבר שיאפשר טיפול רפואי טוב יותר. לבסוף, עצם הניסוח של דיווח רפואי סדור ואיכותי מסייע לצוות המטפל לבצע בקרה עצמית ולתת טיפול טוב יותר.

## סיכום

פרק זה עוסק בשלבים אשר "סוגרים" את הסקר הראשוני. סקר ראשוני טוב הוא זה שיניח את התשתית לטיפול מיטבי בפצוע. ביצוע מהיר ואיכותי של הפעולות המתוארות בפרק זה, לרבות: הערכה נוירולוגית גסה, הפשטה מלאה של הנפגע, סריקת פציעות, טיפול בפציעות מסכנות חיים, מניעת היפותרמיה, דיווח רפואי איכותי ופינוי, הוא מרכיב מרכזי בטיפול נכון בפצוע על מנת לשפר את סיכוייו לשרוד.
