# פציעות עיניים

## עיקרי העדכונים
- 1/22 
    - כתיבת הפרק

## הקדמה
שטח העין מהווה 0.1% מכלל שטח הגוף, ולמרות זאת, פגיעות עיניים מהוות כ-8%-13% מכלל הפציעות בשדה הקרב המודרני. חלק  גדול מן הפציעות בשדה הקרב המודרני הן פציעות רב מערכתיות הכוללות בנוסף לפגיעה בעיניים טראומת ראש וגפיים עליונות. שדה הקרב הוא מקור בלתי נמנע למגוון פגיעות עיניות, החל משריטות קלות, ועד לפציעות חמורות עם אובדן מוחלט של הראיה או אף אובדן של גלגל העין עצמו. בסדרות שונות דווחה פציעת עיניים דו צדדית ב15-25% מהמקרים.

אחוז פגיעות העיניים מכלל מקרי הטראומה עלה מכ-2% במלחמת העולם השניה, ל-2.8% במלחמת קוריאה ועד כ-9% במלחמת וייטנאם ו-13% במהלך המבצעים הצבאיים בעירק. במלחמות ישראל מגמה דומה בעיקרה, כ-6% במלחמת ששת הימים, כ7% במלחמת יום כיפור, כ7% במלחמת לבנון הראשונה, כ-9% במלחמת לבנון השניה ו-11% במבצע "עופרת יצוקה".  ב"צוק איתן" כ-6%.

העליה בפציעות עיניים מיוחסת לשימוש בנשק המפיץ רסיסים, כגון מטעני חבלה, RPG וכד'. הנזק יכול להגרם במנגנון הדף ראשוני – לחץ כתוצאה מגל האנרגיה של הפיצוץ או הדף משני – רסיסים וחלקיקים במהירות גבוהה. אלו הם מנגנוני הפציעה הנפוצים בעימותים ארוכי טווח, בעולם ובישראל. פציעות רסיסים הן על פי רוב מרובות. 

לפגיעה או אובדן של חוש הראיה יש השלכות מרחיקות לכת שכן פגיעות עיניים דורשות בחלק גדול מן המקרים פינוי, ובכך בטווח הקצר יכולות לגזול משאבים יקרים ומצומצמים, לסכן את הלוחמים האחרים ואף לפגוע בהצלחת המשימה, ובטווח הארוך לפגוע בכשירות קרבית או בכשירות לשירות, ובכלל פגיעה מהותית באיכות החיים, לרבות מוגבלות תפקודית משמעותית ונזק נפשי משני בסביבה הצבאית והאזרחית. 

עבור המטפל בדרג השדה ניהול המטופל עם פציעות עיניים משמעותיות עלול להיות מרתיע ומתסכל, בין היתר בשל חשיפה מינימלית במהלך ההכשרה, היותה של העין עדינה ורגישה וחשש מהחמרת הפציעה. אפשרויות הטיפול בפגיעות עיניים בתנאי השדה הן מוגבלות, ומטרת הטיפול העיקרית היא מניעת החמרה, עד לטיפול דפיניטיבי ע"י רופא עיניים שברשותו הכלים הנדרשים לאבחנה ולטיפול.

## פרוטוקול

***************** תרשים

## ביאור הפרוטוקול
### כללי
כאמור, יכולת הטיפול בפגיעות עיניים בתנאי השדה מוגבלת. מטרת הטיפול העיקרית היא מניעת החמרה, עד לפינוי לצורך אבחנה וטיפול דפיניטיביים ע"י רופא עיניים.

ממצאים וסימנים המבטאים פגיעה משמעותית ומחייבים זירוז דחיפות הפינוי:

- אובדן ראיה, פגיעה בחדות הראיה או התדרדרות מהירה בחדות הראיה
- פגיעה בשלמות גלגל העין או ממצאים אחרים בבדיקה המרמזים על נזק משמעותי – אישון שאינו עגול או סימטרי או שהינו מורחב, דימום בלשכה הקדמית (היפמה)
- חשד לדימום רטרו-בולברי: בלט  עין, אובדן ראיה, תגובת אישון אפרנטית חיובית (RAPD) בצד הפגוע או מהלך קליני עם החמרה מהירה –canthotomy+ cantholysis תוך עד שעתיים בבית חולים. 
- כווייה כימית – לאחר שטיפה מרובה כמתואר.

### שימוש במשקפי מגן לצורך מניעה
לעין מנגנוני הגנה טבעיים, הארובה הגרמית, העפעפיים, הדמעות. מנגנונים אלו אינם מספקים לצורך הגנה מפני פציעות חודרות. משקפי מגן מגנים על גלגל העין והרקמות הסמוכות ע"י יצירת מחסום לפגיעות מכאניות, כימיות, ביולוגיות ,רדיואקטיביות ותרמיות. הן במנגנון של הפחתת חדירת גופים זרים וכימיקליים והן במנגנון של פיזור עצמת הטראומה הקהה הרחק מהעין והרקמות הסמוכות.

כבר משחר ההיסטוריה ניתן למצוא סיפורים על פציעות חודרות לעין ולארובה שגרמו למוות. החל ממעשה "דוד וגוליית" בו נהרג גוליית כתוצאה מחדירה של אבן הקלע דרך הארובה, ועד למלך הנרי השני באנגליה, שהשתתף בדו-קרב תחרותי בשנת 1559 וכיוון שלא הידק את קסדתו ומגן העיניים, חדר לארובת העין שלו שבב עץ מחנית יריבו, חדירת הגוף הזר גרמה לצלוליטיס אורביטלית שהביאה לבסוף למותו. החשיבות הקריטית להגנה מספקת על העין ועל המבנים הסמוכים, נצפתה כבר בימי קדם. הביטוי לכך הוא שימוש בשריון הגנה שכלל קסדות ומגיני עיניים בחיילים עוד בתקופה היוונית – רומית.

במלחמת העולם הראשונה פותחו מסיכות הגז בכדי להגן על העיניים ולמנוע שאיפת גז. ב-1977 פורסמו סטנדרטים להגנה על העיניים. ההתקדמות הטכנולוגית בשנות ה-80 וה-90 שיפרה משמעותית את יעילות משקפי המגן. השימוש בפוליקרבונט כתחליף לזכוכיות ופלסטיקים עבים בעבר, שינה את תכנון משקפי המגן והפך אותם לקלים ושמישים יותר. הגנה מקרינת -UV גם הוכנסה כסטנדרט.  רשימת הAuthorized Protective Eyewear List – (APEL) שפורסמה בארה"ב ב2004 כוללת התייחסות לפרמטרים הבאים: משקל, תכונות אופטיות, שדה ראיה, ולא רק את העמידות לפגיעה, על מנת לשפר את ההיענות לשימוש. 

צה"ל אימץ את ה-APEL בשנת 2012, ומשקפי המגן המודרניים מסוג Revision Sawfly (Revision Military LTD.) כוללים מתאם לעדשות אופטיות. בסדרות שונות מן הארץ והעולם, שימוש במשקפי מגן היה בקורלציה לחדות ראיה טובה יותר לאחר הפציעה ובמניעת הפציעה ונזק משמעותי לעין בעד 90%. למרות היתרונות הברורים, ההיענות לשימוש במשקפי מגן נותרה נמוכה, קיימות תלונות על טשטוש ראיה, אדים ופגיעה בשדה הראיה.  ולכן קיימת חשיבות רבה לחינוך הלוחמים ועידוד השימוש במשקפי מגן ע"י המפקדים והרופאים בשטח.

### חדות ראיה (Visual Acuity)
חדות הראיה, מהווה את הפונקציה של העין, והיא הסמן הפרוגנוסטי המשמעותי ביותר לתוצאה הראייתית של הפציעה. זו גם אינדיקציה טובה לדחיפות הפינוי. ככל שחדות הראיה גרועה יותר – גוברת קדימות הצורך בפינוי. יש להקפיד לבדוק חדות ראייה בכל עין בנפרד כשהאין שאיננה נבדקת מחוסה היטב בבד/חבישה/ידנית. בדיקת חדות הראיה תוך שימוש בלוח סנלן או אפליקציה מקבילה עדיפה, אך בד"כ אינה זמינה ואינה פרקטית למגיב ראשוני, ולכן Godbole ושות' הציעו שיטה אובייקטיבית לבדיקה מהירה בשטח, הערכת חדות הראיה באמצעות ניסיון לזהות תגי שם ודרגות על מדי הבודק, והקבלתם ללוח סנלן, אך בפועל כל שיטה אובייקטיבית מספקת. אפשרות פרקטית ברמת השטח – טופס 101. העובדה שהמטופל הצליח לקרוא אותיות ממרחק מסוים, לעומת חדות ראיה שאינה מספקת לקריאת אותיות – ספירת אצבעות, תנועות ידיים, תפיסת אור או העדר תפיסת אור, יכולה לעזור לרופא העיניים בהמשך בהערכה הראשונית. להערכה ראשונית של חדות הראיה חשיבות נוספת, שכן לעיתים במטופלים עם פציעות חמורות בהם נדרש אשפוז בטיפול נמרץ והרדמה, לא יהיה ניתן להעריך את חדות הראיה במשך ימים לאחר מכן.

### בדיקת כלל מבני העין (Best exam of Both eyes)
יש לשאוף לבצע את הבדיקה הטובה ביותר האפשרית של שתי העיניים. תחילה כאמור להעריך את חדות הראיה ובהמשך להעריך את מבני העין באופן שיטתי בעזרת פנס. על מנת שלא לפספס פציעות פחות בולטות, מומלץ להתחיל את ההערכה בעין הנראית פחות פצועה. הערכת העין תתבצע מן החוץ – פנימה ועליה לכלול הערכת העפעפיים לקרעים, הערכת מנח העין - בלט עין (פרופטוזיס) שקיעת העין (אנופתלמוס) ובצקת פרי-אורביטלית משמעותית. בחשד לדימום רטרו-בולברי הטיפול הנדרש הוא ביצוע  lateral canthotomy  + cantholysis מוקדם ככל הניתן ולא יאוחר משעתיים (ראו איור 6).  פעולות אלו יבוצעו בחירום בבית החולים. 

************* תמונה

איור 6: Lateral Canthotomy and Cantholysis
Iserson KV, et al. Orbital Compartment Syndrome: Alternative Tools to Perform a Lateral Canthotomy and Cantholysis Wilderness Environ Med. 2016 Mar;27(1):85-91. doi: 10.1016/j.wem.2015.09.002.

זו פרוצדורת הבחירה לטיפול בתסמונת מדור ארובתית. מטרתה להגדיל את חלל הארובה ובכך לאפשר הצטברות הדם באופן שבו יפחת הלחץ על עצב הראיה. הפרוצדורה מבוצעת ע"י חיתוך הזוית הלטרלית של העפעף התחתון לכיוון גבול העצם בשולי הארובה. חיתוך זה חושף את ה-crus התחתון של ה-lateral canthal tendon. לאחר מכן יש לבצע inferior cantholysis ע"י חיתוך ה-lateral canthal tendon ושחרורו מחיבורו אל העפעף התחתון. אם הפעולה בוצעה באופן נכון, העפעף יהיה משוחרר לחלוטין.

לאחר מכן יש להעריך את גלגל העין, הלחמית, לובן העין (סקלרה) והקרנית להמצאות חתכים, דימומים, גופים זרים, ופריצת תוכן מחלל העין (שיכול להראות כלכלוך). יש להעריך את שקיפות הקרנית ואת מיקום הקשתית והאישון. האם האישון עגול ומרכזי או מוסט? האם יש דם בלשכה הקדמית מאחורי הקרנית (היפמה)? יש להמנע מהפעלת לחץ על העין. אם בצקת בעפעפיים מונעת את פתיחתם, יש להשאיר את הבדיקה לרופא עיניים. 

### הערכת המבנים הסמוכים לגלגל העין, המנעות מהסרת עדשות מגע (Contiguous structures, Contact lenses)
בדיקת העיניים חייבת לכלול הערכת המבנים הסמוכים לאיזור הפציעה הברורה. אם העין נפצעה, האם נפצעו מבנים אחרים בפנים? אם הפצוע סובל מפציעה מסכנת ראיה, חשוב לוודא שלא מפספסים פציעה המסכנת חיים באופן פוטנציאלי כתוצאה משברים בפנים ובגולגולת או לצרציות בקרקפת. האם למטופל יש שברים או פציעות פנים שיכולות להביא לדקומפנסציה של נתיב האויר? אם לפצוע יש חתך באיזור הלחי – יש לבדוק המשכיות לתוך העפעף. אם יש חתך בעפעף -  יש להעריך את מערכת ניקוז הדמעות ולחפש קרעים בקנליקולי, וכן להעריך את שלמות גלגל העין. הקרנית היא המשכית ללובן העין (הסקלרה) וללחמית. ולכן אם יש קרע בקרנית – יש לבחון את שלמות לובן העין. 

העיניים המשכיות לעפעפיים ולארובה, אשר המשכית לסינוסים ולמוח. יש לבדוק בהתאם ולתת לכך את הדעת. יש לשים לב לעדשות מגע, גם במקרה שאין פציעה של העין. בחולה מורדם או שאינו משתף פעולה, קיים חשש שיעבור זמן רב עד שיבחינו בעדשות מגע, מה שמעלה את הסיכון לזיהומים בעין. עם זאת הסרת עדשות מגע בסביבה שאינה מבוקרת אינה מומלצת. במידה וזוהו עדשות מגע, יש להעביר את המידע לדרג המטפל הבא ולתעד בטופס 101, על מנת שהמידע יגיע בסופו של דבר עם הפצוע לביה"ח.

### תרופות, ומה לא לעשות: (Drugs, Don’ts)
כאשר קיים חשש לפציעה חודרת לעין – יש להתחיל טיפול אנטיביוטי בהתאם למתואר בפרק "הטיפול האנטיביוטי בשדה" כאשר ההתייחסות היא כחבלת ראש. הקרנית והסקלרה אינן אלסטיות ולכן בפציעות החודרות את גלגל העין, תוכן מתוך העין יכול לפרוץ החוצה עקב הפעלת לחץ חיצוני, וולסלווה, הקאות או תמרונים אחרים, ולכן יש להמנע מהפעלת לחץ על העין ולטפל בכאב (כמתואר בפרק "הטיפול בכאב בדרג השדה") ובחילות באופן ליברלי, גם על מנת למנוע עליית לחץ דם הנגרמת כתוצאה מהכאב. 

כאמור, אין להפעיל לחץ על העין ובכלל זה לא לבצע אולטרא-סאונד. אין  להזליף טיפות, לחבוש את העין או את הראש מעל עין שאינה מוגנת. טיפות או משחות יכולות להיות טוקסיות למבנים תוך עיניים שפרצו החוצה. יש להזהר בעת מתן תרופות אשר משרות בחילות / הקאות, כדוגמת פנטניל או מורפין ובכל חשש לתת לפצוע טיפול בפרמין.

### מגן לעין ופינוי (Eye-shield, Evacuate)
הגנה נכונה על העין ע"י מגן מפלסטיק קשיח, מתכת, משקפי מגן או ע"י מגן מאולתר מכוס פלסטיק/נייר מהגבות ועד ללחיים ללא מגע בגלגל העין וללא תחבושות, חשובה ביותר עד לטיפול דפנטיבי. חשוב לקבע את המגן, ולוודא את נוכחותו בכל דרג טיפולי. חבישת לחץ מכל סוג שהוא אסורה. יש להרים את הראש, אם ניתן. הרמת הראש מורידה את הלחץ הורידי ואת הלחץ בעין. ולפנות את הפצוע לבדיקת רופא עיניים בהקדם.

## רקע
### אנטומיה
#### אנטומיה של העפעפיים ומערכת ניקוז הדמעות
תפקיד העפעפיים – הגנה על משטח העין הקדמי ופיזור הדמעות על פני משטח העין באמצעות המצמוץ. העפעפיים מורכבים מן החוץ-פנימה מעור, תת עור, שריר האורבקולריס, הטרסוס – רקמת חיבור קשיחה המהווה את שלד העפעף והמשכית לספטום ול-canthal tendons, השרירים הרטרקטורים של העפעפיים, כריות השומן הרטרו-ספטליות והלחמית הטרסלית שהיא המשכית ללחמית הבולברית המצפה את לובן העין (הסקלרה). (איור1).

הדמעות מופרשות בעיקר מבלוטת הדמעות הממוקמת בארובה העליונה טמפורלית ומתנקזות דרך הפונקטה – החרירים הקטנים המצויים בצד הנזאלי של העפעפיים ומשם אל האמפולה, הקנליקולי, ואל תעלת הדמעות (lacrimal duct) בין העצמות המקסילרית והלקרימלית המתנקזת לחלל האף. (איור 2).


 איור 1 – אנטומיה של העפעפיים        
 
 ******** תמונה
 
 איור 2 – אנטומיה של דרכי הדמעות
 
 ******* תמונה 
 
A.A. Gordon, L.T. Tran and P.O. Phelps, Eyelid and orbital trauma for the primary care physician, Disease-a-Month, https://doi.org/10.1016/j.disamonth.2020.101045

#### אנטומיה של גלגל העין
מבני העין העיקריים (איור 3):

**הלחמית (conjunctiva)** רקמת חיבור שקופה המצפה את לובן העין, ואת משטח העפעף האחורי.

**הקרנית (cornea)** רקמת קולגן קשיחה ושקופה התורמת כ-2/3 מכוח התשבורת של העין.

**לובן העין (sclera)** רקמת קולגן קשיחה בעלת גוון לבן המהווה את עיקר קיר גלגל העין.

**לימבוס (limbus)** אזור המעבר בין הקרנית ללובן העין (360 מעלות).

**הקשתית (iris)** רקמה שריר מעגלית האחראית על ויסות חדירת האור לעין ע"י שינוי גודל 

**האישון (pupil)** – החריר שבמרכזה.

**העדשה (lens)** מבנה שקוף התורם לכ-1/3 מכוח התשבורת של העין.

**הזגוגית (vitreous)** ג'ל שקוף המורכב בעיקר מקולגן וחומצה היאלורונית וממלא את מרבית חלל העין הפנימי.

**הרשתית (retina)** השכבה הפנימית של העין, רקמה רגישה לאור המעבירה את המידע הראייתי דרך **עצב הראיה (optic nerve)** אל המוח.

**המקטע הקדמי** של העין כולל את המבנים מן העדשה וקדמית לה, **והמקטע האחורי** כולל את מבני העין אחורית לעדשה.

******** תמונה 

איור 3: אנטומיה של גלגל העין

#### אנטומיה גרמית של הארובה (איור 4)
הארובה מורכבת מ-7 עצמות: frontal, sphenoid, zygomatic, palatine, lacrimal, ethmoid, maxillary. מקובל להתייחס לגג הארובה, רצפת הארובה והקירות המדיאלי והלטרלי.

*********** תמונה 

איור 4: אנטומיה גרמית של הארובה

### פציעות ברקמות השטחיות (Adnexa)
#### קרעים (lacerations) בעפעפיים
נפוצים יחסית וחומרתם תלויה בעומק הפציעה, מיקומה ומעורבות המבנים הסמוכים. הקנליקולוס רגיש במיוחד לפציעה. ניתן לחלק פציעות אלו לפגיעות ישירות – חודרות הנגרמות כתוצאה מחפצים חדים ובלתי ישירות – קהות. 

תלונות יכולות לכלול טשטוש ראיה, כאב או אי נוחות, חוסר יכולת לפתוח את העפעפיים ודמעת. עם זאת מטופלים רבים יהיו אסימפטומטיים.

בעת הערכת טראומה לעפעפיים, חשוב להעריך את עומק הפציעה, מיקומה והמבנים הסמוכים – גלגל העין, ומערכת ניקוז הדמעות. בשלב ראשון יש להעריך את שלמות גלגל העין. כאשר ניתן לראות פגיעה בשלמות גלגל העין או בחשד לכך, אין להפעיל לחץ על האזור.  רק אם אין חשד לפגיעה כזו – הראיה שמורה, וגלגל העין נראה תקין, – ניתן להפוך את העפעף בעדינות ולהסיר בעדינות באמצעות מטוש גופים זרים אם נמצאו. אי מציאת גוף זר אינה שוללת את קיומו במידה וקיימת עדיין תחושה של גוף זר. לאחר מכן ניתן להעריך את עומק הפציעה (חלקי/מלא), מיקומה המדויק ומעורבות שולי העפעף. כאשר יש מעורבות של שולי העפעף המדיאליים יש לחשוד במעורבות של הקנליקולוס בסבירות גבוהה.

******* תמונה

איור 5: אופן ביצוע היפוך עפעף 

#### כוויות כימיות
כוויות כימיות למשטח העין יכולות להגרם כתוצאה מחשיפה לחומרים שונים, כולל גזים או נוזלים. חשיפה לחומרים בסיסיים חמורה יותר מחומרים חומציים, בשל חדירה מהירה שלהם דרך הקרנית אל הלשכה הקדמית. הרס התאים ושחרור קולגנזות ומטאלו-פרוטאינזות מביא לתמס של הקרנית. חומרת הנזק תלויה ב-pH ובסוג החומר הכימי. תלונות נפוצות במקרים אלו יכללו רמות משתנות של כאב, פוטופוביה, טשטוש ראיה, תחושת גוף זר, ואודם. אם העין הפגועה לבנה ללא כלי דם בלחמית לאחר פגיעה בסיסית, הדבר יכול לרמז על נזק איסכמי.

במצב של פגיעה כימית יש לטפל במשככי כאבים סיסטמיים במידת הצורך ובלוקלין טופיקלי ולבצע ללא דיחוי שטיפה יסודית של העין למשך 20 דקות לפחות באמצעות תמיסת סליין או רינגר לקטט, ואם לא ניתן – באמצעות מים, עד הגעה  ל-pH נייטרלי (לבדוק באמצעות סטיק שתן במידה ונמצא) יש להפוך עפעף בזמן השטיפה על מנת להסיר שאריות חומר כימי כלוא מתחתיו. כמו כן, יש להעביר מטוש על לחמית העפעף. רק לאחר השטיפה יש לעבור להערכת חדות הראיה.


### טראומה המערבת את גלגל העין

**************************** תרשים

### טראומה המערבת את ארובת העין
#### דימום תוך-ארובתי
ניתן לחלק את הארובה לשני מדורים אנטומיים – preseptal ו-postseptal. המדור הפוסט-ספטלי, התוך ארובתי מוגבל ע"י עצמות הארובה מידאלית, לטרלית ופוסטריורית וקדמית ע"י הספטום הקשיח. כיוון שכך, חלל הארובה הוא מוגבל ובעל יכולת מינימלית להתפשט, ולכן דימום אחורי לגלגל העין (רטרו-בולברי) בתוך חלל זה, יכול לגרום לתסמונת מדור עם לחץ גבוה הפוגע במבנים הוסקולריים והעצביים העדינים בארובה. הלחץ הישיר על עצב הראיה יביא לירידה בפרפוזיה ואיסכמיה לעצב הראיה, או לחסימה של העורק הרטינלי ואיסכמיה לרשתית. לכן דימום שכזה עלול להביא לאובדן ראיה מהיר.

חשוב לציין כי דימום רטרו-בולברי הוא אבחנה קלינית ולא רדיולוגית. הביטויים הקליניים כוללים כאב, תגובת אישונים אפרנטית (RAPD) חיובית בצד הפגוע, עליה בלחץ התוך עיני, בלט עין (proptosis), ירידה בחדות הראיה וחוסר יכולת לפתוח את העין בשל נפיחות ניכרת. 

במצבים בהם יש אובדן ראיה, RAPD חיובי או מהלך קליני עם החמרה מהירה – הטיפול כולל דה-קומפרסיה ע"י ביצוע lateral canthotomy + cantholysis בבית החולים, לפני ביצוע בדיקות דימות, שכן לאחר 120 דקות ללא התערבות – הנזק הופך לבלתי הפיך. 
#### שברים בארובה
מהווים עד כ-16% מכלל השברים בפנים. יתכנו פציעות נלוות משמעותיות בהתאם לסוג ומנגנון הפציעה.

שברים יכולים לערב את הקומפלקס ה-zygomatico-maxillary, רצפת הארובה או קירות הארובה.

מרביתם אינם דורשים התערבות ניתוחית. בדיקת הבחירה – CT ללא חומר ניגוד. אינדיקציות להתערבות ניתוחית, לאחר דימות הן שקיעת העין (אנופתלמוס) הגורמת לאסימטריה של הפנים, או כליאת שריר המביאה להגבלה בתנועות העין (גם בצקת ללא כליאת שריר עשויה להביא להגבלה בתנועות העין ומכאן חשיבות הדימות) וגירוי ואגאלי. ירידה בחדות הראיה ונוכחות RAPD מרמזים על פציעה נלווית משמעותית של העין.

## סיכום
למרות טיפול רפואי אופטימלי, פציעות עיניים בשדה הקרב גורמות לנכות משמעותית ואי כשירות ללוחמה. פציעות רסיסים הן מהנפוצות, וניתן למנוע חלק גדול מהן ע"י שימוש במשקפי מגן. לכן יש חשיבות רבה לחינוך הלוחמים ע"י המפקדים והרופאים בשטח לשימוש במשקפי מגן.

למרות האתגר שבטיפול בתחום פחות מוכר, והמגבלות הברורות של תנאי השטח, המחייבות במרבית המקרים פינוי והמשך טיפול ע"י רופא עיניים, הערכה נכונה והגנה על העין הפצועה יכולה להציל את העין ואת הראיה ולפיכך יש להערכה הראשונית חשיבות רבה.
- במקרה של חשיפה לחומרים כימיים – יש לבצע שטיפה ממושכת בהקדם האפשרי וטרם  ההערכה.
- בחשד לדימום רטרו-בולברי – יש לבצע lateral canthotomy & cantholysis במסגרת בית חולים. 
- בחשד לחבלה חודרת, יש להתחיל טיפול אנטיביוטי סיסטמי, משככי כאבים ונוגדני הקאה. יש להמנע מתרופות טופיקליות לעין.
- יש להמנע מלחץ על העין, ולהגן עליה באמצעות מגן קשיח ללא מגע עד לפינוי.

במקרים רבים הפציעה היא רב מערכתית, ולכן האמור בפרק אינו יכול להחליף את ההתייחסות הכוללת לפצוע.


## נספח א' – קלסיפיקציה של טראומה המערבת את גלגל העין
כאשר הפציעה מערבת את גלגל העין, מקובל להגדיר את סוג הפציעה העינית באמצעות ה-Birmingham Eye Trauma Terminology System (BETT), ואת מיקום הפציעה באמצעות ה-Ocular Trauma Classification System.

### ה-Birmingham Eye Trauma Terminology System

*********** טבלה 

### חלוקת מיקום הפציעה בעין לפי ה-Ocular Trauma Classification System (איור 7)
 
 **************** תמונה
 
Gundogan FC, et al. J R Army Med Corps 2015;0:1–5. doi:10.1136/jramc-2015-000408
#### Closed globe (איור שמאלי)

איזור 1- מעורבות של פני השטח בלבד: לחמית בולברית / קרנית / לובן העין (סקלרה) (ירוק)

איזור 2- מעורבות המקטע הקדמי של העין (תכלת)

איזור 3- מעורבות המקטע האחורי של העין (ורוד)
#### Open Globe (איור ימני)
איזור 1-  פגיעה המערבת את הקרנית והלימבוס (ירוק)

איזור 2- פציעות המערבות 5 מ"מ קדמיים של הסקלרה (תכלת)

איזור 3 – פציעות המרוחקות מעל 5 מ"מ מהלימבוס

