# אובדן סימני חיים

## עיקרי העדכונים:

-   22.2.22

1.  **עדכון פעולות מצילות חיים= הנשמה באמבו, ניקור חזה במחט דו צידי ומתן נפח. אינטובציה ו/או נקזי חזה לא יבוצעו כחלק מהפרוטוקול.**
2.  **הבדלה בין חבלה קהה לחודרת.**
3.  **תחימת משך מאמצי ההחייאה.**
4.  **הוספת PEA בקצב \>40 לדקה כקריטריון להמשך מאמצי החייאה ( במקרים בהם התבצע שימוש במוניטור)**
5.  **חובת מדידת ל"ד במסגרת הערכת סימנים חיוניים**
6.  **הוספת נספח- טופס פטירה צבאי**
7.  **הבהרה על הצורך במדידת חום לצורך הפסקת מאמצי החייאה/**

-   19.07.2021

1.  הבהרת הפרוטוקול

-   11.04.2021

1.  חידוד רצף פעולות ההחייאה

-   01.02.2020

1.  עדיפות למתן מוצרי דם ולא נוזלים
2.  ביצוע ניקוז חזה בנקז חזה או וייגון
3.  ניתן לקבוע מוות גם בנוכחות PEA בקצב מתחת ל-40

## הקדמה

אחד המצבים המורכבים בשטח הוא איבוד סימני חיים "תחת העיניים" ובמצב כזה עלינו להעניק לנפגע את מירב הסיכויים לשרוד (באירוע רב נפגעים, עיתוי הפעולות ידחה). אחת ההחלטות הקשות להן נדרש המטפל במתאר טרום בית החולים, היא ההחלטה על אי-התחלה או הפסקת פעולות ההחייאה בפצוע ללא סימני חיים. על המטפל להחליט, לעיתים קרובות בתנאי דחק, האם יש בפעולות טעם, ובמידה והוחל בהן, מתי כלו סיכויי ההצלה ויש לסיימן. ההחלטה על התחלת מאמצי החייאה מושפעת גם ממספר הפצועים -- פצוע ללא סימני חיים יוגדר כ"ממתין" ורק לאחר סיום הטיפול ביתר הנפגעים תתבצע הערכה מקיפה שלו (ראה פרק אר"ן). מאידך, לביצוע מאמצי החייאה כאשר אין להם סיכוי להצלחה, יש השפעה על ניצול יכולות וצוותי רפואה, קשב לפצועים נוספים, סיכון כוחות פינוי ועוד. פרק זה יגדיר קווים מנחים שמטרתם לסייע למטפל בשטח בתהליך קבלת ההחלטות בנוגע לסיום או הימנעות מביצוע מאמצי החייאה **בנפגע טראומה.**

**פרוטוקול -- סיום מאמצי החייאה וקביעת מוות בנפגע טראומה במתאר טרום בית חולים** \*\*\*\*\*\*\*\*\*\*\*\*\*\*תרשים

## ביאור פרוטוקול

### קווים מנחים להפסקת מאמצי החייאה בנפגע טראומה בשטח

1.  בנפגע טראומה הסובל *מחבלה קהה* שנמצא ללא נשימה, ללא דופק, ללא קריאה במדידת לחץ דם וללא תגובת אישונים -- אין להתחיל מאמצי החייאה.
2.  בנפגע טראומה ללא סימני חיים ע"ר *חבלה חודרת* (או כשהמנגנון אינו ברור) יש להמשיך ולבצע הערכה מהירה של סימני חיים אחרים: תנועות גוף עצמוניות או במידה וחובר מוניטור -- PEA בקצב של מעל 40. אם א*חד* מסימני החיים לעיל (דופק/נשימה/ל"ד/תג' אישונים/תנועות ספונטניות) קיים או התקיים בחמש הדקות יש לבצע *פעולות החייאה* על פי פרוטוקול אובדן סימני חיים (פירוט בסעיף 3). אם לא קיים אחד מסימנים אלה, אין לבצע מאמצי החייאה.
3.  **כאשר הנפגע מאבד סימני חיים "תחת העיניים" או כאשר נצפה אחד מהסימנים החיוניים יש לבצע פעולות מצילות חיים על מנת לוודא שההידרדרות אינה נובעת מאחד הגורמים למוות בר מניעה** ( כדוגמת חזה אוויר בלחץ, שוק עמוק או חסימת נתיב אוויר): יש לנקר את בית החזה משני הצדדים ע"י מחט Vygon או Tpak מהדגם המאושר בצה"ל. כמו כן, יש להנשים באמצעות אמבו, AW ומסיכה ולתת נפח (דם מלא, כדוריות דחוסות, פלסמה מיובשת או נוזלים על פי הזמינות והכתוב בפרק " **החייאת בקרת הנזקים**"). לאחר מכן יש להעריך שוב את הפצוע. במידה ולאחר ביצוע הטיפולים הנ"ל אין סימני חיים יש להפסיק את מאמצי ההחייאה ועל רופא לקבוע מוות. יודגש כי במידה ואובדן סימני חיים מתרחש במהלך הפינוי יש להתחיל באופן מיידי ביצוע החייאה כמתואר לעיל.
4.  במידה ולאחר ביצוע הפעולות הנ"ל קיימת חזרה של סימני חיים יש לעבור לטפל על פי "**סכמת הטיפול האחודה**", לשקול ביצוע נקז או התקנת נתיב אוויר דפינטיבי על פי ההתוויות באגרות הרלבנטיות (**גישה לנתיב אוויר/גישה לפציעות חזה/החייאת בקרת הנזקים**).
5.  אין מקום לביצוע אק"ג בטרום בית החולים בנפגע טראומה. במידה וחובר, בחבלה חודרת, ממצא של PEA בקצב מעל 40 לדקה יחייב ביצוע מאמצי החייאה. במידה וחובר מוניטור ונצפתה אסיסטולה או PEA בקצב נמוך מ-40 (לצד היעדר תנועות ספונטניות ותגובת אישונים) -- אזי ניתן לקבוע מוות.
6.  אין לבצע פעולות החייאה בפצועי טראומה, שפציעתם הביאה לאובדן צלם אנוש: דקפיטציה -- ניתוק הראש, ניתוק האגן, התפחמות של ראש ו\או של הגו וכו'.
7.  **אין לבצע מאמצי החייאה בנפגע עם עדות לכך שהמוות התרחש לפני זמן רב** (סימני ריקבון, קישיון מוות, כתמי מוות מפושטים, הצטברות דם במקומות נמוכים).
8.  **מאמצי החייאה בטראומה אינם כוללים החייאה קרדיאלית -- לפיכך לא נבצע עיסויים בטראומה.**

אין עדויות לכך שעיסויי חזה בטראומה משפרים הישרדות. עיסויי חזה רלוונטיים בעיקר בדום לב בהיפותרמיה שלא על רקע טראומה וגם אז השרידות נמוכה ביותר. כמו כן, ישנו דגש על כך שביצוע עיסויי חזה במקרה של פצוע קשה עלול לבוא על חשבון ביצוע פעולות מצילות חיים (פתיחת נתיב אוויר, ניקוז בית חזה וכו').

9.  לנפגעי טביעה, התחשמלות (לרבות מכת ברק) והיפותרמיה שלא על רקע טראומה-- תבוצע החייאה לבבית מלאה על פי תורת ה ACLS.
10. קביעת מוות באישה הרה מתבצע על פי אותם השיקולים המפורטים לעיל.
11. הפסקת מאמצי החייאה הינה בסמכות פרמדיקים ורופאים. קביעת המוות וחתימה על תעודת פטירה נשארת בסמכותו הבלעדית של רופא.

## רקע וסקירת ספרות

### מבוא:

ההחלטה שלא להתחיל בטיפול או להפסיק טיפול בפצוע ללא סימני חיים מהווה אתגר למטפלים, הן בהיבטים מקצועיים והן בהיבטים מנטליים. לצד שיעורי ההצלחה הנמוכים , עיקר הקושי בקבלת ההחלטה במתאר צבאי נובע בין היתר מסביבת העבודה המאתגרת, מהמיידיות הנדרשת בקבלת ההחלטות, מהאינטימיות של ההיכרות בתוך היחידה, מחשש מהשפעות על רוח הגיסות ומהניסיון החסר של המטפל.

כדי לקבל החלטה מושכלת ונאותה, על הצוות המטפל לזהות מתי מצבו של הפצוע בלתי הפיך. באופן טבעי, האינסטינקט המוטבע בכל מטפל הוא להילחם על חיי כל פצוע. עם זאת, מנגד עומדת המציאות, אשר מחייבת אותנו להתייחס בכובד ראש להיבטים נוספים: 1. **שיקולים רפואיים:** 1. מהרגע שאירע דום לב על רקע טראומה הישרדות הפצועים נמוכה מאוד - לפי הספרות בין-ל2%-8%, כאשר מרבית העבודות בנושא עוסקות בפצועים שאיבדו סימני חיים בתוך מרכז רפואי (ולא בטרום בית החולים) (3,8,14). 2. מדידת דופק והערכת נשימה בשטח אינן מדויקות וביצוען תלוי במיומנות המטפל.

2.  **חלוקת משאבים:**
    1.  השקעת משאבי טיפול (כ"א ואמצעים) בחלל עלולה לבוא על חשבון פצועים אחרים בני הצלה באותה זירה.
    2.  במתארי לחימה הקצאת משאבי פינוי, כגון כח פינוי קרקעי או מסוק, מציבה את צוותי הפינוי בסכנה ובאה על חשבון הקצאתם לפצועים אשר סיכויי ההישרדות שלהם תלויים לעיתים בפינוי.\
3.  **שיקולים פסיכולוגים:**
    1.  מפקדים, חבריו ובני משפחתו של הפצוע מצפים מהצוות המטפל להעניק לו כל סיכוי אפשרי ולו הקלוש ביותר (גם כאשר הספרות אינה תומכת במאמצים אלו).
    2.  הימנעות מטיפול הינה החלטה סופית ולא בת תיקון, אשר תוצאותיה בלתי הפיכות. החלטה כזו כרוכה בקושי רגשי רב למטפל, בייחוד במצבים בהם הוא חלק מהיחידה או בעל היכרות אישית עם הפצוע. קושי זה מקשה על המטפל לסיים את ניסיונות ההחייאה.

יודגש כי ראוי לשקול את השקעת המשאבים והסיכון הכרוכים בטיפול ובפינוי החלל לאור הנסיבות המבצעיות. במידה ונקבע מוות, הרי שדחיפות הפינוי יורדת, ואין צורך לסכן צוותים מטפלים לצורך ביצועו, הגם שברור כי ייעשה מאמץ רב כדי להשלימו. \### סקירת הנחיות מאיגודים מקצועיים בעולם בשנת 2003 ובהמשך ב 2012 פרסמו ה National association of EMS physicians וה- American college of surgeons (ACS) קווים מנחים לגבי הימנעות או הפסקה של מאמצי החייאה בשטח (1).

על פי הנחיות הACS קיימים מספר מתארים בהם יש מקום להפסקת מאמצי החייאה: 1. בכל מקרה של פציעה שאינה מאפשרת חיים -- אובדן צלם אנוש. 2. בכל מקרה בו קיימת עדות למעבר זמן ממושך מרגע החבלה ועד הגעת הצוות המטפל -- קשיון מוות (Rigor Mortis) רקבון או הצטברות נוזלים במקומות נמוכים בגוף וכו'. 3. בכל מקרה של חבלה קהה בפצוע ללא דופק, ללא נשימה ולא עדות לפעילות חשמלית סדורה במוניטור או PEA איטי מ-40 לדקה (13). 4. בכל מקרה של חבלה חודרת בפצוע ללא דופק, ללא נשימה, ללא עדות לפעילות חשמלית סדורה במוניטור או PEA איטי מ-40 לדקה וללא עדות לתגובה נוירולוגית (תגובת אישונים, הנעת איברים ספונטאנית). 5. בכל מקרה בו מאמצי ההחייאה אינם מפיקים דופק ספונטאני במשך יותר מ15 דקות.

בשנת 2011 פורסמה עבודה שמטרתה לתקף את הקריטריונים להימנעות או הפסקה של מאמצי החייאה בשטח. עבודה זו כללה 294 נפגעים שטופלו ופונו לבית החולים למרות שעמדו בקריטריונים הנ"ל ועל פי הנחיות ה ACS לא היו אמורים לעבור החייאה. מתוך 294 הנפגעים, ב93.2% נקבע מוות בחדר המיון. מכלל הנפגעים שרד 1 (0.3%) עד לשחרור מבית החולים. נפגע זה שוחרר למוסד שיקומי עם FGCS 6 (מצב שווה ערך לצמח). (2)

### שימוש במוניטור

לא קיימת בספרות התייחסות לשאלת החובה בשימוש במוניטור על מנת לקבוע מוות בפצועים. עם זאת במרבית העבודות (אשר מתבצעות במתארים עירוניים ע"י צוותי אמבולנסים) מתבצע שימוש במוניטור כחלק מתהליך קבלת ההחלטות. יתרונו העיקרי בהיותו מדד אובייקטיבי שאינו תלוי בהערכת הבודק ( בשונה מאישונים/ תחושת דופק או תנועות).

ישנם שני מצבים בהם קצב הלב המופיע במוניטור יכול לתמוך בהחלטה להפסקת החייאה: 1. אסיסטולה -- היעדר פעילות חשמלית. נמצא כגורם מנבא שלילי להצלחה ברסוסיטציה עם אחוזי הצלחה שנעים בין אפס ( מרבית העבודות) ועד 1.8%. 2. PEA עם דופק מתחת ל40 לדקה.

מחקר משנת 2004, על 497 פצועים עם פציעה חודרת, הראה שאף אחד מהפצועים עם אסיסטולה או עם PEA עם דופק נמוך מ-40 לדקה **לא שרד** (9). לציין כי קצב לב הגבוה מ-40 נמצא כגורם מנבא חיים (OR -- 6.7).(8)

### שיעורי התמותה בספרות

מאז פרסום הקריטריונים הנ"ל העוסקים בקבלת ההחלטה שלא להתחיל או להפסיק מאמצי החייאה פורסמו מספר עבודות העוסקות בשיעורי ההצלחה של ביצוע החייאה בנפגעי טראומה במתאר אזרחי עירוני אשר בהערכה ראשונית נמצאים ללא נשימה או דופק. אחוזי ההישרדות של פצועים במקרים אלו נעה בין 0% ל-10% (4-8). כשמדובר במתאר צבאי, הנתונים ככל הנראה דומים. בעבודה שכללה 52 נפגעי טראומה במתאר צבאי שפונו לטיפול בבית חולים צבאי שרדו 4 מטופלים (8%). בכל 4 השורדים אובדן סימני חיים התרחש במהלך הפינוי.(3)

### מנגנון הפציעה

יש לציין כי למרות שקיימות מספר עבודות המצביעות על קשר בין מנגנון הפציעה בפצועים הנזקקים להחייאה (חודרת לעומת קהה) לבין שיעורי השרידות, קשר זה אינו חוזר על עצמו באופן מובהק. במטה-אנליזה שכללה 6,634 מטופלים, נמצאו שיעורי תמותה דומים בין מטופלים לאחר חבלה חודרת (96.4% ) וחבלה קהה (96.7%). (4). ממצא זה חוזר על עצמו במספר עבודות נוספות5)). מאידך, בתוך בית החולים, מנגנון החבלה (חודרת/קהה) מהווה שיקול משמעותי בביצוע מאמצי החייאה (לרבות פתיחת חזה כירורגית -- Resuscitative Thoracotomy) כאשר מרבית ההנחיות אינן ממליצות על ביצוע מאמצי החייאה במקרי היעדר סימני חיים ע"ר חבלה קהה (15).

### תגובת אישונים

בדיקת אישונים מהווה קריטריון לקביעת מוות בכלל הפצועים. ממצא של אישונים מורחבים ולא מגיבים מהווה מדד רגיש ומוכח להיפוקסיה מוחית ממושכת ובלתי הפיכה. קיימות מספר עבודות העוסקות בתגובת אישונים כגורם פרוגנוסטי בפצועים. בעבודות אלו נמצא כי בפצועים שאינם מגיבים בבדיקתם בשטח (GCS=3) אישונים מורחבים ללא תגובה לאור מנבאים שיעור תמותה של %100. (10,11,12)

### היפותרמיה

היפותרמיה שנגרמה מתנאי סביבה ולא מטראומה) עלולה להיות מלווה בברדיקרדיה עד דום לב, היפווטנטילציה עד אפנאה וירידה במצב ההכרה. יתרה מכך היפותרמיה מגינה על איברים חיוניים בזמן איסכמיה. לכן, לא מקובל להפסיק מאמצי החייאה בנפגע היפותרמי שלא על רקע טראומה -- "Not Dead until Warm Dead" . **לעומת זאת, בטראומה אין קורלציה בין הצלחת החייאה לבין היות הפצוע בהיפותרמיה (אשר לרוב משנית למנגנוני המוות). *לכן כאשר הפציעה טראומה) היא מנגנון הנזק המרכזי אין צורך במדידת חום להחלטה על הפסקת מאמצי החייאה*.**

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* תמונה הודעת פטירה
