# אירוע רב נפגעים

### **עיקרי העדכונים:**

### תוכן עניינים

#### הקדמה ורקע

#### פרוטוקול

#### ביאור הפרוטוקול

-   בטיחות הטיפול של ה-S
-   סריקת השטח ואיתור נפגעים
-   טריאז'
-   סיכום טריאז'
-   סבב טיפולי
-   חבירה
-   סיום אירוע

#### סיכום

#### נספח א' -- טבלת שליטה לניהול אירוע רב נפגעים

#### נספח ב' -- טבלת שליטה לניהול אירוע רב נפגעים -- מילוי לדוגמא

### הקדמה ורקע

אירוע רב נפגעים (אר''ן) הוא אירוע בו מספר הנפגעים וחומרת הפציעות גוברים על המשאבים הקיימים בשטח ועל יכולת הצוות הרפואי להעניק טיפול מיטבי לכלל הפצועים. כך שבאר''ן הטיפול בפצוע אחד משפיע באופן משמעותי על איכות הטיפול ו/או על היכולת לפנות פצוע אחר. המטרה המרכזית באירוע רב נפגעים היא לנצל את המשאבים הקיימים עבור איתורם המוקדם ככל האפשר של הפצועים בני הצלה והקצאת משאבי הפינוי והטיפול באופן היעיל ביותר לטובתם.

טיפול בפצוע בטרום בית חולים מהווה אתגר מורכב גם עבור מטפלים מנוסים, על אחת כמה וכמה כאשר מדובר באירוע רב נפגעים. אר''ן הוא אירוע נדיר יחסית הן במתאר הצבאי והן במתאר האזרחי ובעקבות כך רוב מכריע של המטפלים לא התנסו בניהול אירוע מסוג זה.

חשוב לציין כי להקשר האג"מי חשיבות רבה בניהול אר"ן. אין דין אירוע בשטחנו ללא איום אג"מי כדין אירוע תוך כדי לחימה בשטח אויב, והמצב התודעתי במהלך ניהול האירוע צריך להיות בהתאם.

קיימות שתי הגדרות מקובלות של אר"נים: 1. עפ"י פיזור מרחבי: 1. אר"ן מרוכז -- כל הפצועים מרוכזים בתא שטח קטן אחד, ופעולת הריכוז מתמקדת בסידור הזירה וסריקה לשלילת נפגעים נוספים. 2. אר"ן מפוזר -- הפצועים מפוזרים על פני שטח גדול יותר. השלב הראשון באר"ן כזה יהיה להפוך אותו לאר"ן מרוכז. 2. עפ"י מהלך אג"מי: 1. אר"ן תחום בזמן (סטטי / סגור) -- האירוע האג"מי הסתיים, אין התווספות של פצועים. מרבית האירועים הם מסוג זה כדוגמת תאונת דרכים עם נפגעים מרובים ואף חלק גדול מהאירועים המבצעיים. 2. אר"ן מתגלגל -- תוך כדי ריכוז הפצועים והטיפול האירוע האג"מי ממשך להתגלגל ופצועים מתווספים (או עלולים להתווסף) כדוגמת אירוע ציר המתפללים בחברון אשר היה אירוע שנמשך 4 שעות ו -- 5 דקות בו נהרגו 14 לוחמים ונפצעו 14 נוספים.

אר"ן יוגדר עפ"י שתי הגדרות אלו, למשל מפוזר ומתגלגל, סטטי ומרוכז וכן הלאה.

בעלי התפקידים המרכזיים יהיו: 1. המפקד הרפואי -- המטפל הבכיר ביותר באירוע. ראוי לציין כי המפקד הרפואי יכול להתחלף במהלך אירוע. לדוגמא אירוע אר"ן בו הצוות הראשון הינו פרמדיק גדודי, אשר מתחיל כמפקד הרפואי בהגיע הקרפ"ג / קרפ"ח יעביר אליהם את הפיקוד באופן ברור ויתפנה לטיפול. 2. מנהל האירוע -- האחראי על יישום ההנחיות של המפקד הרפואי, סידור הזירה, איסוף הנתונים, חלוקת המשימות, הדיווח והחבירה לגורמים נוספים. מנהל האירוע יהיה חוג"ד, מפקד חוליה רפואית, או מנהל אירוע אחר שהוגדר למשימה זו. 3. מטפל מס' 2 -- יד ימינו הרפואית של המפקד הרפואי בזמן הטריאז' -- יהיה חובש (המיומן ביותר) או מטפל בכיר. אין טעם לבצע טריאז' במקביל ע"י שני מטפלים בכירים מאותו צוות, כי אין ערך משמעותי לטריאז' שמתבצע ללא מנהל אירוע. 4. חובשים נוספים ("חובשי C"). 5. מח"צים.

### פרוטקול

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה

### ביאור הפרוטוקול

#### בטיחות הטיפול- שלב ה-S

טרם הכניסה לאירוע יש להבין את הסכנות הרלוונטיות עבור הצוות המטפל ולחבור בהתאם (ראה פרק מס' 2 -- הטיפול תחת אש ובטיחות הטיפול). יש לאסוף מידע רב ככל הניתן טרם הכניסה לאירוע - מספר פצועים, מיקום מדויק, נקודת חבירה לכוח שנמצא באזור וכו'. מיד לאחר מכן, יש להוציא דיווח לרמה הממונה (מבצעית ורפואית) שיכלול: 1. עדכון על חבירה לאירוע ומיקום 2. סוג האירוע 3. תמונת מצב אג"מית (בקצרה) 4. ההגדרה של האירוע כאר"ן במידה וזה המצב

בנוסף ישנו ערך קריטי בהערכה של הסיטואציה והבנתה -- הן לטובת הבנת מנגנון הפציעות והן לטובת דיווח לגורמים ממונים ופינוי הפצועים לבית חולים.

יש להבין את מבנה הזירה, אזורים מאוימים ובטוחים ולבחור את נקודת ריכוז הפצועים. מאפייני הנקודה: 1. בטוחה עד כמה שניתן בתנאים האג"מיים. 2. מאפשרת עד כמה שניתן סידור מרווח של הפצועים, באופן לינארי (כלומר בסדר שבו ברור עבור כל פצוע מי הפצוע שלפניו ומי אחריו). 3. בעלת נקודת כניסה ברורה -- חשוב במיוחד באר"ן מתגלגל (ראה מטה). 4. סמוכה לציר הפינוי.

לבחירת הנקודה תפקיד קריטי באופן שבו יתנהל האר"ן בהמשך, ויש לבחור אותה בתבונה. באירועי לחימה לרוב נשתדל להגדיר אותה מראש -- זו נקודת האיסוף הפלוגתית (נאפ"ל).

#### סריקת השטח ואיתור נפגעים

-   **חלוקת הכח לגזרות סריקה והגדרת נק' הריכוז:**

החלוקה תתבצע בצורה פשוטה ככל האפשר תוך היעזרות בסימנים בולטים בשטח ("מהעץ הגבוה עד החומה"). במתאר מאוים יש להקפיד על סריקה בצמדים לכל הפחות. יש להדגיש לחובשים / מח''צים את המטרה המרכזית שהיא עצירת דימומים פורצים בלבד וריכוז הפצועים. מטרת השלב היא להפוך אר"ן מפוזר או מבולגן לאר"ן מכונס ומסודר, כדי לאפשר טריאז', טיפול ופינוי יעילים.

דגשים חשובים: \* **סריקת הנגזרות** \* אין לבצע סכמה בנקודת הפציעה \* אין להתעכב בנקודת הפציעה למעט לצורך עצירת דימומים פורצים \* **עצירת דימומים פורצים/קטיעות** \* יש לעצור דימומים פורצים בלבד או קטיעות (גם אם נעצר הדימום). \* יש לעצור דימום על ידי חוסם עורקים מסוג CAT, מומלץ ע"י זה הקיים **בחזקתו של הפצוע**. בהעדר אמצעי זה, או באי מציאתו יש להשתמש בחסם העורקים שברשות המטפל. יש לנסות להניח את חסם העורקים על גפה חשופה מבגדים ואמצעים. במצב מאוים מבצעית ניתן להניח את חוסם העורקים מעל בגדי הפצוע , בראש הגפה, ובהמשך להפשיט ככל הניתן את האזור בלי להסיר את ה-CAT. \* במידה וניתן לעצור את הדימום בלחיצה בלבד -- יש לנסות להביא את המטופל לנק' הריכוז תו"כ לחיצה על נק' הלחיצה, באמצעות עבודת צוות. \* **ריכוז הנפגעים לנק' הריכוז**

יש לרכז את הפצועים בנקודה אחת באופן שהוגדר בתדריך על ידי מנהל האירוע. יש למקם את הפצועים באופן לינארי (שורה, ח' וכיוצ"ב בהתאם לתנאי השטח) על מנת לאפשר מעבר קל בין הפצועים, ללא חזרתיות וללא פספוס של פצועים, כך שקל יהיה לאתר פצוע לפי מספרו. מבלי לעכב את ריכוז הפצועים ותחילת הטריאז', ניתן לשקול לגבי פצועים שנראים חיצונית דחופים יותר למקמם קרוב יותר לתחילת הטריאז' המתוכנן. בהתאם, הפצועים המתהלכים יופנו לצד הקרוב לסוף הטריאז'. \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה

יש למספר את הפצועים באופן בולט. הדבר מקל על הזיהוי שלהם הן ע"י הצוות המטפל והן לצורך העברת מידע להמשך.

יש להגדיר את הכניסה לנק' הריכוז. באירועים ''מתגלגלים'' עלולים הפצועים להגיע בכל שלב, גם לאחר סיום הטריאז', וייקלטו בכניסה לנק' ריכוז הפצועים. מיקום הנקודה יוגדר באופן שלא יפגע בניהול האירוע וטיפול בפצועים ולא יחסום את ציר הפינוי. לאחר בדיקה ע"י המפקד הרפואי בנק' הריכוז והוספה לסיכום הטריאז' יועברו לקצה הזירה, בשליטה של מנהל האירוע.

-   **כריזה לנפגעים המהלכים להגיע לנק' הריכוז** יש לרכז את הפצועים המתהלכים סמוך לפצועים השוכבים אך באופן שלא יהווה שיבוש בניהול האירוע וטיפול בנפגעים השוכבים. יש להקפיד גם על ביצוע טריאז' שלהם, **אין ערובה שפצוע מתהלך אינו פצוע דחוף.**

#### טריאז'

טרם תחילת הטריאז' באחריות מנהל האירוע לדווח למפקד האג"מי ולרמה הממונה הרפואית דיווח שיכלול את מיקום האירוע, אופיו, מצב אג"מי עדכני, כמות הפצועים (בשלב זה כמובן ללא התייחסות לדחיפות) ונתונים רלוונטיים נוספים, כמו קיום של פצועים לכודים. יש להעלות דרישה לכוחות נוספים ופינוי מוסק בהתאם להערכת המצב, כבר בשלב זה.

הטריאז' מתבצע ע"י 3 בעלי תפקידים: 1. **המפקד הרפואי**- יבצע בדיקה של הפצוע וטיפולים דחופים כמתואר מטה, יגבש תמונת מצב ראשונית ויעביר אותה למנהל האירוע (כמפורט מטה). 2. **מנהל האירוע**- יהיה צמוד בשלב זה למפקד הרפואי ויקבל ממנו את כלל המידע הקיים לגבי הפצוע, כולל שאיבה אקטיבית של המידה מצידו. 3. **מטפל מס' 2**- יסייע למפקד הרפואי לבצע בדיקה מהירה ככל האפשר של הפצוע, בדגש על סיוע בהפשטה, בדיקה של פלג הגוף התחתון ועצירת דימומים.

עד לסיכום הטריאז' אין בידינו תמונת מצב של הפצועים, מה שמונע מאיתנו לקבל החלטות מושכלות ולתעדף טיפולים ופינויים. לאור זאת, יש לתת עדיפות לביצוע מהיר ויעיל של הטריאז' תוך זרימה מתמדת.

-   S: זיהוי ועצירה של דימומים פורצים ע"י CAT/PACKING או נקודת לחיצה. יש לשאוף כי מח"צ / חובש יהיו אלו שיבצעו את עצירות הדימום מתוך שיקולי ניהול זמן. במידה ובוצע PACKING מח"צ/חובש יבצע את הלחיצה על החבישה על מנת לא לעכב את המשך הטריאז'). בכל ספק יש להניח ח"ע ישירות. במידה וזה בוצע, כפי שרצוי, בשלב ריכוז הפצועים -- יש לוודא שהדימום נעצר כראוי. כמו כן סימון של הפצוע במספר.

-   A: בדיקת הכרה (AVPU), התרשמות מאיום על נתיב אוויר

-   B: חשיפה של בית החזה, התרשמות מהנשימה, הנחת פאלס-אוקסימטר

-   C: איתור דימומים נוספים, מדידה **כמותית** של דופק רדיאלי בפאלס-אוקסימטר או במידה ולא ניתן -- ידנית (בהעדרו -- קרוטידי).

-   שלב D לא מתבצע

-   E - הפיכה וסריקת דימומים בצד האחורי של הגוף

החלטה על הטיפולים הנדרשים תתקיים עבור כל פצוע בשלב זה. **אין לבצע טיפולים עד לסיכום הטריאז' על כלל הפצועים**, למעט הפעולות הבאות: \* ביצוע ניקור בית החזה בצד הפגוע עבור פצוע עם דופק רדיאלי / קרוטידי מעל 130 בנוכחות פגיעת חזה. בניגוד לטיפול בפצוע בודד, אין להתעכב לצורך הערכה של השפעת הניקור אלא לבצעה לאחר סיום הטריאז' (כמשימה בעדיפות גבוהה). \* פתיחת נתיב אוויר, החדרת מנתב אוויר והטייה על הצד עבור פצוע מחוסר הכרה נושם / איום על נתיב אוויר. \* סימון פצוע לא נושם (ממתין) באופן שיובהר כי עד לסיום הטיפול בכלל הפצוע אין לשוב אליו, לדוגמא הוצאתו משורת הטריאז'.

-   סיווג הפצוע:
    -   פצוע דחוף: סכנה לחיים או איבר. לדוגמא: פגיעת גו חודרת, דימום שנעצר ע"י חסם עורקים, פגיעת עין חודרת ועוד.
    -   פצוע לא דחוף -- ללא סכנה לחיים או איבר. לדוגמא: רסיסים בגפיים ללא דמם משמעותי.
    -   פצוע ממתין -- פצוע שאינו נושם באופן ספונטני -- סיכויי ההישרדות של פצוע כזה הם נמוכים ביותר, והטיפול בו יתבצע רק לאחר השלמת הטיפולים הנדרשים בפצועים הדחופים, מתוך העיקרון של הצלת מקסימום פצועים בני הצלה.

**בתום ביצוע הבדיקה של כל פצוע, ימסור המנהל הרפואי למנהל האירוע את הפרטים הבאים, שיתועדו על-ידיו בטבלה ייעודית לניהול אר"ן (נספח א') / בטופס 101 דיגיטלי:** 1. מספר הפצוע (כפי שסומן על גבי הפצוע בצורה בולטת). 2. הפציעה, לרבות מנגנון, אנטומיה ושינויים פיסיולוגיים משמעותיים, כפי שידועים בשלב זה (לדוג': פגיעת ירי לבטן, בהלם; חבלת ראש קהה, מגיב לכאב; פציעת חזה, סטורציה 90) 3. מהם הטיפולים הנדרשים וסדר ביצועם (בעמודה זו יש לציין גם טיפולים שכבר בוצעו תו"כ הטריאז', כדוגמת הנחת CAT, ניקור חזה) 4. דחיפות לפינוי 5. דגשים לפינוי (צורך במט"ב, הנשמה, שכיבה / ישיבה וכו')

במקביל לביצוע הטריאז', יתר החובשים והמח"צים יבצעו במקביל את הפעולות הבאות, לפי סדר חשיבות: 1. עצירת דימומים פורצים. 2. הפשטה של הפצועים שטרם נבדקו וסריקת דימומים. 3. הכנה לפינוי.

#### סיכום הטריאז'

בשלב זה בפעם הראשונה לא רק בוחנים כל פצוע לגופו, אלא מסדרים את סדר הקדימויות בין הפצועים השונים. המפקד הרפואי ומנהל האירוע עוברים על טבלת הפצועים (ראה נספח), מוודאים שכל המידע רשום בה, ומגדירים עבור כל פצוע: \* **קדימות לטיפול**- הסדר שלפיו יבוצעו הפעולות הטיפוליות בזמן הסבב הטיפולי. הקדימות תיקבע לפי הקדימות של הבעיות בסכימה -- כלומר בעיות נתיב אוויר (A), לאחריהן בעיות נשימה (B), לאחריהן טיפול בהלם ועצירת דימומים שאינם פורצים (C) וכן הלאה. \* **קדימות לפינוי**- הסדר לפיו יפונו הפצועים, המוכתב עפ"י מידת דחיפותם. במידה ופצוע ספציפי זקוק לפינוי עם מט"ב, גם אם הוא ראשון בתור לפינוי, אולם הפינוי הוא ללא מט"ב, יש לדלג עליו עד להגעת פינוי עם מט"ב.

בתום סיכום הטריאז' ידווח מנהל האירוע: \* **למפקד האג"מי**- מס' הפצועים הכולל, חלוקה לפי דחוף / לא דחוף / ממתין (לדוגמא: "סה"כ 6 פצועים -- 2 דחופים, 3 לא דחופים, 1 ממתין") ודרישות מיוחדות -- צורך בפינוי מוסק, חילוץ לכוד. \* **לרמה הממונה הרפואית**- מס' הפצועים הכולל, חלוקה לפי דחוף / לא דחוף / ממתין ובהמשך, מבלי לפגוע בניהול האירוע -- תועבר הטבלה באופן סדור (לדוגמא: "פצוע מס' 1, פציעת ירי בבטן ורגל ימין, הלם, הונח ח.ע., זקוק לפלסמה והקסאקפרון, דחוף לפינוי. פצוע מס' 2...").

#### סבב טיפולי

מטפל בכיר בצמוד לחובש ישלים את סכמת סקר ראשוני (כפי שהיא מופרטת בפרק "הסכמה -- הטיפול בפצוע טראומה בשדה") בכלל הפצועים על פי הקדימות לטיפול שנקבעה בטריאז', זאת במקביל להערכות לביצוע פעולות באותו פצוע ככל שהוחלט עליהן בטריאז' (הכנת פלסמה, החדרת עירוי, פריסת פרוצדורה וכיוצ"ב) . מנהל האירוע יקצה לחובשים משימות שניתנות לביצוע ללא מט"ב -- כדוגמת עצירת דימומים שאינם פורצים, נטילת מדדים, השגת גישה ורידית, הכנת פלסמה, מתן טיפול נגד כאבים -- כל זאת במסגרת החלטות שהתקבלו ע"י המפקד הרפואי בטריאז'. חובש יהיה רשאי לחבר פלסמה לפצוע אך ורק באישורו של מטפל בכיר.

מנהל האירוע ינהל גם את עבודת המח"צים / חובשים נוספים שיכינו פצועים לפינוי, בדגש על העמסה לאלונקות וכיסוי, בהתאם לסדר הקדימות לפינוי .

במידה והושלמו כלל הטיפולים שהוחלט לגביהם בטריאז' ונותרו פצועים בשטח שטרם פונו, יש לבצע הערכה חוזרת שלהם, להחליט לגבי צורך בטיפולים נוספים ובעיקר לקדם את פינוים.

#### חבירה

משאבי הטיפול והפינוי הם משאב החסר באירועים רבי נפגעים. לכן, יש להיערך להגעה של כוחות רפואה נוספים בכל שלב ולהכווינם כך שיהוו גורם מסייע ולא גורם מפריע. אופן החבירה תלוי בשלב בו מגיע הצוות החובר. ככלל, במידה והזירה ומספר הפצועים מאפשרים, יש להפוך את האירוע מהר ככל הניתן לאירוע בו ישנו צוות אורגני על כל פצוע. עם זאת, יש להקפיד על ניהול מרכזי ע"י מפקד רפואי ומנהל אירוע ששולטים בתמונת המצב, נותנים מידע והנחיות לצוותים לגבי פינוי ומדווחים לרמה ממונה. בנוסף, יש לשקול את התועלת הפוטנציאלית המרבית בכל צוות שמגיע - האם יועיל יותר בסיוע לטיפול או שמא בפינוי של פצוע דחוף.

#### חבירה טרם/ במהלך הטריאז'

עם המפגש בין הצוותים, יוגדר באפן ברור המטפל הבכיר ביותר כמפקד הרפואי של האירוע. לאחר סידור הזירה בהתאם לדגשים, ובאופן לינארי, יתחילו שני הצוותים טריאז' במקביל משני כיוונים מנוגדים כאשר בתיאום צוות אחד ימספר את הפצועים במספרים עוקבים (1,2,3...) והשני באותיות עוקבות (א',ב',ג'...). בתום הטריאז' מטבע הדברים שני הצוותים ייפגשו במרכז הזירה, הצוות הזוטר יותר ימסור לצוות הבכיר את טבלת ניהול האירוע שלו ויתבצע סיכום טריאז' משותף. בשלב הסבב הטיפולי יש עדיפות שהמפקד הרפואי ימשיך בניהול האירוע בסיוע מנהל האירוע שלו, בעוד המטפל הזוטר יותר מבצע פעולות טיפוליות בהתאם לסדר העדיפויות שהוגדר. עם זאת, במידה ויש מס' פעולות מצילות חיים הנדרשות לביצוע, גם המפקד הרפואי ישתתף בטיפול, כשמנהל האירוע שלו ממשיך בניהול האירוע. בשאיפה בצמוד לכל מטפל בכיר יעבוד חובש אורגני. באופן זה יש לנהוג כל עוד החבירה מתרחשת טרם סיכום הטריאז'.

#### חבירה לאחר הטריאז'

הצוותים החוברים יחברו למנהל האירוע, ובמידה וניתן גם למפקד הרפואי, ויקבלו מהם משימות בהתאם לסדר העדיפויות שהוגדר בסיכום הטריאז', בין אם לפינוי או לטיפול, לפי הצורך. במקרה של דילמה, יכריע המפקד הרפואי של האירוע. יש לזכור כי לניהול וקבלת הכרעות באר"ן חשיבות מכרעת לגורל הפצועים, לרוב יותר מפעולה ספציפית זו או אחרת.

#### סיום האירוע

1.  וידוא פינוי של כלל הפצועים. במידה ונותרו בשטח פצועים ממתינים, יש לבצע עליהם סקר ראשוני, ובמידת הצורך פרוטוקול אובדן סימני חיים, לרבות קביעת מוות.
2.  השלמת ואיסוף הרישום.
3.  דיווח מסכם
4.  ארגון כוח האדם והציוד וחזרה לכשירות, לרבות העלאת דרישה לרמה ממונה להשלמות ציוד.
5.  שיחות סיכום של הצוותים המטפלים.

### סיכום

אירוע רב נפגעים מהווה אתגר גדול לצוותים המטפלים, עתיר הסחות, ומכיל עומס של קבלת החלטות ואי-ודאות .הניסיון המצטבר מאירועים רבי נפגעים בצה"ל מראה כי ניהול נכון של אירוע רב נפגעים והיצמדות לפרוטוקולים משפיעים באופן ישיר על תוצאות הטיפול באר"ן.

### נספח א' -- טבלת שליטה לניהול אירוע רב נפגעים

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה של הנספח

### נספח ב' -- טבלת שליטה לניהול אירוע רב נפגעים -- מילוי לדוגמא

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה של הנספח
