# פציעות שריר שלד

## עיקרי העדכונים:

- 6/2022

 1. כתיבת הפרק

## תוכן עניינים:

**כותבים:	212**

**רקע:	213**

**קדימויות הטיפול בפציעות שריר ושלד:	214**

**אבחנה:	215**

**קדימויות הפינוי:	217**

**סיכום:	217**

תסמונת מדור – Compartment Syndrome	218

שברי אגן - 
Pelvic Fractures	218

שברי עצם הירך - Femur Fractures
223

**נספחים:	229**




### רקע: 

פציעות שריר ושלד מהוות כ-85% מהפציעות עקב חבלות קהות וכ-50% מהפציעות במתאר קרב. פציעות אלו עלולות להוות פוטנציאל לסכנת חיים ללא מתן טיפול מתאים. יש לציין, כי בעשור האחרון לא אירע מקרה תמותה אחד כתוצאה מפציעות שריר ושלד מבודדות, בקרב חיילי צה"ל ונפגעים אשר טופלו ע"י כוחות צה"ל. חרף זאת, פציעות שריר ושלד הן פציעות אשר לעיתים מלוות בנכות ופגיעה משמעותית באיכות החיים.  

מרבית פציעות השריר והשלד נגרמות במנגנון של פגיעה באנרגיה גבוהה. כתוצאה מכך, קיימת היארעות גבוהה של פגיעה רב מערכתית לרבות בבית החזה, הבטן והאגן. חשוב לזכור כי למרות שפציעות בעצמות ארוכות (זרועות, אמות, ירכיים ושוקיים) עלולות להיות התלונה העיקרית של הנפגע ובולטות לעין, יש לבדוק את הנפגע באופן מערכתי על מנת לא לפספס פגיעות המאיימות על נתיב האוויר, הנשימה ומחזור הדם. על אף שלרוב פציעות בעצמות ארוכות אינן מסכנות חיים, תסמונת מדור עלולה לגרום לנכות משמעותית. באופן נדיר, שברים בעצמות ארוכות עלולים לייצר תסחיפי שומן (Fat emboli)  אשר עשויים לפגוע במערכות הגוף השונות.

בניגוד לפציעות שריר ושלד אחרות, בפגיעות עמוד שדרה/ עמוד שדרה צווארי יתכן קיפוח המודינמי ע"ר שוק נוירוגני ובפציעות באגן קיימת סכנה המודינמית משמעותית עקב אובדן הדם האפשרי. קרונות הטיפול המרכזיים בפציעות אגן במתאר טרום בית החולים הן הפחתת הדימום ע"י קיבוע/ייצוב והחזר של נפח. הטיפול בכלל פציעות השריר והשלד ע"י קיבוע מסייע בהפחתת הכאב ועשוי אף למנוע פגיעה במערכת העצבים וכלי הדם בגפה.

 הטיפול המוחלט (דפיניטיבי) בפציעות שריר ושלד נעשה בבית החולים, אך אין להתעלם מפציעות אלו במתאר טרום בית החולים על מנת לצמצם סכנה לחיים ולגפה ולמנוע נכות עתידית. פרק זה, יציג את עקרונות הטיפול בפציעות שריר ושלד במתאר טרום בית החולים וינחה בטיפול בפציעות המעורבות בנפגעי טראומה בחומרה קשה. 
 
**לפרק זה יתווסף בהמשך תוכן נוסף אשר עוסק בפציעות עמוד שדרה ועמוד שדרה צווארי והניהול של מקרים אלו במתאר טרם בית חולים.**


### קדימויות הטיפול בפציעות שריר ושלד:

*****תרשים

### אבחנה:

לצורך זיהוי פציעות שריר ושלד ואבחנה של שבר בעצמות ארוכות נדרשת הפשטה מלאה של הפצוע, הפיכתו תוך שמירה על עמוד השדרה ככל הניתן ובדיקה קפדנית מכף רגל ועד ראש בכלל המישורים. כאשר נבדוק כל אחת מן הגפיים, ראשית נתבונן ונתרשם **מפצעים, שינויי או עיוותי צורה (deformations), נפיחות, שטפי דם, שינוי צבע הגפה ונתרשם מזילוח הדם (perfusion)**. במתאר טרום בית החולים, לאחר התבוננות נבצע **בדיקה נוירו-וסקולרית** בה נמשש דפקים פריפריים, נעריך מילוי קפילרי, תחושה דיסטלית וכוח מוטורי. יש לתעד את הבדיקה הנוירו-וסקולרית באופן מדויק לצורך השוואה בהמשך. במידה ולא מצאנו ממצא חריג עד כה, נשלים מישוש של הגפה לאורכה בחיפוש אחר **רגישות, נפיחות, שינוי טמפרטורה או עיוות** אשר עשויים להצביע על פגיעה **(כגון שבר או פריקה).** לעיתים, נוכל לחוש ולשמוע חריקות (crepitus) בין חלקי שברים אך אין צורך להפיק זאת במיוחד ולהכאיב לפצוע. מומלץ לצלם תמונה של הפציעה
לצורך התייעצות ומעקב. 

### טיפול:
הטיפול המיידי בפצוע הסובל מפציעות שריר ושלד מתבצע על פי  *סכימת הטיפול האחודה* וקדימויות הטיפול הידועות: כך שפציעות שריר ושלד המלוות בדימום פעיל יעצרו ע"י לחץ ישיר )בעדיפות ראשונה) או לחץ עקיף.

**שברים ופריקות –** ככלל, הטיפול הדפיניטיבי בבית החולים בפציעות אלו יכלול החזרה וצמצום (Reduction) וקיבוע מוחלט (Fixation). פעולות אלו יתבצעו לרוב בדרג ב' או בביה"ח על ידי אורתופדים. במתאר טרום ביה"ח, פציעות אלו נדרשות לעבור קיבוע יחסי בסד (Splinting). לא תתבצע רדוקציה במתאר טרום בית החולים אלא ע"י אורטופד או בייעוץ ישיר שלו. קיבועים של מערכת השריר והשלד יתבצעו בשלב הסקר השניוני למעט שברים באגן והירך בהם נטפל כבר בסקר הראשוני וסקר ההחייאה כפי שנסביר בפרק נפרד. על אף שפעולת הרדוקציה חשובה, היא אינה פשוטה לביצוע ועלולה לגרום לסיבוכים או להחמיר אף יותר את הפגיעה, ועל כן תיעשה ע"י צוות המומחה בכך בדרג ב' או בבית החולים. **יש להימנע מהחזרת עצמות ו\או מפרקים למקום אלא לקבע בסד או חבישה את הגפה כפי שהיא - בעדיפות על ידי שימוש בסד ייעודי כגון SAMSplint.** לקיבוע הזמני עצמו (בסד או בכריכה) קיימת השפעה מפחיתת כאב כיוון שחלקי העצם אינם זזים ומגרים את סיבי העצבים סביבם בשכבת הפריאוסט (מעטפת העצם). את הטיפול בכאב יש להשלים בהתאם
לפרק *הטיפול בכאב*. 

**שברים פתוחים -** הינם שברים בהם קיימת פגיעה בשלמות העור או באחד מחללי הגוף וחשיפת מקטע העצם לסביבה החיצונית. בספרות מקובל לחלק את השברים על פי קלסיפיקציית גוסטילו המתייחסת למידת חשיפת העצם, לרמת הזיהום ולרמת הפגיעה ברקמה הרכה. שברים כאלו אשר נחשפים לסביבה חיצונית נוטים להזדהם. פציעות אלו, כאמור, הינן מרשימות ועלולות להסיח את הדעת מפציעות חמורות יותר אשר מסכנות חיים באופן מידי. על כן, אלא אם הפציעה מלווה בדמם משמעותי, *הטיפול יבוצע במהלך הסקר השניוני.*

**שטיפה והטרייה -** את הפציעה יש לנקות מגורמים מזהמים על ידי הוצאת לכלוך גס ושטיפה מרובה על ידי *2 ליטר לפחות* של נוזל סטרילי כדוגמת הרטמן\סליין ישירות על הפציעה (אין לנסות להכניס צינורית לתוך הפצע). לאחר מכן, *יש לחבוש* בתחבושת לחה ונקייה כגון תחבושת בטן, תחבושת אישית או פדי גזה הספוגים בתמיסת הרטמן או סליין. לבסוף, יש *לקבע* את הגפה. יש להשלים טיפול נגד זיהומים בהתאם לפרק טיפול באנטיביוטיקה ולטפל בכאב בהתאם לפרק *הטיפול בכאב. א*יחור בטיפול מעל לשלוש שעות מהווה גורם סיכון משמעותי לזיהום באתר הפציעה.

*אין צורך להניח חסם עורקים על גפה עם שבר פתוח שאינו מדמם.*

**קטיעות ופציעות** – בכל מקרה של קטיעת גפה (מלאה\חלקית) יש להניח חסם עורקים גם אם לא נצפה דימום פעיל.

את הגדם יש לשטוף, ולחבוש כפי שתואר. במקרים של קטיעה חלקית (בה הגפה עודנה מחוברת לגוף באמצעות גידים, רצועות או שרירים) יש לקבע את החלק הקטוע כדי למנוע נזק נוסף. במקרים של קטיעה מלאה, במידה והחלק הקטוע נמצא, יש לפנות את החלק יחד עם הפצוע, בעדיפה למרכז טראומה (Level 1). על החלק הקטוע יש לשמור על ידי שטיפתו בנוזל סטרילי והכנסתו לשקית ניילון אטומה ולשמור בקירור במיכל עם קרח (ללא מגע ישיר של הקרח עם רקמה). יש להקפיד על הטיפול האנטיביוטי (קטיעה = שבר פתוח). 

פציעות בהן העור מופשט מן הגפה (degloving) צריכות להיחבש בסביבה **לחה ונקייה.** לצורך כך, ניתן להשתמש בחבישה לחה (תחבושת בטן, תחבושת אישית או פדי גזה הספוגים בקריסטלואידים או במים סטריליים). 

הפציעות עשויות להסיח את הדעת מפציעות דחופות אחרות, לכן יש להתייחס קודם לעצירת דימומים פורצים ופציעות מסכנות חיים אחרות על פי *הסכמה האחודה* בסקר הראשוני
.

 ******* תרשים


### קדימויות הפינוי:
ככלל, שברים בגפיים אינם מוגדרים "דחופים" לפינוי אך במצבים בהם יש חשד לפגיעה משמעותית המסכנת את הגפה או כזו אשר יכולה או גרמה לדימום משמעותי יש להגדיר את הנפגע כ"דחוף". לדוגמא:

1. כל שבר אשר מלווה בקיפוח המודינמי (הלם עמוק)

2. שבר פתוח

3. כל שימוש בחסם עורקים

4. חשד לשבר בגפה בליווי קיפוח נוירוסקולרי (כפי שהוערך ע"י רופא) 

### סיכום:
למעט שברים באגן ובירך, לרוב פציעות שריר ושלד אינן מסכנות חיים. עם זאת, כאשר קיימת סכנה לגפה הפציעות דורשות פינוי דחוף לבית החולים או לטיפול בדרג ב'. יש לזהות פציעות עמוד שדרה צווארי, אגן וירך בסקר הראשוני ופציעות אחרות ניתן לזהות בשלב הסקר השניוני. בפציעות אגן נטפל בכריכת אגן ע"מ למנוע דימום פוטנציאלי. שברים בירך יטופלו בהנחת סד תומס בהתאם להתוויות. עם זאת, עבור פציעות אחרות פעולות אלו לא יעכבו פינוי בשטח. לקיבוע הפציעות יכולת להקל על הכאב ולמנוע פגיעה נוירו-וסקולרית. יש לזהות ולטפל בגפיים איסכמיות כבר במתאר טרום בית החולים בטיפול שמרני ובקיבוע. בשברים פתוחים חשוב למנוע זיהומים על ידי שטיפה וטיפול 
באנטיביוטיקה.

## תסמונת מדור – Compartment Syndrome

### רקע:
מדורים אנטומים בגוף מכילים עצמות וסביבם שרירים ועצבים אשר תחומים ברקמת פאציה (Fascia). מדורים אלו הינם סגורים כך שלחצים פנימיים מוכלים בתוכם. כך לדוגמא, כיווץ שרירים ברגליים יעלה את הלחץ במדור כנגד ורידים ודם "ייסחט" במעלה הורידים חזרה אל הלב. חבלות קהות בגפה עלולות לגרום לאיסכמיה (הגבלה בזרימת הדם) חמורה בגפה, גם **ללא פגיעה ישירה** בכלי הדם שבגפה. דימום, בצקת, דלקת או זיהום עשויים להעלות את הלחץ בתוך המדורים השונים בגפיים. כתוצאה, זרימת הדם בנימים (קפילרות) קטנה ואספקת הדם לשריר פוחתת. האיסכמיה השרירית גורמת בעצמה לבצקת, עליית לחצים נוספת במדורים וכתוצאה אספקת דם פחותה אף יותר במנגנון של "מעגל אכזרי" (Vicious Cycle). אי זיהוי מהיר של התסמונת וטיפול מוקדם עשויים להוביל לפגיעה משמעותית ובלתי הפיכה בגפיים.

### אבחנה:
האזורים העיקריים אשר מועדים לפתח תסמונת מדור לאחר פציעה הינם השוק, האמה, הירך, הזרוע, כף הרגל וכף היד, כמו גם  **אזורים אשר נפגעו על ידי מעיכה או בכוויה היקפית.** בתסמונת מדור הפגיעה באספקת הדם נפגעת בכלי הדם הקטנים הקפילריים ולא בכלי הדם הגדולים. לכן, עדיין **ניתן לחוש בדופק והעור לא יהיה חיוור** בניגוד לאיסכמיה בכלי דם גדולים. הסימן הראשון לאיסכמיה, לעיתים אפילו היחיד, הינו **כאב לא פרופורציונאלי שמרגיש כפורץ מתוך הגפה.** שינויים תחושתיים וחולשה בהפעלת השרירים הם תסמינים נלווים ומאוחרים.

בנוסף, שריר איסכמי הינו **רגיש במיוחד למתיחה.** לכן כאשר קיימת תלונה על כאב חמור בגפה לצד נפיחות נוקשה ניתן לבדוק חשד לתסמונת מדור על ידי מתיחה של השריר – לדוגמא דורסיפלקציה של הקרסול ואקסטנציה של אצבעות בכף הרגל להערכת תסמונת מדור במדור האחורי של השוק.

במידה והבדיקה קלינית לא חד משמעית או בעת צורך אבחנתי במטופל לא בהכרה, האבחנה מתבצעת על ידי מדידת לחצים באמצעות קטטר ייעודי אשר מוחדר למדור  או באמצעות סט ל"ד עורקי (arterial line). פעולה זו תתבצע בדרג ב' או בית החולים.  

### טיפול:
הטיפול החשוב ביותר בתסמונת מדור הינו פינוי מהיר לחדר ניתוח שם יבוצע שחרור של הלחצים במדור. שריר מתחיל לסבול לאחר שעתיים של איסכמיה ומתחיל לעבור נקרוזיס (נמק) לאחר 4 עד 6 שעות של איסכמיה.

במתאר טרום בית החולים, טיפול תומך יכלול **הסרה מוחלטת של קיבועים וכל אמצעי שיכול ללחוץ על הגפה ולא הוסר קודם לרבות הסרת תחבושות אשר אינן עוצרות דימומים פורצים.** אין צורך להרים את הגפה. טיפול מוחלט יתבצע בחדר ניתוח ע"י פאציוטומיה (Fasciotomy).



## שברי אגן - Pelvic Fractures

### רקע: 
שבר באגן הוא פציעת לוחמה שכיחה וקטלנית. בקרב המתים במהלך הלחימה של צבא ארה"ב בעיראק ואפגניסטאן, ב-16% הייתה מעורבות של האגן. נצפתה תמותה גבוהה יותר של פצועים עם שברים באגן שנגרמו כתוצאה מפגיעת פיצוץ וירי. התמותה יכולה להגיע **עד 40%** בפצועים עם שברים מדממים באגן ואי יציבות המודינמית. בקרב פצועי אגן במתאר צבאי, 76% משברי האגן הקטלניים הם תוצאה של פגיעות פיצוץ, 15% פציעות ירי ו-4.5% תאונות דרכים. **עיקרי הטיפול בשבר באגן בדרג א' הינם כריכת אגן, החזר נפח על פי ההנחיות בפרק DCR ופינוי מהיר לבית החולים.**

******תרשים


האגן והרטרו-פריטוניאום (retroperitoneum) מהווים חלל פוטנציאלי לצבירת דימום אשר יכול לגרום להלם עמוק. פציעת אגן מדממת הינה מצב חירום מסכן חיים ויש לחשוד בפציעה זו **בכל פצוע בטן וגפיים תחתונות.** מנגנוני הפציעה כוללים לרוב **תאונות דרכים, נפילות מגובה ופגיעות מעיכה או הדף\פיצוץ.** הדימום בפציעות אגן נובע לרוב הן מפגיעה בפקעת הורידית (venous plexus) (75%) אשר נמצאת על חלקו האחורי של טבעת האגן והן משולי העצם השבורים של טבעת האגן עצמה.

*****תרשים

מערכת כלי הדם באגן – שימו לב לקרבת כלי הדם לקיר האגן האחורי.


חרף המחסור במחקר והוכחות חד משמעיות לכך שקיבוע אגן מפחית תמותה, זוהי פעולה מומלצת על ידי איגודים מקצועיים רבים לרבות ועדת מומחים שכונסה בישראל ב-2020. על פי מחקרים בגופות, מקבע אגן בגובה הטרוכנטרים (Trochanters) והסימפיזיס פוביס(Symphysis Pubis)  מייצב שברים באגן ומצמצם את תנועתם. פעולה זו, כאשר מתבצעת בגובה הנכון של הטרוכאנטרים, הינה בעלת סיכונים מועטים זאת במיוחד למול התועלת הפוטנציאלית - ישנן עדויות קליניות שמקבע אגן מצמצם צורך במנות דם ומפחית שכיחות דימום קטלני. המלצותיהם של האיגודים המקצועיים וועדת המומחים הישראלית הן לבצע קיבוע אגן בשלב מוקדם ככל הניתן. קיבוע נחוץ במיוחד במנגנוני פציעה באנרגיה גבוהה מחבלה קהה או ירי באגן המתייצגים עם סימני הלם, ירידה במצב ההכרה וסימני פגיעה באגן. מבחינת סוג הקיבוע המומלץ, יש להשתמש במקבע אגן ייעודי (pelvic binder) שהוא אמצעי פשוט ונוח לשימוש. בהיעדר אמצעי ייעודי, ניתן להשתמש בסדין אשר ימצא על האלונקה לפני העמסת הפצוע (ולהוסיף קיבוע קרסוליים).

### אבחנה: 
האגן נבדק במהלך הסקר הראשוני בשלב ה-C. 

זיהוי פציעת אגן בשלב ה-C יתבצע ע"י **התרשמות ממנגנון החבלה (כאשר המנגנון מרמז על שבר באגן- לדוגמה נפילה מגובה עם סימני הלם, אין הכרח להמצאות סימנים נוספים), התבוננות ומישוש עדין.**

בהתבוננות ניתן למצוא סימנים רומזים כגון: נפיחות ושטפי דם בבטן התחתונה, ירכיים, פרינאום (Perineum), שק האשכים, הנרתיק ודימום מפתח השופכה (Meatus). מדרגה גרמית במידה ומבוצעת בדיקת PR. במישוש עדין ניתן להתרשם מרגישות וכאבים באזור האגן. **יש להימנע ככל הניתן מהפעלת לחץ על עצמות האגן ואם קיימת רגישות יש להימנע מחזרה על הבדיקה שנית.** פצוע בהכרה ללא רגישות באגן ככל הנראה אינו סובל משבר לא יציב באגן.

בעבר, לימדו לבצע בדיקת "ספר פתוח" (open book) בה בוצע לחץ על עצמות האגן לצורך התרשמות מפתיחתו והתרחבותו. אך מחקרים הראו כי לא רק שפעולה זו בעלת רגישות נמוכה לזיהוי שברים באגן אלא גם מלווה בסיכון להחמרת השבר או שחרור קרישי דם ויצירת תסחיפים. הבדיקה הזו לא תבוצע בדרג השטח ותשקל בדרג ב' בלבד ובייעוץ עם אורתופד.

*****תרשים

### טיפול: 
כריכת אגן תבוצע בשלב ה C באינדקציות הבאות:

מנגנון חבלה בקינמטיקה קשה  (תאונת דרכים, נפילה מגובה, מעיכה, הדף, פיצוץ או פגיעת ירי באגן)
**ואחד מהסימנים הבאים:**

1. סימני *הלם המודינמי*.

2. כאבים או *רגישות במישוש עדין.*

3. *נפיחות, שטפי דם או פגיעה חודרת* באגן.

כריכת אגן תבוצע באמצעי ייעודי ( Pelvic binder) או באמצעות סדין באופן הבא:

1. יש להניח את הסדין או המקבע על מרכז האלונקה **טרם העמסת הפצוע.**

2. יש למקם את הסדין בגובה המותניים, בפרט **בגובה הטרוכאנטרים** (ראו תמונה בהמשך).

3. יש לבצע את הקיבוע **במהלך שלב ה-C** על ידי שני אנשי צוות (ראו סרטוני הדרכה בהמשך).

החזרת השברים וייצוב האגן בכריכה וקיבוע מאפשר יצירת קרישי דם הן בפקעת הורידית והן בשולי העצם. קרישי דם אלו יסייעו לעצור את הדימום. בבית החולים, במידה והדימום נמשך בעוצמה משמעותית ניתן לבצע אמבוליזציה /packing  בחדר ניתוח וקיבוע זמני ניתוחי. 

******תרשים

כריכת אגן בסדין.
סרטון הדרכה (לחצו על התמונה).

******תרשים

מקבע אגן ייעודי.
סרטון הדרכה (לחצו על התמונה).

******תרשים

שימו לב לגובה של האמצעים לקיבוע האגן ביחס לטרוכאנטרים והסימפיזיס פוביס.

על הקיבוע לשבת על גבי הטרוכאנטרים הגדולים (הנקודה שבין הישבן לירך, מתחת לגובה המותניים) וזאת  כדי להצמיד את טבעת האגן יחדיו. הפעלת לחץ גבוה יותר או נמוך יותר עשוי להפריד את חלקי השבר ולהחמיר את הפציעה.


### סיכום:
שברי אגן יכולים לגרום לדימום מסכן חיים ולכן יש לזהות אותם מוקדם בסקר הראשוני (בשלב ה-C) ולהתייחס אליהם בטיפול במתאר טרום בית החולים. **יש לבצע את כריכת האגן בכל חשד לשבר באגן.**

נחשוד בשבר באגן כאשר מנגנון הפציעה התרחש **בקינמטיקה קשה** כגון: נפילה מגובה, תאונת דרכים, מעיכה, הדף, פיצוץ או פגיעה חודרת ישירה באגן **ביחד עם אחד הסימנים הבאים:**

1. **סימני הלם המודינמי.**

2. **סימני חבלה קהה** באזור האגן, הבטן והירכיים או **פציעה חודרת ישירה** באגן.

3. תלונות הפצוע על **כאבים** באזור האגן או **רגישות במישוש עדין** של האגן.

יש להתקין את הקיבוע **טרם** פינוי הפצוע באופן דחוף לביה"ח או דרג ב' להמשך בירור וטיפול.



## שברי עצם הירך - Femur Fractures

### רקע:
עצם הירך הינה העצם הארוכה ביותר בגוף האדם והיא העצם היחידה בירך. שברים  בעצם זו נחשבים למסכני חיים פוטנציאלית **עקב אובדן דם** של 1,000-1,500 מ"ל לירך. שבר פתוח נחשב מסוכן עוד יותר עקב אובדן דם מתמשך דרך הפצע העורי. מנתוני חיל הרפואה נמצא כי כמחצית (49%) מהשברים בעצם הירך במתאר הצבאי היו שברים פתוחים **והתאפיינו בדימום מהירך שהיה קשה לעצירה.** פציעות המערבות שברים בשתי הירכיים אף קשורים בסיכון גבוה מאוד לסיבוכים ותמותה, גם בשל אובדן הדם וגם עקב **מנגנוני פציעה משמעותיים בפציעות נלוות בית החזה, הבטן והאגן.** 

פציעות מבודדות בעצם הירך לרוב **לא מופיעות עם סימני הלם עמוק** בהעדר פציעות מסוכנות נוספות בחלל הבטן והאגן. בסקירת המקרים שהתרחשו בצה"ל לפחות מ-10% מהפצועים היו סימנים של הלם תת נפחי. לכן, בדומה לפציעות שריר ושלד אחרות, **חשוב להתרכז בסקר הראשוני בפציעות מסכנות חיים אחרות שנלוות לפציעות אלו.** 

שברים מבודדים בעצם הירך **אינם שכיחים.** למעשה, בעבודה שבוצעה לאחרונה בענף הרפואה המבצעית, נמצאו רק 130 מקרים שטופלו ע"י צוותי פג"ה ב-20 השנים האחרונות. מרבית השברים נגרמו בעקבות **תאונות דרכים (48%) ופציעות ירי בירך (24%).**


### אבחנה:
חלק מהשברים בעצם הירך יזוהו בשלב ה C, והשאר עד סיום הסקר הראשוני. האבחנה תיעשה על פי הימצאות: שברים פתוחים או פציעות ירי בירך המלוות בעיוות (דפורמציה) משמעותי של הירך בהשוואה לירך השנייה כגון נפיחות, קיצור או סיבוב של הגפה. עצם הירך חולקת מפרק עם עצמות האגן ולכן כאשר נחשוד בשבר בירך יש לבצע גם הערכה של שברים באגן. 


*****תרשים

סיבוב חיצוני של הירך וקיצור של הגפה.

*****תרשים

שבר בעצם הירך.



### טיפול:
הטיפול על ידי **קיבוע של שברים בעצם הירך נחשב כיעיל בהפחתת דימום ובהפחתת כאב (לאחר המתיחה).** סד התומס (Thomas Splint) פותח במאה ה-19 והיה בשימוש נרחב במלחמת העולם הראשונה. בדיווחים מאותה תקופה עלה כי השימוש בסד הפחית את התמותה כתוצאה משברים בעצם הירך בכ-80%. עם זאת, ספרות עכשווית בנושא הינה דלה וזאת ככל נראה עקב ההיארעות הנמוכה של פציעות אלו. במחקרים עדכניים נמצא כי השימוש בסד התומס הפחית ב-30% מהפצועים את הצורך במנות דם ואשפוז ממושך, במיוחד כאשר ההנחה התבצעה בטרום בית החולים. המנגנון בו הקיבוע והמתיחה של הסד מפחית את הדימום הינו במניעת תזוזת חלקי השבר ופגיעה נוספת ברקמה רכה, יצירת סביבה המעודדת התפתחות והתייצבות קרישי דם וכן גם בהקטנת הנפח הפוטנציאלי בירך אליו ניתן לדמם.

*****תרשים

לפני ואחרי מתיחה עם סד תומס.

*****תרשים

לפני ואחרי מתיחה עם סד CT6.

******תרשים 

הנחת סד תומס- סרטון הדרכה


בכ-38% מהמקרים מתקיימות לכאורה התווית נגד להנחת סד תומס (כגון שבר באגן, הברך, השוק והקרסול). עם זאת, קיימת הסכמת מומחים כי התועלת ההמודינמית גבוהה מהסיכון לנזקים עקב קיבוע של עצם הירך. בנוסף, קיימת הסכמה כי קיבוע הירך לא צריך לעכב פינוי וניתן לבצע זאת במהלך הפינוי. בצה"ל קיים סד קל משקל העשוי מצינורות סיבי פחם חזקים בשם סד CT6  (Carbon-fiber Tubing).


### לסיכום:
שברים בעצם הירך הינם סמן לפגיעה קשה ומסכנת חיים. הטיפול היעיל ביותר עבורם במתאר טרום בית החולים הינו **קיבוע עם סד תומס ומתיחת חלקי השבר.** יש לבצע הערכה של שברים בירך בסקר הראשוני בשלב ה-C ולחשוד בשבר בעצם הירך בכל פצוע עם פגיעת ירך בקינמטיקה קשה עם סימנים אופייניים לשבר בהשוואה לגפה השנייה.

בחשד לשבר בעצם הירך יש לבצע מתיחה באמצעות סד תומס:

1. שבר פתוח בירך.

2. דפורמציה משמעותית בירך (כגון נפיחות, קיצור או סיבוב גפה)

את סד התומס יש להניח **בשלב סקר ההחייאה** ולמתוח בשלב מוקדם כל עוד והפעולה אינה מעכבת פינוי. עם זאת, לאור התוויות הנגד היחסיות, מתיחת הסד תתבצע רק על ידי מטפל בכיר. יש לעצור את ביצוע המתיחה במידה והפעולה גורמת לכאב בלתי נסבל אצל הפצוע. יש לבצע בדיקה נוירו-וסקולרית לפני הנחת הסד ואחריו ולתעד אותה.



## רשימת ספרות (Bibliography)

<div dir="ltr">

1. 	American College of Surgeons, Comittee on Trauma. Advanced Trauma Life Support: Student Course Manual. 10th ed. American College of Surgeons; 2018.
2. 	Tornetta P, Court-Brown CM, Heckman JD, et al. Rockwood, Green, and Wilkins Fractures in Adults and Children: Eighth Edition. Vol 1-2.; 2014.
3. 	Solomon L, Warwick D, Nayagam S. Apley and Solomon’s Concise System of Orthopaedics and Trauma.; 2014. doi:10.1201/9780429166808
4. 	Melamed E, Blumenfeld A, Kalmovich B, Kosashvili Y, Lin G. Prehospital care of orthopedic injuries. Prehosp Disaster Med. 2007;22(1):22-25.
5. 	Azar FM, Beaty JH, Canale ST. Campbell’s Operative Orthopaedics, Thirteenth Edition. In: Elsevier. ; 2017.
6. 	Davis JM, Stinner DJ, Bailey JR, Aden JK, Hsu JR, Skeletal Trauma Research Consortium. Factors associated with mortality in combat-related pelvic fractures. J Am Acad Orthop Surg. 2012;20 Suppl 1. doi:10.5435/JAAOS-20-08-S7
7. 	White CE, Hsu JR, Holcomb JB. Haemodynamically unstable pelvic fractures §. doi:10.1016/j.injury.2008.11.023
8. 	Bailey JR, Stinner DJ, Blackbourne LH, Hsu JR, Mazurek MT. Combat-related pelvis fractures in nonsurvivors. J Trauma. 2011;71(1 Suppl). doi:10.1097/TA.0B013E31822154D8
9. 	Zong Z wen, Chen S xu, Qin H, et al. Chinese expert consensus on echelons treatment of pelvic fractures in modern war. Mil Med Res. 2018;5(1):1-13. doi:10.1186/S40779-018-0168-3/FIGURES/1
10. 	Cullinane DC, Schiller HJ, Zielinski MD, et al. Eastern association for the surgery of trauma practice management guidelines for hemorrhage in pelvic fracture-update and systematic review. J Trauma - Inj Infect Crit Care. 2011;71(6):1850-1868. doi:10.1097/TA.0B013E31823DCA9A
11. 	Magnone S, Coccolini F, Manfredi R, et al. Management of hemodynamically unstable pelvic trauma: results of the first Italian consensus conference (cooperative guidelines of the Italian Society of Surgery, the Italian Association of Hospital Surgeons, the Multi-specialist Italian Society of Young Surgeons, the Italian Society of Emergency Surgery and Trauma, the Italian Society of Anesthesia, Analgesia, Resuscitation and Intensive Care, the Italian Society of Orthopaedics and Traumatology, the Italian Society of Emergency Medicine, the I. World J Emerg Surg. 2014;9(1). doi:10.1186/1749-7922-9-18
12. 	Coccolini F, Stahel PF, Montori G, et al. Pelvic trauma: WSES classification and guidelines. World J Emerg Surg. 2017;12(1). doi:10.1186/S13017-017-0117-6
13. 	Incagnoli P, Puidupin A, Ausset S, et al. Early management of severe pelvic injury (first 24 hours). Anaesth Crit Care Pain Med. 2019;38(2):199-207. doi:10.1016/J.ACCPM.2018.12.003
14. 	Shackelford S, Hammesfahr R, Morissette D, et al. The Use of Pelvic Binders in Tactical Combat Casualty Care: TCCC Guidelines Change  1602 7 November 2016. J Spec Oper Med  a peer Rev J SOF Med  Prof. 2017;17(1):135-147.
15. 	בנוב א, אנקורי ר, גיא א, et al. סיכום דיון ועדת מומחים – פציעות אגן וירך. In: ספר הטראומה. ; 2020:1-9.
16. 	Shlamovitz GZ, Mower WR, Bergman J, et al. How (un)useful is the pelvic ring stability examination in diagnosing mechanically unstable pelvic fractures in blunt trauma patients? J Trauma. 2009;66(3):815-820. doi:10.1097/TA.0B013E31817C96E1
17. 	Lieurance R, Benjamin JB, Rappaport WD. Blood loss and transfusion in patients with isolated femur fractures. J Orthop Trauma. 1992;6(2):175-179. doi:10.1097/00005131-199206000-00007
18. 	Kajja I, Bimenya GS, Eindhoven B, Jan Ten Duis H, Sibinga CTS. Blood loss and contributing factors in femoral fracture surgery. Afr Health Sci. 2010;10(1):18-25.
19. 	Lee C, Porter KM. Prehospital management of lower limb fractures. Emerg Med J. 2005;22(9):660-663. doi:10.1136/EMJ.2005.024489
20. 	Neumann M V., Sudkamp NP, Strohm PC. Management of femoral shaft fractures. Acta Chir Orthop Traumatol Cech. 2015;82(1):22-32. Accessed January 30, 2022. https://pubmed.ncbi.nlm.nih.gov/25748658/
21. 	Conway D, Albright P, Eliezer E, Haonga B, Morshed S, Shearer DW. The burden of femoral shaft fractures in Tanzania. Injury. 2019;50(7):1371-1375. doi:10.1016/J.INJURY.2019.06.005
22. 	Stachurski J, Sionek A. Epidemiology of femoral shaft fractures in Poland. Przegl Epidemiol. 2020;74(3):492-502. doi:10.32394/PE.74.43
23. 	Wertheimer A, Olaussen A, Perera S, Liew S, Mitra B. Fractures of the femur and blood transfusions. Injury. 2018;49(4):846-851. doi:10.1016/J.INJURY.2018.03.007
24. 	Lynch JM, Gardner MJ, Gains B. Hemodynamic significance of pediatric femur fractures. J Pediatr Surg. 1996;31(10):1358-1361. doi:10.1016/S0022-3468(96)90827-1
25. 	Ciarallo L, Fleisher G. Femoral fractures: are children at risk for significant blood loss? Pediatr Emerg Care. 1996;12(5):343-346.
26. 	Kobbe P, Micansky F, Lichte P, et al. Increased morbidity and mortality after bilateral femoral shaft fractures: myth or reality in the era of damage control? Injury. 2013;44(2):221-225. doi:10.1016/J.INJURY.2012.09.011
27. 	Campagne D, Cagle K, Castaneda J, et al. Prehospital Traction Splint Use in Midthigh Trauma Patients. J Emerg Trauma Shock. 2020;13(4):296. doi:10.4103/JETS.JETS_152_19
28. 	Hoppe S, Keel MJB, Rueff N, Rhoma I, Roche S, Maqungo S. Early versus delayed application of Thomas splints in patients with isolated femur shaft fractures: The benefits quantified. Injury. 2015;46(12):2410-2412. doi:10.1016/J.INJURY.2015.09.039
29. 	Wood SP, Vrahas M, Wedel SK. Femur fracture immobilization with traction splints in multisystem trauma patients. Prehosp Emerg Care. 2003;7(2):241-243. doi:10.1080/10903120390936860

</div>

## נספחים: 
דוגמאות לקיבועים שונים (סרטונים)

**לחצו על התמונות לצפייה בסרטוני הסבר**

*****תרשים

קיבוע נקע או שבר קל בקרסול

*****תרשים

קיבוע נקעים, פריקות או שברים 
בכתף, מרפק ובאמה

******תרשים

קיבוע שברים בעצם השוק

*****תרשים

קיבוע קרסול באמצעות
 SAM SPLINT
 
*****תרשים
 
קיבוע הזרוע באמצעות
SAM SPLINT

******תרשים

קיבוע עצם השוק באמצעות
SAM SPLINT

********תרשים
          					           חבישת גדם


