# טיפול בכאב

## עיקרי העדכונים:

-   19/07/2021
    -   הוספת משקל סף למתן אקטיק
-   23.12.20:
    -   עדכון הפרוטוקול (כולל הפרדה למסלול תוך-ורידי ומסלול אקטיק).
    -   הגדרת קטמין כתרופה תוך-ורידית ראשונה, ובמתן בודד.
    -   היתר מתן אקטיק ע"י חובש.
    -   אי-מהילה של קטמין.
    -   הוספת מינוני ילדים.

## תוכן עניינים:

**מבוא**

**עקרונות והנחות יסוד**

**פרוטוקול**

**ביאור הפרוטוקול**

-   **פרק א: רקע כללי**

-   **פרק ב': הערכת רמת הכאב**

-   **פרק ג': החלטה על סוג הטיפול**

**סיכום**

**ביבליוגרפיה ומקורות**

## מבוא:

כאב הינו תלונה שכיחה בפצועי טראומה ולטיפול אנלגטי בפצוע חשיבות גבוהה במיוחד במתארי לחימה, בהם רמת הדחק (סטרס) של הפצוע גבוהה, ותתכן המתנה ממושכת לפינוי. הוכח כי טיפול מוקדם ויעיל בכאב מסייע לתוצא (outcome) מוצלח יותר בפציעה טראומטית. לכאב לא מטופל השפעות פיזיולוגיות אשר מעלות את רמת החרדה של הפצוע וכתוצאה מכך מקשה על הטיפול בו. כאב אקוטי לא מטופל אף נקשר לשכיחות מוגברת של התפתחות כאב כרוני ו-Post-Traumatic Stress Disorder (PTSD) בקרב הפצועים. עם זאת, בין אם מחוסר מודעות או מחשש לתופעות לוואי (מצד המטפלים), חלק מהפצועים בשדה לא מקבלים טיפול הולם לכאב או שמתן משככי הכאב נדחה לשלבי טיפול מאוחרים מאוד. כאב מתחיל בנקודת הפציעה ומחקרים מצביעים על כך כי בפני המטפל הראשוני ניצבת ההזדמנות הראשונה ויתכן אף המשמעותית ביותר לשבור את מעגל הכאב ולשפר את התוצאות ארוכות הטווח של הפצוע.

## עקרונות והנחות יסוד:

1.  כאב צריך להיות מנוטר (בסולם 1-10) ומתועד כאחד הסימנים החיוניים, הטיפול לכאב צריך להתבצע במהלך *סקר ההחייאה*, בהמתנה לפינוי או במהלכו.

2.  חובשים יטפלו בכאב "בלתי נסבל" (דרגה 5 ומעלה מתוך 10 בסולם NRS ) באמצעות סוכריות פנטניל ציטרט (OTFC).

3.  מטפלים בכירים וחובשים יטפלו בכאב קל - עד 4 כולל (מתוך 10) פומית באמצעות אקמול ו\או אופטלגין.

4.  מומלץ לשלב טיפול פומי גם במקרים של כאב משמעותי שמוגדר כ-5 ומעלה, בכל מקרה בו לא קיימת התווית נגד לשתייה - ערפול הכרה, פציעה חודרת לגו ופציעה לפנים או לצוואר המגבילה את יכולת הבליעה.

5.  מטפל בכיר יטפל בכאב בינוני ומעלה, שמוגדר כ-5 ומעלה באמצעות קטמין ומורפין תוך ורידי ו\או סוכריות פנטניל ציטרט, על פי קיום גישה ורידית ונוכחות הלם.

6.  שיעור תופעות הלוואי לטיפולים הנ"ל נמוך ואינו צריך למנוע הטיפול והקלת סבלו של הפצוע.

7.  ככלל, כל מתן של קטמין, מורפין או פנטניל מחייב השגחה ופינוי ע"י מטפל בכיר (ולכל הפחות חובש), והשגת גישה ורידית (מבלי לעכב פינוי).

## תרשים מס' 1 -- פרוטוקול טיפול בכאב

\*\*\*\*\*\*תרשים

## פרוטוקול הטיפול בכאב

\*\*\*\*\*\*תרשים

## ביאור הפרוטוקול

### פרק א: רקע כללי

כאב הינו תחושה גופנית ורגשית לא נעימה, הנגרמת כתוצאה מפגיעה ברקמה. פצוע יכול לסבול מכאב עקב פציעתו, או כתוצאה מפרוצדורות רפואיות שמבוצעות כחלק מהטיפול בו, ופעמים רבות יוחמר עקב מצב החרדה בו נמצא הפצוע. באופן גס ניתן לחלק את הכאב לכאב אקוטי וכאב כרוני -- בפרק זה נתייחס לכאב אקוטי בלבד, שלעתים קרובות מלווה פציעה.

הגירוי הכואב, שיכול להיות מכאני, כימי או תרמי, נקלט ע"י רצפטורים ייעודיים הנמצאים ברקמות ומועבר דרך סיבי עצב מסוג Aδאו C אל חוט השדרה, ומשם אל המוח. תוך כדי העברת הגירוי קיימים מנגנונים שונים שיכולים להגביר או להחליש את עוצמת הגירוי שמועבר (Gate Theory). עוצמת תחושת הכאב וסף הכאב משתנים מאדם לאדם, וגם מושפעים מגורמים נוספים, המביאים למודולציה של הולכת הכאב ע"י בקרה ממרכזים מוחיים גבוהים יותר, ביניהם:

1.  *רגשי (Affective):* רגש ומצב רוח ממלאים תפקיד חשוב בתחושת הכאב. כך פחד וחרדה מגבירים את תחושת הכאב, ואילו העדרם מפחית מעוצמת הכאב.

2.  *קוגניטיבי (Cognitive):* הבנת הגורם לכאב ומשמעותו משפיעה על תחושת הכאב הסובייקטיבית של הפצוע, וגורמת לירידה ברמת החרדה ולעליית סף הכאב שלו. כלומר, להבנתו של הפצוע את פציעתו ואת תוכנית הטיפול בו יש משקל בהפחתת עוצמת הכאב שלו.

3.  *קשב (Attention):* קשב שמופנה לתחושת הכאב לרוב יגביר את עוצמת הכאב, לעומת הסחת הדעת שיכולה להקל את עוצמת הכאב של הנפגע. במקביל, יכולתו של הנפגע להתרכז במשימה אחרת ולהמשיך לתפקד יורדת משמעותית במקרים בהם הוא סובל מכאב.

טיפול הולם בכאב מונע סבל ומוריד את רמות הפחד והחרדה, והוא חלק מסטנדרט טיפול בסיסי בעולם המערבי. יתרה מכך, לטיפול בכאב ישנם מספר יתרונות בולטים בשטח: למשל, פצוע הסובל מכאב יכול להיות במצב של אי-שקט משמעותי שיקשה מאוד על טיפול יעיל בו וכן יפגע בכשירות המבצעית של המסגרת. דוגמא נוספת היא העובדה שכאב פוגע ביעילות הנשימה (במיוחד בפגיעות חזה) ועלול להרע את תפקודו הנשימתי של הפצוע ולהחמיר את ההיפוקסיה ממנה הוא סובל. כמו-כן, במחקרים אחרונים הודגם קשר בין מתן טיפול אנלגטי בשטח, לבין ירידה בשכיחות התפתחות PTSD בקרב הפצועים.

במקרים רבים, מטפלים בשטח נמנעים מטיפול בכאב או מבצעים תת טיפול בכאב בשל מגוון חששות, כגון הפחד מתופעות לוואי של הטיפול (דיכוי נשימה, השפעות המודינאמיות לא רצויות ועוד), חשש למיסוך סימנים וסימפטומים של החמרה בפגיעה, ופחד מהתמכרות לתרופות נרקוטיות. חששות אלו *אינם מבוססים מחקרית,* וההפך הוא הנכון: מחקרים הדגימו כי טיפול אנלגטי נכון בסמוך למועד הפציעה הנו בטוח, מביא *להפחתת הס*יבוכים וההשפעות השליליות של הכאב ואינו מביא להתמכרות לחומרים נרקוטיים.

חשוב לזכור שתיעוד של הטיפול נוגד הכאבים חיוני לצורך העברת מידע בין המטפלים, ומונע טעויות בקבלת החלטות רפואיות.

### פרק ב': הערכת רמת הכאב

כאשר ניגשים להערכת רמת הכאב של הפצוע, ניתן לחלק את הערכת רמת הכאב להתרשמות סובייקטיבית על ידי המטופל ולהתרשמות אובייקטיבית של המטפל.

1.  **התרשמות סובייקטיבית:** ניתן לנסות ולכמת את רמת הכאב הסובייקטיבית ממנה סובל הפצוע על ידי שימוש בסרגל ה-VAS (Visual Analog Scale) או ה-NRS (Numeric Rating Scale). נבקש מהפצוע לדרג את עוצמת הכאבים שלו מ-0 עד 10, כאשר 0 משמעו שאין כאבים כלל, ו-10 מסמל כאב עז ובלתי נסבל. ערכים בין 4-6 מייצגים כאב בינוני (moderate), וערך של 7 ומעלה מסמן על כאב בעוצמה קשה (severe). מצופה כי חובשים יבצעו הערכה פשוטה יותר של מידת הכאב באמצעות שתי שאלות: "האם כואב לך?" ו"האם הכאב נסבל"? באופן גס, מקובל להתייחס לכאב "בלתי נסבל" כשווה ערך ל-5 ומעלה בסרגל הכאב, וערך זה ישמש אותם בהחלטה על הצורך במתן טיפול אנלגטי באמצעות אקטיק.

2.  **התרשמות אובייקטיבית:** במקרים בהם קיים קושי בתקשורת עם הפצוע (ממגוון סיבות), ישנה אפשרות להעריך את מצבו של הפצוע ואת רמת הכאב שלו על סמך סימנים קליניים כגון אי-שקט, טכיקרדיה, טכיפנאה ועוד. חשוב לזכור כי לאי-שקט/טכיקרדיה /טכיפנאה קיימת אבחנה מבדלת רחבה שכוללת היפוקסיה, הלם וכו'. על כן, הטיפול בכאב יבוא לאחר איתור וטיפול בבעיות נוספות מהן סובל הפצוע. הערכה והחלטה כזו תתבצע ע"י מטפל בכיר בלבד.

מכאן, בהערכת רמת הכאב של הפצוע יש להתבסס על דיווח סובייקטיבי של הפצוע וגם על התרשמות האובייקטיבית של המטפל, ולהפעיל שיקול קליני לגבי הטיפול לו זקוק הפצוע. ככלל, בשטח נמנע ממתן טיפול בכאב לפצועים מחוסרי הכרה, למעט פצועים מונשמים עם נתיב אוויר דפנטיבי.

### פרק ג': החלטה על סוג הטיפול

1.  הטיפול בכאב יתבצע בשלב סקר ההחייאה, בהמתנה לפינוי או במהלכו, לאחר שניתן מענה למצבים מסכני חיים ובעיקרם עצירת דימומים, טיפול בנתיב אוויר חסום, פגיעות חזה וביצוע RDCR.

2.  ההחלטה על הצורך וסוג הטיפול אשר ינתן לפצוע מתבצעת על סמך מענה לשתי שאלות המפתח (ראה תרשים מס' 1):

    1.  *מה מידת הכאב?* כאב קל יטופל פומית בלבד בעוד כאב בינוני ומעלה ( 5 ומעלה) יטופל ע"י קטמין, מורפין או פנטניל.

    2.  *האם קיים צורך בהתקנת גישה ורידית או האם כבר קיימת?*

        1.  פצועים אשר יזדקקו לפתיחת וריד לצורך מתן נוזלים/ הקסאקפרון/ פלסמה וכו' ( כחלק למשל מ (Damage Control Resuscitation, יטופלו *בקטמין IV ובמידת הצורך גם במורפיןIV*.
        2.  פצועים אשר עבורם אין התוויה לפתיחת וריד ( לדוג' פציעות אורטופדיות אשר אינן מחייבות כעת טיפול תוך ורידי) או פצועים בהם המטפל נכשל בהשגת גישה ורידית ( עקב היעדר גפה לדוג' או כוויות נרחבות בגפיים)- יטופלו בסוכרית הפנטניל, אקטיק, כתרופת הבחירה. במידה ויש צורך בקו טיפולי נוסף, יש להשיג גישה ורידית.

3.  *כאב קל:* בהעדר התוויות נגד לטיפול פומי, יש להעדיף טיפול באקמול 1000 מ"ג או באופטלגין 1000 מ"ג, ולחזור על הטיפול מדי 6 שעות בהתאם לצורך. לפני מתן הטיפול הפומי, יש לשאול על אלרגיות ידועות לתרופות, בדגש על אופטלגין. רצוי לשלב טיפול פומי גם במקרים בהם נעשה שימוש בטיפול נוסף על מנת להשיג אפקט אנלגטי סינרגיסטי. יש לתת טיפול בתרופה פומית אחת, ובמידה ואין שיפור לאחר 15 דקות לתת תרופה פומית נוספת.

    1.  *אקמול (Acetaminophen):* מנגנון הפעילות המדויק של אקמול לשיכוך כאב אינו מובן לגמרי אך משערים כי הוא פועל ע"י עיכוב יצירת פרוסטגלנדינים באמצעות אינהיביציה של אנזים ה COX (במחקרים אחרונים מדברים על ספציפיות ל COX3). התרופה מיועדת לטיפול בכאב בעוצמה של קל-בינוני, במינון של 1000 מ"ג אחת ל-6 שעות (לפי הצורך). האקמול נספג במעי הדק בזמינות של 70-90%, מתחיל לפעול תוך כעשר דקות ועובר מטבוליזם כבדי. זמן מחצית החיים שלו הוא כארבע שעות (אין לבלבל עם משך ההשפעה). התרופה מנופקת בכדורים של 500 מ"ג. אין לעבור מינון של 4000 מ"ג תוך 24 שעות, מחשש לפגיעה כבדית.
    2.  *אופטלגין (Dipyrone):* תרופה השייכת לקבוצת NSAIDs, פועלת ע"י עיכוב יצירת פרוסטגלנדינים דרך עיכוב האנזים cyclooxygenase. הטיפול עבור כאב קל הוא במינון של 500-1000 מ"ג אחת ל-6 שעות. התרופה מנופקת בכדורים במינון 500 מ"ג, או בנוזל בריכוז של 500 מ"ג/25 טיפות (1 מ"ל). אין לעבור מנה יומית של 4000 מ"ג.

תופעת הלוואי המסוכנת ביותר (אשר בגינה נאסרה התרופה לשימוש בחלק ממדינות העולם) הינה אגרנולוציטוזיס. המדובר בתופעת לוואי נדירה ביותר אשר שכיחותה היא 5/1,000,000 ובמרבית המקרים מתפתחת רק לאחר טיפול ממושך ורצוף של מעל למס' שבועות.

4.  **כאב בינוני ומעלה (5 ומעלה)**

-   כאמור, פצוע המדווח על רמת כאב של 5 ומעלה יטופל, בנוסף לטיפול הפומי, גם בתכשירים פוטנטיים יותר, אם באמצעות פנטניל ציטרט (Transmucosal) או באמצעות קטמין ו\או מורפין תוך ורידי.

-   במסלול הטיפול התוך-ורידי נתחיל ממנה בודדת של קטמין 25 מ"ג. במידה ואין הקלה תוך 5 דקות נעבור לטיפול במורפין במנות חוזרות כל 15 דקות במידה ואין שיפור בכאב. אורך המרווח נובע מהזמן שלוקח לתחילת ההשפעה של המורפין, ומתן במרווחים קצרים יותר (טרם הופעת התגובה) עלול לגרום למינון יתר.

-   ניתן לעבור ממסלול האקטיק למסלול התוך ורידי -- במקרה כזה יש להוציא את הסוכריה מהפה ולהתחיל מהמשבצת של מתן קטמין.

-   יש לשלב טיפול פומי (אקמול\אופטלגין) יחד עם נרקוטיקה בכל פצוע עם כאב משמעותי כל עוד אין התווית נגד לשתיה - ערפול הכרה, פציעה חודרת לגו ופציעה לפנים או לצוואר המגבילה את יכולת הבליעה.

    1.  **קטמין (Ketamine Hydrochloride)**

        קטמין הנו חומר בעל תכונות היפנוטיות ואנלגטיות (לא גורם לשיתוק שרירים) .קטמין נקשר לרצפטור לגלוטמט (NMDA) ופועל כאנטגוניסט. בנוסף, לקטמין יש פעילות של הקטנת שחרור פרה-סינאפטי של גלוטמט, וכן השפעה אנטגוניסטית על רצפטורים ניקוטיניים לאצטיל כולין והשפעה אגוניסטית על רצפטורים אופייאטיים מטיפוס µ.

        הטיפול בקטמין לצורך שיכוך כאב יתבצע כקו ראשון לטיפול תוך ורידי השילוב עם מורפין / פנטניל משיג אפקט סינרגיסטי בשיכוך הכאב - שילוב בין שתי התרופות גורם לשיכוך כאבים יעיל יותר עם מינון נמוך יותר של מורפין, כך שנתחיל את הטיפול בקטמין ונעשה טיטרציה למול חומרת הכאב ע"י שימוש במורפין.

        במינונים גבוהים של מעל 0.5-1 מ"ג/ק"ג IV קטמין משמש לצורך הרדמה, ואילו **מינונים נמוכים יותר של 0.2-0.5 מ"ג/ק"ג משמשים לשיכוך כאבים (אנלגזיה)**. הנחיות איגוד המרדימים האמריקאי ממליצות על הגבלת המינון האנלגטי ל- 0.35 מ"ג לק"ג. אין תועלת משמעותית מבחינת שיכוך כאבים מעל מינונים אלו, בעוד הסיכון לתופעות לוואי, בעיקר פסיכומימטיות. לכן, ככלל, באינדיקציה של טיפול בכאב קטמין IV ינתן **בבולוס של 25 מ"ג.** במידה והפינוי הוא ממושך, ניתן לחזור על מינון קטמין **כל 45 דקות** כמנת אחזקה. ניתן כמובן במקביל להמשיך ולטפל גם במורפין. בילדים, מינון הקטאמין לשיכוך כאב יחושב לפי 0.3 מ"ג/ק"ג.

        אופן ההכנה: מרבית אמפולות הקטמין מכילות 500 מ"ג ב 10 מ"ל. על מנת לתת בולוס של 25 מ"ג קטמין יש לשאוב 0.5 מ"ל למזרק 3 מ"ל, לתת את התרופה לוריד ולשטוף בעזרת 10 מ"ל של סליין, במידה והפצוע לא מקבל נוזלים כלשהם דרך הוריד.

        היתרון העיקרי של שימוש בקטמין בפצועי טראומה טמון בהיותו חומר בעל תכונות סימפטומימטיות, שלרוב אינו גורם לירידה בל"ד, בעיקר במינונים המשמשים לטיפול בכאב (זאת בניגוד לרוב תרופות הכאב האחרות). על כן יש לו יתרון במיוחד בפצועים הסובלים מהלם.

        בעבר היה קיים חשש ממתן קטמין לפצועי ראש, עקב אפקט של עלייה ב- ICP. עם זאת, בעבודות אחרונות הודגם כי לקטמין השפעה זניחה על האוטו-רגולציה של זרימת הדם במוח, ויש אף מחקרים שהדגימו יתרון של שימוש בקטמין דווקא בפצועי ראש. על כן אפשר לתת את הטיפול בבטחה לפצוע ראש הזקוקים לשיכוך כאב. יתרון חשוב נוסף בקטמין בשימוש במתאר הטרום בית חולים הינו שהוא מאפשר לפצועים לשמור באופן יחסי על הרפלקסים הפרינגיאלים שלהם וכך לשמור על נתיב האוויר שלהם (אפילו כשמצויים בדיסוציאציה מלאה), אם כי לא ניתן להסתמך על כך באופן מלא ויש להשגיח על נתיב האוויר של הפצוע באופן רציף.

        תופעות לוואי אפשריות: טכיקרדיה הינה תופעת לוואי שכיחה של מתן קטמין. עם השימוש בקטמין לצורך הרדמה ייתכנו תופעות נוירולוגיות שונות, כגון אי-שקט, והזיות. תופעות אלו מופיעות לרוב בשלבי היציאה מההרדמה (Emergence from anesthesia) ושכיחותן יורדת משמעותית ככל שיורדים במינון קטמין. במינונים שניתנים לצורך טיפול בכאב תופעות לוואי הנ"ל -- *נדירות ביותר* בנוסף, קטמין (לרוב במינונים הרדמתיים) עלול לגרום לריור והפרשות, אשר הצטברות שלהן עלולה להביא לגירוי הלרינקס ולרינגוספאזם. במידה ומופיע ריור משמעותי ניתן להפחיתו באמצעות שאיבת הפרשות ובשימוש במנת אטרופין- 0.5 מ"גIV .

    2.  **מורפין (Morphine Sulphate)**

        תרופה מקבוצת האופיאטים, שפועלת לשיכוך כאב ע"י קישור לרצפטורים מסוג Mu במערכת העצבים המרכזית. מדובר בתרופה נפוצה, שנמצאת בשימוש בשדה הקרב מעל ל100 שנים. התרופה קיימת בצה"ל בצורת אמפולות של 10 מ"ג/1 מ"ל או בצורת מזרק אוטומטי למתן תוך שרירי.

        מתן מורפין IV יתבצע במנות של 5 מ"ג (בילדים במנות של 0.05 מ"ג/ק"ג). את האמפולה יש למהול עם 9 מ"ל נוזלים (לקבלת ריכוז של 1 מ"ג/מ"ל). בהיעדר גישה ורידית ומאחר ואקטיק איננו אופציה בילדים, ניתן באוכלוסייה זו לתת מורפין IM במינון 0.1 מ"ג/ק"ג, ללא מינון חוזר.

        הערכה חוזרת של הכאב תתבצע לאחר 15 דקות, ולאחריה במידה והפצוע עדיין כאוב ינתנו מנות חוזרות של 5 מ"ג.

        איגרת זו נכתבת בתחילתו של מהלך להחלפת מזרקי המורפין האוטומטיים שברשות החובשים בסוכריות פנטניל. עד תום ההחלפה מאושר השימוש במזרקי מורפין אוטומטיים, בתנאים הבאים:

        -   טיפול ע"י חובש בלבד.

        -   אין בנמצא סוכריות אקטיק.

        -   הפצוע ללא סימני הלם.

        -   מזרק שני יינתן רק בהתקיים כל הנ"ל, במידה והפצוע עדיין כאוב ברמה של 5 ומעלה, וחלפו לפחות 30 דקות מהמזרק הראשון. לא יינתן טיפול ביותר מ-2 מזרקים.

        בפצוע כאוב הסובל מהלם משמעותי המתבטא בל"ד \<90 או דופק \>130 (אותו פצוע הדורש גם טיפול במוצרי דם) יש לשקול היטב את הצורך במתן מורפין, ובמידת הצורך לתת טיפול במנות מופחתות של 2 מ"ג למנה (בילדים מנות של 0.02 מ"ג/ק"ג).

        תופעות לוואי אפשריות כוללות: ישנוניות, בחילות והקאות, היצרות אישונים (miosis), ירידה בלחץ הדם ודיכוי נשימתי. עם זאת, חשוב לציין כי ככלל, בנפגע שסובל מכאב משמעותי, טיפול במורפין במינונים המומלצים שומר על יציבות המודינמית ואינו גורם לדיכוי נשימתי משמעותי. כמו-כן, בניגוד לדעה הרווחת, אין מניעה למתן מורפין בפצוע שסובל מחבלת ראש ושמתלונן על כאב משמעותי. במידה ומתן התרופה לא מתבצע במקביל למתן נוזלים יש לשטוף את התרופה ב 20 מ"ל לפחות על מנת לקבל את מלוא האפקט הטיפולי ולהימנע מflushing ( אודם מקומי) של הגפה ( במנגנון של שחרור היסטמין מהתאים).

        בבחילה המופיעה בעקבות טיפול במורפין ניתן לטפל באמצעות (Metoclopramide) 10mg Pramin IV במתן איטי (מהילה ל-10 מ"ל, מתן על פני 5 דקות) על מנת לצמצם את הסיכון לת"ל נוירולוגיות. אין צורך בטיפול פרופילקטי בפראמין לכל פצוע המטופל במורפין.

    3.  **פנטניל ציטרט: Oral Transmucosal Fentanyl Citrate:**

        הינה תרופה נרקוטית מקבוצת האופיאטים, בעלת פוטנטיות של פי 100 ממורפין אך עם פחות תופעות לוואי. פועלת כאגוניסט של רצפטורי µ, נמצאת בשימוש פרנטרלי משנות השישים, לאור יתרונה כחוצה במהירות את ה-BBB ובכך מאפשרת הקלה מהירה של כאב.

        תינתן לפצועים הסובלים מכאב בינוני ומעלה ע"י חובש או מט"ב במידה ואין להם עדיין גישה ורידית.

        השימוש המרכזי בפנטניל טרנסמוקוזטלי (אקטיק- ACTIQ , בשמו המסחרי בארץ) הינו לטיפול בכאב מתפרץ בחולי סרטן אך מחקרים שבדקו הכנסת פנטניל לפרוטוקול האנלגזיה בטראומה בבית חולים ומחוצה להם הראו יעילות גבוהה לצד מיעוט בתופעות לוואי. ACTIQ מגיע בתצורה של "סוכריה על מקל". בהסתמך על נסיון האמריקאים בשימוש בתרופה בעיראק ואפגניסטן הוחלט בחיל הרפואה לרכוש את סוכריות ה ACTIQ במינון אחיד של 800mcg ולהכניסה לשימוש בהתוויה שאינה רשומה בישראל (אנלגטיקה בפצועי טראומה).

        הספיגה הטרנסמוקוזלית מביאה להשפעה אנלגטית מהירה, כאשר החלק של התרופה שנבלע ונספג במערכת העיכול מאפשר הארכת האפקט האנלגטי. המדובר בדרך מתן שאינה פולשנית, עם זמן פעולה מהיר ואפקט אנלגסטי ממושך, ההופך את ה- ACTIQ לאידיאלי בשימוש במתאר קדם בית חולים בדגש על מתאר קרבי.

        *אופן השימוש:* סוכריות האקטיק מגיעות כאשר הן ארוזות בנפרד. על מנת לעשות שימוש בתכשיר יש לגזור באמצעות מספרים/ מלע"כ את הקצה ( היכן שמסומן cut to open) , לפתוח האריזה ולהוציא את הסוכריה. את הסוכריה יש להניח בפה בין פנים הלחי לחניכיים ( על מנת להגביר הספיגה) ולהנחות את הפצוע למצוץ באופן פעיל וכן להניע את התרופה בחלל הפה לאורך הלחי ( בתנועות סיבוביות). יש להנחות הפצוע *שלא לנגוס או ללעוס התרופה.* יש לסיים ולהוציא את התרופה מהפה תוך 15 דקות ולאחר מכן לבצע הערכה מחדש של הכאב.

        פצוע שבהערכה חוזרת (לאחר 15 דקות) עדין סובל מכאב משמעותי (5 ומעלה) יוכל לקבל סוכריה נוספת, בלחי השניה (כאשר את הראשונה יש לזרוק). אין מקום לטיפול ביותר מ-2 סוכריות.

        במצבים בהם הפינוי מתארך או מתעכב, מומלץ להשיג גישה ורידית ולטפל עפ"י הפרוטוקול התוך-ורידי, היינו קטמין ומורפין. \*\*\*\*\*\*\*תרשים \*\*\*\*\*\*\*תרשים

        Adopted from: Actiq prescribing information, FDA website, 2011

        *תופעות לוואי:* במחקר שבדק 7 שנות נסיון בטיפול ב ACTIQ בעיראק ואפגניסטן נמצאה יעילות גבוהה מאוד וירידה משמעותית בכאב כאשר ניתן לפצועים סמוך לנק' הפציעה (רובם פצועי ירי בגפיים) ובמקביל מיעוט תופעות לוואי כאשר המרכזית בהן הייתה בחילה (12%). בנוסף יתכנו: בחילה, גרד, ישנוניות וסחרחורת. במקרה של בחילה משמעותית ניתן להוסיף פרמין IV 10 מ"ג ( או PO ). תופעות לוואי נדירות יותר כוללות דיכוי נשימתי, ירידת ל"ד. תופעות אלו *לא תועדו ולא דווחו* במינונים המדוברים. אין אישור לטפל באקטיק בילדים (מתחת ל-40 ק"ג ע"פ הערכת המטפל), לאור תגובה בלתי צפויה.

    4.  **ניטור**

        התדרדרות נשימתית/ המודינמית סביר יותר שתיגרם כתוצאה מפציעתו העיקרית של הנפגע או פציעה אשר פוספסה במהלך הסבב הראשוני ועל כן ראשית יש לתת על כך את הדעת במקביל להפסקת הטיפול האנלגטי.

        כל פצוע המקבל טיפול לכאב בינוני ומעלה באמצעות נרקוטיקה ( מורפין/ קטמין/ פנטניל) חייב **בניטור של מדדים חיוניים ב**דגש על מצב נשימתי תוך שימוש במד סטורציה ומעקב אחר רציף מצב ההכרה.

    5.  **טיפול בפצועים חסרי הכרה**

        בפצוע חסר הכרה אשר אינו מונשם **אין מקום** לשימוש באנלגטיקה במתאר טרום בי"ח. בפצועים מונשמים אשר פינויים מתעכב יש בהחלט מקום לטיפול בכאב כחלק מהסדציה (ראה פרק "הסקר השניוני).

    6.  **ככלל, מתן של קטמין או אופיאטים מחייב גישה וורידית (מבלי לעכב פינוי) והשגחה ופינוי ע"י מטפל בכיר.**

## סיכום:

טיפול בכאב בטראומה מהווה נדבך משמעותי בטיפול בפצוע ומסייע להפחתת תחלואה ואף תמותה.

בפרק זה הבאנו בפני המטפל כלים אפקטיביים, מתוקפים, פשוטים ויעילים לטיפול בכאב. כל פצוע הסובל מכאב משמעותי (5 ומעלה) יקבל טיפול אנלגטי מתאים אשר יקבע על פי הכשרת המטפל וקיום גישה ורידית, הפצוע ינוטר לכאב ויקבל תוספת והמשך טיפול על פי הצורך. המטפל ינטר את הפצוע במהלך כל הטיפול להתפתחות ת"ל אשר בעיקרן התדרדרות נשימתית/ המודינמית ובמקביל יתעד את הטיפול שניתן ע"ג טופס 101.

## ביבליוגרפיה ומקורות

::: {dir="ltr"}
1.  Morgan's Clinical Anesthesiology, 5th ed., Chapter 18. Pain management.

2.  The Merck Manual for Health Care Professionals, Critical care, Shock and fluid resuscitation.

3.  Cognitive modulation of pain: how do attention and emotion influence pain processing. Villemure C, Bushnell C. Pain 2002 (95): 195-199.

4.  Prehospital Analgesia: Systematic Review of Evidence. J R Army Med Corps 156. CL Park

5.  Acute pain on and off the battlefield: What we do , what we know, and future directions. Kent ML, Upp JJ, Buckenmaier CC Int Anesthesiol Clin Volume 49, 3: 10-32.

6.  Pain management in current combat operations. Black IH, McManus J. Prehosp Emerg Care 2009; 13: 223-227.

7.  Intravenous morphine titration to treat severe pain in the ED. Lvovschi V, Aubrun F et al. Am J Emerg Med 2008, 26: 676-682.

8.  Ketamine: a new look at an old drug. Raeder JC, Stensetfh LB, Curr Opin Anaesthesia 2000, 13:463-468.

9.  Morphine and Ketamine is superior to morphine alone for out-of-the-hospital trauma analgesia: a randomized controlled trial. Jennings PA, Cameron P, Walker T, Jolley D, FitzgeraldM, Masci K. Ann Emerg Med 2012, Jan 11 \[epub ehead of print\].

10. The effect of combined treatment with morphine sulpahte and low-dase ketamine in a prehospital setting. Johansson P, Kongstad P, Jahansson A. Scand J Trauma Resusc Emerg Med 2009 nov 27;17: 61.

11. Prehospital use of Ketamine in battlefield analgesia . Butler Frank, Defense Health board Recommendation for the CoTCCC committee, march 2012.

12. Prehospital analgesia: Systematic Review of Evidene. Moore RA. Journal of Royal Army Medical Corps. Dec 2010

13. Safety and efficacy of Oral Transmucosal Fentanyl Citrate for prehospital pain control on the battelfiled. Wedmore I, Kotwal R et al. Journal of Trauma. December 2012.

14. A fentanyl-based pain management protocol provides early analgesia for adulttrauma patients. Curtis KM et al. Journal of trauma. Oct 2007.

15. Management of Pain, Anxiety and Delirium in Injured Warfighters. JTTR Clinical guidelines. Apr 2013

16. Tactical Combat Casualty Care guidelines. September 2012

17. Schwenk ES, Viscusi ER, Buvanendran A, Hurley RW, Wasan AD, Narouze S, et al. Consensus Guidelines on the Use of Intravenous Ketamine Infusions for Acute Pain Management From the American Society of Regional Anesthesia and Pain Medicine, the American Academy of Pain Medicine, and the American Society of Anesthesiologists. Reg Anesth Pain Med. 2018;

18. Laskowski K, Stirling A, McKay WP, Lim HJ. A systematic review of intravenous ketamine for postoperative analgesia. Canadian Journal of Anesthesia. 2011.

19. The Harriet Lane Handbook International Edition: 17th Edition. Robertson J, Shilkofski N.

20. Clinical Anesthesia Procedures of the Massachusetts General Hospital: Ninth Edition, Pino RM et al.
:::
