# טראומה בילדים

## עיקרי העדכונים
06/2022
* כתיבת ההנחיה

## מבוא 

טראומה היא בין גורמי המוות המובילים בילדים בעולם ובישראל.

**הגישה הבסיסית בטיפול בילדים הינה ברובה זהה לגישה המוכרת במבוגרים: עצירת דימומים, ניהול נתיב האוויר, זיהוי וטיפול בבעיות נשימתיות, והחייאה לפי עקרונות ה-Remote Damage Control Resuscitation. ההבדלים בין הטיפול בפצועים מבוגרים לטיפול בילדים – הינם בפרטים הקטנים.**

מטרת פרק זה היא לאגד את ההנחיות והדגשים לטיפול בילדים נפגעי טראומה בדרג השדה.

על אף שטיפול בילדים אינו המיקוד של כוחות הרפואה בצה"ל, לא נדיר שאנו מגיעים אל זירה שבה יש ילדים שנפגעו, הן באירועים בעלי אופי אזרחי והן באירועים בעלי מאפיינים צבאיים, בבט"ש בגזרות השונות ולעיתים אף בזמן לחימה. עם זאת, ניסיונם של מרבית המטפלים בצה"ל בטיפול בילדים ובפרט בילדים נפגעי טראומה- אינו רב. מובן כי למטפל אשר אינו מנוסה בטיפול בילדים ביומיום, הסיטואציה יכולה להיות מאתגרת ומלחיצה. 

הפרק יביא את העקרונות המרכזיים בהתאמת הטיפול לאוכלוסיית הילדים.

עיקרי הדגשים לטיפול בטראומה **בילדים** על פי שלבי סכמת הטיפול האחודה 

************************************************************ תמונה של פרוטוקול
 
## ביאור הפרוטוקול 
 
 נדגיש את החשיבות בשימוש בסרגל ההחייאה (סרגל ברסלאו- Broselow-Luten Tape), הנמצא בערכת צר"פ הילדים בכל שלבי הטיפול. את קצה הסרגל האדום מניחים לצד ראש הילד, ובמשבצת שתהיה ליד עקביו ניתן יהיה לראות מידע שימושי לגבי סימנים חיוניים מותאמים גיל,  מינוני התרופות וגדלי הציוד המתאימים לילד.
 
כמו כן, ניתן להיעזר בהורי הילד לטובת תקשורת, אנמנזה, הרגעה וסיוע בטיפול.

*************************************************************************** תמונה של סרגל ברסלאו 

שימוש בסרגל ברסלאו


### שלב ה-S: סקר ראשוני בילדים

שמירה על בטיחות המטפל והמטופל, התרשמות ממנגנון הפציעה ומפציעות אפשריות ועצירת דימומים פורצים - יעשו כולם בדומה למבוגרים, כאשר קיימת עדיפות לעצירת דימום בלחץ ישיר.

עצירת דימומים בקרב ילדים תתנהל ע"פ רוב בדומה לטכניקות במבוגרים. השימוש ב-CAT נבדק בקרב ילדים החל מגיל 6 ונמצא כיעיל בעצירת דימום באוכלוסייה זו. בילדים קטנים יותר, קיים חשש כי קוטר הגפה עלול להקשות על עצירת דימום באמצעות CAT ועל כן באוכלוסייה זו יש למצות את השימוש באמצעי לחץ ישיר.

#######################################תמונה של קאט

### שלב ה-A: ניהול נתיב אוויר

#### ניהול נתיב אוויר בסיסי והנשמה

ישנה חשיבות עליונה לחימצון הפצוע הפידיאטרי. בילדים, היפוקסיה יכולה להוביל בפני עצמה לברדיקרדיה ולשוק- על כן 
חשוב להבין את מנגנון הפגיעה.

ככלל, ההערכה והטיפול בבעיות נתיב האוויר בילדים יעשו בצורה זהה למבוגרים, בהתאם לעקרונות המפורטים בפרק " נתיב האוויר - הערכה וטיפול" בספר הרפואה המבצעית. 

מעל לכל, במידה ויש בעיה בנתיב האוויר, יש להקפיד לבצע ניסיונות מיטיביים לניהול נתיב האוויר באמצעים הבסיסיים: פתיחת פה, סילוק הפרשות (ידנית או עם סקשן), דחיקת לסת ו/או הרמת סנטר, והקפדה על תנוחה מתאימה. התנוחה המומלצת לפתיחת נתיב אוויר הינה כאשר פתח תעלת השמע באוזן הינו בגובה הסטרנום של המטופל, והפנים מקבילות לשמיים. 

מכיוון שראשם של ילדים גדול יחסית לגופם, לעיתים קרובות יידרש ריפוד דווקא מתחת לשכמות של ילדים קטנים על מנת להשיג תנוחה זו, ולא מתחת לראשם. במקרים בהם ישנו חשד לפגיעת עמ"ש, מומלץ להניח את הריפוד מתחת לכל גופו של הפצוע, ולא רק מתחת לשכמות (למשל שמיכה מקופלת – ראה תמונה).

***************************************************************************************************************** תמונה

יש לספק חמצן במסיכה מתאימה עם שקית העשרה לכל אורך הטיפול בפצוע. במידה והילד מסרב לחבוש את המסיכה, ניתן להניחה בסמוך לאף ולפה על מנת לנסות לחמצן סביבתית.

במידה ולמרות פתיחת נתיב האוויר, סילוק ההפרשות ומתן חמצן במסיכה הילד הפצוע ברדיפנאי, אינו נושם, ו/או אינו מעלה סטורציה, יש לסייע נשימתית עם אמבו המחובר לחמצן ולשקית/צינור העשרה. יש להקפיד על שימוש במסיכה בגודל מתאים לפניו של הילד ובמנתב אוויר פומי מתאים (מזווית הפה ועד תנוך האוזן או עד לזווית הלסת). במידת האפשר, יש להכניס את מנתב האוויר ללא סיבוב, על מנת להימנע מפגיעה ברקמות הרכות.

********************************************************************************* תמונה 
כמו במבוגרים, יש לפעול תחילה באמצעים שמרניים לחמצון הפצוע אך במידה והמאמצים כושלים ( על פי ההתוויות), יש להתקדם להתקנת נתיב אוויר דפיניטיבי
.במידה והוחלט על ביצוע

אינטובציה ראוי כי תבוצע ע"י המטפל המנוסה ביותר בצוות.
כמו כן, בחשד לפגיעה בעמוד שדרה צווארי יש לבצע קיבוע ידני של הראש כמו במבוגרים (לדגשים נוספים ראה "הכנה לפינוי")

### שלב ה-B: פגיעות חזה

כאמור, ישנה חשיבות עליונה לחמצון הפצוע הפידיאטרי, ועל כן יש לספק חמצן לכל נפגע עם חשד לפגיעת חזה או בעיה בחמצון.  

העצמות (ובכללן הצלעות) בילדים גמישות יותר מאשר במבוגרים, ועל כן ניתן לראות פגיעות ריאתיות קשות על אף שאין שברים בצלעות. במידה וישנם שברים כל שהם בצלעות - הדבר צריך להעלות חשד גבוה מאוד לפגיעה באיברים הפנימיים.

במידה ונדרשת הנשמה בילד, יש לבצע בנפח אשר גורם לעליה של בית החזה, ובכך להקפיד שלא להנשים בלחצים ונפחים גבוהים. קצב הנשימה התקין תלוי גיל (ומופיע על גבי סרגל ההחייאה). **בהכללה גסה, בתינוק קצב נשימה של עד 60 יכול להיות תקין, בפעוטות עד 40, בילדי בי"ס עד 3פ0** ואילו לילדים גדולים יותר ניתן לתהייחס כמבוגרים. 

### שלב ה-C: הערכת הלם בילדים 
יכולתם של ילדים לפצות על איבוד דם עלולה למסך איבוד דם משמעותי. זאת בנוסף לשונות הגבוהה בערכי הנורמה של הדופק והל"ד בילדים, העלולה להקשות על זיהויו של ההלם בילדים על ידי המטפל שאינו מיומן בכך. בהערכה גסה (הערכים המדויקים מופיעים על גבי סרגל ההחייאה), טכיקרדיה בתינוק תוגדר כדופק מעל 160, בפעוט מעל 140, בילדי בי"ס מעל 120, ובילדים גדולים יותר מעל 100 - כמו במבוגרים. מדידת דופק בתינוקות (עד גיל שנה) תעשה בדופק ברכיאלי ולא רדיאלית. עם זאת יש לזכור  כי טכיקרדיה יכולה להיות ביטוי של כאב או חרדה. מכיוון וכך, חשוב לשים לב לסימנים העקיפים להלם, כגון: מנגנון הפציעה, מצב ההכרה של המטופל, מצבו הנשימתי, צבע העור, טמפרטורת העור, מילוי קפילרי, ודפקים פריפריים חלשים.

*********************************************************************************תמונה

לחץ הדם הסיסטולי התקין המינימלי לילד יחושב לפי הנוסחה "**גיל בשנים כפול 2 ועוד 70**" - אולם כאמור ל"ד צפוי לרדת רק לאחר איבוד דם מסיבי של כ45% מנפח הדם של הילד. כמו במבוגרים, סימן מוקדם יותר של הלם יכול להיות Pulse Pressure צר (פחות מ 30 ממ"כ). יש להקפיד למדוד ל"ד עם מנג'טה המתאימה לגודלו של הפצוע.

### שלב ה-D

בעת התרשמות ממנגנון הפציעה יש לזכור שבשל מבנה גופם של הילדים וראשם הגדול באופן יחסי, פגיעות ראש נפוצות יותר מאשר במבוגרים. יתר על כן, קיים קושי בהערכת ההכרה בקרב ילדים בשל היעדר תקשורת או ביטוי שונה של הכרה ירודה. על כן, יש לשאוף להעריך את מצב הכרה על ידי מדדים אובייקטיבים ככל הניתן, ולהתחשב גם במנגנון הפגיעה:

**תגובה עינית** : מדד אובייקטיבי אשר יכיל כחלק מההערכה בכל הגילאים, בין אם ספונטנית, לכאב או לקול.

**תגובה ורבלית** : עד לגיל שנה, הילד צפוי להגיב בבכי וקולות ללא מילים ועל כן זו תגובה תקינה בגילאים אלו. החל מגיל שנה, הילד צפוי להתבטא במילים במצב הכרה תקין. 

**תגובה מוטורית** :  עד לגיל חצי שנה, הטונוס הנורמלי הוא פלקציה של הגפיים, והחל מגיל חצי שנה, צפוי הילד למקם כאב. החל מגיל שנתיים, ניתן לצפות גם למילוי פקודות בדומה למבוגר.

*נוסיף כי ההתרשמות של ההורה ממצב ההכרה עשויה לסייע רבות להבנת מצב הילד בהשוואה ל-Baseline. 

### שלב ה-E: חום גוף והכנה לפינוי

#### שמירה על חום הגוך 
 חשוב ! יש לזכור שלאור שטח גופם הגדול יחסית של ילדים (והנפח הקטן) - הם מאבדים בקלות רבה חום אל הסביבה, ועל כן יש להקפיד הקפדה יתרה על כיסוי, חימום ושמירה על חום גופו של הילד בשוק.
 
 #### הכנות לפינוי וקיבוע עמוד שדרה:
 
 כמו במבוגרים, אנחנו לא עושים שימוש בקרש גב במתאר טרום בית חולים. 
 
באם קיימת התוויה לשמירה על עמוד שדרה יש לקבע לאלונקה ולהתאים צווארון בגודל מתאים ( בצר"פ הילדים ניתן למצוא צווארון פילדלפיה לילדים). כמובן שיש להפעיל שיקול דעת בילדים קטנים יותר אשר אינם משתפים פעולה ולהעדיף את נוחות הילד ( אפילו בידי ההורה) על פני ניסיונות קיבוע "בכוח". 

### סקר החייאה

#### נתיב אוויר מתקדם

בפעוטות ניתן להשתמש בלהב מקינטוש 2 הנמצא בערכת הצר"פ לילדים. בילדים מבוגרים יותר (גיל 10 שנים ומעלה) בלהב מקינטוש 3. 

במקרים נדירים של אינטובציה לתינוק, ניתן להשתמש בלהב מילר הנמצא בערכת הצר"פ לילדים, בהתאם לגודל הנפגע (להב מילר 0 ליילוד, ולהב מילר 1 לתינוק). נדגיש שבעת ביצוע לרינגוסקופיה עם להב מילר - מרימים את האפיגלוטיס עצמו עם קצה להב הלרינגוסקופ, במקום להכניסו לוולקולה.

************************************************************************ תמונות 

 גודל הטובוס יקבע בעדיפות ע"י שימוש בסרגל ההחייאה (ראה לעיל). במידה ואין אפשרות להשתמש בסרגל, ניתן להעריך את גודל הטובוס לפי השוואתו לרוחב הזרת **שלהמטופל**, או לפי הנוסחה "**גיל חלקי 4, ועוד 4**".
 
 מינוני התרופות לאינטובציה יקבעו גם הם בעדיפות ע"י שימוש בסרגל ההחייאה. במידה ואינו זמין, יש לחשב את המינון בהתאם למשקל המוערך, בדומה למינונים במבוגר **(קטמין 2-3 מ"ג לק"ג IV, דורמיקום 0.05-0.1 מ"ג לק"ג IV עד מינון מקסימלי של 5 מ"ג)**.
 
קטמין עלול לעיתים לגרום להפרשות מרובות בנתיב האוויר, לכן להיות תמיד מוכן עם מכשיר הסקשן הקיים לרשותך לטיפול בהפרשות. 

לעיתים נדירות יהיה צורך במתן אטרופין במינון 20 מיקרוגרם לקילוגרם לסייע בהפסקת הריור. 

יש להקפיד להכניס את הטובוס כ2-3 ס"מ מעבר למיתרי הקול - לא פחות ולא יותר. ניתן להעריך את עומק הטובוס הצפוי לפי הנוסחה "**גודל טובוס כפול 3**", אך יש לוודא את המיקום ע"י ההסתכלות הישירה (מעבר מיתרי הקול והמצאות הבלונית מתחת למיתרים), הקפנוגרפיה וההאזנה ולא להסתמך רק על הנוסחה. קיבוע יעיל של הטובוס הינו חשוב! בטובוס קטן (<6) מקובל לעשות זאת עם מיקרופור ולא ע"י שרוך.  במהלך הטיפול והפינוי יש להעריך מחדש את מיקום הטובוס לעיתים קרובות, מכיוון שהטרכיאה בילדים קצרה, וכל תנועה קלה של ראש המטופל או של הטובוס עלולה לגרום לאקסטובציה מחד או לכניסת הטובוס לסימפון אחד מאידך.

#### נתיב אוויר כירורגי

מומלץ לא לבצע קוניוטומיה בילדים. במקרה הנדיר שבו הפעולה נדרשת הרי שבילדים גדולים, בהם ניתן למשש היטב את הסחוסים ואת ממברנה הקריקותירודאלית (לרוב מגיל 12, אך תלוי בגודל המטופל), ניתן לבצע קוניוטומיה כמו במבוגר.

בילדים מתחת גיל 12 אין לבצע קוניוטומיה. בילדים אלו, יש למצות את האפשרויות האחרות לחמצון ואוורור המטופל (אמבו, אינטובציה). במקרים נדירים ביותר בהם אין כל אפשרות אחרת, ניתן לנסות ולחמצן את הפצוע דרך וונפלון (Jet Ventilation):
1. החדרת הוונפלון:

יש לחבר וונפלון 14-18G למזרק 10 מ"ל (אליו שאבנו כ2-3 מ"ל של סיילין טרם הפעולה). יש להחדיר את הוונפלון לממברנה הקריקותירואידאלית בזהירות כשהוא מכוון בזווית של כ30-45° כלפי הרגליים, תוך כדי ביצוע שאיבה במזרק עד לכניסת בועות אוויר (המצביעות על כניסה לקנה). לאחר הופעת אוויר יש להפסיק את החדרת הוונפלון כולו ולהחדיר את הפוליתילן בלבד הלאה אל תוך הקנה.

2. חיבור לאמבו:

יש לנתק את מזרק ה10מ"ל ששימש להחדרה, ולחבר מזרק 3 מ"ל (הנמצא לשם כך בערכת הצר"פ לילדים) שהוצאה ממנו הבוכנה. למזרק ה3 מ"ל יתחבר מתאם של טובוס 7.5, והוא כמובן יחובר לאמבו.

**כאמור, פעולה זו תבוצע רק כפעולת "אין ברירה" במקרים בהם אין כל אפשרות אחרת לחמצן את הנפגע.

**הנשמה** תתבצע עד לעליית בית חזה. יש להקפיד לאפשר מספיק זמן ליציאת האוויר לאחר כל הנשמה (האקספריום עלול לקחת 4 שניות ויותר בשל קוטרו הקטן של הוונפלון).

################################################תמונות 

#### ניקוז חזה

כמו במבוגרים, ניקוז החזה יבוצע בשטח רק במקרים החשודים לחזה אוויר בלחץ (ראה פרק "הגישה לפגיעות חזה בשדה" בספר הרפואה המבצעית).

בילדים מחט ניקוז רגילה עלולה לפגוע באיברים חיוניים. כיוון שכך, יש לבצע את ההחדרה מעט אנטריורית לקו מיד-אקסילרי בין צלעות  4-5 ( באותו המיקום המיועד להחדרת נקז חזה), ולא בנקודת ההכנסה הקידמית (מידקלביקולרית). בנוסף, אין להשתמש בTPAK (שהינו ארוך מידי) אלא בוונפלון: בפעוטות וילדים קטנים מומלץ להשתמש בוונפלון 20G, ובילדים מעל גיל 10 בוונפלון 18G.

במקרים נדירים בהם נדרש להכניס בשטח נקז חזה כירורגי לילד, ההכנסה (אשר תבוצע במהלך סקר ההחייאה) תבוצע בטכניקה דומה לזו שבמבוגר. בערכת הצר"פ לילדים בצה"ל קיימים 3 גדלים של נקזים פדיאטרים (תינוק, ילדים, נוער). בערכות הקיימות כיום נקזים אלו אינם מתחברים ישירות לשסתום ההימליך הצה"לי, ויש להיעזר במתאם של טובוס 7 על מנת לאפשר חיבור לשסתום. 

#####################################################תמונה

#### החזר נפח (מוצרי דם או קריסטלואידים)
**יבוצע כמו במבוגרים**- רק בשוק עמוק לפי אותן התוויות במבוגרים, דהינו: ל"ד נמוך במפורש לגילו (כאמור "גיל כפול 2 ועוד 70"), שינוי בולט במצב ההכרה המיוחס להלם או היעדר דופק פריפרי (מיקום בהתאם לגיל- ברכיאלי/רדיאלי). 

ניתן לשקול מתן נפח גם במקרים של טכיקרדיה ברורה (כמופיע בסרגל ההחיאה וטבלת מדדים, נספח ג') – בתנאי שהיא מלווה בסימני הלם ברורים נוספים.

מינון מוצרי דם/קריסטלואידים הינו **20 מ"ל לק"ג**. על מנת לאפשר מתן מהיר במינון הנכון, מומלץ (ובמתן תוך גרמי - חובה) להשתמש בברז תלת כיווני מערכת הילדים ובמזרק 10 מ"ל, לשאוב את הדם/פלסמה מהשקית אל המזרק ואז להזריק את הנוזל לוריד (וחוזר חלילה עד להגעה לנפח הרצוי).

במתארי פינוי ממושך או עיכוב פינוי ניתן להיעזר בתפוקת השתן למעקב אחר מצבו הוולמי של הפצוע (תפוקה רצויה של כ1 מ"ל לק"ג לשעה).

בדומה למבוגרים, **הקסקפרון** לווריד ינתן בילדים (בסקר ההחיאה) בכל פגיעה חודרת לגו (או לאזורי מעבר) ללא קשר למדדים, ובכל פצוע בשוק עמוק על רקע דימום, ללא קשר למקום הפציעה. זאת, בתנאי שלא עברו 3 שעות מהפציעה. 

מינון הקסקפרון בילדים הינו **15 מ"ג לק"ג,** וניתן להעריך את משקל הילד עם סרגל ההחייאה. שיטות נוספות להערת משקל בילדים מובאות בנספח. ככלל אצבע, חצי אמפולה (250 מ"ג) תתאים לילד בן 3-4 (15 ק"ג), ואילו אמפולה אחת (500 מ"ג) מתאימה לילד סביב גיל 10 (30 ק"ג). בילדים מעל גיל 12 ינתן מינון מלא של 1 גר' (2 אמפולות), כמו במבוגרים (ראה טבלת מינונים, נספח ג').  

#### טיפול בכאב 

ניתן לטפל בכאב ע"י אמצעים לא תרופתיים כגון חבישה, קיבוע, הסתרת הפציעה, הרגעה, הסחת דעת. במידה ונדרש טיפול תרופתי, ניתן לטפל בקטמין לוריד במינון של **0.3 מ"ג לק"ג. יש להימנע ממתן של קטמין IM לצורך טיפול בכאב.**

### סקר שניוני 
בפינוי ממושך או במתארי עיכוב פינוי, יש לשקול הכנסת זונדה (דרך הפה) בסקר השניוני לכל ילד מונשם (מבלי לעכב את הפינוי), מכיוון שבילדים הרחבת הקיבה (acute gastric dilation) נפוצה יחסית, ועלולה לגרום לא רק להקאות ואספירציות - אלא גם להפרעות בהנשמה ואף להפרעות המודינמיות (בשל פגיעה בהחזר הוורידי). 

#### אנטיביוטיקה
כפי שמפורט בפרק " הטיפול האנטיביוטי בשדה", אנטיביוטיקה תינתן בשטח במתארי פינוי ממושך בלבד (מעל שעה), לפצועים עם פגיעה חודרת.

פצוע עם פגיעה חודרת יטופל ב Ceftriaxone במינון של 100 מ"ג לק"ג (עד מקסימום של 2 גר' לילד במשקל של 20 ק"ג ומעלה), פעם ביום. במידה וישנה פגיעה חודרת בבטן או בראש, יש להוסיף גם Metroniadazole במינון 10 מ"ג לק"ג (עד מקסימום 500 מ"ג) מדי 8 שעות.

### הורים לילד פצוע 

ההורים או בהעדרם, אדם אחר המוכר לילד יחד עם הנפגע. יש לוודא בתום או במהלך הטיפול כי קיימת תקשורת של הצוות המטפל עם ההורים.

### הפסקת מאמצי החייאה 

טיפול בילד במצב של אובדן סימני חיים עלול להיות חוויה קשה עבור המטפלים, אך במצבים אלו יש לפעול בדומה לכתוב בפרק  "מאמצי החייאה בנפגע טראומה המאבד סימני חיים", עם מספר דיוקים. **סיבות המוות** במתאר טראומה בילדים **אינן שונות במהותן** ולכן, גם במקרים אלו עלינו להעניק את הטיפול עם המירבי אשר יתן לפצוע את הסיכויים לשרוד, בדגש על האבחנות הסבירות במתאר טראומה, ואלו כוללים ניקוז חזה, הנשמה באמבו ומסיכה ומתן נפח.

בשל שוני במבנה בית החזה, יש לבצע ניקור חזה במיקום המקובל באקסילות, בניגוד למבוגרים בהם קיימת אפשרות לנקר גם בקו מיד-קלויקולרי. מעבר לכך, חישוב מתן הנפח צריך להתבצע לפי משקל, כפי שמפורט בהנחיה זו. יש להדגיש כי במידה והילד עונה על הקריטריונים לאי-ביצוע מאמצי החייאה, אין המצב שונה מטיפול במבוגר ואין לבצע הנחיה שלא לפי הנחית סיום מאמצי החייאה.

### לאחר האירוע 
כבכל אירוע, יש לבצע תחקור של האירוע בהשתתפות כלל המטפלים, ולוודא הזנה ודיווח עליו כנדרש. מאחר ואירועים אשר מערבים ילדים אינם מהווים חלק משגרת הטיפול בצה"ל, אלו יכולים להוביל למטען משמעותי יותר בקרב המטפלים, בדגש על הפחות מנוסים. לכן, יש להקפיד לדיין את תחושות הצוות לאחר האירוע, לחזק תחושת מסוגלות ובמידת הצורך לשקול מעורבות של גורמי ברה"ן. 

## סיכום
הטיפול בילדים פצועי טראומה ע"י צוותי הרפואה של צה"ל אינו אירוע שכיח, אך בהחלט אינו נדיר. על הצוותים המטפלים להכיר את עקרונות הטיפול ואת הדגשים בנפגעים אלו, ולזכור שהטיפול הבסיסי מושתת על העקרונות האוניברסליים של טיפול בנפגעי טראומה, בהתאמות קלות.

## נספח א':  תכולת ערכת צר"פ ילדים
ערכת צר"פ; לילדים, דגם 2016

********************************************************************************טבלה 

## נספח ב': הערכת משקל ילדים

ככלל, יש להעדיף הערכה המבוססת על גודלו הפיזי של הילד הספציפי, ועל כן השיטה המועדפת להערכת משקל בילדים בשטח תהיה שימוש בסרגל ההחייאה, הנמצא בערכת צר"פ הילדים. במידה והמטפל מתרשם שניתן לקבל דיווח אמין על משקל הילד מההורים - ניתן להיעזר גם במספר זה.

רק בהיעדר אפשרויות אלו, יש לבצע הערכה המבוססת גיל, כמפורט להלן. במקרים אלו, מומלץ לרשום את המשקל המשוער במקום בולט על מנת לצמצם את הצורך בחישובים חוזרים.

שיטות להערכת משקל בילדים (לפי סדק עדיפויות): 
1. שימוש בסרגל החייאה
2. דיווח של ההורים 
3. הערכה לפי גיל 

***********************************************************טבלה

4. "שיטת האצבעות":

על יד אחת נספור מספרים אי זוגיים החל מהאגודל (1, 3, 5, 7, 9). מספר זה מייצג את גילו של הילד. על היד השניה נספור מהאגודל החל מ10, בקפיצות של 5 (10, 15, 20, 25, 30). הצמדת אצבע הגיל לאצבע המקבילה לה ביד השניה תיתן הערכה גסה של משקל הילד.

**********************************************תמונה 

מקור: Young et al, 2015

## נספח ג': מינונים ומדדים על פי גיל
ככלל, יש להיעזר בסרגל ההחייאה לקביעת המדדים הצפויים, המינונים וגדלי הציוד הנדרשים.

במידה והנתון הדרוש לא מפורט בסרגל, או במידה והוא אינו זמין - יש להעריך קודם כל את משקל הפצוע לפי אחת השיטות המפורטות בנספח הקודם, ולאחר מכן לחשב את המינון/גודל לפי המפורט בנספח זה.

******************************************************* תמונה 

## נספח ד': דגשים לציוד ותרופות לפי גיל

*************************************************************************טבלה 

*****************************************************************************תמונה 

