# טיפול מתמשך בפצוע

## עיקרי העדכונים:
15/07/2021:
- כתיבת הפרק

28/01/22:
- עריכת הפרק והכנה להפצה

## הקדמה ורקע
**מקומו של הפצוע הוא בבית החולים,** וכלל מאמצי ההחייאה המבוצעים בשטח מטרתם לשפר את סיכוייו של הפצוע לשרוד את הגעתו לבית החולים. מאידך, הניסיון ההיסטורי מוכיח כי מנקודת מבט מבצעית לא תמיד ניתן לפנות את הפצוע באופן מיידי לבית החולים, מה שהוביל ליצירת דרגי ביניים, כדוגמת פלה"ק\יר"א ועוד.

עם זאת, ייתכן מצב חריג של כוח, שנמצא בנתק מבצעי, ואין לו את היכולת לפנות את הפצוע לדרגים אלו, או שהם אינם זמינים לו. כך ייתכן מצב של מטפל בכיר המטפל בפצוע דחוף, ללא יכולת פינוי, במשך שעות רבות. מדובר במצב בלתי-רצוי, אולם לעתים בלתי נמנע. מטרת איגרת זו לתת כלים לאותו מטפל לעשות את המיטב במצב בלתי-מיטבי זה, ובהינתן ניסיון מועט יחסית בטיפול בפצועים מורכבים ו\או טיפול נמרץ. במצבים אלו יש יתרון עבור רופאים, שהכשרתם כוללת גם עבודה במחלקות אשפוז, ובשאיפה גם חשיפה מסוימת לעבודת טיפול נמרץ.

**פרק זה נוצר על מנת לתת כלים שימושיים למטפל הבכיר בחוליה הרפואית או בתאג"ד כאשר עליו להעניק טיפול למשך פרק זמן העולה על כמה שעות בודדות (ובהסתמך על האמצעים הקיימים בדרג הגדודי)**. 

**הפרקטיקה המובאת באיגרת נחותה באופן חד משמעי לעומת האלטרנטיבה של פינוי הפצוע לבית החולים או לדרג בו קיימות יכולות כירורגיה ו\או טיפול נמרץ, והיא מהווה אילוץ למצב שנוצר בשטח** 
.

ההנחיות המופיעות בפרק נסמכות בעיקר על דעותיהם של מומחים במקצועות הרלוונטיים ובחלקן בהתאמה של עקרונות המשמשים בבתי החולים, לתנאים ולאמצעים הקיימים בשטח. 

מקור נוסף לתרחישים שנדונו בפרק הוא סקירה שפורסמה ב-2017 של 54 מקרים בצבא ארה"ב בהם התבצע טיפל ממושך (4-120 שעות) בפצועים וחולים, שתיארה מגוון רחב של פציעות ותרחישים שונים. מן הסתם לא התייחסנו לכל פציעה ותרחיש, אלא נתנו כלים המתייחסים לעקרונות המתייחסים למצבים המרכזיים שבהם.

**מתי בסכמה נבצע את ההנחיות המוזכרות בפרק?**

מקומן הכרונולוגי של ההנחיות מגיע לאחר השלמת הסקר השניוני.
הטיפול בפצוע המעוכב כולל מספר שלבים:
1. השלמת הסקר השניוני ומעבר לשלב אחזקת הפצוע.
2. יצירת סביבת עבודה, חלוקת תפקידים וסבבים.
3. הערכת הפצוע עפ"י מערכות, הגדרת בעיות ויצירת תוכנית טיפולית.
4. באם ניתן – הצגת הפצוע לגורם רפואי בכיר – חפ"ק אחורי\פלה"ק וכיוצ"ב.
5. מעקב והערכות חוזרות.
5. פינוי. לבית חולים או למסגרת בעלת יכולות טיפול נמרץ וכירורגיה (ומשם לבית חולים).

**בכל מקרה של התדרדרות במצב הפצוע, יש לבצע סקר ראשוני מחודש, ולשקול במסגרת האבחנה המבדלת פציעות מפוספסות וכן השפעות של הטיפולים שנתנו - ירידת ל"ד ו\או חזה אוויר בלחץ לאחר הנשמה בלחץ חיובי, ירידת ל"ד\שינוי במצב הכרה כתוצאה מהשפעת תרופות וכן הלאה.**

## מרכיבי הטיפול 
### סביבת העבודה
מתן טיפול רפואי מתמשך מחייב יצירת סביבת עבודה מוגנת, מסודרת ונוחה ככל הניתן. סביבה זו יכולה להיות:
- נייחת – מבנה, עמדת הסוואה, רכב בשהייה, שיח, מחסה סלע וכיוצ"ב.
- ניידת – כלי רכב\טיס\שיט, תוך כדי פינוי ממושך. האיגרת לא תדון במקרים אלו, שהם נחלתן של יחידות ספציפיות, אולם חלק מהמידע המובא כאן ישים גם אליהם.

לא תמיד ניתן יהיה לבחור את סביבת העבודה, אולם עד כמה שניתן יש לשאוף שהיא תהיה:
- **מוגנת מאויב**, ככל הניתן, ולכל הפחות מאש שטוחת מסלול.
- **נסתרת** - בשאיפה עד רמה שניתן להיעזר בתאורת פנסים. 
- **מוגנת מאיתני הטבע** – גשם, שמש, חום, קור וכיוצ"ב. במידה ואין עמדה כזו, יש לנסות למצוא דרך להגן לפחות על הפצוע עצמו.
- **מרווחת ונוחה** – מאפשרת מספיק מקום לפצוע, למטפלים ולציוד. לצורך שהייה וטיפול.
- **מאפשרת תקשורת בין המטפל למפקד בשטח (תקשורת פיזית ו\או תג"מית)**

לאחר שנבחרה סביבת העבודה, יש להתחיל בארגונה:
- **הגדרת הצוות המטפל** – יש להקצות ולתדרך באופן תמציתי מי המטפלים בפצוע, מה הכשרתם (רופא, פאראמדיק, חובש ומציל חיים) ומה תפקידם בטיפול. ייתכן מצב שבו יידרש ממטפל לבצע דברים שלא הוכשר אליהם דיו (למשל הנשמה באמבו דרך צינור הנשמה) – יש להקדיש זמן ומאמץ כדי להסביר לו ולוודא הבנה, ולהגדיר באופן חד וברור את גבולות סמכותו ובאילו מצבים עליו לדווח למטפל הבכיר. במקרה שאדם נוסף מצטרף לצוות המטפל, יש לתדרכו מחדש באופן דומה.
- **השכבת הפצוע –** הפצוע יושכב באופן שיהיה **מבודד מהקרקע**. יש להשתדל שישכב **בתנוחה אנטומית** ככל האפשר, ועם **מינימום לחץ מקומי** שעלול להביא ליצירת פצעי לחץ, שעלולים להתפתח תוך שעות. רצוי **לרפד** את האלונקה מתחת לפצוע בחומרים רכים (שמיכת צמר, מזרון, מעילים) במידה וניתן למצוא אותם בסביבה. יש לשים דגש על אזורי לחץ – ראש, שכמות, עצם הזנב והעקבים. במידה ויש חשד לפגיעת עמ"ש, יש להמשיך הגנה עליו, תוך הקפדה על מניעת לחץ של הצווארון על עצמות (למניעת פצעי לחץ) ועל הצוואר (באופן שיפריע לניקוז הורידי מהמוח). באופן דומה יש להקפיד ששרוך קיבוע של טובוס אינו לוחץ על הרקמות הרכות של הצוואר באופן שיפריע לניקוז הורידי. **זווית ההשכבה** תיבחר בהתאם למצבו הרפואי של הפצוע – פצוע בהלם תת-נפחי עמוק נשכיב בתנוחת טרנדלנבורג (30- מעלות) כדי לנסות ולשמר את ההחזר הורידי, בעוד פצוע עם פגיעת ראש וחשד לעליית ICP (Intra-Cranial Pressure),   או פצוע עם בעיה נשימתית נעדיף להשכיב בזווית של +30° (תנוחת פאולר, ראש למעלה) כדי להוריד ICP  ולהעלותFunctional Residual Capacitiy ( FRC).  במידה וקיים הלם תת-נפחי יחד עם אחד המצבים המתוארים לעיל, ההשכבה תתבצע בזווית של 0 מעלות.יצירת הזווית תהיה באמצעות ניצול תוואי הקרקע או הוספת תמיכה תחת האלונקה (תיקים, אבנים וכו'). **יש לכסות את הפצוע היטב**, בעזרת שמיכת מילוט ובמידת הצורך והאפשר שמיכות\ריפוד אחר. מומלץ לכסות\לעטוף גם את הראש, דרכו ניתן לאבד חום רב גם במבוגרים. מומלץ לתמוך בראש משני צידיו עם ריפוד רך כלשהו, כדי למנוע התנדנדות של הראש, שעלולה לגרום ליציאה של צינורות או שינוי מיקומם, בדגש על צינור ההנשמה. במידה והפצוע מורדם ומונשם, מומלץ **לקשור את ידי הפצוע** לאלונקה כדי למנוע שליפה של צינור ההנשמה. יש לוודא כי לא מופעל לחץ על פרקי ידיו וכי ניתן לשחרר את הקשירה בקלות יחסית, למשל כדי להפוך את הפצוע. במידה וניתן יש לכופף את ברכי הפצוע (יצירת זווית של 30 מעלות מהאלונקה) על מנת להפחית את הסיכון ליצירת פקקת ורידים עמוקה ונזקים עצביים. 
- **סדר בצנרת –** כל צינור המחובר לפצוע – צינור הנשמה, נקז חזה, עירוי, קתטר שתן וכיוצ"ב – יש לוודא קיבוע שלו ולוודא שהצינורות מופרדים, אינם מסובכים זה בזה, אינם מפעילים לחץ על רקמות הפצוע ומסומנים באופן שקל ונוח לזהותם. שקיות עירוי צריכות להיות תלויות מעל הפצוע באמצעות שרוך\אגד\אזיקון הקשורים לזיז בסביבה (ענף, מסמר, קורה וכיוצ"ב). יש לוודא כי הווסתים אינם פתוחים בטעות ואין עירוי יתר לא מווסת של נוזלים לפצוע. שקיות ניקוז של קתטר שתן, נקז חזה וזונדה צריכות להיות מונחות\תלויות יותר נמוך מהפצוע כדי לאפשר ניקוז. בעת תנועה על כלל הצנרות להיות מחוברות לפצוע וסגורות במידת האפשר.
- **הכנת תרופות הרדמה** – בפצוע מונשם מומלץ להכין תרופות הרדמה מהולות שיהיו מוכנות למתן מיידי במקרה הצורך. יש להקפיד על שאיבה סטרילית של התרופות. יש לסמן את המזרקים ואת המינון בהם, בצורה בולטת כדי למנוע בלבול ביניהם, ולרכזם באופן מסודר בסמוך לפצוע או על גופו של המטפל הבכיר. תרופות שמומלץ להכין:
    - **KETAMINE 25mg/ml** – שואבים 5 מ"ל סליין ומוסיפים 5 מ"ל של קטאמין מהאמפולה (50 מ"ג למ"ל). 
    - **MIDAZOLAM 0.5mg/ml**  - שואבים 9 מ"ל סליין ומוסיפים אמפולה של מידזולם (5מ"ג למ"ל).
- **מעקב, רישום ותיעוד** – יש להתחיל מעקב רציף אחר הסימנים החיוניים של הפצוע - (סטורציה, דופק, ל"ד, GCS, רמת כאב), ולתעד באופן ברור, בעדיפות על הטופס המופיע בנספח א'. תדירות מומלצת לתיעוד סימנים תהיה אחת ל-15 לדקות בפצוע דחוף או שקיבל טיפול בנרקוטיקה, ואחת לשעה בפצוע לא דחוף. במידה ומתגלה שינוי משמעותי במצב הפצוע, יש לחזור ולהעלות את תדירות המעקב. תפוקת שתן ותפוקה מנקזים תנוטר בתדירות של אחת לשעה.
- **הגדרת מסגרות זמנים וסבבי עבודה ומנוחה** – מנוחות הן חשובות ביותר לשמירת יכולתו של הצוות להמשיך בלחימה ובטיפול בפצוע, בדגש על המטפל הבכיר. במידה והפצוע נשאר בהשגחת מטפל אחר, יש להגדיר לו **באופן חד וברור** מה המצבים בהם עליו לקרוא באופן מיידי למטפל הבכיר – שינוי במצב הכרה, שינוי משמעותי במדדים (לרבות הגדרת ספים מספריים בטופס המעקב) או כל מצב אחר שנתפס כחשוד\לא ברור בעיני המטפל המשגיח. כל החלפת משמרות מטפלים תהיה בנוכחות המטפל הבכיר ותכלול הערכה מחודשת של הפצוע לפי מערכות ווידוא ביצוע פעולות לפי צ'קליסט (ראה טופס בנספח א'). לא מומלץ שמשך הזמן בין ההחלפות יעלה על שעה. במידה וקיים יותר ממטפל בכיר אחד, מומלץ שיחלקו ביניהם את שעות הערות באופן שיאפשר לכל אחד מהם מקסימום של שינה רציפה..
- **תכנון משאבים** – תכנון השימוש במשאבים, הגבולות שהם מציבים והאלטרנטיבות הקיימות – אנרגיה, נוזלים, תרופות וכיוצ"ב. ניתן לתכנן למשל שימוש לסירוגין במכשירי ניטור שהאנרגיה שלהם מוגבלת. בכל מקרה יש לציין כי לכל משימה מומלץ להצטייד באנרגיה המספיקה ל- 18 שעות לפחות.

### הערכת הפצוע עפ"י מערכות
בתרחיש של טיפול ממושך בפצוע בשדה אנו מנסים ככל הניתן לייצר **סביבה הדומה לטיפול נמרץ**, אם לא באמצעים ובמיומנות הצוות, לפחות בעקרונות הטיפול הבסיסיים. הערכת הפצוע והטיפול בו מתקיימים בשני רבדים:
- זיהוי **בעייתו הבסיסית של הפצוע** וטיפול המוכוון לפתרונה.
- **הערכה וטיפול תומך לפי מערכות** – נתיב האוויר, הנשימה,  קרדיו-ווסקולרית, מערכת העצבים, מערכת העיכול, מניעה וטיפול בזיהומים, מערכת השריר והשלד וכן הלאה. הערכה זו מתבססת על אנמנזה (במידה וקיימת), בדיקה גופנית ואמצעי ניטור שונים. חשוב לזכור כי אין אמצעי אחד שנותן מדד מושלם לתפקוד מערכת כלשהי, וכל נתון צריך להישפט כחלק מכלל הנתונים הרלוונטיים ליצירה של תמונה קלינית.

התייחסות לפי מערכות:

#### נתיב האוויר
פצוע בהכרה, אפילו חלקית יוכל לרוב לשמור על נתיב אוויר באופן עצמאי. זו האפשרות המועדפת, מכמה טעמים:
- אינה חושפת את הפצוע לסיכונים שבניסיון להשגת נתיב אוויר דפיניטיבי ולסיכוני הנשמה.
- אינה חושפת את הפצוע להנשמה בלחץ חיובי, על הפגיעה ההמודינמית הכרוכה בה.
- חוסכת באופן דרסטי במשאבי הטיפול המוגבלים בלאו הכי.

פצועים שיהיו אפילו מעט ישנוניים (אבל ניתנים להערה -  Arousable) עלולים לסבול מחסימה לסירוגין של נתיב האוויר בשל צניחת בסיס הלשון. זו לבדה אינה סיבה מספקת להשגת נתיב אוויר דפיניטיבי במתאר זה. במידה והרפלקסים הלרינגיאליים תקינים (הפצוע מסוגל לבלוע ולהשתעל), ניתן במקרה זה להסתפק בהשכבה בחש"י ובמידת הצורך בהחדרה זהירה של מנתב אוויר פלסטי, אך ורק במידה והפצוע אינו פולט אותו. 

בפצוע ללא נתיב אוויר דפיניטיבי יש להמשיך ולנטר את נתיב האוויר, ע"י מדידה רציפה של ריוויון החמצן בדם (סטורציה) וכן, לסירוגין – שיחה עם הפצוע. **פצוע מדבר שומר על נתיב האוויר**. התייחסות מחודשת לנתיב האוויר נדרשת בכל "ביקור."

האינדיקציות והשיטה להחדרת נתיב אוויר דפיניטיבי בפרק "ניהול נתיב האוויר", והן אינן שונות בתרחיש זה. 

בכל מקרה – **לא נבצע אקסטובציה בשטח.** פעולה זו תתבצע בדרג עם יכולות טיפול נמרץ, גם אם חלפה ההתוויה להנשמה פולשנית או בלחץ חיובי.

פצוע שנדרש להרדמה לצורך צנרור הקנה, יידרש לרוב למנות אחזקה של ההרדמה כדי שיוכל להמשיך ולסבול את הגירוי של צינור ההנשמה בקנה ושל ההנשמה המלאכותית. מנות אלו יהיו קטנות בהרבה ממנת האינדוקציה, היות והגירוי הוא חלש משמעותית מזה של לרינגוסקופיה. במידה ויש גירוי נוסף של כאב ממקור הפציעה למשל, יש להוסיף טיפול אנלגטי, בדגש על מורפין (ראה תת-פרק "כאב" בהמשך). המינון הנדרש משתנה משמעותית בין מטופלים שונים, בשל הבדלים פיזיולוגיים (טרם הפציעה) ופתו-פיזיולוגיים. לאור זאת מומלץ לבצע את האחזקה ע"י מתן מינונים חוזרים של תרופות הרדמה. זה יתבצע ע"י מטפל בכיר בלבד, לפי סימני התעוררות של המטופל (תזוזה, שיעול, פקיחת עיניים). יש לזכור כי מהירות ההשפעה של תרופות ההרדמה שאנו משתמשים בהן נעה בין דקה לשלוש דקות, ולכן לאחר מתן מנת הרדמה יש להמתין משך זמן זה על מנת להעריך את השפעתה. במידה והפצוע זז, יש להחזיק אותו בחוזקה עד העמקת ההרדמה, בדגש על מניעת שליפה של צינורות. מינוני אחזקה התחלתיים יהיו:

- KETAMINE   -בולוס של 25-50 מ"ג (1-2 מ"ל ממזרק לפי ההוראות לעיל) כל 15 דקות לערך.
- MIDAZOLAM  - בולוס של 1-1.5 מ"ג (2-3 מ"ל ממזרק לפי ההוראות לעיל) כל 15 דקות לערך.
- במידה והפצוע יציב המודינמית, מומלץ להוסיף MORPHINE  - בולוס של 5 מ"ג כל שעה.

ככל שהמטפל "יבלה" יותר זמן עם הפצוע, הוא ילמד להעריך את צריכת ההרדמה שלו ולהתאים את גודל הבולוס ואת התדירות, ולהימנע מהתעוררויות מיותרות (יש לתעד זאת). בכל מקרה יש לזכור את תופעות הלוואי האפשריות של התרופות, בעיקר המודינמיות, ואת העיקרון שקובע כי תמיד ניתן להוסיף תרופות, אולם **לא ניתן "להוציא" תרופות שכבר ניתנו**.

בכל "ביקור" ולאחר כל הזזה של הפצוע יש לוודא מחדש את מיקום הטובוס, בקפנומטריה ובהאזנה דו צדדית ולתעד את עומק הטובוס.

##### נשימה
מבחינה נשימתית, אנו מתייחסים לפצוע משלושה היבטים, הקשורים זה בזה:
- **אוורור** – כניסת אוויר עשיר בחמצן (לפחות כמו אוויר חדר) ועל ידי כך פינוי של פחמן דו-חמצני. אינו בר מדידה בתנאי שטח בפצוע הנושם באופן ספונטני, אולם ירידה משמעותית באוורור תוביל לפגיעה בחמצון, במיוחד בפצוע הנושם אוויר חדר. בפצוע מונשם נעזר בקפנומטריה (ETCO2) כל אימת שהיא זמינה. בכל מקרה של פגיעה באוורור יש לשלול בראש ובראשונה חסימה של נתיב האוויר ושל צנרת ההנשמה.
- **חמצון** – העשרת הדם בחמצן ע"י הריאות. נמדד בקלות ע"י Pulse Oximetry. אוורור מספק הוא תנאי הכרחי לחמצון סביר, אולם לא מספיק – צריכה להיות התאמה כמותית ואנטומית-פיזיולוגית בין האוורור לזרימת הדם בריאה (V/Q Match).. מצבים של היעדר התאמה כוללים: 
    - **נפח מת (Dead Space)** – איזור אנטומי\פיזיולוגי המקבל אוורור אולם לא אספקת דם.
    - **מעקף (Shunt)** – איזור אנטומי\פיזיולוגי המקבל אספקת דם אולם לא אוורור.
    - שילוב של השניים.
- **עבודת הנשימה** – לגוף יש יכולת, במנגנוני משוב המושפעים מהלחץ החלקי של חמצן ופחמן דו-חמצני ומה- pH  של הדם, לפצות על פגיעה באוורור\חמצון ע"י הגברת מאמץ שרירי הנשימה להגדלת האוורור. מבחינה קלינית נראה קצב נשימה מהיר (טכיפנאה) ושימוש בשרירי עזר (רטרקציות בין-צלעיות וסופרא-סטרנליות, נשימה פרדוקסלית). בפצוע בו קיימים סימנים אלו, קיימת ככל הנראה בעיה נשימתית או המודינמית. היעלמותם של הסימנים יכולה להעיד על שיפור, או לחלופין על התעייפות של שרירי הנשימה, שתוביל במהרה לכשל נשימתי ולהיפוקסיה.

לפי שלושת הפרמטרים האלו נעריך כל פצוע שנושם ספונטנית ונחליט לגבי הצורך בתמיכה. זו יכולה לכלול, בשטח:
- **פתרון בעיות נשימתיות** ככל הניתן – וידוא נתיב אוויר פתוח, ניקוז חזה אוויר.
- **שיפור תנוחה ותרגול נשימתי** – ישיבה\שכיבה בתנוחת פאולר (ראש כלפי מעלה) מעלה את ה-FRC ומסיטה את נקודת שיווי המשקל המכאני של הריאות לכזו שמקטינה את עבודת הנשימה ביחס לאוורור. בנוסף היא מסייעת לשמירה על נתיב אוויר פתוח. תרגול נשימתי (5 נשיפות ארוכות דרך מזרק 10 מ"ל ללא הבוכנה) אחת לשעה מסייע במניעת תמטים ובפינוי הפרשות.
- **העשרה בחמצן** – לרוב, בתנאי השטח, אם יהיה ברשותנו חמצן הוא יהיה קיים בכמות מאד מוגבלת, שנרצה לשמור למצבים מאד ספציפיים – פרה-אוקסיגנציה לפני צנרור הקנה, או מצב חירום נשימתי בפצוע מונשם עד לפתרונו. במידה ואיננו מוגבלים בכמות החמצן שברשותנו, הוא ישמש ככלי חשוב לשיפור החמצון ובשאיפה למנוע את הצורך בהנשמה.
- **הנשמה** – הנשמה במסכה מתאימה לפרקי זמן קצרים ביותר, למשל עד אבטחת נתיב האוויר הדפיניטיבי, או במהלך פינוי קצר. הנשמה במתאר השהייה תתבצע דרך נתיב אוויר דפיניטיבי. רוב הפצועים יהיו בעלי נשימה ספונטנית, ולכן יידרשו להנשמה מסונכרנת. בפצוע מונשם יש להקפיד על ניטור מלא ככל הניתן, בדגש על סטורציה, ETCO2  , דופק ול"ד.  הקיבה צריכה להיות מנוקזת באמצעות זונדה ויש לבצע שאיבת הפרשות מחלל הפה הלוע (לא דרך הטובוס) אחת לשעה. אמצעי ההנשמה עצמם יכולים להיות:
    - **ידנית** – אמבו. מאפשר, ע"י מטפל מיומן, הנשמה מסונכרנת לפצוע, והערכה איכותנית של לחצי ההנשמה. חסרונה המרכזי של ההנשמה הידנית בכך שאיכות ההנשמה היא פחותה, תלויה מאד במיומנות המטפל ומחייבת מטפל צמוד לפצוע בכל רגע נתון (סבב מטפלים). יתרון חשוב הוא שאינו תלוי באנרגיה. יתרון חשוב נוסף הוא הפשטות – בכל חשד לתקלה במנשם, נעבור בשלב הראשון להנשמה באמבו.
הנשמה מסונכרנת תתבצע באופן הבא:
        1. קביעת קצב ההנשמה וחישוב המרווח בין ההנשמות (ברירת מחדל – 12 לדקה כלומר הנשמה כל 5 שניות).
        2. במידה והפצוע לא הוסיף נשימה, ניתן הנשמה בקצב שקבענו.
        3. במקרה שהפצוע מוסיף נשימה, ניתן תמיכה לאותה נשימה ונתחיל את ספירת השניות מחדש.
    - **אוטומטיים**–
        - *מיקרו-מנשם (EMV)*  - מאפשר הנשמה מסונכרנת בשיטת Assist-  Control (A/C)  כלומר הנשמה בקצב ונפח קבועים. כאשר הפצוע מוסיף נשימה המנשם מזהה את הניסיון ומשלים את הנשימה לנפח המוגדר. שיטה זו מפחיתה את ההתנגדות של הפצוע למנשם, אולם עלולה לגרום להיפר-ונטילציה. הגדרות הבסיס יהיו קצב הנשמה של 12 בדקה, עם נפח של 7 מ"ל לק"ג (500 מ"ל בפצוע בגודל רגיל) ו- PEEP של 5. במידה וקיים ניטור של ETCO2, יש לעקוב אחריו. במידה ומופיעה ירידה ב- ETCO2  החשודה כאוורור יתר, יש להוריד תחילה את נפח ההנשמה – Tidal Volume(לא לרדת מתחת ל- 5מ"ל לק"ג)  ואם צריך גם את קצב ההנשמה. קיימת גרסה מתקדמת יותר (EMV+) , עם יכולות של הנשמה בשיטת  SIMVהמתאימה יותר לפצוע בשטח ועל כן שיטה זו מועדפת באם היא קיימת. סוללת ה- EMV  מספיקה לכ-10 שעות של הנשמה. 
        - *מנשם רפאל* – מאפשר שיטות הנשמה מתואמות עם הפצוע, כמו SIMV (Synchronized Intermittent Mechanical Ventilation)  ..  שיטה זו מתאימה יותר להנשמה של פצוע עם דרגה כלשהי של נשימה ספונטנית. הכוונון הראשוני נעשה באופן אוטומטי ע"י המכשיר לפי משקל הפצוע ונותן פרמטרים מתאימים, אותם ניתן לשנות בתפריט. ערך ה- PEEP (Positive End Expiratory Pressure)   נקבע ע"י שסתום בצנרת ההנשמה, והערך הנמדד ניתן כחיווי בצג הבקרה. יש להקפיד על הנשמה ב- PEEP  של 5. הנשמה בערכים אחרים של PEEP או בשיטות הנשמה אחרות אינה מאושרת למטפלים ללא הכשרה בהרדמה \ טיפול נמרץ.

ככלל, האינדיקציות להנשמה חופפות לאינדיקציות להחדרת נתיב אוויר דפיניטיבי, כפי שהן מפורטות בפרק "ניהול נתיב האוויר". בכפוף לאינדיקציות אלו, יש לשאוף להשאיר את הפצוע בנשימה ספונטנית ככל הניתן, מהסיבות שפורטו בסעיף "נתיב אוויר".

ההערכה הנשימתית כוללת:
****** טבלה

בפצוע עם נקז חזה יש לבצע מעקב על תפוקת הנקז והתוכן:
- הנקז עלול להיסתם, בעיקר על ידי קרישי דם, או כתוצאה מכיפוף. בכל מקרה של התדרדרות נשימתית או המודינמית יש לוודא כי הנקז מנקז ובמידה ויש ספק או צורך, לבצע שטיפה של הנקז בעזרת תמיסה פיזיולוגית (סליין\הרטמן) דרך מזרק 50 מ"ל (מזרק זונדה). יש לבצע זאת באופן סטרילי ככל הניתן. במקרה של סתימה שאינה נפתחת יש להחדיר נקז חדש ( בפצוע המפגין סימנים של התדרדרות המודינמית/ נשימתית).
- יציאה מתמשכת (מעל 250 מ"ל לשעה) או בכמות גדולה (מעל 1.5 ל' מיד לאחר ההחדרה) של דם דרך הנקז מעידה על קיום דמם בלתי-נשלט בתוך בית החזה, שבמתאר עם גישה לבית החולים מהווה התוויה לתורקוטומיה דחופה. במתאר השהייה ללא יכולת כירורגית, אפשרות זו אינה על הפרק. במידה והפצוע סובל זאת מבחינה נשימתית, מומלץ לסגור את הנקז באמצעות הפאן כדי לייצר מידה מסוימת של טמפונדה בחלל בית החזה, להמשיך טיפול בנוגדי-פיברינוליזה (הקסאקפרון 1 גרם אחת לשעה) ולטפל לפי פרק החייאת בקרת נזקים בשדה ( טיפול במוצרי דם על פי הזמינות הקיימת).

#### המערכת ההמודינמית
הרוב הגדול של מקרי המוות בר-המניעה בשדה הקרב נובעים מדמם. חשוב להבין שבמתאר השהיה ימותו לצערנו חלק ניכר מהפצועים שמותם היה בר-מניעה במידה והיו זוכים לפינוי מהיר לבית החולים. עם זאת, עלינו לעשות את המיטב כדי לתת לפצועים המדממים את סיכויי ההישרדות הטובים ביותר.

ראשית, **יש לבצע סריקה מחודשת ועצירה מלאה של כלל הדימומים**. אין תחליף בשטח לאף טיפת דם שתלך לאיבוד.

חוסמי-עורקים: במידה וניתן, יש לנסות לבצע המרה של כל חוסם עורקים בהקדם האפשרי, תוך מוכנות לעצירה מחודשת של הדימום על ידי חוסם עורקים חדש. במידה ובוצעה המרה יש לבצע מעקב תכוף על הפצעים כדי לזהות בזמן התחדשות של הדימום. עליה בלחץ הדם עלולה לגרום לפצעים שחדלו מלדמם לחזור ולדמם.

גישה ורידית: לכל פצוע מדמם חייבות להיות לפחות שתי דרכי גישה וסקולרית, בקוטר של 18G  לכל הפחות, מקובעות היטב. אין יתרון משמעותי לעירוי מרכזי בשטח (הזרימה דרכו אף איטית יותר מאשר דרך עירוי פריפרי או תוך-גרמי באותו הקוטר), ויש להשתמש בו רק במידה והמטפל מיומן בביצועה ואין גישה פריפרית טובה. במקרה זה יש להשתמש בגישה פמורלית, כדי לצמצם את הסיכון לסיבוכים מידיים (בעיקר חזה-אוויר) .

מבחינת עירוי נוזלים ומוצרי דם, בפצוע המדמם יש לפעול לפי ההנחיות בפרק החייאת בקרת נזקים בשדה.  בפצוע שאינו מדמם (או כלל הדימומים נשלטים באופן מלא) וללא כוויות נרחבות (מעל 20 אחוז משטח הגוף) או פגיעות מעיכה ניתן אחזקה בקצב התחלתי של כ- 100 מ"ל לשעה, עם טיטרציה לפי תפוקת שתן (יעד של 30 מ"ל לשעה – 0.5 מ"ל\ק"ג\שעה). בפגיעות מיוחדות (כוויה, מעיכה וכיוצ"ב), במסגרת המשאבים הקיימים, יש לנסות לפעול בהתאם להנחיות הפרקים הרלוונטיים. בפצוע מונשם או עם פגיעה ריאתית יש לצמצם במתן נוזלים ככל הניתן תוך שמירה על יציבות המודינמית (ל"ד סיסטולי של 90 ומעלה, דופק מתחת ל-130, שמירת רמת הכרה). אין מקום לשימוש במוצרי דם לצורך החזר נפח לפצוע שלא מדמם\דימם.

בפצוע ללא פגיעת גו או ראש (פגיעת גפיים מבודדת), בהכרה מלאה, ניתן ורצוי לתת נוזלים בשתייה (ולא בגישה ווסקולרית), לפי צמא ונקיטת שתן. במידה והוא מצליח לשתות באופן סביר, אין צורך במתן נוזלים דרך הוריד\מוח העצם.

ניטור המודינמי יכלול את המדדים הבאים:
- מצב הכרה – יש לזכור כי בשוק דרגה 2-4 הפצוע עשוי להיות חרד וקומבטיבי.
- סימנים חיצוניים – חיוורון, הזעה.
- דופק – מדידה רציפה ע"י Pulse Oximeter.
- לחץ דם – כל 15 דקות, או באופן תכוף יותר בפצוע לא יציב. היעד במרבית הפצועים יהיה ל"ד סיסטולי של מעל 90 ממ"כ או ממוצע ( MAP=Diastolic×2+Systolic3) של 65 ממ"כ.
- תפוקת שתן – הרזולוציה של השנתות על שקית השתן אינה מספקת – ניתן לרוקן את השקית אחת לשעה לכוס ריקה ולמדוד עם מזרק.

טיפולים נוספים כוללים:

- מעכבי פיברינוליזה (הקסאקפרון) – יש לזכור לתת את המנה השנייה של הקסאקפרון לאחר 3 שעות מהפציעה.

למרות שאנו מגדירים יעדים המודינמיים, חשוב לטפל בפצוע ולא במספרים. פצוע שמפתח הלם, יש לשקול את האבחנה המבדלת בין סוגי ההלם השונים:
- **תת-נפחי (כולל המורגי)** – מקום ראשון בכל פצוע מדמם\ עם פגיעת גו.
- **חסימתי** – חזה-אוויר בלחץ, טמפונדה לבבית, תסחיף ריאתי מסיבי.
- **פיזורי** – אלח-דם (ספסיס), אנאפילקטי\ אנפילקטואידי, מינון יתר של חומרי הרדמה.
- **נוירוגני** – פגיעת עמוד שדרה גבוהה.
- **קרדיוגני** – פחות סביר במרבית מתארי הטראומה, למעט התחשמלות ופגיעות אקלים. יכול להיגרם כתוצאה ממינון יתר של חומרי הרדמה.

יש להתאים את הטיפול לאטיולוגיה כפי שהיא מוערכת ע"י המטפל.

במקרה של חשד גבוה לטמפונדה לבבית (סימני הלם חסימתי ללא חזה אוויר בלחץ) אין לבצע ניקוז במחט של הפריקרד. יש לשמר החזר ורידי מקסימלי ע"י החזר נפח והימנעות מהנשמה בלחץ חיובי ככל הניתן.
יש לזכור כי טראומה ושכיבה ממושכת הם גורמי סיכון משמעותיים לאירועים תרומבו-אמבוליים. פצוע שמסוגל להתהלך – יש לעודד זאת. במידה ואין התווית נגד (חשד לפגיעת עמ"ש) יש להשכיב את הפצוע עם כיפוף של הברכיים בזווית של 30 מעלות מהרצפה ולבצע עיסוי עמוק של השוקיים בתדירות גבוהה ככל הניתן למניעה.

#### מערכת העצבים
בכל פצוע עם חשד לפגיעת עמוד השדרה, נניח ונשאיר צווארון פילדלפיה. יש לוודא שהוא הונח כראוי, מונע תזוזה ואינו גורם לפצעי לחץ או ללחץ על ורידי הצוואר שיפגע בניקוז הורידי מהמוח. יש להקפיד בכל הזזה של הפצוע על שמירת עמוד השדרה. אין להשאיר את הפצוע על מצע קשיח, שעלול לגרום להופעת פצעי לחץ קשים תוך זמן קצר למדי, ויש להניח את הפצוע על משטח רך, ישר ויציב (למשל אלונקה עם ריפוד).

בפגיעות ראש, מטרתנו **לצמצם ככל האפשר את הנזק המשני** – לשמר פרפוזיה מוחית ולמנוע הרניאציה. 

הנוסחה המרכזית שיש לזכור היא:

**CPP = MAP – ICP**

(CPP = Cerebral Perfusion Pressure; MAP – Mean Arterial Pressure; ICP = Intra-Cranial Pressure)

האמצעים העומדים לרשותנו במתארי אחזקת פצוע כוללים:
- תנוחה – ראש למעלה בזווית 30 מעלות (תנוחת פאולר) מסייע בהורדת ICP .
בפצוע הנמצא בהלם עמוק לא נרים את הראש לתנוחה זו.  
- בפצוע המונשם – שמירה על נורמוקפניאה על הצד הנמוך-  יעדETCO2  של 25-30 ממ"כ, או במידה ולא ניתן לנטר – עליה בקצב ההנשמה של כ- 20%.
- יעד ל"ד סיסטולי מעל 100 ממ"כ, או ממוצע (MAP) מעל 75 ממ"כ (ולא מעל 90 ממ"כ).
- מניעת עליות חדות ב- ICP – הרדמה עמוקה ככל שמתאפשר מבחינה המודינמית, תוך שימוש מועדף במידזולם (בעל תכונות נוירו-פרוטקטיביות). שימוש במורפין, כאמור במגבלות המודינמיות.
- בניגוד למתאר בית-החולים – אין צורך להעיר את הפצוע כדי לבצע הערכה נוירולוגית שלו – הדבר לא ישנה את הטיפול בו בכלים הקיימים בשטח, או את דחיפות הפינוי שלו שהיא מירבית גם כך.
- פגיעות עמוד השדרה הגבוהות (צווארי\גבי) עלולות לגרום להלם נוירוגני בשל הירידה בטונוס הסימפתטי. הטיפול כולל החזר נוזלים ובמידת הצורך תמיכה בקטכולאמינים – בשטח ע"י אדרנלין – יש להתחיל במנות חוזרות של 10 מק"ג כל דקה (נמהל 1 מ"ל של אדרנלין עם 9 מ"ל סליין, ולאחר מכן מ"ל אחד מהתערובת עם 9 מ"ל סליין- יתן לנו תמיסה של 10מק"ג אדרנלין למ"ל), לאחר כל מנה נבצע מדידה של לחץ דם ולבצע טיטרציה לקבלת האפקט הקליני הרצוי – ל"ד סיסטולי מעל 100 ממ"כ. לרוב האפקט יהיה קצר טווח ויהיה צורך להמשיך במתן מנות אחזקה כל מס' דקות, בכפוף למדידות לחץ הדם.
- שימוש בקורטיקוסטרואידים במינון גבוה היה נהוג בעבר בפגיעות עמ"ש, אולם העדויות לגבי כך אינן חד משמעיות, וישנן עדויות כי הטיפול גורם לתמותה מוגברת מפגיעות ראש בדרגה בינונית-קשה (שלא ניתן לשלול בתנאי השטח). לאור זאת, טיפול זה אינו מומלץ.

ניטור יכלול בדיקה נוירולוגית בסיסית, כולל GCS, מוטוריקה גסה ובדיקת אישונים אחת לשעה.

**פגיעה בעצבים פריפריים אינה ניתנת לטיפול בשטח, אך ניתנת למניעה**. השכבה בתנוחה לא אנטומית, עם לחץ מקומי, או יצירה של תסמונת מדור, עלולות לגרום לנזק עצבי בלתי-הפיך. יש לבצע שינוי תנוחה ובדיקה מקיפה של ההשכבה אחת לשעה (בכל "ביקור").

טיפול בכאב הוא חלק משמעותי מאד בהשהיית פצוע בשטח. יש לפעול בהתאם להנחיות בפרק "הטיפול בכאב בדרג השדה". סוכריות אקטיק (OTFC) פחות מתאימות לטיפול ממושך, ויש העדפה לשימוש בקטאמין ומורפין דרך הוריד. כמו-כן במידה וניתן יש לשלב טיפול פומי בהתאם למפורט בפרק "הטיפול בכאב בדרג השדה".

חסמים עצביים פריפריים (Peripheral Block) מצריכים לרוב מיומנות ואמצעים שאינם קיימים בשטח. יוצא דופן בהקשר זה הם חסם אצבע (Digital Block)– מומלץ לרכוש ניסיון בביצועו, אולם הוא פשוט יחסית ובטוח לביצוע, ומאפשר הימנעות ממתן אופיאטים בפציעות שעלולות לגרום לכאב עז בשל צפיפות העצבים הסנסוריים באזורים אלו. החסם מתבצע בשטח בעזרת לידוקאין (ללא אדרנלין). ניתן לחזור אחת ל- 1-4 שעות לפי הופעת כאבים.

#### מערכת העיכול
פצוע בהכרה מלאה (GCS=15) ללא פגיעה בגו, רשאי (וצריך) לשתות מים, בתור האופציה הטובה ביותר להחזר נוזלים. אכילה תותר רק לפצועים לא דחופים לפינוי, ללא פגיעה חודרת בגו, ללא פוטנציאל התדרדרות אמיתית, ולא בשלוש השעות הראשונות שלאחר הפציעה.

בכל פצוע מונשם יש להכניס זונדה לניקוז הקיבה דרך הפה, כפי שמפורט בפרק "הסקר השניוני".

יש לנטר יציאה של תוכן בזונדה, הן מבחינת כמות (כחלק מהערכת מאזן הנוזלים) והן מבחינת הצבע. הופעה של תוכן דמי עלולה להעיד על פגיעה במערכת העיכול או בדרכי הנשימה העליונות, או על הופעת Stress ulcers בקיבה. 


#### מניעה וטיפול בזיהומים
כל פציעה חודרת בשדה היא מזוהמת כהגדרה, ומצריכה טיפול אנטיביוטי מונע, עפ"י פרק "הטיפול האנטיביוטי בשדה".  יש לחזור על הטיפול בתדירות הנדרשת. בפצועים שיכולים לקבל טיפול פומי, נעדיף לרוב אפשרות זו.

פצעים מלוכלכים יש לשטוף, בעדיפות בתמיסה סטרילית (כתלות בכמות הנוזלים הקיימת ובתעדוף) או לפחות במים, כדי להוריד את העומס החיידקי בפצע, ולחבוש עם משחה אנטיביוטית במידה וזמינה, בעדיפות מופירוצין (בקטרובן), ואם לא, אזי להשאיר את הפצע מעט לח וחבוש. במידה וניתן, מבחינת ציוד, יש לשטוף ולהחליף חבישה כל 4 שעות.  במידה ומופיע אודם סביב פצע, יש לסמן את גבולותיו ולעקב אחר התפשטות. לאחר מספר שעות מהפציעה, בייחוד בנוכחות פצעים מלוכלכים, אלח דם (ספסיס) צריך להיות באבחנה המבדלת של הלם בפצוע מעוכב פינוי, כאשר הטיפול כולל שליטה במקור הזיהום (לא ישים בשדה) וטיפול אנטיביוטי רחב טווח (במידה וטרם ניתן), זאת במקביל לטיפול תומך בהלם.

פעולות חודרניות יש להשתדל לבצע בטכניקה סטרילית ככל הניתן. במתאר השהיה יהיה לרוב מספיק זמן להקדיש לצורך כך, והדבר יכול למנוע מהפצוע סיבוכים קשים.

בנוסף, יש לשמור על ההיגיינה של המטופל, לרבות הנחת משטח בד מתחת לעכוזו של המטופל\אלתור חיתול, פינוי הצואה ושמירה על נקיון העכוז.

#### מערכת השלד והשרירים
כל שבר יש לקבע בתנוחה אנטומית ככל הניתן, באמצעים הקיימים – משולשי בד, SAM Splints, סד תומס (לפגיעות ירך) ואמצעים מאולתרים שניתן למצוא בסביבה. קיבוע נכון של השבר מפחית במידה רבה את הכאב, וצריך להתבצע לאחר מתן טיפול נוגד כאב. יש לזכור כי קיבוע לאחר מתן כמות גדולה של נרקוטיקה עלול לגרום לתופעות של מינון יתר (בשל הפחתת הגירוי הכואב) ויש להשגיח על מצב ההכרה ותפקודי הנשימה של המטופל.

יש לבדוק בכל "ביקור" את אזורי המגע של הקיבוע עם המטופל למניעת פצעי לחץ, דופק וסימנים נוירולוגיים דיסטליים.

יש להקפיד על טיפול נכון בשברים פתוחים, בדגש על שטיפות וטיפול אנטיביוטי. יש לזכור שבמידה והונח חוסם עורקים, אנטיביוטיקה שניתנה באופן סיסטמי לא מגיעה לאזור הפגוע. במידה והדימום ניתן לעצירה בחבישת לחץ\חבישה המוסטטית יש עדיפות לביצוע המרה.

כל גפה פגועה – שבר, נקע וכו' – יש להרים אל מעל גובה הלב באמצעות מתלה. יש לעקוב אחר המצב הנוירו-ווסקולרי הדיסטלי בכל ביקור ולשלול הופעה של תסמונת מדור (לפי 5 ה- P: Pain, Pallor, Paresthesia ,Pulselessness ו- Paralysis). הסימן הבולט ביותר יהיה כאב לא פרופורציוני למצופה, שמוחמר בהנעת האצבעות\בהונות. יש להסיר מראש כל גורם חיצוני שעלול לגרום לכך – טבעות, שעונים וכו'). פצוע שמפתח תסמונת מדור יוגדר כדחוף גם אם לא הוגדר כדחוף קודם לכן. אין לבצע פציוטומיה שלא במתקן עם יכולות כירורגיות.בפריקות כתף, שבמתארי פינוי מהיר מומלץ להחזיר בבית-החולים לאחר הדמיה, במתארי השהיה נבצע החזרה בשטח כדי להקל על הכאב ולהקטין את הסיכון לנזק ארוך טווח. במידה ומחזירים פריקת כתף יש:
- לבדוק מצב נוירו-ווסקולרי דיסטלי לפני ואחרי הפעולה.
- לתת אנלגטיקה טובה (קטאמין 25 מ"ג ומורפין 0.1 מ"ג\ק"ג).

קיימות שיטות רבות להחזרת כתף. יש להשתמש בטכניקת החזרה אשר המטפל שולט בה. יש עדיפות לטכניקות מסוג Traction-Counter traction כמו ה- Assisted Hippocratic method.  להן יש יתרון כאשר מבצעים החזרה ללא שלילה רדיוגרפית של שבר. 

#### בקרת טמפרטורה
כל פצוע דחוף יופשט לחלוטין לצורך סריקה, ייובש, יופרד מהקרקע (על ידי אלונקה\מיטה\אלתור אחר) ויכוסה היטב (ע"י שמיכת מילוט ואמצעים נוספים שניתן למצוא בשטח – שמיכות, ביגוד חם יבש, עלים יבשים). במידה וקיימים אמצעים לחימום אקטיבי (שקיות חימום, שמיכת חימום אקטיבית) יש להשתמש בהם אם טמפרטורת הפצוע היא מתחת ל- 36.0 מעלות. יש להקדיש מאמצים רבים למניעת היפותרמיה. חשוב להדגיש כי טיפול בנוזלים מחוממים אינו טיפול להיפותרמיה. מדידת חום לפצוע מחוסר\מעורפל הכרה או שאינו מתנייד תתבצע בגישה רקטלית אחת לשעה. 

#### העברת מידע וייעוץ מרחוק
במידת הניתן, רצוי להציג באמצעות אמצעי הקשר את הפצוע לגורם רפואי בכיר – רופא רמה ממונה\חפ"ק\פלה"ק\יר"א וכו' לצורך התייעצות וטיוב הטיפול.

את ההצגה יש לבצע עפ"י הסדר הבא:
- מנגנון הפציעה.
- זמן הפציעה.
- אזורים פגועים והטיפול שבוצע.
- הצגה לפי מערכות – נתיב אוויר, נשימתית, קרדיו-ווסקולרית, נוירולוגית, אורתופדית. עבור כל מערכת יש להציג מצב עדכני והתערבויות שבוצעו.
- רשימת בעיות של הפצוע. 
- שאלות ממוקדות (במידה ויש).

חשוב לזכור כי היכולת של רופא יועץ לסייע היא מוגבלת, ואין תחליף לבדיקה בלתי-אמצעית של הפצוע. עם זאת, במידה ואפשרות זו קיימת, יש לנצלה.

##### היבטים פסיכו-סוציאליים
מצב של כח המצוי בנתק בשטח אויב ללא יכולת פינוי נושא בחובו עקה נפשית משמעותית, על אחת כמה וכמה אם קיימים בכח פצועים בסכנה לחיים או איבר שלא ניתן לפנותם. במצב זה, תשומת הלב של הכח תהיה מופנית במידה רבה לצוות המטפל, ולהתנהלותו של הצוות תהיה השפעה רבה על אנשי הצוות, הן ברמת התפקוד המבצעי והן בעיבוד האירוע בהמשך על השלכותיו על הבריאות הנפשית של אנשי הכח. יש לשדר לאנשי הכח כי מיטב המאמצים להצלת הפצוע מתבצעים, ובמידת האפשר לחלק משימות תומכות, שיסייעו לטיפול וגם ייצרו תחושת שותפות של הלוחם בטיפול – לשוחח עם הפצוע, הבאת פריטים מועילים מהסביבה או עיסוי השוקיים למניעת DVT.

גם עבור אנשי הצוות המטפל מדובר במצב לא קל מבחינה מנטאלית. היכולת להשפיע על הסיטואציה – לטפל בפצוע, לנסות להיטיב את מצבו ולנהל שגרת טיפול מהווה גורם מגן, וזו סיבה נוספת וחשובה לתכנן לוחות זמנים מסודרים לעבודת הצוות הרפואי ולדבוק בהם. יש להשתדל ככל הניתן לספק צרכים בסיסיים – שינה בתורות, שתייה ואכילה עד כמה שניתן. יש לבצע חיתוכי מצב שמחברים את כלל אנשי הצוות לסיטואציה, חלוקת משימות ברורה וגם הסבר לגבי התוכנית והפרוגנוזה. יש לקיים שיחות פנימיות של הצוות בפרטיות ככל הניתן, שלא לאוזני הפצוע או הלוחמים האחרים.

כמובן שיש חשיבות גם ליחס לפצוע הער – הסבר לפני כל פעולה, הרגעה והקשבה. יש לייצר נוחות מרבית עבור הפצוע, ולתת תקווה.

במידה ומצבו של הפצוע אנוש וסיכוייו לשרוד עד הפינוי קלושים, יש להכין בהדרגה את הכח לאפשרות של מוות.

#### קביעת מוות
מוות ייקבע בהתאם לפרק "מאמצי החייאה בפצוע המאבד סימני חיים". חשוב לזכור, לקביעת המוות בשדה הקרב יש השפעה משמעותית היכולה להציל חיים. מבצע לחילוץ חלל עלול לעלות בחייהם של חיילים נוספים שלא לצורך. חלל ינותק מכלל המכשור (ללא הוצאה של צנרת דוגמת עירויים, טובוס, נקזים וכיוצ"ב), יכוסה כולו (בעדיפות לכיסוי הפנים) ויופרד מהכח עד כמה שניתן. יש לקיים שיחה עם הכח (באחריות מפקד הכח) ושיחה לצוות המטפל (באחריות המטפל הבכיר). מטרת שיחות אלו לאפשר אוורור והתמודדות והמשך פעילות של הצוותים.

יש לעדכן רמה ממונה\חפ"ק לגבי מותו של הפצוע, כדי למנוע מאמצי פינוי שמותאמים לפצוע דחוף ולא לחלל.

#### סיכום
טיפול מתמשך והחזקת פצוע בשטח בדרג הגדוד היא אירוע בלתי-רצוי, עם משמעויות קשות מבחינה מבצעית, רפואית ופסיכו-סוציאלית. יש להימנע ממנה ככל הניתן. מאידך, איגרת זו נותנת כלים בסיסיים למטפל על מנת לעשות מה שביכולתו למען הפצוע ולמען הכח במצב קיצון זה, באמצעות גישה מערכתית, איסוף נתונים שיטתי, שיקול קליני ומעקב.
