# החייאת בקרת נזקים בשדה

### **עיקרי העדכונים:**

-   31/03/2022

1.  **עדכון הגדרת "שוק עמוק"**
    1.  **חובת מדידת ל"ד- שוק עמוק מוגדר כ ל"ד \<90 מ"מ כספית, או היעדר דופק רדיאלי בנוכחות ל"ד שאינו ניתן למדידה, או ירידה במצב הכרה שאינה מוסברת ע"י פג' ראש או טיפול תרופתי**
    2.  **דופק \>130 לבדו ( בנוכחות ל"ד תקין) אינו נחשב שוק עמוק**
    3.  **עדכון על הטיפול בילדים ( TXA ונפח)**
    4.  **תזכורת על כך שאין לעשות שימוש בהגדרות יציב/ לא יציב בטרום בית חולים**

-   15/11/2021

1.  הוספת נספח מתן דם מלא בשדה, הנחיה למט"ב

-   19/07/2021

1.  פלסמה נוזל הבחירה במצב של הלם עמוק על רקע כוויות.

-   01/03/2021

1.  עדכון אופן הכנת ומתן הפלסמה -- העדפה למתן באמצעות שקית העירוי

-   2019

1.  ניתן לתת TXA בפוש

### תוכן עניינים

#### הקדמה ורקע

#### פרוטוקול

#### ביאור הפרוטוקול

#### שיטות וחומרים

-   תהליך הכנת FDP
    -   תיאור התכשיר
    -   הוראות שימוש
    -   הוראות אחסנה
-   הנחיות למתן דם מלא
    -   הנחיות למתן דם מלא למטפל בכיר
    -   פירוט תגובות למתן דם ופרוטוקול טיפול \#### סיכום

### הקדמה ורקע

דימום הינו הגורם השכיח ביותר לתמותה בשדה הקרב ומהווה את הסיבה המובילה למוות בר מניעה. הדמם יכול לנבוע ממקור שהינו לחיץ ברמת השטח, לדוגמה דימום מגפה אשר ניתן לעצור ע"י חוסם עורקים, או ממקור שהינו בלתי לחיץ בשטח, לדוגמה דימום מאיבר בחלל הבטן. במתארים צבאיים כיום, כ- 2/3 ממקרי מוות בר ההצלה הדימום נובעים מפגיעות גו, כלומר במרבית המקרים הדימום אינו ניתן לעצירה בשטח, אלא רק בחדר ניתוח. בפצועים מדממים, ובמיוחד במקרים בהם לא ניתן ללחוץ על מקור הדימום, יש צורך בהחזרת נפח הדם שאבד. בעבר, היו ניתנות כמויות גדולות של נוזל קריסטלואידי כדי להחזיר את הנפח שאבד. אולם, עם השנים הסתבר כי מתן מסיבי של קריסטלואידים עלול לסכן את הפצוע ואף לגרום למותו, עקב החמרת חמצת, הפרעת קרישה והיפותרמיה (ראה פירוט בפרק המלא). לאור זאת פותחה בשנים האחרונות תורת החייאת בקרת נזקים, או Damage Control Resuscitation.

#### עקרונות התורה

1.  **השגת שליטה על מקור הדימום במהירות האפשרית** - ע"י הפעלת לחץ ישיר/ עקיף בשטח או ע"י הגעה מהירה לחדר ניתוח.
2.  **Permissive Hypotension** - כדי להימנע מתופעת הלוואי של עודף נוזלים, נחזיר לפצוע רק את הכמות הדרושה לשימור נפח דם מינימלי. יעדי ההחייאה יהיו בראש ובראשונה לחץ דם סיסטולי של 90 מ"מ כספית ומצב הכרה תקין (בפצועים שלא סובלים במקביל מפגיעת ראש ).
3.  מוצרי דם כעדיפות ראשונה ומובילה מול מתן קריסטלואידים שינתנו רק במקרה ואין יכולת לערות מוצרי דם מאחר והפצוע איבד דם, נעדיף להחזיר לו דם; הנוזל המועדף הינו **דם מלא** ולאחר מכן ע"פ הסדר הבא:

-   כדוריות דם אדומות ופלזמה ביחס של 1:1.
-   פלזמה מיובשת
-   קריסטלואידים -- יינתנו רק כאשר צפי ההגעה של צוות עם מוצרי דם הינו מעל ל 15 דקות.

4.  כדי להימנע מחשיפה מיותרת למוצרי דם, יעדי ההחייאה יהיו גם כאן: לחץ דם סיסטולי של 90 מ"מ כספית ומצב הכרה תקין (בפצועים שלא סובלים מפגיעת ראש במקביל).
5.  **תמיכה במערכת הקרישה**- למשל ע"י תרופות דוגמת הקסאקפרון.
6.  **שמירה על חום גוף הפצוע** - לרבות חימום פעיל, למניעת תופעות הלוואי הקשורות בהיפותרמיה.

### פרוטוקול החייאת בקרת נזקים בשדה בפצוע המדמם

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה של הפרוטוקול

### ביאור הפורטוקול

1.  הטיפול הראשון אותו יש להעניק לפצוע הוא עצירת דימום. 2. מתן הנפח מבוצע כחלק מסקר ההחייאה בזמן הכנה לפינוי או במהלך הפינוי. בכל מקרה, **אין לעכב פינוי הפצוע לצורך מתן נוזל החייאה או תרופה בעירוי**. אם נדרש, יש לבצע את הפעולות תוך כדי פינוי.
2.  תן 1 גרם הקסאקפרון לכל פצוע עם פגיעה חודרת בגו או באזור מעבר (צוואר, בית שחי, עכוז, מפשעה) ללא קשר למדדיו, כל עוד המנה ניתנת תוך 3 שעות מרגע הפציעה. אין לטפל בפצוע בהקסאקפרון במידה וחלפו יותר מ-3 שעות מרגע פציעתו.
3.  מתן **נוזל החייאה מכל סוג שהוא (קריסטלואידים, FDP, דם) יהיה ככלל לפצועים בהלם דימומי (המורגי) עמוק**, כלומר פצועים העונים על אחד מהקריטריונים הבאים:

-   לחץ דם סיסטולי הנמוך מ-90 מ"מ כספית.
-   דופק רדיאלי שאינו נימוש בנוכחות ל"ד שאינו ניתן למדידה
-   שינוי ברמת ההכרה **בפצוע טראומה** שאינו על רקע חבלת ראש או טיפול תרופתי.

5.  **בצה"ל, נוזל ההחייאה המועדף לשימוש בפצוע בהלם דימומי עמוק הוא דם מלא, במרבית יחידות השדה הנוזל הקיים הוא FDP.** רק במידה ומנת FDP אינה זמינה לשימוש, (זמן הגעה של צוות עם מנת פלזמה הינו מעל ל 15 דקות -- מקרה שאינו סביר בשגרה), יש לטפל בפצוע במנה של 500 מ"ל הארטמן עד להגעת הפלסמה.
6.  **בילדים** נטפל בהקסאקפרון במינון של 15 מ"ג לקילו עד גיל 12 ומגיל 12 "מנת מבוגר" של 1 גר'. דם או פלסמה ינתנו בנפח של 20 מ"ל לק"ג עד למשקל של כעשרים ק"ג ( השקול לכמנה אחת של 400 מ"ל דם או פלסמה).
7.  פגיעת ראש מבודדת, שאינה מלווה בהלם דימומי עמוק, אינה אינדיקציה למתן הקסאקפרון או נוזלי החייאה.
8.  **מתן נפח קודם תמיד למתן הקסאקפרון!** רק במידה והדם טרם זמין או בתהליכי הכנה נתחיל עם טיפול ב TXA עד להגעת הדם/ פלסמה.
9.  **בכל מקרה, אין לתת מנות נפח (כולל FDP) ברצף - יש לעצור ולהעריך מחדש את מצב הפצוע בתום כל מנת נפח.** נטפל בפצוע במנות נוספות רק במידה והפצוע עדיין בהלם דימומי עמוק .
10. במידה והפצוע עדיין בהלם דימומי עמוק לאחר מתן מנת FDP ובמידה ומנת PRBC זמינה, יש להמשיך את ההחייאה ביחס של 1:1 בין מנות ה-FDP למנות ה- PRBC. 11. **בכל שימוש במוצר דם (FDP או PRBC) יש לנטר את הפצוע מחשש להתפתחות תופעות לוואי חריפות**, בעיקר אחר תסמינים כדוגמת גרד, נפיחות, צמרמורות וכאבי חזה/גב. במידה ותסמינים אלו מופיעים, יש לעצור את עירוי מוצר הדם באופן מיידי, להחליפו במנת 500 מ"ל תמיסת הארטמן ולתעד את המקרה בטופס 101 ( פירוט על תגובות למתן דם בנספח ב').
11. במידה והפצוע התאושש לאחר הטיפול ואין סימני הלם דימומי עמוק, נעצור את החייאת הנוזלים. אין צורך לחבר את הפצוע לעירוי לצורך שמירה על ווריד פתוח בלבד, מומלץ לשטוף ב-10 מ"ל של סליין בלבד. יש להמשיך ולהעריך מחדש את מצבו של הפצוע בכל 10 דקות מחשש להידרדרות מחודשת.
12. **שמירה על חום גופו של הפצוע היא חלק בלתי נפרד מההחייאה** והיא תתבצע ע"י שימוש באמצעים פסיביים (שמיכות) או אקטיביים (שקיות חימום) ע"פ שיקול דעתו של המטפל הבכיר.
13. בשלב הטיפול הראשוני נפגע כוויות יטופל בפלסמה כנוזל הבחירה במצב של הלם עמוק. חשוב לזכור שפעמים רבות נפגע עם כוויות משמעותיות יהיה עם פציעות נוספות שעשויות להיות הסיבה להלם העמוק.
14. מסקר שערך חיל הרפואה בקרב 531 מטפלים בכירים בסדיר ובמילואים עלה כי הסיבה העיקרית למתן עודף של נוזלים היא העובדה שמטפלים בכירים חשים כי עליהם להעניק לו טיפול כלשהו, גם אם הוא אינו זקוק לטיפול. **נוזלי החייאה הם תרופה ככל התרופות! לכן יש להשתמש בהם בהתאם לאינדיקציות בלבד**, לא בחוסר ולא בעודף.
15. נזכיר כי אין מקום לשימוש במושגים יציב/ לא יציב במתאר טרום בית חולים. יש לדווח על מדדים מדויקים ועל פי הם להחליט על המשך הטיפול. דימום והלם המורגי הם מצבים מתמשכים אשר לרוב מקבלים טיפול דפיניטיבי רק בבית החולים לכן ההסתמכות על מס' מדידות מוגבלות בטרום בית חולים להערכת 'יציבות' אינו מתאים ויש בו בכדי להטעות את המטפל והדרג הפיקודי. במקום, נכון לתאר את מצב הפצוע כ 'תקין המודינמית' או כ'מצוי בשוק עמוק או לא' אך לא להשתמש במושג יציב/ לא יציב.

\#### סיכום כאשר החייאת בקרת הנזקים מתבצעת במתאר טרום בית חולים, בו אופציות טיפוליות רבות אינן זמינות, היא מכונה החייאת בקרת נזקים בשדה, או Remote Damage Control Resuscitation (R-DCR). בפרק פורטו עקרונות ה- R-DCR, הקריטריונים לטיפול, תכונותיהם של נוזלי ההחייאה השונים, ההיגיון מאחורי השימוש בהם וכן פרוטוקול אחוד לטיפול בפצוע המדמם. פרוטוקול זה מחייב את כלל המטפלים בצה"ל -- חובשים ומטפלים בכירים כאחד.

\### נספח א' \#### תהליך ביצוע רקונסטיטוציה בשטח ל FDP \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*כל נספח א' מכל תמונות של התכשיר ואופן השימוש 1. **תיאור התכשיר:** 1. אמפולת פלסמה מיובשת בהקפאה מסוג AB לאינפוזיה: בקבוק זכוכית בנפח של 200 מ"ל הכולל פקק גומי לחיבור מערכת לעירוי. הבקבוק מכיל אבקה גבישית של פלסמה מיובשת בצבע כתום. על הבקבוק רשום: LyoPlas N-w AB. 2. שקית עירוי המכילה 200 מ"ל מים סטריליים להזרקה: יש לה פקק מיוחד (לואר) לחיבור צינור מתאם. על השקית רשום: Aqua ad iniectabilia 200ml. 3. צינור מתאם להחדרת המים להזרקה משקית העירוי לתוך בקבוק הפלסמה המיובשת. על הצינור רשום: Uberleitungssystem. מרכיבי הצינור המתאם: \* פקק הברגה לואר עם מכסה פלסטיק. \* תופסנית פלסטיק לעצירת זרימת הנוזל בצינור. \* דוקרן להחדרה לבקבוק הפלסמה המיובשת לעירוי. \* על גבי הדוקרן -- פילטר לשחרור אויר לזרימה חופשית של הנוזל.

```         
שים לב – הפילטר מגיע פתוח ויש להשאירו **פתוח** לאפשר יציאת אויר בזמן החדרת הנוזל לבקבוק הפלסמה המיובשת.
```

2.  **הוראות שימוש:** הכנת התמיסה לשימוש אורכת כ-5 דקות. להלן שלבי הכנה ועירוי:
    1.  **שלב 1**: חיבור הצינור המתאם לשקית המים להזרקה:
        1.  סגור את תופסנית הפלסטיק שעל גבי הצינור המתאם.
        2.  **חבר את הצינור המתאם לשקית העירוי** בעזרת חיבור ההברגה (לואר). (שים לב שהמתאם מתברג עד הסוף, ולוחץ על הסגר הכחול ושהמים זורמים בתוך הצינור המתאם.
    2.  **שלב 2**: חיבור הצינור המתאם **לבקבוק הפלסמה**:
        1.  בצע חיטוי למכסה הגומי של בקבוק הפלסמה (בעזרת ספונג'טה).
        2.  חבר את הקצה השני של הצינור המתאם (הדוקרן) לתוך בקבוק הפלסמה.
        3.  וודא שמכסה פילטר האוויר פתוח.
    3.  **שלב 3**:הזרמת המים מהשקית לבקבוק:
        1.  הנח את שקית המים להזרקה מעל הבקבוק לאפשר בעזרת כוח הכבידה של המים לבקבוק.
        2.  פתח את תופסנית הפלסטיק והזרם את המים לתוך הבקבוק. שים לב -- הזרימה צריכה להיות חופשית. אין ללחוץ על השקית -- לחיצה על השקית תיצור קצף, שיסתום את פילטר האוויר והזרימה תעצר.
        3.  יש להזרים את כל המים להזרקה מהשקית לבקבוק.
        4.  לאחר סיום הזרמת המים יש לסגור את תופסנית הפלסטיק.
    4.  **שלב 4**: ערבב בעדינות על ידי סיבובים את בקבוק הפלסמה עד להמסת כל החלקיקים המוצקים. התמיסה מוכנה לשימוש כאשר אין חלקיקים נראים לעין. **שים לב**- אין לנער את התמיסה- על מנת שלא יווצר קצף.
    5.  **שלב 5**: העברת הפלסמה לשקית העירוי
        1.  העברת מדבקת הברקוד הגדולה מהבקבוקון לשקית העירוי.
        2.  יש להחזיק את הבקבוקון מעל שקית העירוי, לוודא שהתופסן פתוח ולתת לנוזל לזרום לתוך השקית.
        3.  בסיום העברת הנוזל יש ללחוץ קלות על השקית על מנת להוציא את האוויר מהשקית ולסגור את התופסן.
        4.  החדר מערכת לעירוי **עם פילטר** 170-230 מיקרון לשקית העירוי (סט לעירוי דם).
        5.  **יש להקפיד על סגירת הצינורית בה לא נעשה שימוש על מנת למנוע חדירת אוויר.**
        6.  חבר את העירוי לפצוע והחל בהזלפת הנוזל.
    6.  **שלב 6**: תיעוד:
        1.  על גבי בקבוק הפלסמה נותרו 2 מדבקות ברקוד עם מספר המנה.
        2.  יש להדביק מדבקה אחת על גבי כרטיס הפינוי (טופס 101) של המטופל.
3.  **הוראות אחסנה:**
    1.  את התכשיר יש לאחסן בטמפרטורה של 2 עד 25 מעלות צלזיוס.
    2.  אורך חיי מדף של התכשיר 15 חודשים מתאריך היצור.
    3.  על הבקבוק מופיע
        1.  תאריך היצור (Hergestellt am).
        2.  תאריך התפוגה (Verwendbar bis).
        3.  מספר מנת הדם ממנה הופק (Ch. --B). מספר מנת הדם מופיע בנוסף על גבי 3 מדבקות.
    4.  אין להשתמש בתכשיר אם תאריך התפוגה עבר.

### נספח ב' - מתן דם מלא בשדה, הנחיה למטפל הבכיר

1.  דם מלא הוא הנוזל המתאים ביותר להחייאת נפח של פצוע בשוק המורגי, בהשוואה לכל מוצר דם אחר וגם לשילובים ביניהם. הוא מספק בעת ובעונה אחת:
    1.  החזר של נפח תוך כלי
    2.  גורמי קרישה בדומה לפלסמה
    3.  יכולת נשיאת חמצן שמשפרת משמעותית את אספקת החמצן לרקמות.
2.  בשדה דם מלא מגיע בצורת Cold Stored Low-Titer O Whole Blood (CS-LTOWB), כלומר דם מלא (כדוריות, פלסמה וטסיות) שהופק מתורם יחיד בעל סוג דם O עם כייל נמוך של נוגדנים כנגד קבוצות אנטיגנים A ו- B, ונשמר בקירור.
3.  את הדם המלא יש לשמור בקירור במקרר ייעודי תקני עם בקרת טמפ' בעת כוננות, וביציאה לאירוע יש להעבירו לצידנית ייעודית שהוקפאה מבעוד מועד, ומאפשרת שמירה על המנות למשך עד 72 שעות. גם בה יהיה מדחום מינימום-מקסימום. טווח היעד של הטמפ', הן במקרר והן בצידנית, יהיה 2-8°c. מיד בחזרה לבסיס נקודת ההזנקה, במידה ולא עוברו 72 שעות מהעברת המנות לצידנית, יש להחזירן את המנות למקרר היעודי. במידה ועברו מעל 72 שעות יש להתייחס אליהן כפגות תוקף.
4.  מנות פגות תוקף ייאספו ויוחזרו לבנק הדם לצורך השמדה מבוקרת.
5.  שקית של מנת דם שניתנה לפצוע, בין אם במלואה או בחלקה, תפונה יחד עם הפצוע עד לביה"ח.
6.  האינדיקציות למתן דם מלא מחמירות יותר מאלו של מתן פלסמה בהתאם לפרק "החייאת בקרת נזקים בשדה (RDCR) בספר הטראומה והרפואה המבצעית" מבחינה זו שהן מחייבות ל"ד סיסטולי מתחת ל- 90 (לא ניתן להסתפק במדידת דופק בלבד)
7.  פרוטוקול מתן דם: \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה של הפרוטוקול
8.  סיכונים מרכזיים הקשורים במתן דם ועלולים להופיע באופן מידי ודרכי התמודדות בשדה:
    1.  **Febrile Non-Hemolytic Transfusion Reaction**- תופעה שכיחה יחסית שנגרמת כתוצאה מתגובה לתאי דם לבנים של התורם, מוגבלת בטבעה ומגיבה למורידי חום כדוגמת אקמול. מתבטאת בעליית חום של 1-2 מעלות, צמרמורות וכאב ראש אצל המטופל. במקרה כזה, יש ראשית לשלול גורמים אחרים, נדירים אך מסוכנים יותר, כמפורט מטה, ובכל מקרה לעצור את מתן הדם ולעבור לטיפול בפלסמה.
    2.  **Acute Hemolytic Transfusion Reaction**- תגובה המוליטית חריפה הנגרמת כתוצאה מ- Major Incompatibility של סוגי דם (A ו-B), ותוארה גם עבור קבוצות דם משניות במטופלים שנחשפו לעירויים בעברם. מדובר בתגובה מסכנת חיים עם שיעור תמותה גבוה (10%), שעולה ככל שמטופל מקבל כמות גדולה יותר של דם (20% עבור כמות של מעל 50 מ"ל). הביטוי כולל חום, ל"ד נמוך, ברונכוספאזם, אורטיקריה, חרדה, קוצר נשימה והסמקה. הטיפול כולל:
        1.  **עצירת מתן הדם וניתוק המנה מהמטופל** יש לפנות את המנה יחד עם המטופל להמשך בדיקות.
        2.  הרצת נוזלים -- 1-2 ליטר של Normal Saline, בנוסף לפלסמה לפי אינדיקציה. לצורך כך יש צורך לרוב בהשגת גישה ורידית\גרמית נוספת.
        3.  תמיכה נשימתית לפי הצורך.
        4.  במקרה של חשד לתגובה אנפילקטואידית (שהסתמנותה דומה מאד, ראה מטה) יש לתת טיפול בהתאם.
    3.  **Anaphylactoid/Anaphylactic Reaction** - תגובה אלרגית חריפה של מערכת החיסון של המטופל כנגד אנטיגנים בדם התורם -- במיוחד כנגד נוגדנים מסוג IgA. ההסתמנות דומה להסתמנות הרגילה של תגובה אנפילקטית, ודומה מאד גם לזו שלAHTR . לכן**הטיפול כולל את כלל מרכיבי הטיפול ב-AHTR ובנוסף:**
        1.  IM Adrenaline 0.5mg באופן מיידי. במידת הצורך ניתן לתת מנות חוזרות כל 5 דקות.
        2.  IV Solu-Medrol 125mg למניעת תגובת ריבאונד.
    4.  **Urticaria**- תגובה אלרגית מתונה המתבטאת בגרד ופריחה אדומה בתבנית Wheel and Flare. במידה ומופיעה פריחה כזו, יש לעצור את מתן המנה, ולשלול סימני תגובה אנפילקטואידית או AHTR (צמרמורות, רעד, ירידה חדה בלחץ הדם, קוצר נשימה פתאומי). במידה ונשללו יש לתת IV Solu-Medrol 125mg. המשך הטיפול בהלם יתבסס על מתן פלסמה.
    5.  **Hyperkalemia**- עלולה להתרחש כתוצאה מהמוליזה, בעיקר של מנות דם ישנות. אבחנה לפי א.ק.ג. במקרה של סימני היפרקלמיה בא.ק.ג (גלי T מחודדים, קומפלקס QRS מורחב, תבנית סינוסואידית). יש לעצור את המנה, לעבור לטיפול בפלסמה ולתת Calcium Gluconate 10% 10 ml.
9.  פרוטוקול תגובה למנת דם \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה של הפרוטוקול

#### **רשימת מקורות בספרות המקצועית:**

::: {dir="ltr"}
1.  Holcomb JB, McMullin NR, Pearse L, Caruso J, Wade CE, Oetjen-Gerdes L, et al. Causes of death in U.S. Special Operations Forces in the global war on terrorism: 2001-2004. Ann Surg. 2007;245(6):986-91.
2.  Kelly JF, Ritenour AE, McLaughlin DF, Bagg KA, Apodaca AN, Mallak CT, et al. Injury severity and causes of death from Operation Iraqi Freedom and Operation Enduring Freedom: 2003-2004 versus 2006. J Trauma. 2008;64(2 Suppl):S21-6; discussion S6-7.
3.  Eastridge BJ, Mabry RL, Seguin P, Cantrell J, Tops T, Uribe P, et al. Death on the battlefield (2001-2011): implications for the future of combat casualty care. J Trauma Acute Care Surg. 2012;73(6 Suppl 5):S431-7.
4.  איגרת טראומה - החייאת נוזלים.
5.  Bickell WH, Wall MJ, Jr., Pepe PE, Martin RR, Ginger VF, Allen MK, et al. Immediate versus delayed fluid resuscitation for hypotensive patients with penetrating torso injuries. The New England journal of medicine. 1994;331(17):1105-9.
6.  Rhee P. Shock, electrolytes, and fluid. In: Courtney M. Townsend J, MD, Courtney M. Townsend, Jr., MD, R. Daniel Beauchamp, MD, B. Mark Evers, MD, R. Daniel Beauchamp, MD, Kenneth L. Mattox, MD, B. Mark Evers, MD and Kenneth L. Mattox, MD, editor. Sabiston Textbook of Surgery. 19th ed: Elesevier; 2012. p. 94-5.
7.  Shires T, Coln D, Carrico J, Lightfoot S. FLUID THERAPY IN HEMORRHAGIC SHOCK. Arch Surg. 1964;88:688-93.
8.  Advanced Trauma Life Support. 7th ed: Chicago: American College of Surgeons; 2006.
9.  Perel P, Roberts I, Ker K. Colloids versus crystalloids for fluid resuscitation in critically ill patients. Cochrane Database Syst Rev. 2013;2:Cd000567.
10. Schierhout G, Roberts I. Fluid resuscitation with colloid or crystalloid solutions in critically ill patients: a systematic review of randomised trials. Bmj. 1998;316(7136):961-4.
11. Bulger EM, May S, Kerby JD, Emerson S, Stiell IG, Schreiber MA, et al. Out-of-hospital hypertonic resuscitation after traumatic hypovolemic shock: a randomized, placebo controlled trial. Ann Surg. 2011;253(3):431-41.
12. Kiraly LN, Differding JA, Enomoto TM, Sawai RS, Muller PJ, Diggs B, et al. Resuscitation with normal saline (NS) vs. lactated ringers (LR) modulates hypercoagulability and leads to increased blood loss in an uncontrolled hemorrhagic shock swine model. J Trauma. 2006;61(1):57-64; discussion -5.
13. Mikhail J. The trauma triad of death: hypothermia, acidosis, and coagulopathy. AACN clinical issues. 1999;10(1):85-94.
14. Nardi G, Agostini V, Rondinelli B, Russo E, Bastianini B, Bini G, et al. Trauma-induced coagulopathy: impact of the early coagulation support protocol on blood product consumption, mortality and costs. Critical care (London, England). 2015;19:83.
15. Moffatt SE. Hypothermia in trauma. Emergency medicine journal : EMJ. 2013;30(12):989-96.
16. Mitrophanov AY, Rosendaal FR, Reifman J. Mechanistic Modeling of the Effects of Acidosis on Thrombin Generation. Anesth Analg. 2015;121(2):278-88.
17. Cap A, Hunt BJ. The pathogenesis of traumatic coagulopathy. Anaesthesia. 2015;70 Suppl 1:96-101, e32-4.
18. Kaufman DC, Kitching AJ, Kellum JA. Acid-Base Balance. In: Hall JB, Schmidt GA, Kress JP, editors. Principles of Critical Care, 4e. New York, NY: McGraw-Hill Education; 2015.
19. Ross SW, Christmas AB, Fischer PE, Holway H, Walters AL, Seymour R, et al. Impact of common crystalloid solutions on resuscitation markers following Class I hemorrhage: A randomized control trial. J Trauma Acute Care Surg. 2015;79(5):732-40.
20. Rhee P, Wang D, Ruff P, Austin B, DeBraux S, Wolcott K, et al. Human neutrophil activation and increased adhesion by various resuscitation fluids. Critical care medicine. 2000;28(1):74-8.
21. Rhee P, Burris D, Kaufmann C, Pikoulis M, Austin B, Ling G, et al. Lactated Ringer's solution resuscitation causes neutrophil activation after hemorrhagic shock. J Trauma. 1998;44(2):313-9.
22. Robinson BR, Cotton BA, Pritts TA, Branson R, Holcomb JB, Muskat P, et al. Application of the Berlin definition in PROMMTT patients: the impact of resuscitation on the incidence of hypoxemia. J Trauma Acute Care Surg. 2013;75(1 Suppl 1):S61-7.
23. Kenneth L. Mattox EEM, David V. Feliciano. Trauma. 7th ed: McGraw-Hill Professional; 2012.
24. Tactical Combat Casualty Care Guidelines, 2 June 201417 June, 2015. Available from: https://www.jsomonline.org/TCCC.html.
25. Salomone JP PP, McSwain NE. PHTLS: Prehospital Trauma Life Support. 7th ed: St. Louis: Mosby; 2011.
26. Paul G. Barash BFC, Robert K. Stoelting, Michael Cahalan, M. Christine Stock. Clinical Anesthesia. 6th ed: Lippincot Williams & Wilkin; 2009.
27. Gonzalez EA, Moore FA, Holcomb JB, Miller CC, Kozar RA, Todd SR, et al. Fresh frozen plasma should be given earlier to patients requiring massive transfusion. J Trauma. 2007;62(1):112-9.
28. Borgman MA, Spinella PC, Perkins JG, Grathwohl KW, Repine T, Beekley AC, et al. The ratio of blood products transfused affects mortality in patients receiving massive transfusions at a combat support hospital. J Trauma. 2007;63(4):805-13.
29. Scope A, Farkash U, Lynn M, Abargel A, Eldad A. Mortality epidemiology in low-intensity warfare: Israel Defense Forces' experience. Injury. 2001;32(1):1-3.
30. Glassberg E, Nadler R, Gendler S, Abramovich A, Spinella PC, Gerhardt RT, et al. Freeze-dried plasma at the point of injury: from concept to doctrine. Shock. 2013;40(6):444-50.
31. French Lyophilised Plasma (Flyp) Brochure \[18/11/2015\]. Available from: http://www.defense.gouv.fr/content/download/194893/2151829/file/CTSA%20site%20internet%20PLYO.pdf.
32. Bux J, Dickhorner D, Scheel E. Quality of freeze-dried (lyophilized) quarantined single-donor plasma. Transfusion. 2013;53(12):3203-9.
33. Inaba K. Freeze-dried plasma. J Trauma. 2011;70(5 Suppl):S57-8.
34. Martinaud C, Ausset S, Deshayes AV, Cauet A, Demazeau N, Sailliol A. Use of freeze-dried plasma in French intensive care unit in Afghanistan. J Trauma. 2011;71(6):1761-4; discussion 4-5.
35. Glassberg E, Nadler R, Lipsky AM, Shina A, Dagan D, Kreiss Y. Moving forward with combat casualty care: the IDF-MC strategic force buildup plan "My Brother's Keeper". Isr Med Assoc J. 2014;16(8):469-74.
36. Freedman JE, Loscalzo J. Arterial and Venous Thrombosis. In: Kasper D, Fauci A, Hauser S, Longo D, Jameson JL, Loscalzo J, editors. Harrison's Principles of Internal Medicine, 19e. New York, NY: McGraw-Hill Education; 2015.
37. Maegele M, Schochl H, Cohen MJ. An update on the coagulopathy of trauma. Shock. 2014;41 Suppl 1:21-5.
38. Shakur H, Roberts I, Bautista R, Caballero J, Coats T, Dewan Y, et al. Effects of tranexamic acid on death, vascular occlusive events, and blood transfusion in trauma patients with significant haemorrhage (CRASH-2): a randomised, placebo-controlled trial. Lancet. 2010;376(9734):23-32.
39. Roberts I, Prieto-Merino D, Manno D. Mechanism of action of tranexamic acid in bleeding trauma patients: an exploratory analysis of data from the CRASH-2 trial. Critical care (London, England). 2014;18(6):685.
40. Morrison JJ, Dubose JJ, Rasmussen TE, Midwinter MJ. Military Application of Tranexamic Acid in Trauma Emergency Resuscitation (MATTERs) Study. Arch Surg. 2012;147(2):113-9.
41. Zehtabchi S, Abdel Baki SG, Falzon L, Nishijima DK. Tranexamic acid for traumatic brain injury: a systematic review and meta-analysis. Am J Emerg Med. 2014;32(12):1503-9.
42. Yutthakasemsunt S, Kittiwatanagul W, Piyavechvirat P, Thinkamrop B, Phuenpathom N, Lumbiganon P. Tranexamic acid for patients with traumatic brain injury: a randomized, double-blinded, placebo-controlled trial. BMC emergency medicine. 2013;13:20.
43. Meng ZH, Wolberg AS, Monroe DM, 3rd, Hoffman M. The effect of temperature and pH on the activity of factor VIIa: implications for the efficacy of high-dose factor VIIa in hypothermic and acidotic patients. J Trauma. 2003;55(5):886-91.
44. Bartfai T, Conti B. Fever. TheScientificWorldJournal. 2010;10:490-503.
45. Jurkovich GJ, Greiser WB, Luterman A, Curreri PW. Hypothermia in trauma victims: an ominous predictor of survival. J Trauma. 1987;27(9):1019-24.
46. Vymazal T. Massive hemorrhage management-a best evidence topic report. Therapeutics and clinical risk management. 2015;11:1107-11.
47. van der Meer PF, Cancelas JA, Cardigan R, Devine DV, Gulliksson H, Sparrow RL, et al. Evaluation of overnight hold of whole blood at room temperature before component processing: effect of red blood cell (RBC) additive solutions on in vitro RBC measures. Transfusion. 2011;51 Suppl 1:15s-24s.
48. Chandler MH, Roberts M, Sawyer M, Myers G. The US military experience with fresh whole blood during the conflicts in Iraq and Afghanistan. Seminars in cardiothoracic and vascular anesthesia. 2012;16(3):153-9.
49. Garcia Hejl C, Martinaud C, Macarez R, Sill J, Le Golvan A, Dulou R, et al. The implementation of a multinational "walking blood bank" in a combat zone: The experience of a health service team deployed to a medical treatment facility in Afghanistan. J Trauma Acute Care Surg. 2015;78(5):949-54.
50. Strandenes G, De Pasquale M, Cap AP, Hervig TA, Kristoffersen EK, Hickey M, et al. Emergency whole-blood use in the field: a simplified protocol for collection and transfusion. Shock. 2014;41 Suppl 1:76-83.
51. Murdock AD, Berseus O, Hervig T, Strandenes G, Lunde TH. Whole blood: the future of traumatic hemorrhagic shock resuscitation. Shock. 2014;41 Suppl 1:62-9.
52. Nair PM, Pidcoke HF, Cap AP, Ramasubramanian AK. Effect of cold storage on shear-induced platelet aggregation and clot strength. J Trauma Acute Care Surg. 2014;77(3 Suppl 2):S88-93.
:::
