# סקר החייאה והכנה לפינוי

## עיקרי העדכונים

14/05/2021: כתיבת הפרק תיאור מרכיבי ההכנה לפינוי GCS ובדיקת אישונים הועברו לסקר ההחייאה בשלב מילוי טופס 101

### הקדמה ורקע

הטיפול בפצוע הבודד כולל עבודה על פי שרשרת פעולות סדורה בהתאם לסכמה האחודה. בשלב הראשון בסכמה, בסקר הראשוני - בטיחות המטפל והמטופל מאובטחים, נעשות פעולות מצילות חיים מיידיות על פי התוויה (עצירת דימומים, פתיחת נתיב אוויר, הנשמה באמבו, ניקור חזה בוייגון ומתן חמצן), מבוצעת סקירה מהירה על פציעותיו ומצבו של הפצוע (הכרה, נשימות, מדדים חיוניים וכו'), נעשים פעולות להכנה ראשונית של הפצוע לפינוי וכן מועבר דיווח רפואי ואג"מי. במהלך הסקר הראשוני מתקבלות החלטות בנוגע לטיפולים מצילי החיים להם זקוק הפצוע. תכלית סקר ההחייאה **בהשלמת פעולות מצילות חיים והכנת הפצוע לפינוי** באופן המיטבי.

פרק זה ייתן דגשים לאופן העבודה בסקר ההחייאה. תנאי להתחלת סקר ההחייאה -- הסקר הראשוני הושלם והפצוע מועמס על אלונקה (במידה וזו קיימת). נזכור כי הסיבות המובילות למוות בר הצלה בסדר יורד הן דימומים, בעיות נתיב אוויר ובעיות בנשימה. בד בבד יש לזכור כי ככלל אצבע בעיה ב- A תהרוג לפני בעיה ב- B שתהרוג לפני בעיה ב- C, בוודאי לאחר שעצרנו דימומים "פורצים". יודגש כי הפעולות בסקר החייאה יכולות ומומלץ שיבוצעו במקביל, כאשר פעולות אשר לא דורשות את המטפל הבכיר יבוצעו על ידי הצוות המטפל המסייע.

### פרוטקול

הפעולות אשר יבוצעו (במידת הצורך) במהלך סקר ההחייאה: 1. המשך ניטור והערכה של הפצוע 2. השגת גישה ורידית 3. החייאת נוזלים/מוצרי דם -- בהתאם לכתוב בפרק "החייאת בקרת נזקים בשדה (RDCR)" 4. השגת נתיב אוויר דפיניטיבי -- בהתאם להתוויות בפרק "ניהול נתיב אוויר" 5. ניקוז חזה -- בהתאם להתוויות בפרק "הטיפול בפגיעות חזה בשדה" 6. קיבוע עמוד שדרה -- בהתאם לכתוב בפרק "פציעות עמוד שדרה וקיבוע צוואר" 7. קיבוע שבר בירך - בהתאם לכתוב בפרק "פציעות גפיים" 8. טיפול בכאב -- בהתאם לכתוב בפרק "טיפול בכאב" 9. השלמת טופס 101 10. בדיקת Glasgow Coma Scale 11. הערכה ראשונית לקיומה של תגובת דחק/קרב

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תמונה

### הכנה לפינוי

במהלך או בסיום הסקר הראשוני הפצוע צריך, עד כמה שניתן, להיות מועמס על אלונקה. פצוע קשור לאלונקה איננו בהכרח פצוע מוכן לפינוי. פינוי רפואי מהיר, חיוני לצמצום תמותה ונכות כתוצאה מטראומה. מרבית הפעולות אשר יתבצעו בסקר ההחייאה נכון שיבוצעו במהלך הפינוי עד כמה שניתן. עם זאת, על מנת לשפר את סיכויי ההישרדות של הפצוע, ישנן פעולות שיש לבצען טרם התחלת הפינוי. ההנחיות הפרטניות עבור המצבים השונים, יפורטו בפרקים בהמשך ספר זה. מכאן, טרם התחלת הפינוי יש לוודא כי: \* נתיב האוויר של המטופל פתוח ויש גישה אליו. \* פעולות מצילות חיים אשר נדרש לבצע טרם התחלת הפינוי הושלמו. \* ישנה אפשרות להשלים את יתר הפעולות מצילות החיים במהלך הפינוי (נוכחות מטפל וציוד מתאימים). \* יש אפשרות לנטר את המטופל בהתאם לנדרש במהלך הפינוי. \* הפצוע קשור לאלונקה ומכוסה. כמו כן עמוד השדרה מקובע במידה ויש התוויה לכך וישנה גישה לראש, צוואר, ידיים ובמידת הצורך לאיברים נוספים בהתאם לפציעות. \* פרוצדורות **מקובעות**. חבישות ושרכים מוצנעים. \* בטרם ביצוע שחלוף של המטופל בין צוותים מטפלים, יש לוודא השלמת 101.

### תיעוד רפואי

התיעוד הרפואי הינו מרכיב חשוב בטיפול בפצוע טראומה בכל הדרגים הטיפוליים. התיעוד כולל רישות של מאפייני הפציעה (מנגנון הפגיעה, אזורי הגוף שנפגעו וכד'), ממצאים בהערכת הפצוע (רמת הכרה, מדדים חיוניים וכד') וכן את הטיפול הרפואי שניתן (תרופות שניתנו, פרוצדורות שבוצעו וכד'). מספר מחקרים הוכיחו כי תיעוד רפואי חסר או לקוי, נמצא קשור לעלייה בתמותה ואף נמצא כי, ארגונים כדוגמת יחידות בצבא ארה"ב, אשר שיפרו את התיעוד הרפואי שלהם הפחיתו את שיעור המוות בר המניעה בקרב פצועיהם. יתרון נוסף של הטופס הוא בכך שהוא משמש כעזר קוגניטיבי (צ'קליסט), למשל בזמן מדידת GCS, אותה יש להשלים עד גמר מילוי הטופס).

### סיכום

סקר ההחייאה הוא השלב בו מתבצעים הטיפולים מצילי החיים הדחופים עליהם הוחלט במהלך הסקר הראשוני, ומהווה מעבר מ״החלטה למעשה״. הטיפול בשלב זה יהיה בהתאם להנחיות המפורטות בספר זה, תוך עיכוב מינימלי של הפינוי, שהוא לרוב המרכיב המהותי ביותר בהצלת חיי הפצוע. בשלב זה גם יתבצע התיעוד הרפואי, שהוא בעל חשיבות רבה לטיפול בפצוע עצמו.
