# בטיחות

## עיקרי העדכונים

2021-05-14:

-   כתיבת הפרק

**הקדמה ורקע**

**הנחות ייסוד**

**פרוטוקול טיפול תחת אש/ איום**

**ביאור הפרוטוקול**

-   **מענה באש**
-   **הבאת הפצוע למחסה**
-   **עצירת דימומים פורצים**
-   **העברת דיווח אג"מי**
-   **ביצוע פעולות בסיסיות לשמירת נתיב אוויר**
-   **המשך לחימה והשלמת המשימה תוך שאיפה להשגת זירת טיפול מאובטחת**
-   **טיפול סדור בשטח**
-   **פינוי**

## הקדמה ורקע

גורמים רבים משפיעים על הטיפול הרפואי בשדה הקרב וגורמים לו להיות שונה מהטיפול הרפואי הניתן במתאר האזרחי. הגורמים הבולטים הם: עוצמת האש של האויב, מגבלות טקטיות, פציעות השונות באופיין, תנאי שטח קשים, חושך, עקה נפשית ועוד. כל אלו משפיעים בצורה דרמטית על יכולת הטיפול הרפואי ובאופן ישיר על סיכויי הישרדות הפצועים. על מנת לספק את הטיפול המיטבי בסביבה מאוימת, על המטפל לשלב שיקולים מבצעיים לצד שיקולים רפואיים בטיפול. **שלושת העקרונות ברפואה קרבית**

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תרשים

חשוב לזכור, צוותי רפואה צבאים מטפלים לעתים קרובות בתנאים הדומים באופיים למתאר האזרחי, בו לא נשקפת סכנה ישירה לחיי המטפל (תאונות דרכים, התחשמלות, שריפה). גם במקרים אלו טרם תחילת הטיפול יש לשמור על מודעות סביבתית, לשמור על ביטחון הצוות המטפל ולהרחיק את הנפגע מהגורם המסכן. לאחר מכן יש להמשיך בסקר הראשוני, לתת טיפול הכרחי ומציל חיים ולפנות את הפצוע בהקדם האפשרי.

**מטרת פרק זה היא יצירת שפה משותפת ומתן קווים מנחים וכלים מעשים למתן טיפול נכון לפצועים בסביבה מאוימת.**

\## הנחות יסוד

1.  התפקיד החשוב ביותר של כוח לוחם בעת התקלות הוא נטרול האיום והשלמת המשימה. יחד עם זאת, בסיטואציות רבות פרק הזמן שבין נפילת הפצוע הראשון לבין השלמת המשימה ואף נטרול האיום יכול להמשך דקות ארוכות ואף שעות, מה שמצריך טיפול במקביל להמשך הלחימה.
2.  השלב הראשון בסכמת הטיפול הינו שלב הSafety. בלחימה **הנחת המוצא היא שקיים איום יחסי** ולכן השלב הזה מקבל משמעות אחרת שתכליתו צמצום האיום וניהול הסיכון ככל הניתן. **יכולות המענה הרפואי עלולות להיות מוגבלות לאור האיום** ועל המטפלים לחתור למציאת האיזון והתנאים הטובים ביותר לטיפול במסגרת הסיטואציה המבצעית.
3.  מנגנון הפציעה העיקרי בטראומה בשדה הקרב הינו פציעות חודרות בדגש על פציעות כתוצאה מפיצוץ (מטענים, רימונים וכו') ופציעות ירי. פציעות בגפיים ובאזורי מעבר שכיחות מאוד ומהוות מעל 50% מכלל הפציעות. דימום מהגפיים או אזורי המעבר הניתן לעצירה בלחיצה (חסם עורקים/packing) מהווה כ-30% מגורמי המוות בר ההצלה.
4.  **שלושת שלבי הטיפול במתאר מאוים - טיפול תחת אש, טיפול סדור בשטח, טיפול בפינוי**. הטיפול הרפואי בפצוע בלחימה משלב שיקולים מבצעיים לצד שיקולים רפואיים, כאשר לעוצמת האיום והצורך בהשלמת המשימה השפעה ישירה על יכולת המענה הרפואי. במהלך חילופי אש מירב המאמצים יופעלו על מנת להשיג עליונות באש ולנטרל את האיום. ככל שהאיום קטן, ניתן להעלות את הדגש על מתן טיפול רפואי איכותי לפצוע ופינויו.
5.  במתאר צבאי, כ 90% מהפצועים מתים טרם ההגעה למרכז רפואי בעל יכולות כירורגיות, מתוכם כ90% בטווח של שעה מהפציעה. **לפעולות הראשונות מרגע הפציעה ישנה השפעה מכרעת על סיכויי הפצוע לשרוד** וכך גורלו של הפצוע נמצא פעמים רבות בידיים של האדם הראשון שייגש אליו. מטפל זה נקרא המגיב הראשון, לרוב יהיה זה לוחם בעל הכשרת מח"צ בכוח. כתפיסה, המגיב הראשון יהיה במידת האפשר הפצוע עצמו.

## פרוטוקול טיפול תחת אש/ איום

\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*תרשים

## ביאור הפרוטוקול

1.  **מענה באש**

**המענה הטוב ביותר במהלך לחימה הוא השגת עליונות באש ונטרול האיום.** ריתוק אש האויב יאפשר את השלמת המשימה, ימזער את הסיכון לפצועים נוספים ולפגיעה נוספת בפצועים הנוכחיים. כמו כן, בשלב זה הגורם המסכן ביותר את חיי הפצוע ואת הכוח הוא אש עוינת.

יש להכריז על נפגע בכוח ולתת פכט"ת-- פנייה, כיוון, טווח ותיאור שיאפשר לדייק את האש לעבר האיום. בו בזמן, יש להשיב באש ולתפוס מחסה, תוך חתירה להשגת עליונות באש. כל הכוח נדרש להשתתף בשלב הזה, כולל הפצוע במידה והוא כשיר לכך. אי לכך, יש להנחות את הפצוע להישאר מעורב בלחימה במידה והפציעה מאפשרת זאת. המשך הטיפול בפצוע ומספר הפצועים תלוי בהצלחת שלב זה.

במידת האפשר, יש להעלות דיווח אג"מי בהקדם. **מטרת הדיווח בשלב זה היא מתן תמונת מצב אג"מית למפקד הבכיר בזירה לצורך ניהול הלחימה ולא תמונת מצב של הפצועים.** דיווח יכלול פניה, הזדהות, מה קרה מבחינה מבצעית (התקלות, מטען, צלף), מיקום, כמות פצועים ודרישה לפינוי.

2.  **הבאת הפצוע למחסה**

תפיסת מחסה על ידי הנפגע עצמו תאפשר התמקדות מקסימלית בנטרול האיום וניהול לחימה לצד מניעת הצורך בחילוץ וחשיפת לוחמים נוספים לאיום. במידה והנפגע מזהה אויב בעין מטווח קרוב, השבה באש תהיה הפעולה החשובה ביותר להצלת חייו.

יש להנחות את הנפגע לתפוס מחסה, לטפל בעצמו ולהשיב באש. במידה והפצוע לא מסוגל לתפוס מחסה בעצמו והסיטואציה המבצעית מאפשרת זאת, גרור אותו/ תכנן ובצע תוכנית חילוץ חפוזה. יש לזכור שחילוץ נפגע משטח השמדה הינה פעולה שמטרתה הצלת חיים אך בו זמנית היא מעמידה בסיכון ישיר לוחמים אחרים. יש לתכנן את החילוץ תחת המחסה המיטבי שניתן להשיג ולבצעו במהירות האפשרית, תוך התחשבות באיום, מיקום המחסה, מיקום הפצוע ומשקלו. שיטת הגרירה המהירה ביותר היא גרירה בצמד במקביל לציר האורך של הפצוע כשפני המחלצים לכיוון התנועה. אין לנסות לשמור על עמוד השדרה של הנפגע במהלך החילוץ. במהלך חילופי אש ונפילת פצוע בשטח השמדה בפרט, הגורם מסכן החיים המשמעותי ביותר הינו אש האויב, הרבה יותר מאשר החמרה של פציעת עמ"ש. במידה והפצוע לא זז, לא מגיב ולא מראה סימני חיים מרגע הפציעה יש לקחת זאת בחשבון למול הסיכון בחילוץ/יציאה לחילוץ תחת אש, כיוון שייתכן ומוצדק להמתין לעליונות משמעותית יותר באש. יש לחלץ נפגעים מרכבים ובניינים בוערים/קורסים גם במחיר של אי שמירת עמ"ש או כל פעולה למעט עצירת דימום פורץ.

**לפני יציאה לחילוץ יש לשלב תמיד מכת אש. אין לצאת לחילוץ ללא השגת עליונות באש.** משיקולי אבטחה ומהירות החילוץ, קיימת עדיפות לחיפוי סטטי מאשר אבטחה דינאמית על ידי המחלצים עצמם. במידה והפצוע מחוסר הכרה/ הכרה מעורפלת/ לא מסוגל לטפל בעצמו - נצור את נשקו טרם החילוץ.

3.  **עצירת דימומים פורצים**

יש לעצור דימומים חיצוניים פורצים מהגפיים ואזורי המעבר ע"י ח"ע CAT או Packing בהתאם. בדימום פרוקסימלי שלא נעצר על ידי packing, נבצע נקודת לחיצה (במפשעה, בצוואר או תת-בריחית). אם הפצוע מסוגל, ננחה אותו לטפל בעצמו.

**תחת אש, CAT יונח על המדים, בראש הגפה, פרוקסימאלית** ככל הניתן (ויומר או ימוקם דיסטאלית יותר בשלבי הטיפול הבאים במידת האפשר). לא ניתן לבצע זיהוי אמין של מקור הדימום בטיפול תחת אש, ויש סכנה לפספס מקור דמם נוסף. מיקום הנחת ה-CAT בראש גפה מונע פספוס של מקור דימום שניתן לעצירה. יש לקחת בחשבון ש-Packing הינה פעולה שדורשת יותר זמן באופן יחסי מהנחת חסם עורקים ומבוצעת רק על ידי מטפל בעל הכשרה רפואית פורמלית. לכן, פעולה זו תבוצע תחת אש רק במידה והתנאים המבצעיים מאפשרים זאת (עליונות באש, מחסה מתאים וכו').

*אופן הנחת ח"ע CAT בטיפול תחת אש:* 1. **התרשמות מהירה מדימומים** מהגפיים בהסתכלות, מישוש והפיכת הפצוע. 2. שליפת CAT **מווסט הפצוע**. במידה ולא מוצאים את CAT הפצוע תוך שניות ספורות יש לעבור לשימוש בCAT של המטפל. 3. וידוא היעדר חפצים בכיסים וניתוק פק"לי ירך.\
4. הנחת חסם העורקים CAT **על המדים בראש הגפה** (פרוקסימלית ככל הניתן). 5. מתיחה בחוזקה והידוק של רצועת הסקוטש מסביב לגפה. 6. הרמה וסיבוב של המקל **חזק ככל הניתן**. 7. קיבוע המקל בגשר. 8. ליפוף הרצועה הנותרת מסביב לגפה ובתוך הגשר ככל הניתן 9. אבטחת המקל והרצועה ע"י רצועת האבטוח הלבנה/אפורה על הגשר. 10. וידוא כי נעצר הדימום. הוידוא בשלב הזה (S) כולל וידוא ויזואלי, בהמשך במהלך הטיפול הסדור (בשלב ה-C) יבוצע וידוא על ידי מדידת דופק. במידה והח"ע הראשון כשל בעצירת הדימום יש לבצע הערכה מהירה לכשלים המרכזיים האפשריים, ולאחר שלילתם להניח ח"ע נוסף צמוד לראשון.

**אין לרשום את שעת הנחת הCAT או את שם המטפל תחת אש.** בשלבים הבאים של הטיפול יתבצע הרישום ותישקל המרה. יש להצמיד לפצוע לוחם לצורך אבטחה וטיפול ראשוני במידת הצורך.

**סיבות נפוצות לכישלון ושגיאות בהנחת CAT** - אי שימוש ב-CAT בזיהוי דימום מהגפיים בטיפול תחת אש - מתיחה חלשה מידי של הרצועה - הנחה על חפצים בכיסים - מקור דימום פרוקסימלי לנק' ההנחה - סיבוב חלש מידי של המקל. חשוב לציין כי במידה והפצוע בהלם עמוק, עם ל"ד נמוך, יספיק לחץ חלש יחסית כדי לעצור את הדימום, אולם לאחר טיפול בהלם ועליה של לחץ הדם יתחדש הדימום במידה והלחץ שהופעל אינו מספיק. - קיבוע לא טוב של הרצועה ע"י רצועת האבטוח הלבנה/ אפורה. - ביצוע נקודת לחיצה עם הברך במפשעה במהלך הנחת CAT ברגל. פעולה זו אינה מביאה תועלת משמעותית, מעכבת את הנחת ה- CAT ומפריעה לה.

4.  **העברת דיווח אג"מי**

הדיווח האג"מי חיוני על מנת לקבל תגבורת, להשיג שליטה באירוע ולדרוש אמצעי פינוי עבור הפצוע. כאמור, הדיווח בשלב זה הינו אג"מי. מעבר לפרטים שדווחו מעלה, במידה ובשלב זה כבר ידוע שמדובר בפצוע דחוף לפינוי יש לכלול את המידע הזה בדיווח.

5.  **ביצוע פעולות בסיסיות לשמירת נתיב אוויר**

    1.  ניהול נתיב אוויר מתקדם יידחה ככלל לשלב הטיפול הסדור בשטח.
    2.  פצוע בהכרה -- יש לאפשר לפצוע להישאר בתנוחה הנוחה לו/להושיב ולהשעין קדימה.
    3.  פצוע מחוסר הכרה- יושכב על הצד (תנוחת חש"י). תנוחה זו פותחת את נתיב האוויר, מנתבת את ההפרשות מחוצה לנתיב האוויר והיא פשוטה ליישום גם על ידי מח"צ.

6.  **המשך לחימה והשלמת המשימה תוך שאיפה להשגת זירת טיפול מאובטחת** -- במידה וניתן להשיג זירת טיפול מאובטחת, יש לעשות זאת. במידה ולא יש לשאוף להעביר את הפצוע לזירת טיפול מאובטחת שם יתאפשר המשך הטיפול הסדור.

7.  **טיפול סדור בשטח** -- בפצוע הבודד בהתאם לפרק "הסכמה -- הטיפול בפצוע טראומה בשדה". באר"ן בהתאם לפרק "הטיפול באירוע רב נפגעים".

8.  **פינוי**
