# סכמת הטיפול בפצוע

## הקדמה ורקע

הטיפול בנפגעי טראומה, בייחוד במתאר טרום בית החולים בנקודת הפציעה, דורש ביצוע הערכה ממוקדת וביצוע פעולות מהירות על מנת להציל פצועים בני הצלה. על מנת לפשט, לטייב ולזרז את תהליך קבלת ההחלטות והטיפול, מערכות טראומה בעולם יצרו פרוטוקולים סדורים המהווים מנחה עבור המטפלים, בוודאי עבור מטפלים מעוטי ניסיון. דוגמאות לפרוטוקולים בולטים שכאלו בעולם הם ה- **ATLS (Advanced Trauma Life Support)** כמנחה לטיפול בטראומה בבית החולים, ה-**PHTLS (Prehospital Trauma Life Support)** למתאר הטראומה האזרחי טרום-בית חולים, וכן ה **TCCC (Tactical Combat Casualty Care)** שהן ההנחיות בצבאות ארה"ב לטיפול בנפגעי טראומה תחת אש, בשדה הקרב ובמהלך הפינוי. בצה"ל, המטפלים נדרשים לטפל בטראומה הן בשדה הקרב והן במתארים אזרחיים. כל אחד מהפרוטוקולים נותן מענה לתרחישים במאפיינים להם הוגדר -- צבאי מול אזרחי, מחלות מול טראומה, זמני פינוי קצרים מול ארוכים, יכולות בכל דרג ועוד. עצם השונות בין הפרוטוקולים הללו לפרוטוקולים הקיימים בספר זה נובעת מהצורך להתאים את הטיפול בפצוע לתרחישים בהם צפויים להיתקל המטפלים בצה"ל בשגרה ובחירום, להכשרתם ולסביבת הפעולה (לדוגמה קרבה יחסית של מרכזי טראומה **LEVEL 1**). הפרוטוקולים בספר הנוכחי נכתבו לאחר סקירת הפרוטוקולים המקבילים, עיון בספרות המקצועית והתייעצות עם מומחים בתחומים הרלוונטיים.

סכמת הטיפול בפצוע הינה סכמה אחודה לכלל המטפלים ומתווה למטפל שרשרת פעולות אותן יש לבצע בהתאם לשלב בטיפול ובהתאם להכשרת המטפל. כל זאת תחת העיקרון המנחה -- מה שהורג קודם יזוהה ויטופל קודם. ככל שמתאפשר, נכון לבצע את השלבים במקביל ע"י הצוות המטפל. הסכמה מורכבת משלושה סבבים -- ראשוני, החייאה ושניוני.

::: callout-important
## חשוב!

סכמת הטיפול זהה לכלל המטפלים הבכירים ומותאמת לעיקרון מרכזי - מה שהורג ראשון, יזוהה ויטופל ראשון.
:::

## הסכמה האחודה לטיפול בפצוע בודד

+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| S           | -   בטיחות המטפל והמטופל -- הרחקת הפצוע מאיום                                                                                                                                               |
|             |                                                                                                                                                                                             |
|             | -   התרשמות מזירת האירוע -- סיפור המקרה, מנגנון הפציעה, בחינה ויזואלית                                                                                                                      |
|             |                                                                                                                                                                                             |
|             | -   עצירת דימומים פורצים                                                                                                                                                                    |
|             |                                                                                                                                                                                             |
|             | -   דיווח ראשוני לרמה ממונה                                                                                                                                                                 |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| A           | -   בדיקת הכרה A.V.P.U                                                                                                                                                                      |
|             |                                                                                                                                                                                             |
|             | -   התרשמות מדרכי האוויר                                                                                                                                                                    |
|             |                                                                                                                                                                                             |
|             | -   סילוק הפרשות במידת הצורך                                                                                                                                                                |
|             |                                                                                                                                                                                             |
|             | -   במידת הצורך: הסרת קסדה                                                                                                                                                                  |
|             |                                                                                                                                                                                             |
|             | -   בפצוע שאינו מגיב לכאב - ביצוע HT והחדרת AW                                                                                                                                              |
|             |                                                                                                                                                                                             |
|             | -   בחשד לפגיעה בעמש"צ - שמירה על עמש"צ וביצוע JT                                                                                                                                           |
|             |                                                                                                                                                                                             |
|             | -   התרשמות מאזור הצוואר - המטומה צווארית, סימני חריכה וכו'                                                                                                                                 |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| B           | -   חשיפת בית החזה - התרשמות מחבלות קהות/חודרות והתפשטות דו צדדית (מישוש ו / או האזנה)                                                                                                      |
|             |                                                                                                                                                                                             |
|             | -   הערכת נשימה כמותית -- 30 שניות ואיכותית (סימני מצוקה)                                                                                                                                   |
|             |                                                                                                                                                                                             |
|             | -   ניטור רוויון חמצן (סטורציה) כמותי                                                                                                                                                       |
|             |                                                                                                                                                                                             |
|             | -   העשרה בחמצן                                                                                                                                                                             |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| C           | -   חיפוש אחר דימומים באזורים נסתרים - עורף, בתי שחי, גב, גפיים, עכוז ומפשעות                                                                                                               |
|             |                                                                                                                                                                                             |
|             | -   עצירת דימום- כולל חבישה המוסטטית (Packing) וחבישות לחץ                                                                                                                                  |
|             |                                                                                                                                                                                             |
|             | -   בדיקת דופק כמותי - ע"י מד רוויון חמצן ובהיעדרו ידנית 15 שניות                                                                                                                           |
|             |                                                                                                                                                                                             |
|             | -   בדיקת לחץ דם כמותית                                                                                                                                                                     |
|             |                                                                                                                                                                                             |
|             | -   מט"ב: בחשד לחזה אוויר בלחץ, בצע ניקור חזה מיידי והיכון למתן מוצרי דם                                                                                                                    |
|             |                                                                                                                                                                                             |
|             | -   התרשמות בהסתכלות מסימני חבלה בבטן ובאגן                                                                                                                                                 |
|             |                                                                                                                                                                                             |
|             | -   העברת דיווח ובעבודת צוות -- תיעוד בטופס 101                                                                                                                                             |
|             |                                                                                                                                                                                             |
|             | -   במידה והפינוי זמין מיד לאחר שלב זה - יש להשלים את יתר שלבי הסכמה במהלך הפינוי                                                                                                           |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| D           | -   הערכת מצב הכרה חוזרת לפי A.V.P.U                                                                                                                                                        |
|             |                                                                                                                                                                                             |
|             | -   התרשמות מתנועות ידיים ורגליים                                                                                                                                                           |
|             |                                                                                                                                                                                             |
|             | -   הערכת כאב כמותית                                                                                                                                                                        |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| E           | -   השלמת הפשטה מלאה והפיכה                                                                                                                                                                 |
|             |                                                                                                                                                                                             |
|             | -   עצירת דימום במידה ומזוהה בשלב זה                                                                                                                                                        |
|             |                                                                                                                                                                                             |
|             | -   מניעת היפותרמיה - כיסוי והעמסת הפצוע לאלונקה (כריכת אגן במידת הצורך)                                                                                                                    |
|             |                                                                                                                                                                                             |
|             | -   סיכום הממצאים, הגדרת דחיפות הפינוי והתוכנית הטיפולית ודיווח                                                                                                                             |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| סקר החייאה  | -   ביצוע פעולות ומתן טיפול תרופתי על פי הממצאים בסקר הראשוני                                                                                                                               |
|             |                                                                                                                                                                                             |
|             | -   טיפול בכאב                                                                                                                                                                              |
|             |                                                                                                                                                                                             |
|             | -   השלמת טופס 101 במקביל לבדיקת GCS ובדיקת אישונים                                                                                                                                         |
|             |                                                                                                                                                                                             |
|             | -   הערכה ראשונית לקיומה של תגובת דחק/קרב                                                                                                                                                   |
|             |                                                                                                                                                                                             |
|             | -   ניטור רציף                                                                                                                                                                              |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| סקר שניוני  | -   בפצוע מונשם: Bite block, חיבור למנשם אוטומטי, כיוונונו ווידוא הנשמה תקינה, הכנת תרופות הרדמה להמשך.                                                                                     |
|             |                                                                                                                                                                                             |
|             | -   השלמת עירוי פריפרי שני לגיבוי.                                                                                                                                                          |
|             |                                                                                                                                                                                             |
|             | -   בדיקה גופנית מלאה מהקודקוד ועד לבהונות הרגליים -- טיפול בכל פציעה המזוהה בדרך (שטיפת פצעים, קיבוע שברים, חבישת כוויות וכיוצ"ב).                                                         |
|             |                                                                                                                                                                                             |
|             | -   הסרת חסמי עורקים במקרים בהם אין ולא היה דימום או פציעה, ושקילת המרה של חסמי עורקים במידה וניתן.                                                                                         |
|             |                                                                                                                                                                                             |
|             | -   מתן טיפול אנטיביוטי במידה ומדובר בפציעה חודרת.                                                                                                                                          |
|             |                                                                                                                                                                                             |
|             | -   בפצוע שקיבל הקסאקפרון -- במידה וחלפו 3 שעות יש לתת מנה נוספת.                                                                                                                           |
|             |                                                                                                                                                                                             |
|             | -   הכנס צנתר שתן (בסמכות רופא בלבד) בכל פצוע הלם, פצוע מחוסר\\מעורפל הכרה או אינדיקציה אחרת למעקב תפוקת שתן (פגיעת מעיכה, כוויות וכו') -- בהיעדר התוויית נגד - במידה וצפי הפינוי מעל לשעה. |
|             |                                                                                                                                                                                             |
|             | -   הכנס זונדה לניקוז הקיבה (בסמכות רופא בלבד) בפצוע מונשם -- דרך הפה בלבד, במידה וצפי הפינוי מעל לשעה.                                                                                     |
+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: סכמת הטיפול בפצוע בודד

## ביאור הסכמה

ביאור הפרוטוקול שלושת שלבי הסכמה הינם:

1.  הסקר הראשוני (Primary survey) - מטרתו הערכה מהירה של פציעותיו ומצבו של הפצוע ומתן מענה לבעיות מסכנות חיים בטווח המיידי לפי קדימויות הטיפול. שלב זה מכיל חמישה תתי שלבים:

    -   שלב ה -S , בטיחות המטפל והמטופל.

    -   שלב ה -- A: הערכת נתיב אוויר וביצוע פעולות מיידיות לפתיחתו.

    -   שלב ה -- B: הערכה של קיומה של פציעת חזה וכן התרשמות ממצבו הנשימתי של הפצוע.

    -   שלב ה -- C: הערכת מצבו ההמודינמי של הפצוע, עצירת דימומים והתערבות מיידית בחשד לחזה אוויר בלחץ המתבטא כהלם עמוק.

    -   שלב ה -- D: הערכה חוזרת של מצב ההכרה, סימנים נוירולוגיים גסים אחרים וכאב.

    -   שלב ה -- E: הפשטה מלאה, איתור פציעות נסתרות, מניעת היפותרמיה והעמסה לאלונקה.

2.  סקר ההחייאה (Resuscitation survey) -- תכליתו בהשלמת פעולות מצילות חיים והכנת הפצוע לפינוי באופן המיטבי, מפורט בפרק "סקר ההחייאה".

3.  הסקר השניוני (Secondary survey) -- ניטור רציף של הפצוע, מתן טיפול אחזקתי הולם וכן מתן מענה לבעיות שאינן מסכנות חיים בשלב המיידי. מפורט בפרק "הסקר השניוני".

## סיכום

פרק זה מציג את הרעיון המסדר הבסיסי בהערכה ובטיפול בפצוע על ידי כלל המטפלים בצה"ל. העקרון המוביל הוא ביצוע הפעולות על פי סדר ותיעדוף, תוך ביצוע מס' שלבים במקביל ככל הניתן, וזאת על מנת לצמצם ככל הניתן מוות בר הצלה. הפרקים בהמשך הספר מפרטים על מרכיבי הסכמה השונים שביצוע נכון שלהם, במסגרת הרעיון המסדר של הסכמה, מאפשר מניעה מיטבית של מוות בר-הצלה.
