# הסקר השניוני

## עיקרי העדכונים:
15/07/2021:

- כתיבת הפרק

## הקדמה ורקע
**מקומו של הפצוע הוא בבית החולים, מהר ככל האפשר.** כל עיכוב לא הכרחי של הפצוע בשטח מפחית את סיכוייו לשרוד. לחוליה הרפואית, לצוות הרפואי ולמחלקת הרפואה הגדודית לא קיימת יכולת להשהות פצוע. התנאים בסביבה מאוימת, תחת אילוצים מבצעיים, ללא יכולות ניטור מתקדמות, ללא רופאים מומחים מכלל התחומים הנדרשים, ללא צוות סיעודי, ללא יכולות הדמיה ובדיקות מעבדה, עם ציוד מוגבל, ללא אפשרות לסטריליות, וללא חדר ניתוח, אינם מאפשרים טיפול מיטבי בפצוע. הטיפול בסביבה זו מסכן את הפצוע ואת הכח – ולכן יש לחתור בכל שלב לפינוי המיידי של הפצוע ובעדיפות ליעד הדפניטיבי – בית חולים.

**ההשפעה של ההנחיות המופיעות בפרק זה על תוצאי הפצוע (Outcome) מוגבלת, בוודאי בהשוואה לפעולות המבוצעות בסקר הראשוני ובסקר ההחייאה ובהשוואה לפינוי מהיר.** על כן, חובתו של כל מטפל בכיר להדגיש בפני המפקדים את חשיבות הפינוי, ולוודא כי אינו מתעכב. פצוע, שניתן לפנותו בתום סקר ההחייאה או בתום הסקר הראשוני, או אפילו תוך כדי הסקר הראשוני, יפונה מייד, ויעבור את הסקר השניוני תוך כדי הפינוי. יחד עם זאת, במתארים מסוימים, בחירום ובפעילויות מיוחדות בעיקר, עלול להיות מצב של מטפל בכיר המטפל בפצוע דחוף, ללא יכולת פינוי, למשך שעות בודדות. רק במידה ואין אפשרות להתחיל בפינוי משיקולים מבצעיים, יבוצעו ההנחיות בזמן ההמתנה לפינוי. גם אם הוחל ביצוע סקר שניוני, ניתן ואף רצוי להפסיקו בכל עת לטובת פינוי, היות ואף אחת מהפעולות המתבצעות בו לא עולה בחשיבותה על פינוי הפצוע.


## תנאי סף לתחילת הסקר השניוני

- הפצוע תו"כ פינוי או מוכן לפינוי בכל רגע נתון - כלל הצנרת מאובטחת, השרכים מוצנעים, והמכשירים צמודים לפצוע או ניתנים להצמדה בכל רגע נתון.

- במידה והפצוע אינו במהלך פינוי, בוצעו המאמצים המרביים להאיץ את פינויו.

- בוצע סקר ראשוני מלא.

- בוצע סקר החייאה מלא, לרבות טיפול בכאב, כריכת אגן והנחת סד תומאס ע"פ ההנחיות.

- הפצוע מנוטר באופן מקיף ורציף -  ל"ד, דופק, סטורציה, קצב נשימות, GCS והערכת כאב (NRS) לפחות כל 15 דקות (ובתדירות גבוהה יותר ככל שמצב הפצוע מצריך זאת). במידה והפצוע מצונרר יכלול גם ETCO2. ניטור ורישום מוקפד של המדדים בטופס 101 תוך ציון זמנים.

- הועבר דיווח מפורט על הפצוע לדרג הבא.

## סקר שניוני עפ"י סדר פעולות (הרחבה בהמשך)
- בפצוע מונשם –Bite block, חיבור למנשם אוטומטי, כיוונונו ווידוא הנשמה תקינה, הכנת תרופות הרדמה להמשך, קשירת הידיים לאלונקה (בעדינות).

- וידוא כלל הקיבועים.

- השלמת עירוי פריפרי שני לגיבוי.

- בדיקה גופנית מלאה מהקודקוד ועד לבהונות הרגליים – טיפול בכל פציעה המזוהה בדרך (שטיפת פצעים, קיבוע שברים, חבישת כוויות וכיוצ"ב).

- הסרת חסמי עורקים במקרים בהם אין בהם יותר צורך, ושקילת המרה של חסמי עורקים במידה וניתן. יש לשים דגש על חסמי עורקים אשר הונחו בשל סיבה מבצעית וזהו 
המועד לבדוק את הפציעה.

- מתן טיפול אנטיביוטי בהתאם להתוויות המופיעות בפרק "הטיפול האנטיביוטי בשדה".

- בפצוע שקיבל הקסאקפרון – במידה וחלפו 3 שעות יש לתת מנה נוספת.

- הכנס צנתר שתן (בסמכות רופא בלבד) בכל פצוע הלם, פצוע מחוסר\מעורפל הכרה או אינדיקציה אחרת למעקב תפוקת שתן (פגיעת מעיכה, כוויות וכו') – בהיעדר התוויית נגד - במידה וצפי הפינוי *מעל לשעה*.

- הכנס זונדה לניקוז הקיבה (בסמכות רופא בלבד) בפצוע מונשם – דרך הפה בלבד, במידה וצפי הפינוי *מעל לשעה*.

- הערך לשגרה מחזורית של טיפול בפצוע – ניטור, סדציה (לפי הצורך), טיפול בכאב, בדיקה גופנית, טיפול סיעודי לרבות שינויי תנוחה וכן הלאה, כמפורט בפרק "אחזקת פצוע לאחר הסקר השניוני", **בעזרת הטופס הייעודי.**

### Bite Block
פצוע המונשם דרך טובוס (לא קוניוטום) ואינו משותק עלול לנשוך את הטובוס ולהביא לחסימתו. ניתן למנוע זאת בראש ובראשונה ע"י מתן סדציה מספקת, אולם יש להניח גם אמצעי בפיו של הפצוע שימנע סגירה של המנשך הטובוס. לצורך כך, בטווח הקצר, מקובל להשתמש במנתב אוויר פלסטי ("Airway"). בפינוי הקצר הוא נותן מענה מספק. עם זאת, במידה והוא מונח לזמן ממושך הוא עלול לגרום ללחץ על עורק הלשון ולגרום לנמק שלה. לכן, בתחילת הסקר השניוני נמיר אותו לחסם נשיכה רך – אגד מגולגל שיונח בין השיניים הטוחנות (מבלי לדחות את הלשון לאחור). יש להקפיד להשאיר שרך שבולט אל מחוץ לפה (ניתן לקשור בעדינות לטובוס. יש לבצע את ההחדרה בעדינות ותוך זהירות שלא להזיז את הטובוס ממקומו. לאחר מכן יש לבצע שנית האזנה דו"צ על מנת לוודא שהטובוס לא הועמק אל תוך אחת הסימפונות.

### חיבור למנשם אוטומטי

יש לחבר מנשם אוטומטי בהקדם האפשרי לכל פצוע שעבר אינטובציה או קוניוטומיה – ללא קשר למשך הפינוי. הנשמה של פצוע עם צינור בקנה (טובוס או קוניוטום) באמצעות אמבו הינה מורכבת, היא מנטרלת את המטפל המנשים פיזית וקוגניטיבית לאורך כל זמן ההנשמה, נוטה להיות לא סדירה - בקצב מהיר או איטי, בלחצים גבוהים או קטנים ובנפחים קטנים או גדולים מהרצוי. הנשמה ביתר (Hyperventilation) גורמת לבססת נשימתית המובילה לכיווץ כלי דם, הפרעות קצב, טכיקרדיה ואף איסכמיה לבבית ומוחית (במקרי פגיעות ראש). הנשמה בחסר (Hypoventilation) גורמת לחמצת נשימתית המחמירה קואגולופתיה של טראומה והיפותרמיה, ומעלה תמותה. לחצים גבוהים גורמים לנזק ישירות לריאה, ומחמירים חזה אוויר.
המנשם האוטומטי נועד לפתור בעיות אלו. פירוט על המנשמים הקיימים בצה"ל ניתן למצוא בפרק "אחזקת פצוע לאחר הסקר השניוני". 

 
בעת הנשמה דרך צינור בקנה, בין אם על ידי מנשם ידני ובין אם על ידי מנשם אוטומטי, יש לחבר לקפנוגרף או קפנומטר (כמותי). ערכי המטרה הינם EtCO2 של 30-35 מ"מ כספית. בעת שחלוף, יש להכין את המנשם האוטומטי של הצוות המקבל, לנתק מהמנשם האוטומטי של הצוות המעביר תוך חיבור מיידי של המנשם האוטומטי של הצוות המקבל. המסנן הויראלי ימשיך עם הפצוע למנשם החדש.
אין התוויות נגד לחיבור המנשם האוטומטי. על מנת להיות בקיאים בתפעול המנשם האוטומטי, ישנה חשיבות לתרגול השימוש במכשיר. במהלך התרגול נדרש לחבר למנשם ריאה מלאכותית, שנמצאת בערכת המכשיר. על מנת לאפשר תרגול גם כאשר אין מכשיר בהישג יד פותחה אפליקציה ייעודית בענף צוה"ר. אפליקציה זו מאפשרת תרגול כלל הפונקציות במכשיר: טיפול בתקלות, חיבור אביזרים למקומם במנשם וכיוב'.

 
### בדיקה גופנית מדוקדקת
בשלב הסקר השניוני נבצע בדיקה גופנית מדוקדקת המלווה בטיפול  Head to toe – Treat as you go . הבדיקה מבוצעת באופן שיטתי, מהראש ועד לרגליים, לזיהוי פציעות שלא ניתנה להן התייחסות בסקר הראשוני. פציעות עם פגיעה בשלמות העור יישטפו במים וייחבשו, שברים ונקעים יקובעו (באמצעים כמו סד  ,SAMחבישות אלסטיות, משולשי בד ובמידת ההכרח חבישות מאולתרות). כוויות ושפשופים ייחבשו בתחבושת מטלין. בשלב זה הפצוע כבר אמור להיות מופשט ומכוסה – יש להסיר את הכיסוי בהדרגה ולהחזירו מיד כתום הבדיקה של כל פלג גוף. בסיום הבדיקה יש להחזיר את הפצוע למצב של מוכנות לפינוי.

### המרת חסמי עורקים
הנחת חסם עורקים היא פעולה דחופה ומצילת חיים. לחסם עורקים שתי התוויות עיקריות. הראשונה, כאשר לחץ ישיר אינו יעיל – לדוג' לחץ ישיר כשל, רסיסים מרובים מדממים בגפה או קטיעה גדולה. השנייה, כאשר בנסיבות המיידיות באירוע, אין זמן או יכולת להפעיל לחץ ישיר – למשל תחת אש, בחושך ובאר"ן. במספר מחקרים שבוצעו, חסמי עורקים שהונחו למשך עד שעתיים, נמצאו כבטוחים ולא גרמו לעלייה בשיעור הקטיעות. מסיבות אלו, בעת ספק, יש להניח חסם עורקים.

במידה וחסם עורקים הונח לדוגמא בעת אירוע מבצעי, ובדיעבד מתגלה כי אין כלל פציעה שעשויה לדמם חיצונית בגפה, ניתן להסיר את חסם העורקים באיטיות תוך וידוא כי לא מופיע דימום.

בפצוע ללא סימני הלם עמוק, במידה וחסם העורקים הונח בהתוויה נסיבתית, ניתן לנסות ולהמיר את חסם העורקים בלחץ ישיר בתנאים הבאים: (א)  לחץ הדם הסיסטולי גבוה מ-90 מ"מ כספית וגם הדופק קטן מ-110 לדקה, ו(ב) קיימת גישה ורידית פתוחה. בתנאים אלו מטפל בכיר רשאי להמיר בשש השעות הראשונות לאחר ההנחה. במידה ועברו יותר משש שעות אין להמיר את חסם העורקים.

את ניסיון ההמרה נתחיל בחיבור מלא של הפצוע לניטור, חשיפה מלאה של הגפה, והכנת חסם עורקים נוסף מעל (קריבני) חסם העורקים הנוכחי. לאחר מכן נבצע חבישה לוחצת קפדנית על מקום הדימום. במידה ונראה שיש מקום גם לביצוע של packing, זה יבוצע טרם הסרת חסם העורקים. את חסם העורקים נשחרר באיטיות. אין לגזור את חסם העורקים. יש לוודא שהדימום לא התחדש ושהדופק הרחיקני כן. נתעד את ההמרה בטופס 101 לרבות:

- מיקום וסוג התחבושת שהונחה. 
- שעת ההמרה.

- הצלחה או כשלון.

- לאחר ביצוע הפעולה, נשגיח באופן רציף במשך 5 דקות, ולאחר מכן נמשיך ונעריך את המדדים והתחדשות הדימום כל 15 דקות.

במידה וחסם העורקים היה מונח מעל לשעתיים, יש לתת טיפול בנוזלים - בין חצי ליטר לליטר של תמיסת הרטמן בהרצה - על מנת לצמצם את הסיכון לנזק כלייתי כתוצאה מתוצרי פירוק שריר ואת הירידה בלחץ הדם שנגרמת כתוצאה משחרור חומרים וזו-דילטוריים מהגפה שהיתה חסומה. הסיכון הולך וגדל ככל שהמסה של הגפה החסומה גדולה יותר (חסם פרוקסימלי, גפה תחתונה) ומשך החסם ארוך יותר. בנוסף קיים סיכון להיפרקלמיה זמנית. לאור הנ"ל, במידה והפצוע צפוי להגיע למסגרת **בעלת יכולות טיפול נמרץ** (בי"ח, פלה"ק וכיוצ"ב) בשעה הקרובה יש לשקול לדחות את ההמרה עד הגעתו לאותה מסגרת.

### מתן אנטיביוטיקה
בכל פצוע עם פגיעה חודרת  יש לתת טיפול אנטיביוטי עפ"י פרק "הטיפול האנטיביוטי בשדה". ההנחיה היא על מתן של אנטיביוטיקה לכל פצוע שאינו צפוי להגיע לביה"ח תוך שעה מרגע הפציעה, אולם גם לפצועים עם משך פינוי קצר יותר מומלץ לתת טיפול אנטיביוטי, שלא על חשבון פעולות הסקר הראשוני או סקר ההחייאה. 

הטיפול המקובל כיום בצה"ל הוא IV Ceftriaxone 2g פעם ב-24 שעות. במידה וקיימת גם פגיעת ראש או בטן יש להוסיף IV Metronidazole 500mg פעם ב-8 שעות.

### הקסאקפרון
במידה וחלפו 3 שעות ממתן המנה הראשונה של הקסאקפרון שקיבל הפצוע, יש לתת מנה שניה של 1 גרם.

### צנתר (קתטר) שתן
קתטר שתן יוכנס בהחלטת רופא בלבד (אינו בסמכות פרמדיק), על ידי רופא\ה או אח\ות בלבד. פעולה זו כרוכה בסיבוכים פוטנציאליים, במיוחד בסביבה של סטריליות לא מיטבית, ולכן לא תבוצע בפצוע שצפוי להגיע לביה"ח בתוך שעה מרגע הפציעה.
פצועים שלהם יש להכניס קתטר שתן:

- פצועים בהלם (על מנת לעקוב אחר תפוקת השתן).

- פצועים מורדמים או מחוסרי הכרה למניעה של  (Bladder distention).

- פצועי מעיכה או כוויות, שעבורם מתן נוזלים מוכוון עפ"י תפוקת השתן.

התוויות נגד להחדרת קתטר שתן
כוללות:

- חשד לשבר באגן

- דם בקצה השופכה.

- המטומה בסקרוטום (שק האשכים) ו/או בפרינאום (בין פי הטבעת לשק האשכים).


שיעור הזיהומים עם קתטר שתן הוא כ-5% ליום,  לכן יש חשיבות גדולה בביצוע הפרוצדורה באופן סטרילי. בכדי להקל על ההכנסה, חשוב למרוח ג'ל לובריקציה בכמות רבה. יש לבצע את ההחדרה בעדינות, ללא הפעלה של כח מוגזם. בגבר יש להחדיר את הקתטר עד לבסיסו, באישה עד קבלה של שתן ולאחר מכן כ-3 ס"מ נוספים. במידה ולא חוזר שתן דרך הקתטר יש ללחוץ חיצונית (ע"י עוזר) מעל לפוביס במטרה ללחוץ על השלפוחית. רק במידה ויש חזרה של שתן יש לנפח את הבלונית בנוזל (10 מ"ל סליין) ולחבר לשקית שתן. במידה ולא נתקבל שתן **אין לנפח את הבלונית**. בהמשך יש לקבע את השקית לרגל הפצוע, ולתעד בטופס 101 את שעת ההכנסה וכמות השתן בשקית לאחר ההכנסה. בהמשך, יש לתעד את כמות השתן שנוספה לאחר כל שעה. אין מניעה מלהכניס קתטר לפצוע בהכרה, אולם יש להקפיד לתת לו הסבר טרם ביצוע הפעולה.

### זונדה

יש להכניס זונדה אוראלית\נזאלית לכל פצוע שעבר אינטובציה או קוניוטומיה. יחד עם זאת, אין לבצע פעולה זאת עד כל עוד לא בוצעו הפעולות הנדרשות מהסקר הראשוני, סקר ההחייאה והסקר השניוני. 

כל פצוע מונשם הוא בסכנה לאספירציות. בהגדרה, כל פצוע טראומה הוא בעל קיבה מלאה. הנשמה באמבו ומסיכה במיוחד בידיים לא מיומנות, ממלאת את הקיבה באוויר. תרופות ההרדמה נוגדות את רפלקסי השיעול והבליעה המגנים מפני אספירציות. בלונית הטובוס או הקוניוטום מהוות הגנה חלקית בלבד ולא אוטמות באופן מלא מכניסה של תוכן ממע' העיכול אל דרכי הנשימה.

הכנסת זונדה מצמצמת את כמות הנוזלים והגזים בקיבה ובכך מורידה את הלחץ הזה ומקטינה את הסיכוי להקאה ואספירציות. הבחירה במיקום ההחדרה תתבצע בראש ובראשונה בהתאם למיומנות ונסיון המטפל. החדרה אוראלית בפצוע מונשם אינה דורשת את שיתוף הפעולה של הפצוע, ומותרת גם כאשר יש חשד לשבר בבסיס הגולגולת. אין להחדיר זונדה נזאלית בכל מקרה של חשד לשבר בבסיס הגולגולת.

טרם ההחדרה יש למדוד את העומק הדרוש – מהפה\האף, סביב זווית הלסת ועד לאפיגסטריום. ההחדרה תתבצע תוך הרמה של הלסת להקלת ההחדרה. אין להכניס אצבעות לתוך פיו של הפצוע!

לאחר החדרת הזונדה ננסה לשאוב תוכן. במידה ויוצא תוכן יש לחבר לשקית, לקבע לגוף הפצוע את הצינור ואת השקית (יש להקפיד להימנע מלחץ של הצינור על העור), ולתעד בטופס 101 את הפעולה ושעת ביצועה. במידה ולא, ניתן להזריק 20-30cc של אוויר תו"כ האזנה על פני האפיגסטריום. במידה ונשמע רעש גס של כניסת אוויר, הדבר מעיד על הימצאות של הזונדה בדרכי העיכול. יש לנסות שוב לשאוב. במידה וחוזר תוכן או אוויר באותה הכמות, יש לקבע את הזונדה. במידה ולא, יש לנסות להתקדם עוד כ- 5 ס"מ עם הזונדה ולנסות שוב. במידה ובהזרקת האוויר הזונדה אינה בדרכי העיכול יש להוציאה ולנסות שנית. אין לבצע יותר מ-3 ניסיונות להחדרת זונדה – במידה והם נכשלים, יש לוותר על ניקוז הקיבה.


### סיכום
הסקר השניוני כולל בתוכו פעולות אבחנתיות וטיפוליות חשובות, שעשויות לצמצם נכות וסבל, אולם התרומה של כולן נחותה בהשוואה לתרומה של פינוי לביה"ח או מסגרת רפואה מתקדמת אחרת. לפיכך, יש חשיבות ולהכיר ולשלוט בשלבי הסקר השניוני, אולם תמיד לזכור כי אין לעכב פינוי לצורך ביצועו.

