# פציעות ראש

## עיקרי העדכונים: 

- 23.12.20:

    - בדיקת כוח גס ותחושה תתבצע במגבלות המתאפשר
    - הוספת מינוני ילדים.
    - הסרת diazepam.

## תוכן עניינים
**הקדמה ורקע**

**אנטומיה ופתופיזיולוגיה**

- **זרימת הדם המוחית**
- **פתופיזיולוגיה** 

**פרוטוקול**

**ביאור הפרוטוקול**
-   **פרק א: הערכה**
- **פרק ב': בדיקה פיזיקלית**
    - **הסתכלות**
    - **מדדים המודנמיים**
    - **בדיקה נוירולוגית**
        - **GCS**
        - **עצבי הגולגולת**
        - **כוח גס ותחושה**
        - **דינמיקה**
- **פרק ג': טיפול**
    - **נתיב אוויר – Airway**
    - **נשימה – Breathing**
    - **Circulation**
    - **Disability וסבב שניוני**
    - **טיפול במצבים מיוחדים:**
        - **פרכוס**
        - **פגיעת עמוד שדרה**
        -  **ערכי סוכר**
        - **טיפול אנטיביוטי**
- **פרק ד': פינוי**

**דגשים לטיפול בפלה"ק ובמסגרות עם יכולות טיפול נמרץ**

**סיכום**

**ביבליוגרפיה ומקורות**

## הקדמה ורקע
פציעת ראש בשדה הקרב מהווה סיבה לחלק משמעותי ממקרי המוות שאינו בר-מניעה (עד 42% על פי דיווחים מצבא ארה"ב), וגם מאלו ברי-המניעה (7%)1,2. פציעת הראש מהווה אתגר טיפולי מורכב לאור הקושי המובנה באבחונה, השלכותיה על נתיב האוויר והמגבלות שהיא מציבה על הטיפול במצבי פציעה אחרים כדוגמת הלם תת-נפחי. בנוסף, מאחר ויכולות טיפול דפיניטיביות בפציעות ראש קיימות רק במרכז נוירוכירורגי, עד שהפצוע יפונה למרכז שכזה, מצבו הנוירולוגי עלול להחמיר, והסיכוי לנזק נוירולוגי מתמשך ואף תמותה עולים. המטרות במתאר טרום בית החולים הן לזהות מוקדם ככל האפשר את פציעת הראש, לבצע ייצוב המודינמי ונשימתי של הפצוע ולפנותו מהירות האפשרית.
## אנטומיה ופתופיזיולוגיה
*****תמונה

הכרת עקרונות בסיסיים באנטומיה ובפיזיולוגיה של המוח חיונית להבנת הפתופיזיולוגיה של פציעות הראש. הקרקפת הינה השכבה השטחית ביותר בראש אשר מקנה לו הגנה ראשונית. לקרקפת מספר שכבות והיא מאופיינת בעושר כלי דם. מתחת לקרקפת שוכנת הגולגולת, המורכבת ממספר עצמות שמתאחות למבנה אחד במהלך הילדות. מרבית העצמות המרכיבות את הגולגולת עבות וחזקות, אך ראוי לציין את העצמות **הטמפורליות והאתמיאודליות** הרכות יותר והמועדות לשברים (איור 1). בתינוקות ניתן למשש נקודות רכות על גבי הגולגולת (מרפסים, Fontanelles), המתאחות לרוב עד גיל שנתיים. כלי הדם ועצבי הגולגולת עוברים דרך פתחים קטנים (foramina) בבסיס הגולגולת. ה Foramen magnum הוא פתח גדול הנמצא בבסיס הגולגולת אשר דרכו עוברים גזע המוח וחוט השדרה. 

המוח עטוף בשלוש ממברנות הנקראות מנינגים: הדורה, הארכנואיד והפיה, מן השטחי אל העמוק בהתאמה (איור 2). סביב המוח נמצא נוזל ה-CSF (Cerebrospinal fluid) אשר מיוצר במערכת חדרי המוח בפקעת ה-choroid, ומשמש להזנתו וכ"בולם זעזועים" . חשוב לזכור שבתווך שבין הדורה לבין העצמות הטמפורליות (אפי-דורה) עוברים כלי דם החורצים את עצמות הגולגולת. חבלה בעצם הטמפורלית הרכה עלולה להוביל לקרע בכלי דם אלו ולגרום לדימום **אפי-דורלי**.  המרווח שבין הדורה והמח (סאב-דורה) מכיל מערכת **ורידים** מגשרים המחברים בין פני המוח והסינוסים הגדולים בדורה. קרע טראומטי של וורידים אלו הינו סיבה שכיחה לדימום סאב-דורלי המופיע לעיתים קרובות ביחד עם פגיעה מוחית. סוג דימום זה שכיח יותר במבוגרים, מאחר וחלה הצטמקות של המוח ומתיחה של הורידים, כך שהם רגישים יותר להיקרע. מעל ה-

איור 2 – שכבות המנינגים
******* תמונה

Pia עוברים כלי דם רבים המספקים דם לרקמת המוח. כלי הדם הללו עטופים בשכבת ה- Arachnoid, הנמצאת מעל שכבת ה-Pia ועוטפת את המוח כמעין "עטיפת נייר צלופן". קרע של אותם כלים המספקים למוח דם יגרום לדימום בחלל הסאב-פיאלי או תת עכבישי (סאב-ארכנואידלי). הבדל משמעותי בין דימום אפי-דוראלי וסאב-דוראלי, **הוא בהעדר אפקט מסה בדימום הסאב-ארכנואידלי**, בניגוד לאפקט המסה בדימומים האחרים. בטבלה 1 מוצגת השוואה בין שלושת סוגי הדימומים. חשוב לזכור כי הסימנים והסימפטומים של הדימומים עלולים לחפוף, ולכן קשה לאבחנם במדויק במתאר טרום בית החולים. 

##### טבלה 1 – דימומים תוך-גולגולתיים
************ טבלה

### זרימת הדם המוחית
לצורך פעילותו התקינה של המוח נדרשת  זרימת דם מוחית קבועה (CBF; Cerebral Blood Flow). ה-CBF צריך למעשה לספק את צורכי החמצן של המוח (CMRO2 – Cerebral Metabolic Requirements of O2). ה-CBF תלוי בלחץ הזילוח המוחי (CPP; Cerebral Perfusion Pressure), ובהתנגדות כלי הדם במוח (CVR; Cerebral Vascular Resistance), על פי הנוסחה: *CBF=CPP/CVR*. בתנאים רגילים, המוח משמר את ה-CPP (ובעקיפין את ה-CBF) בעזרת מנגנון האוטורגולציה, השולט ומשנה את ההתנגדות (CVR) בהתאם ללחץ הזילוח (CPP). רמת ה-CPP לכשעצמה מושפעת מהלחץ התוך גולגלתי (ICP, Intra Cranial Pressure) ומלחץ הדם בעורק הקרוטידי. לאור המורכבות במדידת ל"ד קרוטידי משתמשים בלחץ הדם הסיסטמי הממוצע (MAP, Mean Arterial Pressure) **כמדד מקורב**, כך שה-CPP יכול להיות מבוטא בנוסחה: *CPP=MAP-ICP*. פגיעה תלוית ערכי CPP יכולה להיות במצב של הלם תת-נפחי (כתוצאה מדימום לדוגמה) אשר גורם לירידה משמעותית ב-MAP. חשוב לציין כי במקרי טראומה מוחית, האוטורגולציה מופרעת במהלך השעות הראשונות, ומכך הצימוד בין CPP ל-CBF נפגע, בייחוד בפגיעות מוח דיפוזיות.

בנוסף לשינויים בזרימת הדם למוח, תמותה ונזק ארוך טווח בטראומה קשורים גם ל-ICP. העלייה ב-ICP מוסברת באמצעות דוקטרינת "קלי-מונרו", המתארת את החלל התוך גולגלתי כקופסא בעלת נפח קבוע המכילה 3 מדורים עיקריים – דם, CSF ורקמת מוח. תוספת מסה נפחית לחלל התוך גולגלתי (**המטומה לדוגמה**) או שינוי בנפח אחד המדורים (עלייה בנפח רקמת המוח **כתוצאה מבצקת**), מחייבים שינויי בנפח אחד המדורים האחרים (בהעדר יכולת אלסטית להתרחבות הגולגולת ושינוי הנפח הכולל). קיימת יכולת מוגבלת ביותר לירידה בנפח ה-CSF והדם, וברגע שאלו ירדו לרמתם המינימלית, מנגנון הפיצוי יכשל, וה-ICP יעלה. העלייה ב-ICP, בהתאם לנוסחה CPP=MAP-ICP, תוביל גם לירידה ב-CPP ולבסוף לאיסכמיה מוחית. כמו כן, עלייה משמעותית ב-ICP עלולה להוביל לדחיפה של מבנים בתוך הגולגולת עד כדי **הרניאציה מוחית**, ולפגיעה בניקוז הורידי של המוח המוחי. הפגיעה בניקוז הורידי יוצרת תהליך המוביל להמשך עלייתו של ה-ICP ולהצטברות מטבוליטים טוקסיים במוח. 

בהקשר זה, חשוב לציין גם כי הניקוז הורידי עלול להיות מושפע מלחץ על הצוואר (**מצווארון** קיבוע לדוגמה או **מקיבוע** אגרסיבי של **טובוס**), מעליית לחץ בבית החזה (כתוצאה **משיעול, חזה אוויר** או **הנשמה** בלחץ חיובי), מלחץ המופעל על הבטן וכו'.

גורם משמעותי נוסף, המשפיע על ההתנגדות והזרימה בכלי הדם המוחיים הינו **הלחץ החלקי של פחמן דו-חמצני (PaCO2)**. כך למשל, בתנאי היפרוונטילציה וצניחת ה-PaCO2, נגרם כיווץ כלי הדם במוח המביא גם לירידת ICP. עם זאת, אותו כיווץ כלי דם שההיפרוונטילציה גורמת עלול לגרום **לירידה דרמטית באספקת הדם** עד כדי נזק איסכמי3. כפי שיפורט בהמשך, במקרי קיצון בהם יישקל לבצע היפרוונטילציה, יש לעשות זאת במשנה זהירות. 

### פתופיזיולוגיה
נהוג לחלק את פציעת הראש לפציעת ראש ראשונית ופציעת ראש שניונית:

**הפציעה הראשונית** היא הטראומה הישירה הנגרמת למוח ולכלי הדם. אופי הפגיעה הראשונית, הפרוגנוזה והטיפול תלויים במנגנון הפגיעה. הפציעה הראשונית מתבטאת בפגיעה ישירה בקרקפת, בעצמות, בכלי הדם של הראש והמוח, במוח עצמו ובעצבי הפנים. מאחר ויכולת הרגנרציה העצבית היא מינימלית, פוטנציאל הריפוי לנזקי המוח והעצבים בפגיעה הראשונית נמוך.

**פציעת ראש שניונית** מתייחסת לתהליך הפגיעה המתמשך שמתחיל מרגע פציעת הראש הראשונית. בזמן הפציעה, כתוצאה מפגיעה באספקת הדם ומהבצקת המוחית, מתחיל תהליך פתופיזיולוגי מתמשך הפוגע במוח בתוך שעות, ימים ושבועות מרגע הפציעה. **המטרה העיקרית בטיפול בפציעות ראש הוא מזעור ועצירה של תהליך הפציעה השניוני**. במתאר טרום בית החולים, כפי שיפורט בהמשך, מטרה זו מושגת בעיקר באמצעות ייצוב המודינמי ונשימתי תוך הימנעות מצעדים שעשויים להחמיר את מצבו של פצוע הראש.

## פרוטוקול – הטיפול בפציעת ראש טראומטית
**בפצועים עם חשד לחבלת ראש ורק לאחר שהפציעות מסכנות החיים טופלו  יש לנטר ולעקוב אחר**
1. **ירידה במצב הכרה כפי שתתבטא בשינוי ב GCS (הערכה ע"י מט"ב) ומצב הכרה לפי שינוי ב A V P U**. 
2. **מעקב אחר אישונים – הרחבה / היצרות, תגובה לאור ותנועתיות** 
3. **שמירה על ל"ד סיסטולי מעל ל  90 מ"מ כספית** 
4. **שמירה על רוויון החמצן מעל ל 90** 
5. **מניעת היפותרמיה**
6. **שמירה ל PCO2 בין 35-40** 
 
## ביאור הפרוטוקול 
### פרק א: הערכה
בהגיענו לפצוע, מספר ממצאים מחשידים לפגיעת ראש: סימני חבלה בפנים או בקרקפת, אובדן הכרה, סימנים נוירולוגים  / חסרים פוקאליים דוגמת שיתוק, תגובה איטית, בלבול, פרכוס מוקדי או כללי, דיבור משובש או איטי וצחוק או בכי מוגזמים או לא תואמים (אָפקט לא תואם). חשוב לזכור כי חלק ניכר מפגיעות הראש הקהות מתאפיינות בהופעה מאוחרת של תסמינים, לאחר שהבדיקה הראשונית הייתה תקינה או עם ממצאים מינימאליים. על כן,  יש לשמור על אינדקס חשד גבוה לפגיעת ראש חמורה גם במידה וההסתמנות הקלינית הראשונית תקינה או עם תסמינים קלים. בפציעה חודרת אין לבצע אקספלורציה של הגולגולת, שברים קטנים מהעצם עשויים  לזוז וליצור נזק שניוני רב.
### פרק ב: בדיקה פיזיקלית כללית
#### 4. הסתכלות :

איור 3 ––  A: Raccoon's eyes,B: Battle's sign
****** תמונה

1. סימני שבר בסיס גולגולת - Raccoon's eyes  ו-Battle's sign (איור 3; אכימוזות פריאורביטליות או פוסטאוריקולריות בהתאמה), דלף CSF מהאף (Rhinorrhea)/אוזן (Otorrhea), דמם באוזן תיכונה, לצרציה בתעלת השמע החיצונית.  
2. בצקת פריאורביטלית / בלט בגלגל העין (Proptosis).
3. סימני חבלה או דפורמציה בעמוד השדרה.
4. תיאור מקרה של נוכחים בשטח על פרכוס, או תנועות קלוניות או אחרות בלתי רצוניות.
5. כל דיווח על שינוי ברמת הכרה או מצב הכרה במהלך השעות הראשונות מאז הפציעה צריך לעורר חשד.
#### 5. מדדים המודינמיים
ל"ד גבוה + דופק נמוך – Cushing Reflex. כאשר אלו מופיעים בפצוע מחוסר הכרה, יש חשש שהפצוע סובל מעלייה ב-ICP ומהרניאציה מרכזית עם לחץ על מבני גזע המוח האחראים על המצב ההמודינמי. 
#### 6. בדיקה נוירולוגית
במתאר טרום בית החולים, מטרתה העיקרית של הבדיקה היא למצוא סימנים המעידים על יתר לחץ תוך גולגלתי כפי שמצוין **בטבלה 2**. מרכיבי הבדיקה הנוירולוגית עשויים להצביע על פגיעה תוך גולגולתית ולרמז על חומרתה:

******* תמונה

1. **GCS (Glasgow Coma Scale)**
    
    מדד גלזגו להערכת הכרה - (טבלה 3). 
    
    במידה והפצוע בהכרה יש לבצע גם בדיקת אוריינטציה.
**טבלה 3– מדד הגלזגו**

************** טבלה

2. **עצבי גולגלת :**
    1. בדיקת אישונים - גודל אישונים (בתנאי תאורה מינימלית), ותגובת אישונים לאור.
    2. בדיקת תנועות עיניים, שדות ראיה והמצאות כפל ראייה כעדות לפגיעות בעצבים קרניאלים : **III, IV, VI** ו-II
    3. בדיקת תחושה בפנים כביטוי לפגיעה בעצב קרניאלי V  
    4. פגיעה בכל אחד מעצבי הגולגולת הללו יכולה להעיד על נזק לעורקים הראשיים המזינים את המוח או על עליית ICP, משמע פרוגנוזה קשה. 
    5. פציאליס (פגיעה בעצב הפנים המתבטאת בחולשה או בשיתוק שרירי הפנים בצד הפגוע) יכול להיות סימן לשבר בסיס גולגולת גם בהעדר סימן אחר.
3. **כוח גס ותחושה (ב-4 גפיים):** 
    1.  בכל פצוע החשוד כפגוע ראש ובו נדרשת הערכה נוירולוגית יש לבצע בדיקת כוח גס ותחושה בארבע גפיים, במגבלות המתאפשר. 
    2. חשוב לתעד תנוחת דהקורטיקציה/דהצרברציה (איור 4).

איור 4––  תנוחות דקורטיקציה (למעלה) ודהצרבציה (למטה)

************* תמונה

4. **דינמיקה** - הסימנים המאוחרים המעידים על החמרה בפציעת הראש עשויים להיות:
    1. עלייה משמעותית בנפיחות באזור הפציעה.
    2. הופעת דיבור משובש.
    3. שינויי התנהגות. 
    4. הקאה חוזרת.
    5. קושי להעיר את הפצוע.
    6. שינוי במצב ההכרה 
    7. פרכוס
    8. חולשה או העדר תחושה בגפיים.
    9. הרחבת אישונים שלא מגיבה לאור

### פרק ג': טיפול 
#### 1. Airway
ניהול נתיב האוויר בפצועי ראש מתבצע בהתאם לפרק 1 העוסק בניהול נתיב האוויר בפצועי טראומה.  מספר נקודות ייחודיות תודגשנה :
1. פצועים הסובלים מפציעת ראש המשלבת גם שבר בפנים ובצוואר ידרשו לעיתים לתנוחה מסוימת המאפשרת נתיב אוויר פתוח ונשימה. **יש לזכור כי שמירה על נתיב אוויר פתוח קודמת להנחת צווארון ושמירה על עמ"ש צווארי**, ויש לאפשר לפצועים להתפנות בישיבה או בכל תנוחה המאפשרת להם לנשום.
2. בהתאם להנחיות ניהול נתיב האוויר בפרק 1, ההחלטה על ביצוע אינטובציה צריכה להתקבל בהינתן ירידה **בסטורציה מתחת ל-90%, ולא** על סמך **פציעת הראש לכשעצמה.**  
3. בחשד לשבר בסיס גולגולת אין להכניס זונדה או כל צנרת דרך חללי האף.

##### 2. Breathing
רמת הסטורציה בפצועי ראש צריכה להישמר על **לפחות 90%.** עיתים קרובות בכדי להשיג יעד זה יהיה צורך להיעזר בחמצן הניתן במסכה. במידה ומד-הסטורציה אינו זמין, יש לספק חמצן לפצוע הראש באמצעות מסיכת פנים בכל מקרה. פצוע שעבר אינטובציה/קוניוטומיה יונשם עם העשרת חמצן במידת האפשר לשימור ערכי הסטורציה הנדרשים. במידה ועדיין ישנה היפוקסיה למרות הטיפול בחמצן, יש לשקול אתיולוגיות כגון אספירציה ו/או פנאומוטורקס כגורם לכך. בחולים מונשמים ניתן לבצע הנשמה עם PEEP (Positive end-expiratory pressure), אך יש לזכור כי PEEP מעל ל-15 ס"מ מים אינו מומלץ מאחר ועלול להעלות ICP. בשינוי ערכי הנשמה יש להימנע מהורדה מהירה של ה-PEEP שעשויה לגרום לבצקת מוחית והעלאת ICP.

**אין לבצע היפרוונטילציה** באופן שגרתי או מניעתי אלא לשקול ביצועה אך ורק עם הופעת הסימנים שפורטו תחת "סימנים המעידים על יל"ד תוך גלגלתי (והרניאציה) ". בשטח, היפרוונטילציה תושג תוך ניטור ETCO2 על ידי הנשמת 20 נשימות בדקה למבוגר, 25 נשימות בדקה לילד ו 30 נשימות בדקה בתינוקות מתחת לגיל שנה, תוך ניטור רמות ETCO2 בעזרת קפנומטר **לרמות יעד של 35-40 mmHg.** 

#### 3. Circulation
ירידה בהמוגלובין ותת לחץ דם גורמים לפגיעה שניונית, ולכן חיוני למנוע ולטפל במצבים הללו. עצירת הדימומים צריכה להתבצע בשלל האמצעים ובמהירות האפשרית. החייאת הנוזלים צריכה להתבצע בהתאם לפרק 2 – "החייאת בקרת נזקים בשדה", תוך התחשבות בעובדה ששמירה על **לחץ דם סיסטולי מעל 90 מ"מ כספית** חיונית במיוחד בפצועי ראש9. ישנן מספר עדויות חדשות שהראו עדיפות לשמירת לחץ הדם הסיסטולי מעל 110 מ"מ כספית. **אין להשתמש בסליין היפרטוני** לאור העדר עדות ליעילות במתאר טרום בית החולים ופרופיל תופעות לוואי מסוכן. 

#### 4.Disability וסבב שניוני
במהלך הסקר הראשוני יש לבצע הערכת ציון גלזגו (נספח א'). הגלזגו מחושב על-ידי סכמת הציון הניתן לתגובה הטובה ביותר בכל אחת משלוש המערכות הנבדקות (עיניים, תגובה מוטורית ותגובה מילולית). חשוב לתעד כל מערכת בנפרד ולא את הציון הכולל, וזאת בכדי לבצע מעקב לאורך זמן. כאשר פצוע ראש סובל גם מפציעה אחרת הגורמת להיפוקסיה (הלם תת-נפחי, פגיעה ריאתית וכו'), ציון הגלזגו שלו עלול להיות נמוך שלא כתוצאה ישירה מפציעת הראש. לאחר ביצוע ההחייאה והגעה למדדים המודינמיים הולמים, יש  לבצע הערכת גלזגו מחודשת, מאחר והציון צפוי לעלות במידה והושפע ממצב המודינמי ירוד. הציון לאחר ההחייאה **ודינמיקת מדד הגלזגו** הם בעלי ערך פרוגנוסטי. 

#### 5. טיפול במצבים מיוחדים:
1. **פרכוס:** ראשית, חשוב להדגיש כי ישנה חשיבות גדולה בהערכה ותיאור מדויקים של הפרכוס (פוקאלי, כללי, מרכיב פוקאלי לפני הכללה וכו'). כמו כן, פצוע מפרכס מוגדר כפצוע ראש, גם בהיעדר ממצאים אחרים, עד שיוכח אחרת. במידה והפצוע מפרכס, יש לטפל בו בתרופה ממשפחת הבנזודיאזפינים. התרופה הזמינה בשטח:  **Midazolam** (דורמיקום) בו ניתן לטפל **תוך ורידית או תוך-שרירית**. Midazolam יינתן במינון 5 מ"ג תוך ורידית (10 מ"ג תוך שרירית) ובמידה והפרכוס ממשיך לאחר 5 דקות תינתן מנה נוספת באותו המינון. חשוב לזכור כי התרופה עשויה לגרום לירידה בלחץ הדם, ולכן יש לתת אותה בזהירות ותחת ניטור המודינמי הדוק, בפרט נכון הדבר בחולים החשודים כמדממים. בילדים, יינתן Midazolam במינון 0.05 מ"ג/ק"ג.
2. **פגיעת עמוד שדרה**: על אף שילוב פגיעת עמוד שדרה בפציעת ראש בכ-4-8% מהמקרים ועד כדי 15% בפגיעת ראש קשה 11-15, יש לנקוט במשנה זהירות בעת הנחת צווארון וקיבוע לקרש גב, שכן ישנן עדויות שהתאמת הצווארון באופן הדוק עלולה לפגוע בניקוז הורידי של המוח ולהעלות את ה-ICP. בפצוע בהכרה מלאה, ששולל כאב ממוקם ויכול להניע את צווארו ללא הגבלה וללא חסרים נוירולוגיים גסים, הסיכוי להחמצה של פגיעה צווארית לא יציבה שמחייבת צווארון הוא נמוך. בכל פצוע מחוסר הכרה / תחת השפעת סמים או אלכוהול / המדווח על כאבים בצוואר בהנעתו (כשהוא מניע, אין לסובב ולבדוק פאסיבית צוואר של פצוע) יש לשים צווארון פילדלפיה באופן תקני, ותמיד לשקול זאת אל מול שיקולי זמן ומרחב.
3. **ערכי סוכר:** היפוגליקמיה והיפרגליקמיה עלולות להחמיר את מצבו של פצוע הראש. במתאר טרום בית החולים, חשוב לוודא כי הפצוע אינו סובל מהיפוגליקמיה, שכן השפעותיה ההרסניות על מערכת העצבים מהירות בהרבה מההשפעות השליליות של ההיפרגליקמיה. במהלך הסקר השניוני יש לבצע בדיקת גלוקוז במידת האפשר (בעזרת גלוקומטר הזמין למטפלים בשטח), ולטפל בתמיסת גלוקוז במידה וערכיו נמצאו נמוכים מ-70 mg/dL. יש להשתדל לשמור שערכי הגלוקוז יישאר מתחת ל-180 mg/dL16.
4. **טיפול אנטיביוטי**
בהתאם לכתוב בפרק 12-"הטיפול האנטיביוטי בשדה", במידה והפינוי צפוי להתעכב מעבר לשעה, יש לטפל אנטיביוטית בפציעת ראש חודרת. הטיפול האנטיביוטי כולל : מתן תוך ורידי של Ceftriaxone 2gr עם תוספת של Metronidazole 500mg תוך ורידית.

### פרק ד': פינוי
לצורך השגת תוצאים מיטביים, פצועי ראש הסובלים מפציעת ראש בינונית או קשה (גלזגו < 13) צריכים להיות מפונים מהר ככל האפשר **למרכז טראומה בעל יכולות נוירוכירורגיות**. במהלך הפינוי, יש לנטר באופן מתמשך את הדופק, לחץ הדם, אחוז הסטורציה וציון הגלזגו וסימני הרניאציה והדרדרות נוירולוגית כפי שפורטו. יש להשכיב את הפצוע כך שראשו מורם ב-30 מעלות, שכן פעולה זו מסייעת לניקוז הורידי ובכך מורידה את ה ICP. חשוב להודיע למוסד הרפואי אליו מפונה הפצוע על הגעתו מוקדם ככל האפשר. על אף כל האמור לעיל, **יש לפנות פצוע ראש עם הלם תת נפחי לבית-החולים הקרוב ביותר** מאחר והטיפול בהלם קודם לטיפול בפגיעת הראש. 

## סיכום
פרק זה עוסק בטיפול בפציעות ראש, שמטרתו למנוע את הנזק השניוני ע"י שמירה על פרפוזיה וחמצון מוחיים ומניעת עליה בלחץ התוך-גולגלתי. ההנחיות בפרק אינן תחליף להתייחסות הכוללת לפצוע, אלא מציינות באופן ספציפי את היעדים הנדרשים בפצועים עם פגיעות אלו.


## ביבליוגרפיה ומקורות:
<div dir="ltr">

1.	Eastridge BJ, Mabry RL, Seguin P, et al. Death on the battlefield (2001-2011): implications for the future of combat casualty care. J Trauma Acute Care Surg. 2012;73(6 Suppl 5):S431-437.
2.	Kelly JF, Ritenour AE, McLaughlin DF, et al. Injury severity and causes of death from Operation Iraqi Freedom and Operation Enduring Freedom: 2003-2004 versus 2006. J Trauma. 2008;64(2 Suppl):S21-26; discussion S26-27.
3.	Obrist WD, Langfitt TW, Jaggi JL, Cruz J, Gennarelli TA. Cerebral blood flow and metabolism in comatose patients with acute head injury. Relationship to intracranial hypertension. J Neurosurg. 1984;61(2):241-253.
4.	Marshall LF, Toole BM, Bowers SA. The National Traumatic Coma Data Bank. Part 2: Patients who talk and deteriorate: implications for treatment. J Neurosurg. 1983;59(2):285-288.
5.	Rose J, Valtonen S, Jennett B. Avoidable factors contributing to death after head injury. Br Med J. 1977;2(6087):615-618.
6.	Bratton SL, Chestnut RM, Ghajar J, et al. Guidelines for the management of severe traumatic brain injury. I. Blood pressure and oxygenation. J Neurotrauma. 2007;24 Suppl 1:S7-13.
7.	Cooper KR, Boswell PA, Choi SC. Safe use of PEEP in patients with severe head injury. J Neurosurg. 1985;63(4):552-555.
8.	McGuire G, Crossley D, Richards J, Wong D. Effects of varying levels of positive end-expiratory pressure on intracranial pressure and cerebral perfusion pressure. Crit Care Med. 1997;25(6):1059-1062.
9.	Carney N, Totten AM, O'Reilly C, et al. Guidelines for the Management of Severe Traumatic Brain Injury, Fourth Edition. Neurosurgery. 2017;80(1):6-15.
10.	Schreiber MA, Aoki N, Scott BG, Beck JR. Determinants of mortality in patients with severe blunt head injury. Arch Surg. 2002;137(3):285-290.
11.	Holly LT, Kelly DF, Counelis GJ, Blinman T, McArthur DL, Cryer HG. Cervical spine trauma associated with moderate and severe head injury: incidence, risk factors, and injury characteristics. J Neurosurg. 2002;96(3 Suppl):285-291.
12.	Frye G, Wolfe T, Knopp R, Lesperance R, Williams J. Intracranial hemorrhage as a predictor of occult cervical-spine fracture. Ann Emerg Med. 1994;23(4):797-801.
13.	Hills MW, Deane SA. Head injury and facial injury: is there an increased risk of cervical spine injury? J Trauma. 1993;34(4):549-553; discussion 553-544.
14.	Michael DB, Guyot DR, Darmody WR. Coincidence of head and cervical spine injury. J Neurotrauma. 1989;6(3):177-189.
15.	Paiva WS, Oliveira AM, Andrade AF, Amorim RL, Lourenco LJ, Teixeira MJ. Spinal cord injury and its association with blunt head trauma. Int J Gen Med. 2011;4:613-615.
16.	Finfer S, Chittock DR, Su SY, et al. Intensive versus conventional glucose control in critically ill patients. N Engl J Med. 2009;360(13):1283-1297.
17.	Shackford SR, Zhuang J, Schmoker J. Intravenous fluid tonicity: effect on intracranial pressure, cerebral blood flow, and cerebral oxygen delivery in focal brain injury. J Neurosurg. 1992;76(1):91-98.
18.	Gantner D, Moore EM, Cooper DJ. Intravenous fluids in traumatic brain injury: what's the solution? Curr Opin Crit Care. 2014;20(4):385-389.
19.	van der Jagt M. Fluid management of the neurological patient: a concise review. Crit Care. 2016;20(1):126.
20.	Nursal TZ, Erdogan B, Noyan T, Cekinmez M, Atalay B, Bilgin N. The effect of metoclopramide on gastric emptying in traumatic brain injury. J Clin Neurosci. 2007;14(4):344-348.
21.	Dickerson RN, Mitchell JN, Morgan LM, et al. Disparate response to metoclopramide therapy for gastric feeding intolerance in trauma patients with and without traumatic brain injury. JPEN J Parenter Enteral Nutr. 2009;33(6):646-655.
22.	Hsiang JK, Chesnut RM, Crisp CB, Klauber MR, Blunt BA, Marshall LF. Early, routine paralysis for intracranial pressure control in severe head injury: is it necessary? Crit Care Med. 1994;22(9):1471-1476.
23. Hughes H, Kahl L. The Harriet Lane Handbook - 21st Ed 2017.; 2018.

</div>
