# השגת גישה למחזור הדם

## עיקרי העדכונים
- **23/12/2021:**
    - **אינדוקציה לאינטובציה כאשר זו נדרשת – התוויה מוחלטת להשגת גישה למחזור הדם** 
- **14/12/2021:** 
    - **כתיבת הפרק**


## הקדמה ורקע
הטיפול בנפגע טראומה מערב מגוון טיפולים ופעולות. חלק מהטיפולים דורשים השגת גישה וסקולרית, **בדגש על החייאת מוצרי דם במסגרת החייאת בקרת נזקים.** גישה ורידית פריפרית היא הגישה הרווחת בעולם להשגת גישה וסקולרית. כאשר יש צורך בגישה וסקולרית, חשוב שהדבר יקרה במהירות ומבלי לעכב את הפינוי של הפצוע. אחוזי ההצלחה בהשגת גישה ורידית פריפרית משתנים ותלויים במגוון גורמים לרבות מאפייני הפצוע, מאפייני הפציעה, מיומנות המטפל, המתאר וכו'. כאשר נתקלים בקושי בהשגת גישה ורידית פריפרית, יש מקום לשקול התקדמות לניסיונות להשגת גישה וסקולרית חליפית. יש לזכור כי מלבד הזמן אשר מוקדש לפעולה קיימים גם סיבוכים אפשריים כגון חשיפה למחטים מזוהמות וכן פגיעות וסקולריות. 

גישה וסקולרית תושג לכל המוקדם בסקר ההחייאה, ולרוב, בהמתנה או בזמן הפינוי. אין לעכב פינוי לצורך השגת גישה וסקולרית. ההתוויות להשגת גישה וסקולרית יכולות להיות מחולקות לשתי קבוצות: התוויות מוחלטות והתוויות יחסיות ועל כך יורחב בהמשך הפרק הנוכחי. כמו כן פרק זה יסקור את האפשרויות הקיימות כיום בצה"ל להשגת גישה וסקולרית חליפית ומתי יש לבחור בכל שיטה.

## פרוטוקול השגת גישה למחזור הדם

***************** תרשים



## ביאור פרוטוקול

### ההנחיות להשגת גישה ורידית
1. יש לוודא שאכן יש צורך בהשגת גישה וסקולרית, ולא לעכב פינויי.
2. במידה ויש התוויה מוחלטת, ויש מטפל בכיר במקום, עד שני ניסיונות להשגת גישה ורידית פריפרית יבוצעו על ידי החובשים. במידה והמטפל הבכיר פנוי לכך, הניסיונות יבוצעו על ידו.
3. ניתן לנסות להשיג גישה ורידית פריפרית על ידי מטפל בכיר עד פעמיים. במידה והגיע חובש ללא מטפל בכיר, יבצע עד שני ניסיונות. כלל הניסיונות להשגת גישה ורידית פריפרית לאותו פצוע לא יעלו על  ארבעה (חובש ואז מטפל בכיר או שני מטפלים בכירים).
4. בשנים האחרונות עולה השימוש במכשיר US כעזר להשגת גישה ורידית פריפרית. כאשר קיים מכשיר US ומטפל המיומן בשימוש בו, לאחר כשלון של שני ניסיונות בלעדיו, יש להיעזר במכשיר.
5. לאחר ארבעה כישלונות יש לעבור לגישה חליפית ( בעדיפות תוך גרמית).
6. במידה והמטפל הבכיר מתרשם כי לא יוכל להשיג גישה פריפרית, ניתן להתקדם לגישה חליפית ( בעדיפות תוך גרמית).
7. התקנת עירויי מרכזי תתבצע כאשר נכשלו ניסיונות התקנת עירוי פריפרי, או תוך גרמי, או כאשר קיימת התוויה מיוחדת להחדרת עירוי לווריד מרכזי, ותבוצע על ידי רופא המיומן לכך בלבד.
### החדרת עירוי פריפרי לווריד הג'וגולרי החיצוני:
הוריד הג'וגולרי החיצוני הינו וריד פריפרי גדול ונגיש יחסית אשר יכול להוות אתר לניסיון השגת גישה ורידית פריפרית, בייחוד למטפל המיומן בכך.

#### 1. התוויות נגד מוחלטות:
1. כישלון בגישה לווריד הקונטראלטרלי (המקביל) אשר הובילה ליצירת המטומה
מקומית. 
1.  חשד גבוה לפגיעת עמש"צ (הימנעות מתנוחת טרנדלנבורג ומניפולציה מיותרת
של הצוואר).
#### 2. הציוד הדרוש: 
הציוד הסטנדרטי להתקנת עירוי בווריד פריפרי. מזרק 10 מ"ל.
#### 3. השיטה:
1.  מקם את הפצוע בשכיבה כאשר ראשו נמוך יותר משאר הגוף (הצבה בתנוחת
טרנדלנבורג תסייע למילוי הוריד והבלטתו) והפניית הראש אל הצד הנגדי לצד
ההחדרה (בגישה לווריד הימני הפצוע יביט שמאלה).
2. זהה את הווריד ובצע חיטוי באמצעות ספונג'טה של מיקום ההחדרה:
הוריד נע מזוית הלסת אינפריורית- לטרלית אל הקלביקולה וחוצה את שריר ה
SCM כ 5 ס"מ מעל הקלביקולה. ראה תמונה מס' 1.


****************** תמונה


- להדגשת הוריד ניתן לבצע חסם ורידי מקומי תוך שימוש באצבע (היד הלא דומיננטית) והפעלת לחץ מעל הקלביקולה (פרוקסימלית לנקודת החדירה). אין להניח חסם ורידים.
3.  בצע מתיחה של הוריד תוך שימוש באגודל היד הלא דומיננטית (כאשר האצבע מפעילה לחץ דיסטלית). הוריד נייד מאוג ולכן יש לשים דגש על קיבוע חזק שלו עם היד הלא דומיננטית. ראה תמונה מס' 2.


**************** תמונה

4. החדר את הונפלון, פרוקסימלית ככל שניתן (על מנת להימנע מהגעה לפסגת הריאה), בעדיפות למחצית הפרוקסימלית של מהלך הוריד. מאחר והווריד שטחי, החדירה אליו תתבצע בזווית של עד 10 - 25 מעלות (ראה תמונה מס' 3).


ניתן לבצע החדרת ונפלון עם מזרק 10 מ"ל במחובר ולבצע החדרה תוך כדי שאיבה על מנת לוודא מיקום בכל עת.

5.  קבע הונפלון באמצעות לויקופלסט. אין לבצע קיבוע היקפי סביב הצוואר. חבר לסט נוזלים שטוף. יש לקבע את צינור הסט בנקודה נוספת באמצעות לויקופלסט, באופן שמונע מתיחה.
- באם הונפלון לא מחובר לסט נוזלים אלא לצורך מתן תרופה מומלץ לבצע שטיפה לפני באמצעות סיילין.
6.  במקרה של כשלון בהחדרה או שליפה של הונפלון והיווצרות המטומה מקומית יש להוציא את הונפלון ולהפעיל לחץ במקום למשך כחמש דקות. אין לנסות החדרה נוספת בווריד זה או בווריד הנגדי!

### עירויי תוך גרמי:
#### 1. היתרונות בגישה התוך גרמית
1. אחוזי הצלחה גבוהים בהשגת גישה וסקולרית.
2. מהירות הביצוע
3. אפשרות להזלפת כלל מוצרי הדם והתרופות. 
#### 2. התוויות נגד מוחלטות:
1) שבר בעצם.
2) זיהום במקום ההחדרה.
3)  פגיעת עצם פרוקסמלית לאזור ההחדרה בגפה.
#### 3. התווית נגד יחסית:
 מחלת עצם: Osteoporosis, Osteogenesis Imperfecta 

דגש בילדים: יש להשתמש ב-NIO או BIG ייעודי לילדים
#### 4. מיקום החדרת ה-NIO:
1) ברירת המחדל ומיקום ההחדרה העיקרי הינה עצם השוקה (טיביה) הפרוקסימלית, -1
2 ס"מ מדיאלית ו-1 ס"מ פרוקסימלית ל-Tuberosity Tibial.


*************************** תמונה

2)  במידה ולא ניתן לבצע את הפעולה בגפה התחתונה, ניתן להחדיר את המחט גם לראש הקדמי של עצם הזרוע (הומרוס). לצורך ביצוע הפעולה בראש ההומרוס יש להשכיב את החולה על גבו, כשהמרפק של היד המיועדת לפעולה נוגע באלונקה וכף היד מונחת על הטבור.  לצורך מציאת המיקום:
- על המבצע להניח יד אחת על אמצע הדלתואיד ויד שנייה בקו האקסילרי הקדמי. הנחת הידיים תהיה בצורת סכין, כך שהזרתות צמודות למטופל לאורכן. על הזרתות להיות מונחות בגובה הכתף. יש להפגיש את האגודלים במרכז ולמשש כלפי מעלה כדי להרגיש את ה Greater Tuberosity. זהו אתר ההזרקה.

******************* תמונה

#### 5. סדר פעולות בהחדרת ה-NIO:
1)  זיהוי אנטומי של מקום ההחדרה וסימונו.
2)  ניקוי וחיטוי מקומי ע"י אלכוהול
3) הצבת המכשיר במקום ההחדרה - בעזרת היד הלא דומיננטית של המשתמש אחוז את המכשיר באזור האחיזה המחוספס והצב את המכשיר ב-90 מעלות לעצם/משטח ההחדרה. יש לשים לב שלא לאחוז אותו באזור החלק, מאחר והוא חלק ממנגנון הפעולה של המכשיר ואחיזה שם תפריע לירי המחט.

******************* תמונה


4) פתיחת נצרת המכשיר - בעזרת היד הדומיננטית יש לסובב את ראש המכשיר כך שיהיה מקביל לכנפונים. אין חשיבות לכיוון הסיבוב.

******************* תמונה

5. בעזרת שורש כף היד של היד הדומיננטית, יש ללחוץ על המכשיר כשהוא עומד בניצב (90 מעלות) למשטח העצם. ללא לחץ ב-90 מעלות מנגנון הבטיחות של המכשיר לא יאפשר את הירי. יש לוודא הצמדה לאורך כל הזמן עם היד הלא דומיננטית.

****************** תמונה

6. לאחר וידוא כי המכשיר במקום הנכון, עומד ניצב ומוכן לירי, יש להמשיך להפעיל לחץ ב-90 מעלות בעזרת שורש כף היד ובמקביל למשוך בעזרת אצבעות היד הדומיננטית את כנפוני המכשיר. רק שילוב בין לחץ ב-90 מעלות למשיכת הכנפונים ישגר את המחט. יש לשים לב שממשיכים להצמיד עם היד הלא דומיננטית גם בשלב זה.

***************8 תמונה

7. לאחר הירי, יש לשחרר בעדינות ובתנועה סיבובית את גוף המכשיר מעיגול הפלסטיק הכחול שנמצא ע"ג עור המטופל ותפקידו לקבע את המחט ואת תעלת העירוי.
8. בעזרת השנץ המיועד בקצה מכשיר הפלסטי, יש לשלוף את המחט הפנימית מתעלת העירוי, בדומה לפתיחת בקבוק משקה בעזרת פותחן, ובמקביל להחזיק את העיגול הכחול על מנת למנוע שליפה של המחט.

******************* תמונה

9. לאחר שליפת המחט הפנימית, נותרת בתוך העצם תעלת מתכת המקובעת לסביבה בעזרת עיגול כחול. במצב זה העירוי מוכן. ניתן להמשיך ולקבע את העיגול הכחול בעזרת לויקופלסט, או מדבקת קיבוע ייעודית.
10. ניתן לוודא את הצלחת הפעולה על ידי ניסיון שאיבה - בחלק מהמקרים תיראה טיפת נוזל מח עצם במזרק. **יש לזכור כי חוסר יכולת לשאוב מח עצם לא מעיד על כישלון הפרוצדורה.** 
11. לפני חיבור לנוזלים/תרופה, יש להזריק בולוס של 10 מ"ל סליין. במידה והרקמות הרכות מסביב לתעלת ההעירוי מתנפחות, העירוי ככל הנראה כשל ואינו יעיל.
12. לאחר מתן בולוס של 10 מ"ל ניתן להשתמש בעירוי כמו בעירוי תוך ורידי רגיל. במידה ואין זרימת נוזלים חופשית דרך העירוי יש להזריק בולוס נוסף של 10 סמ"ק סליין.
13. תרופות ונוזלים יוחדרו במינון זהה למינון הניתן בהזרקה תוך-ורידית. אין מגבלת כמות בהחדרת נוזלים או תרופות.  אין הגבלה או מניעה במתן דם ומוצריו.
14. תעלת העירוי תשלף בבית-חולים בלבד ולא בשטח. במידה והיא נשלפת בשטח יש לחבוש ע"י פד גזה.
15. המכשיר הינו חד פעמי. לאחר ביצוע ירי, לא ניתן להשתמש באותו המכשיר פעם נוספת.

#### 6. בעיות שכיחות בשימוש ב-NIO:
1. החדרה במיקום שגוי – ניתן לפתרון ע"י איתור מדויק של מקום ההחדרה וסימונו טרם
הצבת המזרק.
2. החלקה על פני העצם – ניתן לפתרון ע"י מיקום המזרק בניצב למשטח העצם. החלקה ע"ג
משטח העצם היא סיבת הכישלון המובילה ב-NIO . יש לייצב היטב את המכשיר עם היד הלא דומיננטית, במיוחד על חולים מזיעים ומדממים שעורם חלקלק.
3. ללא קיבוע ב-90 מעלות לעצם, המחט תתעקם במהלך הכניסה לעצם והפעולה תיכשל.
4. זיהום מקומי - לבעיה מספר פתרונות:
    - הקפדה על החדרה לעור שאינו מזוהם או פצוע.
    - חיטוי העור טרם ההחדרה.
    - החדרת עירוי תוך ורידי בהזדמנות הראשונה והסרת העירוי הגרמי.
5. הזלפה איטית או חוסר זרימה של נוזל העירוי – ברוב המקרים הסיבה לכך היא סגירה של
סינוסים ורידיים במח העצם. הפתרון הינו הקפדה על מתן בולוס נוזלים ראשוני לאחר
ההחדרה וכן מתן בולוס נוסף במהלך הזלפת העירוי. בנוסף, יש לוודא שהצנרת לא חסומה. ניתן לתת בולוסים באמצעות ברז תלת (נספח 1).
#### 7. כישלון שימוש ב-NIO:
1. במידה ואין זרימה של נוזל העירוי גם לאחר מתן בלחץ של שלושה בולוסים של 10 מ"ל
2. סליין כל אחד, הפרוצדורה תיחשב ככישלון.
במידה והפרוצדורה נכשלה, ניתן להשתמש במכשיר נוסף ברגל השניה או במיקום
חליפי. המכשיר הינו חד פעמי ולא ניתן להשתמש באותו מכשיר לאחר כישלון הפרוצדורה.
### EZ-IO:
מכשיר נוסף הקיים בצה"ל להשגת גישה תוך גרמית הינו ה- EZ-IO: מקדחה ידנית קטנה עם ראש מתחלף שהוא למעשה המחט והקתטר בגדלים משתנים בהתאם למשקל (ורוד 15 מ"מ למשקלים 3-39 ק"ג, כחול 25 מ"מ למשקל מעל 40 ק"ג) וצהוב 45 מ"מ במצבים של ריבוי רקמה רכה או בהומרוס). 
### ביצוע הפרוצדורה:
#### 1. מציאת המיקום:
- במבוגרים: 
    - בטיביה הפוקסימלית ובהומרוס בדומה למציאת המיקום בשימוש ב-NIO.
    - במלאולוס: 1-2 ס"מ סופריורית למלאולוס (בעדיפות המדיאלי) בקו האמצע.
- בילדים:
    - בטיביה הפרוקסימלית: 2 ס"מ מתחת ל-tibial tuberosity ועד ס"מ מדיאלית על ה- tibial plateau.
    - במלאולוס: בדומה למבוגרים
- בתינוקות עד גיל שנה 
    - בטיביה הפרוקסימלית בדומה לילדים
    - בפמור: בקו האמצע 1-2 ס"מ מעל הגבול העליון של הפיקה כשהרגל באקסטנציה
#### 2. ביצוע הפרוצדורה:
1. חיטוי אתר ההחדרה
2. הסרת מכסה הבטחון מהמחט
3. החדרת המחט דרך העור בעדינות עד שהקצה נוגע בעצם – יש לראות לפחות 5 מ"מ מהקתטר חיצונית.
4. לוחצים על הדק המקדחה תוך הפעלת לחץ עדין ויציב. עוזבים את ההדק כאשר מרגישים הקלה פתאומית בהתנגדות, שמעידה על חדירה לתוך חלל המדולה. באתר ההומרוס לשיפור היציבות המחט צריכה להיכנס 2 ס"מ לאחר המגע עם העצם. במקרה נדיר שהמקדחה לא עובדת ניתן להחדיר את המחט תוך כדי תנועת הברגה לחלל המדולה.
5. מסירים את המקדחה ואת המוליך ומוודאים את יציבות ומיקום הקתטר (יציבות, שאיבת תוכן, שטיפה עם מזרק 10 ס"מ) ומקבעים.
### BIG ילדים:
בילדים עד גיל 12, חל איסור להשתמש במכשיר ה NIO, ויש להשתמש במכשיר PEDIATRIC BIG או Pediatric NIO. 
1. **מציאת המיקום:** מה TIBIAL TUBEROSITY, יש להתקדם 1 ס''מ מידיאלית ו 1-2 ס''מ **דיסטאלית.**
2. **ביצוע הפרוצדורה**: 

Pediatric BIG - יש להצמיד את האקדח עם היד החלשה בזווית של 90 מעלות אל הרגל. יש להקפיד על ההצמדה לאורך כל הפרוצדורה. יש להוציא את הנצרה, תוך הקפדה על ההצמדה לרגל. עם היד החזקה יש ללחוץ עם כרית כף היד כך שיתבצע ירי של המחט. יש להוציא את המחט ולקבע באמצעות הנצרה ולויקופלסט.  יש לבצע שאיבה על מנת לוודא שהמחט במקום. **אי שאיבת מח עצם לא מצביע על כישלון הפורצדורה**. יש לשטוף באמצעות 10 מ''ל סליין.

Pediatric NIO – 
1. התאמת עומק ההחדרה – הסרת מרווח המקום עבור בני 9-12, השארתו עבור בני 3-9.

****************** תמונה

2. איתור מיקום ההחדרה – הנחת החץ המכוון הרלוונטי (R לרגל ימין, L לרגל שמאל) על חלקו הבולט של ה- tibial tuberosity קח שהחץ מקביל לאורך הטיביה 

**********************תמונה

3. אחיזת המכשיר בעזרת היד הלא דומיננטית, באזור המחוספס והצמדת המכשיר לרגל ב-90 מעלות

************** תמונה

4. סיבוב המכסה ב-90 מעלות בעזרת היד הדומיננטית 

***************** תמונה

5. תוך המשך הצמדה של ה-NIO לעור הילד בעזרת היד הלא דומיננטית יש להפעיל לחץ בעזרת כף היד הדומיננטית על המכסה תוך משיכה של הכנפונים.

************** תמונה

6. יש לאחוז בבסיס המייצב בעזרת האצבעות ולהרים כלפי מעלה תוך כדי סיבוב את מכשיר ה-NIO.

********************* תמונה

7. ייצוב הבסיס בעזרת חבישה ייעודית או בעזרת לויקופלסט והסרה של המחט המוליכה בעזרת האצבעות או הגומחה הייעודית במכשיר.

*************** תמונה

8. וידוא החדרה תקינה באמצעות שאיבה על ידי מזרק והזרקה של 10 מ"ל סליין. לאחר מכן חיבור לסט עירוי

### עירוי מרכזי בטכניקת סלדינג'ר:
הגישה הוסקולרית דרך וריד מרכזי אמנם מאפשרת הזלפה של מוצרי דם בקצב המהיר ביותר אך דורשת מיומנות רבה יותר משאר החלופות להשגת גישה וסקולרית. גישה זו אינה מומלצת לביצוע על ידי המטפל הראשוני ובמידה והוא נדרש לכך מטפל זה יבצע עירויי מרכזי *בגישה פמורלית בלבד*, ולא במקומות נוספים (משיקולים של סיכונים וסיכויי הצלחה במהלך הפעולה).
#### 1. התוויות נגד :

**מוחלטות:**
1) פגיעה ורידית ודאית או חשודה פרוקסימלית לוריד הפמורלי (איליאק, IVC)
2)  פקקת ודאית או חשודה באתר ההחדרה, או בצד הנגדי.

**יחסיות:**
1) הפרעת דמם
2) פגיעה מקומית או דפורמציה עקב פציעה.
3) היעדר דופק פמורלי הנימוש היטב.
4) זיהום מקומי באזור ההחדרה.

#### 2. ההכנות לפעולה:
1. כאשר קיים מכשיר US  ומטפל מיומן בשימוש בו, אין לבצע את הפעולה ללא US. 
2. פתח את הערכה לצד הפצוע, והנח על משטח קשיח ולא על גבי הנפגע. ניתן
להשתמש בסיוע חובש לפעולה.
3. בצע חיטוי ולבש כפפות סטריליות. כסה את האזור בסדין סטרילי עם חור.
4. בדוק את הציוד:
הכן מזרק ומחט דרכה יעבור המוביל גייד
    1. בדוק את שלמות המוביל ויציאתו התקינה מהמכשיר והחזר אותו למכשיר
    2.  וודא קיום מרחיב
    3. וקיום הצנתר (ראה
תמונה 4). 
    4. הכן מזרק 10 מ"ל סיילין לשטיפה ומזרק לשאיבה, הכן מחזיק מחט וחוט
לתפירה.


********************** תמונה


#### 3. השיטה:
1.  זיהוי המקום האנטומי:

******************תמונה 


העורק הפמורלי נמצא במרכז קו המפשעה: בין הASIS והPubis Sympysis  ודיסטאלית לLigament Inguinal . הוריד הפמורלי נמצא כחצי ס"מ מדיאלית לדופק הנמוש.

2. בצע הרדמה מקומית: לאחר זיהוי המקום, חטא את האזור ובצע הרדמה מקומית בעזרת 2-3 מ"ל לידוקאין 2% . ניתן לוותר על שלב זה בפצוע מחוסר הכרה ודחיפות בהשגת הגישה.
3. תנוחת הפצוע: בשכיבה על הגב, רגל ישרה בתנוחה אנטומית.
4. זהה את המיקום בשנית (1ס"מ דיסטאלית לליגמנט, חצי ס"מ מדיאלית לדופק
הפמורלי) והחדר את המחט בזווית 45º לכיוון הראש תוך שאיבה במזרק (תמונה 6)
לאחר קבלת החזר ורידי נתק את המזרק תוך קיבוע המחט (תמונה 7).

***************************** תמונה

5. החדר את המוביל אל חלל המחט עד לעומק של הסימן III (מסומן על גבי המוביל, משמעותו 30 ס"מ) או 5 ס"מ מפתח המחט. אם נתקלת בהתנגדות סובב את המוביל על צירו ונסה המשך החדרה. אין לדחוף את המוביל בכוח ואין לאבד אחיזה במוביל! הסר את מחזיק הפלסטיק מהמוביל.

**************** תמונה

6. משוך את המחט בעדינות לאורך המוביל עד ליציאתה, בעיגון המוביל למקומו בפתח ההחדרה עם האצבעות (תמונה 9). בצע הרחבת חתך בעזרת הסקלפל על מנת להקל על החדרת המרחיב.

************************* תמונה

7.  החלק את המרחיב לכל אורכו לאורך המוביל על מנת לבצע הרחבה של הרקמה התת עורית (תמונה 10).

************************* תמונה

8. הסר את המרחיב בזהירות לאורך המוביל, והשחל את הצנתר על גבי המוביל )תמונה 11) **תוך כדי אחיזת המוביל עצמו בכל שלב.**

************************* תמונה

9.  הוצא את המוביל וחבר מזרק עם 10 עם 5 מ''ל סליין. בצע שאיבה עד שיוצא דם ואז הכנס את השטיפה.

************************* תמונה

10. בצע תפירה של הצנתר באמצעות תפר משי דרך החורים הייעודיים.
11. חבוש את האזור בצורה סטרילית.
#### 4. סיבוכים אפשריים:
1. ניקוב עורקי: יזוהה בדימום פולסטילי. יש ללחוץ למשך 5 דקות לעצירת הדימום.
2. ניקוב מעי: בפצועים עם בקע מפשעתי.
3. ניקוב שלפוחית השתן: בפצועים עם הרחבת כיס השתן.
4. תסחיף אויר: יש להקפיד על סגירת הצנתר בכל שלב.
5. הפרעות דמם: דימום ויצירת המטומה, תרומבוזיס של הוריד הפמורלי או האיליאקי.
6. סיבוכים מאוחרים: היווצרות פסאודו אניוריזמה, אבסס בפסואס בחדירת המעטפת השרירית, ארתריטיס ספטי, זיהום.
7. פגיעה בעצב הפמורלי.

## נספחים:
### נספח א - שימוש בברז תלת:
בשימוש בברז תלת מאפשר מתן בולוסים מהירים של נוזלים. דרך השימוש:
1. יש לחבר את הברז תלת כך שבצד אחד מחובר סט הנוזלים וממול החיבור לונפלון

************************* תמונה

2. לפתח הנוסף מחברים מזרק.
3. מסובבים את ברז התלת כך שהוא פתוח לסט ולמזרק ושואבים את מוצר הדם/הנוזל שרוצים להזריק מהשקית.
4. מסובבים את ברז התלת כך שהוא פתוח לכיוון המזרק והמטופל ומזריקים את תכולת המזרק.
5. חוזרים על הפעולות בסעיף ג' ו-ד' עד גמר מתן הטיפול הרצוי.

************************* תמונה

תמונה א'. מצבים אפשריים של ברז תלת 

מצב מספר 1 – המצב בעת שאיבת הנוזל. מצב

מספר 3- המצב בזמן הזרקת הנוזל למטופל

מצבים 2 + 4 – מצבים למתן העירוי כאשר לא נדרש שימוש במזרק
